function output_ = decostand_total(input_,str_margin);
if nargin<2; str_margin = 'row'; end;
[n_r,n_c] = size(input_);
output_ = input_;
if strfind(str_margin,'row');
for nc=1:n_c;
tmp_ = input_(:,nc);
tmp = sum(tmp_);
if ~isfinite(tmp); tmp = 1; end;
if (tmp==0); tmp=1; end;
output_(:,nc) = tmp_/tmp;
end;%for nc=1:n_c;
end;%if strfind(str_margin,'row');
if strfind(str_margin,'col');
output_ = transpose(decostand_total_0(transpose(input_),'row'));
end;%if strfind(str_margin,'col');
