function ...
[ ...
 parameter ...
,BB_inv__ ...
,CC_inv__ ...
,l2_R__ ...
,sum_1 ...
,sum_dt ...
,sum_dtdt ...
,sum_DD_j__ ...
,sum_DD_j_dt__ ...
] = ....
dolphin_estimate_BB_inv_CC_inv_from_aA_wrap_2( ...
 parameter ...
,aid_ ...
,age_ ...
,dat__ ...
,a_ ...
,A__ ...
);
% Estimates BB_inv__ and CC_inv__, given a_ and A__. ;
% if flag_constrain_CC then we constrain CC_inv to be diagonal. ;

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); aid_=[]; end; na=na+1;
if (nargin<1+na); age_=[]; end; na=na+1;
if (nargin<1+na); dat__=[]; end; na=na+1;
if (nargin<1+na); a_=[]; end; na=na+1;
if (nargin<1+na); A__=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;
if (~isfield(parameter,'flag_crude')); parameter.flag_crude = 0; end;
flag_crude = parameter.flag_crude;

if (~flag_crude);
[ ...
 parameter ...
,BB_inv__ ...
,CC_inv__ ...
,l2_R__ ...
,sum_1 ...
,sum_dt ...
,sum_dtdt ...
,sum_DD_j__ ...
,sum_DD_j_dt__ ...
] = ....
dolphin_estimate_BB_inv_CC_inv_from_aA_2( ...
 parameter ...
,aid_ ...
,age_ ...
,dat__ ...
,a_ ...
,A__ ...
);
end;%if (~flag_crude);

if ( flag_crude);
[ ...
 parameter ...
,BB_inv__ ...
,CC_inv__ ...
,l2_R__ ...
,sum_1 ...
,sum_dt ...
,sum_dtdt ...
,sum_DD_j__ ...
,sum_DD_j_dt__ ...
] = ....
dolphin_estimate_BB_inv_CC_inv_from_aA_crude_2( ...
 parameter ...
,aid_ ...
,age_ ...
,dat__ ...
,a_ ...
,A__ ...
);
end;%if ( flag_crude);
