function ...
[ ...
 parameter ...
,dat_fil__ ...
,dat_res__ ...
,P_pos__ ...
,K___ ...
,P___ ...
] = ...
dolphin_estimate_kalman_filter_single_trial_0( ...
 parameter ...
,age_ ...
,dat__ ...
,a_ ...
,A__ ...
,BB_inv__ ...
,CC_inv__ ...
,P__ ...
);

if nargin<1;
%%%%%%%%;
tolerance_master = 1e-2;
n_var = 2; T_max = 64;
if n_var==1; A_tru__ = -5/T_max*eye(n_var); end;
if n_var==2; A_tru__ = [-1/T_max , +1 ; -1 -2/T_max]; end;
a_tru_ = A_tru__*ones(n_var,1)*-0.3;
BB_tru__ = [];
BB_inv_tru__ = 1*eye(n_var);
CC_tru__ = [];
CC_inv_tru__ = 1*eye(n_var);
parameter = struct('type','parameter');
parameter.dt_avg = 0.001;
parameter.T_max = T_max;
parameter.rseed = 1;
[ ...
 parameter ...
,age_ ...
,X__ ...
,Y__ ...
,R_avg ...
] = ...
SDE_generate_data_0( ...
 parameter ...
,a_tru_ ...
,A_tru__ ...
,BB_tru__ ...
,BB_inv_tru__ ...
,CC_tru__ ...
,CC_inv_tru__ ...
);
%%%%%%%%;
parameter = struct('type','parameter');
[ ...
 parameter ...
,X_fil__ ...
,X_res__ ...
,P_pos__ ...
,K___ ...
,P___ ...
] = ...
dolphin_estimate_kalman_single_trial_0( ...
 parameter ...
,age_ ...
,transpose(X__) ...
,a_tru_ ...
,A_tru__ ...
,BB_inv_tru__ ...
,CC_inv_tru__ ...
,[] ...
);
%%%%%%%%;
parameter = struct('type','parameter');
[ ...
 parameter ...
,Y_fil__ ...
,Y_res__ ...
,P_pos__ ...
,K___ ...
,P___ ...
] = ...
dolphin_estimate_kalman_single_trial_0( ...
 parameter ...
,age_ ...
,transpose(Y__) ...
,a_tru_ ...
,A_tru__ ...
,BB_inv_tru__ ...
,CC_inv_tru__ ...
,[] ...
);
%%%%%%%%;
if (n_var==1);
figure;clf;figbig;figbeach();
hold on;
plot(age_,X__,'k.-');
plot(age_,Y__,'go-');
plot(age_,Y_fil__,'rx-');
xlim([min(age_),max(age_)]); xlabel('age');
end;%if (n_var==1);
%%%%%%%%;
if (n_var==2);
figure;clf;figbig;figbeach();
p_row = 2; p_col = 3; ns=0;
subplot(p_row,p_col,1+ns);ns=ns+1;plot(age_,X__(1,:),'r-',age_,X__(2,:),'b-');
xlabel('time');ylabel('X'); xlim([0,T_max]); title('X__','Interpreter','none');
subplot(p_row,p_col,1+ns);ns=ns+1;s = surfline_0(X__(1,:),X__(2,:),age_); set(s,'LineWidth',3);
xlabel('x0');ylabel('x1'); title('X__','Interpreter','none');
subplot(p_row,p_col,1+ns);ns=ns+1;s = surfline_0(X_fil__(:,1),X_fil__(:,2),age_); set(s,'LineWidth',3); title('X_fil__','Interpreter','none');
xlabel('x0');ylabel('x1');
subplot(p_row,p_col,1+ns);ns=ns+1;plot(age_,Y__(1,:),'r-',age_,Y__(2,:),'b-');
xlabel('time');ylabel('Y'); xlim([0,T_max]); title('Y__','Interpreter','none');
subplot(p_row,p_col,1+ns);ns=ns+1;s = surfline_0(Y__(1,:),Y__(2,:),age_); set(s,'LineWidth',3);
xlabel('y0');ylabel('y1'); title('Y__','Interpreter','none');
subplot(p_row,p_col,1+ns);ns=ns+1;s = surfline_0(Y_fil__(:,1),Y_fil__(:,2),age_); set(s,'LineWidth',3); title('Y_fil__','Interpreter','none');
xlabel('y0');ylabel('y1');
end;%if (n_var==2);
%%%%%%%%;
disp('returning'); return;
end;%if nargin<1;

verbose=0;

na=0;
if (nargin<(1+na)); parameter=[]; end; na=na+1;
if (nargin<(1+na)); age_=[]; end; na=na+1;
if (nargin<(1+na)); dat__=[]; end; na=na+1;
if (nargin<(1+na)); a_=[]; end; na=na+1;
if (nargin<(1+na)); A__=[]; end; na=na+1;
if (nargin<(1+na)); BB_inv__=[]; end; na=na+1;
if (nargin<(1+na)); CC_inv__=[]; end; na=na+1;
if (nargin<(1+na)); P__=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;
if (~isfield(parameter,'tolerance_master')); parameter.tolerance_master = 1e-2; end;
tolerance_master = parameter.tolerance_master;

index_use_ = efind( (isfinite(age_)) & isfinite(sum(dat__,2)) );
age_use_ = age_(1+index_use_);
dat_use__ = dat__(1+index_use_,:);
[~,index_srt_] = sort(age_use_,'ascend'); index_srt_ = index_srt_-1;
age_srt_ = age_use_(1+index_srt_);
dat_srt__ = dat_use__(1+index_srt_,:);

n_var = size(dat__,2);
n_smp = size(dat_srt__,1); assert(numel(age_srt_)==n_smp);

dat_fil__ = dat__;
dat_res__ = zeros(size(dat__));
P_pos__ = P__;
if n_smp>1;

if isempty(P__); P__ = eye(n_var); end;

A_inv_a_ = pinv(A__,tolerance_master)*a_;

dat_cen__ = bsxfun(@plus,dat_srt__,+reshape(A_inv_a_,[1,n_var]));

P_old__ = P__;
X_old_ = transpose(dat_cen__(1+0,:));
X_pos__ = zeros(n_smp,n_var);
Y_res__ = zeros(n_smp,n_var);
if (nargout>4);
K___ = zeros(n_smp,n_var,n_var);
P___ = zeros(n_smp,n_var,n_var);
end;%if (nargout>4);
for nsmp=1:n_smp-1;
dt = age_srt_(1+nsmp+0) - age_srt_(1+nsmp-1);
F__ = eye(n_var,n_var) + dt*A__;
X_pre_ = F__*X_old_;
P_pre__ = F__*P_old__*transpose(F__) + BB_inv__*dt;
Z_ = transpose(dat_cen__(1+nsmp,:));
Y_ = Z_ - X_pre_;
S__ = P_pre__ + CC_inv__;
K__ = P_pre__*pinv(S__,tolerance_master);
X_pos_ = X_pre_ + K__*Y_;
P_pos__ = (eye(n_var,n_var) - K__)*P_pre__;
Y_res_ = Z_ - X_pos_;
if (verbose);
if (nsmp<4);
disp(sprintf(' %% nsmp %d/%d: ',nsmp,n_smp));
disp(sprintf(' %% %% dt %0.6f',dt));
disp(sprintf(' %% %% F__: ')); disp(F__);
disp(sprintf(' %% %% X_pre_: ')); disp(X_pre_);
disp(sprintf(' %% %% P_pre__: ')); disp(P_pre__);
disp(sprintf(' %% %% Z_: ')); disp(Z_);
disp(sprintf(' %% %% Y_: ')); disp(Y_);
disp(sprintf(' %% %% S__: ')); disp(S__);
disp(sprintf(' %% %% K__: ')); disp(K__);
disp(sprintf(' %% %% X_pos_: ')); disp(X_pos_);
disp(sprintf(' %% %% P_pos__: ')); disp(P_pos__);
disp(sprintf(' %% %% Y_res_: ')); disp(Y_res_);
end;%if (nsmp<4);
end;%if (verbose);
X_pos__(1+nsmp,:) = transpose(X_pos_);
Y_res__(1+nsmp,:) = transpose(Y_res_);
if (nargout>4);
P___(1+nsmp,:,:) = P_pre__;
K___(1+nsmp,:,:) = K__;
end;%if (nargout>4);
P_old__ = P_pos__;
X_old_ = X_pos_;
end;%for nsmp=1:n_smp-1;

dat_rec__ = bsxfun(@plus,X_pos__,-reshape(A_inv_a_,[1,n_var]));
dat_fil__(1+index_use_(1+index_srt_),:) = dat_rec__;
dat_res__(1+index_use_(1+index_srt_),:) = Y_res__;

end;%if n_smp>1;







