n_step = 1;
dt_all_ = [];
for naid=0:n_aid-1;
tmp_index_aid_ = index_aid__{1+naid};
tmp_age_ = age_(1+tmp_index_aid_);
[tmp_age_sort_,tmp_index_] = sort(tmp_age_,'ascend'); tmp_index_ = tmp_index_-1;
for nstep=0;n_step-1;
dt_ = tmp_age_sort_(1+(1+nstep):end)-tmp_age_sort_(1:end-(1+nstep));
dt_all_ = [dt_all_;dt_];
end;%for nstep=0;n_step-1;
end;%for naid=0:n_aid-1;

%figsml;hist(tmp_age_all_,32);title(sprintf('median %0.2f',prctile(tmp_age_all_,50)));xlabel('measurement age');print('-djpeg',sprintf('%s/dolphin_measurement_age.jpg',dir_jpg));

%%%%%%%%;
% RBCDist and Albumin look strange. ;
%%%%%%%%;
nvar = efind(strcmp(string_dat_ori_name_,'RBCDist'));
tmp_age_all_ = [];
tmp_age_acc_ = [];
tmp_var_all_ = [];
tmp_aid_all_ = [];
tmp_age_min_ = zeros(n_aid,1);
tmp_sbp_all_ = [];
age_base=0;
for naid=0:n_aid-1;
tmp_index_aid_ = index_aid__{1+naid};
tmp_n_aid = numel(tmp_index_aid_);
tmp_age_ = age_(1+tmp_index_aid_);
[tmp_age_,tmp_index_] = sort(tmp_age_,'ascend'); tmp_index_ = tmp_index_-1;
tmp_var_ = dat_ori__(1+tmp_index_aid_,1+nvar); tmp_var_ = tmp_var_(1+tmp_index_);
tmp_age_all_ = [tmp_age_all_;tmp_age_];
tmp_age_acc_ = [tmp_age_acc_;tmp_age_ + age_base];
tmp_var_all_ = [tmp_var_all_;tmp_var_];
tmp_aid_all_ = [tmp_aid_all_;naid*ones(tmp_n_aid,1)];
tmp_age_min_(1+naid) = min(tmp_age_ + age_base);
age_base = age_base + max(tmp_age_) + 1;
end;%for naid=0:n_aid-1;
n_all = numel(tmp_age_all_);
assert(n_all==n_smp);
vlim_ = [prctile(tmp_var_all_,1),prctile(tmp_var_all_,99)];
vlim_ = mean(vlim_) + 0.65*diff(vlim_)*[-1,+1];
n_plot_row = 4;
tmp_f_ = tmp_age_acc_/max(tmp_age_acc_);
tmp_np_ = max(0,min(n_plot_row-1,floor(n_plot_row*tmp_f_)));
%%%%%%%%;
figure(1);clf;figbig;
c_beach__ = colormap_beach();n_c_beach = size(c_beach__,1);
markersize_use = 8;
str_symbol_ = {'o','^','s','p','h'};
for np=0:n_plot_row-1;
subplot(n_plot_row,1,1+np);
tmp_index_ = efind(tmp_np_==np);
tmp_age_ = tmp_age_acc_(1+tmp_index_);
tmp_var_ = tmp_var_all_(1+tmp_index_);
tmp_aid_ = tmp_aid_all_(1+tmp_index_);
for naid=0:n_aid-1;
str_symbol = str_symbol_{1+mod(naid,5)};
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach*mod(71*naid,n_aid)/n_aid)));
tmp_sub_ = efind(tmp_aid_==naid);
if (numel(tmp_sub_)>0);
hold on;
plot(tmp_age_(1+tmp_sub_),tmp_var_(1+tmp_sub_),str_symbol,'MarkerSize',markersize_use,'MarkerFaceColor',c_beach__(1+nc_beach,:),'MarkerEdgeColor','k');
hold off;
end;%if (numel(tmp_sub_)>0);
end;%for naid=0:n_aid-1;
xlim([min(tmp_age_),max(tmp_age_)]);
ylim(vlim_);
grid on;
xlabel('measurements (time)');
ylabel('RBCDist');
end;%for np=0:n_plot_row-1;
title(string_dat_ori_name_{1+nvar});
%%%%%%%%;
print('-djpeg',sprintf('%s/dolphin_ori_RBCDist_1.jpg',dir_jpg));
print('-depsc',sprintf('%s/dolphin_ori_RBCDist_1.eps',dir_jpg));
pause(2);close(gcf);

%%%%%%%%;
% RBCDist and Albumin look strange. ;
%%%%%%%%;
nvar = efind(strcmp(string_dat_ori_name_,'Albumin'));
tmp_age_all_ = [];
tmp_age_acc_ = [];
tmp_var_all_ = [];
tmp_aid_all_ = [];
tmp_age_min_ = zeros(n_aid,1);
tmp_sbp_all_ = [];
age_base=0;
for naid=0:n_aid-1;
tmp_index_aid_ = index_aid__{1+naid};
tmp_n_aid = numel(tmp_index_aid_);
tmp_age_ = age_(1+tmp_index_aid_);
[tmp_age_,tmp_index_] = sort(tmp_age_,'ascend'); tmp_index_ = tmp_index_-1;
tmp_var_ = dat_ori__(1+tmp_index_aid_,1+nvar); tmp_var_ = tmp_var_(1+tmp_index_);
tmp_age_all_ = [tmp_age_all_;tmp_age_];
tmp_age_acc_ = [tmp_age_acc_;tmp_age_ + age_base];
tmp_var_all_ = [tmp_var_all_;tmp_var_];
tmp_aid_all_ = [tmp_aid_all_;naid*ones(tmp_n_aid,1)];
tmp_age_min_(1+naid) = min(tmp_age_ + age_base);
age_base = age_base + max(tmp_age_) + 1;
end;%for naid=0:n_aid-1;
n_all = numel(tmp_age_all_);
assert(n_all==n_smp);
vlim_ = [prctile(tmp_var_all_,1),prctile(tmp_var_all_,99)];
vlim_ = mean(vlim_) + 0.65*diff(vlim_)*[-1,+1];
n_plot_row = 4;
tmp_f_ = tmp_age_acc_/max(tmp_age_acc_);
tmp_np_ = max(0,min(n_plot_row-1,floor(n_plot_row*tmp_f_)));
%%%%%%%%;
figure(1);clf;figbig;
c_beach__ = colormap_beach();n_c_beach = size(c_beach__,1);
markersize_use = 8;
str_symbol_ = {'o','^','s','p','h'};
for np=0:n_plot_row-1;
subplot(n_plot_row,1,1+np);
tmp_index_ = efind(tmp_np_==np);
tmp_age_ = tmp_age_acc_(1+tmp_index_);
tmp_var_ = tmp_var_all_(1+tmp_index_);
tmp_aid_ = tmp_aid_all_(1+tmp_index_);
for naid=0:n_aid-1;
str_symbol = str_symbol_{1+mod(naid,5)};
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach*mod(71*naid,n_aid)/n_aid)));
tmp_sub_ = efind(tmp_aid_==naid);
if (numel(tmp_sub_)>0);
hold on;
plot(tmp_age_(1+tmp_sub_),tmp_var_(1+tmp_sub_),str_symbol,'MarkerSize',markersize_use,'MarkerFaceColor',c_beach__(1+nc_beach,:),'MarkerEdgeColor','k');
hold off;
end;%if (numel(tmp_sub_)>0);
end;%for naid=0:n_aid-1;
xlim([min(tmp_age_),max(tmp_age_)]);
ylim(vlim_);
grid on;
xlabel('measurements (time)');
ylabel('Albumin');
end;%for np=0:n_plot_row-1;
title(string_dat_ori_name_{1+nvar});
%%%%%%%%;
print('-djpeg',sprintf('%s/dolphin_ori_Albumin_1.jpg',dir_jpg));
print('-depsc',sprintf('%s/dolphin_ori_Albumin_1.eps',dir_jpg));
pause(2);close(gcf);


