% collect 4-by-4 results. ;
clear;
%setup_access1;
setup_OptiPlex;

%dir_trunk = '/data/rangan/dir_bcc/dir_dolphin';
dir_trunk = '/home/rangan/dir_bcc/dir_dolphin';
dir_R = sprintf('%s/dir_R',dir_trunk);
dir_irg_csv = sprintf('%s/dir_irg_csv',dir_R);
dir_irg_mat = sprintf('%s/dir_irg_mat',dir_R);
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);

dt_avg = 0.257; %<-- matches d00 data. ;
relative_variation = 0.8973; %<-- matches d00 data. ;

n_T_0in_ = [128,256,512,1024]; n_n_T_0in = numel(n_T_0in_);
snr_ = 2.^[-3:+0.5:+3]; n_snr = numel(snr_);
rseed_ = 0:16; n_rseed = numel(rseed_);

n_var = 4;
n_var_pair = n_var*(n_var-1)/2;
index_ofd_ = efind(ones(n_var,n_var)-eye(n_var));

found_flag_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_est_ofd_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
pvalue_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
nlpvalue_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_irg_ofd_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
pvalue_irg_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
nlpvalue_irg_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
for nn_T_0in=0:n_n_T_0in-1;
n_T_0in = n_T_0in_(1+nn_T_0in);
for nrseed=0:n_rseed-1;
rseed = rseed_(1+nrseed);
for nsnr=0:n_snr-1;
snr = snr_(1+nsnr);
%dolphin_test_5(rseed,n_var,dt_avg,n_T_0in,relative_variation,snr);
string_infix = dolphin_test_5_infix(rseed,n_var,dt_avg,n_T_0in,relative_variation,snr);
fname_dat_mat = sprintf('%s/%s_dat__.mat',dir_irg_mat,string_infix);
fname_age_csv = sprintf('%s/%s_age_.csv',dir_irg_csv,string_infix);
fname_dat_csv = sprintf('%s/%s_dat__.csv',dir_irg_csv,string_infix);
fname_out_mat = sprintf('%s/%s_out.mat',dir_irg_mat,string_infix);
fname_irg_R = sprintf('%s/%s_irg.R',dir_R,string_infix);
fname_irg_out = sprintf('%s/%s_irg_out__.csv',dir_irg_csv,string_infix);
if ( exist(fname_out_mat,'file') &  exist(fname_irg_out,'file') );
found_flag_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = 1;
tmp_mat_ = load(fname_out_mat);
tmp_irg_ = textread(fname_irg_out); %<-- nvar0 nvar1 pval A01_v A01_t A10_v A10_t ;
tmp_irg_ = transpose(tmp_irg_); tmp_irg_ = tmp_irg_(:);
tmp_irg__ = reshape(tmp_irg_,[10,n_var_pair]);
tmp_A_tru__ = tmp_mat_.tru_.A_tru__;
tmp_A_est__ = tmp_mat_.est_.A_est__;
tmp_A_irg__ = zeros(n_var,n_var);
tmp_A_irp__ = zeros(n_var,n_var);
tmp_A_nlp__ = zeros(n_var,n_var);
tmp_A_nlp_ = zeros(n_var_pair,1);
na=0;
for nvar0=0:n_var-1;
for nvar1=nvar0+1:n_var-1;
assert(tmp_irg__(1+0,1+na)==nvar0);
assert(tmp_irg__(1+1,1+na)==nvar1);
tmp_irg_pvalue = tmp_irg__(1+2,1+na);
tmp_irg_nlpvalue = -log(tmp_irg_pvalue);
tmp_A_irg__(1+nvar0,1+nvar1) = tmp_irg__(1+3,1+na).*(tmp_irg_nlpvalue>3.0);
tmp_A_irg__(1+nvar1,1+nvar0) = tmp_irg__(1+5,1+na).*(tmp_irg_nlpvalue>3.0);
tmp_A_irp__(1+nvar0,1+nvar1) = tmp_irg_pvalue;
tmp_A_irp__(1+nvar1,1+nvar0) = tmp_irg_pvalue;
tmp_A_nlp__(1+nvar0,1+nvar1) = -log(tmp_irg_pvalue);
tmp_A_nlp__(1+nvar1,1+nvar0) = -log(tmp_irg_pvalue);
tmp_A_nlp_(1+na) = -log(tmp_irg_pvalue);
na=na+1;
end;%for nvar1=nvar0+1:n_var-1;
end;%for nvar0=0:n_var-1;
tmp_A_tru_ofd_ = tmp_A_tru__(1+index_ofd_);
tmp_A_est_ofd_ = tmp_A_est__(1+index_ofd_);
tmp_A_irg_ofd_ = tmp_A_irg__(1+index_ofd_);
corr_A_est_ofd = corr(tmp_A_tru_ofd_,tmp_A_est_ofd_);
if (~isfinite(corr_A_est_ofd)); corr_A_est_ofd = 0; end;
corr_A_irg_ofd = corr(tmp_A_tru_ofd_,tmp_A_irg_ofd_);
if (~isfinite(corr_A_irg_ofd)); corr_A_irg_ofd = 0; end;
pvalue_est = exp(-tmp_mat_.null_.L_nlp);
nlpvalue_est = tmp_mat_.null_.L_nlp;
pvalue_irg = exp(-mean(tmp_A_nlp_));
nlpvalue_irg = mean(tmp_A_nlp_);
corr_A_est_ofd_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_est_ofd;
pvalue_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = pvalue_est;
nlpvalue_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = nlpvalue_est;
corr_A_irg_ofd_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_irg_ofd;
pvalue_irg_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = pvalue_irg;
nlpvalue_irg_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = nlpvalue_irg;
end;%if ( exist(fname_out_mat,'file') &  exist(fname_irg_out,'file') );
end;%for nsnr=0:n_snr-1;
end;%for nrseed=0:n_rseed-1;
end;%for nn_T_0in=0:n_n_T_0in-1;

disp(sprintf(' %% found %d/%d',sum(found_flag_snr___(:)),n_snr*n_n_T_0in*n_rseed));

%index_rseed_ = [1:14,16:17]-1;
index_rseed_ = 0:16;
found_flag_sn__ = sum(found_flag_snr___(:,:,1+index_rseed_),3);
corr_A_est_ofd_sn__ = sum(corr_A_est_ofd_snr___(:,:,1+index_rseed_),3)./found_flag_sn__;
pvalue_est_sn__ = sum(pvalue_est_snr___(:,:,1+index_rseed_),3)./found_flag_sn__;
nlpvalue_est_sn__ = sum(nlpvalue_est_snr___(:,:,1+index_rseed_),3)./found_flag_sn__;
corr_A_irg_ofd_sn__ = sum(corr_A_irg_ofd_snr___(:,:,1+index_rseed_),3)./found_flag_sn__;
pvalue_irg_sn__ = sum(pvalue_irg_snr___(:,:,1+index_rseed_),3)./found_flag_sn__;
nlpvalue_irg_sn__ = sum(nlpvalue_irg_snr___(:,:,1+index_rseed_),3)./found_flag_sn__;

fname_fig = sprintf('%s/dolphin_test_5_collect_n%d_FIGA',dir_jpg,n_var);
if ( ~exist(sprintf('%s.jpg',fname_fig),'file')); 
disp(sprintf(' %% %s not found, creating',fname_fig));
figure(1);clf;
for nn_T_0in=0:n_n_T_0in-1;
n_T_0in = n_T_0in_(1+nn_T_0in);
subplot(2,2,1+nn_T_0in);
hold on;
plot(log2(snr_),corr_A_est_ofd_sn__(:,1+nn_T_0in),'ro-','LineWidth',2);
plot(log2(snr_),corr_A_irg_ofd_sn__(:,1+nn_T_0in),'bx-','LineWidth',2);
hold off;
xlim([min(log2(snr_)),max(log2(snr_))]);
ylim([0,1]);
xlabel('log2(snr)');
ylabel('recovery');
title(sprintf('%d samples',n_T_0in),'Interpreter','none');
end;%for nn_T_0in=0:n_n_T_0in-1;
sgtitle(sprintf('n_var %d',n_var),'Interpreter','none');
figbig;
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if ( ~exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_test_5_collect_n%d_FIGB',dir_jpg,n_var);
if ( ~exist(sprintf('%s.jpg',fname_fig),'file')); 
disp(sprintf(' %% %s not found, creating',fname_fig));
%%%%%%%%;
figure(2);clf;
for nn_T_0in=0:n_n_T_0in-1;
n_T_0in = n_T_0in_(1+nn_T_0in);
subplot(2,2,1+nn_T_0in);
hold on;
plot([0,1],[0,1],'k-');
plot([0,0],[0,1],'k-');
plot([0,1],[0,0],'k-');
tmp_irg_ = corr_A_irg_ofd_snr___(:,1+nn_T_0in,1+index_rseed_).*(nlpvalue_irg_snr___(:,1+nn_T_0in,1+index_rseed_)>3.0); tmp_irg_ = tmp_irg_(:);
tmp_est_ = corr_A_est_ofd_snr___(:,1+nn_T_0in,1+index_rseed_).*(nlpvalue_est_snr___(:,1+nn_T_0in,1+index_rseed_)>3.0); tmp_est_ = tmp_est_(:);
tmp_irg_win = numel(find(tmp_irg_>tmp_est_)); tmp_est_win = numel(find(tmp_est_>tmp_irg_));
plot(tmp_irg_,tmp_est_,'k.','MarkerSize',25);
hold off;
xlim([0,1]);
ylim([0,1]);
axis square;
xlabel('recovery irg');
ylabel('recovery sde');
title(sprintf('%d samples (sde %d vs irg %d)',n_T_0in,tmp_est_win,tmp_irg_win),'Interpreter','none');
end;%for nn_T_0in=0:n_n_T_0in-1;
sgtitle(sprintf('n_var %d',n_var),'Interpreter','none');
figbig;
%%%%%%%%;
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if ( ~exist(sprintf('%s.jpg',fname_fig),'file'));
