clear;
setup_OptiPlex; dir_trunk = '/home/rangan/dir_bcc/dir_dolphin';
%setup_access1; dir_trunk = '/data/rangan/dir_bcc/dir_dolphin';
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);
dir_mat = sprintf('%s/dir_mat',dir_trunk);
flag_replot=0;
flag_recalc=0;
flag_drift0=1;
flag_a_is_0=0;
flag_center=1;
verbose=0;

dZ = dolphin_dXX_collect_0(0,32);
n_var = numel(dZ.a_Z_);
clear dZ;

dXX_ = setdiff([0:143],[]); n_dXX = numel(dXX_);

fname_mat = sprintf('%s/dolphin_dXX_collect_1.mat',dir_mat);
if (~exist(fname_mat,'file'));
disp(sprintf(' %% %s not found, creating',fname_mat));
A_full_Z___ = zeros(n_var,n_var,n_dXX);
A_full_nlp___ = zeros(n_var,n_var,n_dXX);
A_full_found_ = zeros(n_dXX,1);
A_pair_Z___ = zeros(n_var,n_var,n_dXX);
A_pair_nlp___ = zeros(n_var,n_var,n_dXX);
A_pair_found_ = zeros(n_dXX,1);
for ndXX=0:n_dXX-1;
dXX = dXX_(1+ndXX);
disp(sprintf(' %% ndXX %d <-- dXX %d',ndXX,dXX));
try;
dZ = dolphin_dXX_collect_0(dXX,32);
A_full_Z___(:,:,1+ndXX) = dZ.A_Z__;
A_full_nlp___(:,:,1+ndXX) = dZ.A_nlp__;
clear dZ;
A_full_found_(1+ndXX)=1;
catch;
A_full_found_(1+ndXX)=0;
end;%try;
try;
dZ = dolphin_dXX_pair_cmb_collect_0(dXX,32);
A_pair_Z___(:,:,1+ndXX) = dZ.pair_A_cmb_Z__;
A_pair_nlp___(:,:,1+ndXX) = dZ.pair_A_cmb_nlp__;
clear dZ;
A_pair_found_(1+ndXX)=1;
catch;
A_pair_found_(1+ndXX)=0;
end;%try;
end;%for ndXX=0:n_dXX-1;
save(fname_mat);
end;%if (~exist(fname_mat,'file'));
if ( exist(fname_mat,'file'));
disp(sprintf(' %% %s found, not creating',fname_mat));
end;%if ( exist(fname_mat,'file'));
load(fname_mat);
%%%%%%%%
disp(sprintf(' %% A_full_found_ %d/%d',numel(efind(A_full_found_)),n_dXX));
disp(sprintf(' %% A_pair_found_ %d/%d',numel(efind(A_pair_found_)),n_dXX));
disp(sprintf(' %% A_both_found_ %d/%d',numel(efind(A_full_found_ & A_pair_found_)),n_dXX));
A_both_found_ = A_full_found_ & A_pair_found_;
tmp_index_ = efind(A_both_found_);
A_full_Z___ = A_full_Z___(:,:,1+tmp_index_);
A_full_nlp___ = A_full_nlp___(:,:,1+tmp_index_);
A_pair_Z___ = A_pair_Z___(:,:,1+tmp_index_);
A_pair_nlp___ = A_pair_nlp___(:,:,1+tmp_index_);
dXX_ = dXX_(1+tmp_index_);
n_dXX = numel(dXX_);

%%%%%%%%;
% Check correlation between full and pair. ;
% Note that full and pair are not correlated for individual dolphins. ;
%%%%%%%%;
flag_plot=0;
if flag_plot;
figure(1);clf;
c_ = colormap_beach(); n_c = size(c_,1);
subplot(1,2,1);
hold on;
for ndXX=n_dXX-1:-1:0;
dXX = dXX_(1+ndXX);
nc = max(0,min(n_c-1,floor(n_c*ndXX/n_dXX)));
A_full_Z__ = A_full_Z___(:,:,1+ndXX);
A_pair_Z__ = A_pair_Z___(:,:,1+ndXX);
disp(sprintf(' %% ndXX %d <-- dXX %d: corr %0.2f',ndXX,dXX,corr(A_full_Z__(:),A_pair_Z__(:))));
if (ndXX==0); plot(A_full_Z__(:),A_pair_Z__(:),'k.','MarkerSize',15); end;
if (ndXX> 0); plot(A_full_Z__(:),A_pair_Z__(:),'o','Color',c_(1+nc,:),'MarkerSize',10); end;
end;%for ndXX=0:n_dXX-1;
plot([-4,+4],[-4,+4],'k-');
plot(1.65*[-1;-1;+1;+1;-1],1.65*[-1;+1;+1;-1;-1],'k-');
xlim([-4,+4]); ylim([-4,+4]); xlabel('full'); ylabel('pair');
end;%if flag_plot;

%%%%%%%%;
% Calculate correlations between A_Z__ across dolphins. ;
% Note that the correlations for the pairs are higher (generally) than correlations for full. ;
%%%%%%%%;
flag_plot=0;
if flag_plot;
figure(1);clf;
%%%%%%%%;
subplot(2,2,1);
C_full_Z__ = zeros(n_dXX,n_dXX);
for ndXX0=0:n_dXX-1;
for ndXX1=0:n_dXX-1;
C_full_Z__(1+ndXX0,1+ndXX1) = corr(reshape(A_full_Z___(:,:,1+ndXX0),[n_var^2,1]),reshape(A_full_Z___(:,:,1+ndXX1),[n_var^2,1]));
end;%for ndXX0=1:n_dXX-1;
end;%for ndXX0=0:n_dXX-1;
[tmp_U,tmp_S,tmp_V] = svds(C_full_Z__,1); [~,tmp_U_ij] = sort(tmp_U(:,1)); tmp_U_index=tmp_U_ij-1;
imagesc(C_full_Z__(1+tmp_U_index,1+tmp_U_index),[-0.3,+0.3]);
axis image; axisnotick; title('C full');
colormap(colormap_beach());
subplot(2,2,3); plot(C_full_Z__(1,2:end),'.');
%%%%%%%%;
subplot(2,2,2);
C_pair_Z__ = zeros(n_dXX,n_dXX);
for ndXX0=0:n_dXX-1;
for ndXX1=0:n_dXX-1;
C_pair_Z__(1+ndXX0,1+ndXX1) = corr(reshape(A_pair_Z___(:,:,1+ndXX0),[n_var^2,1]),reshape(A_pair_Z___(:,:,1+ndXX1),[n_var^2,1]));
end;%for ndXX0=1:n_dXX-1;
end;%for ndXX0=0:n_dXX-1;
[tmp_U,tmp_S,tmp_V] = svds(C_pair_Z__,1); [~,tmp_U_ij] = sort(tmp_U(:,1)); tmp_U_index=tmp_U_ij-1;
imagesc(C_pair_Z__(1+tmp_U_index,1+tmp_U_index),[-0.3,+0.3]);
axis image; axisnotick; title('C pair');
colormap(colormap_beach());
subplot(2,2,4); plot(C_pair_Z__(1,2:end),'.');
%%%%%%%%;
end;%if flag_plot;

%%%%%%%%;
% With this in mind, we focus on the pair-wise (combined) interaction-matrix for individual dolphins. ;
% We compare the average Z-score for the pairwise interactions (across individual dolphins) ;
% with the Z_score for the pairwise interactions accumulated across all dolphins. ;
% These are correlated at 0.55, implying a reasonable link between the all-dolphin and single-dolphin pairwise-interactions. ;
% There is only a 0.21 correlation between the all-dolphin and single-dolphin fullwise-interactions. ;
%%%%%%%%;
flag_plot=0;
if flag_plot;
figure(1);clf;
A_Z_0__ = A_full_Z___(:,:,1+0);
A_Z_1__ = mean(A_full_Z___(:,:,1+[1:n_dXX-1]),3);
colormap(colormap_beach());
subplot(2,2,1); imagesc(A_Z_0__,[-4,+4]); axis image; title('full all');
subplot(2,2,2); imagesc(A_Z_1__,[-4,+4]); axis image; title('full ind');
figbig;
disp(sprintf(' %% full: ndXX %d <-- dXX %d: corr %0.2f',ndXX,dXX,corr(A_Z_0__(:),A_Z_1__(:))));
%%%%%%%%;
A_Z_0__ = A_pair_Z___(:,:,1+0);
A_Z_1__ = mean(A_pair_Z___(:,:,1+[1:n_dXX-1]),3);
colormap(colormap_beach());
subplot(2,2,3); imagesc(A_Z_0__,[-4,+4]); axis image; title('pair all');
subplot(2,2,4); imagesc(A_Z_1__,[-4,+4]); axis image; title('pair ind');
figbig;
disp(sprintf(' %% pair: ndXX %d <-- dXX %d: corr %0.2f',ndXX,dXX,corr(A_Z_0__(:),A_Z_1__(:))));
end;%if flag_plot;

%%%%%%%%;
% We repeat the above experiment after eliminating the diagonal terms. ;
% Now there is only a 0.47 correlation between the all-dolphin and single-dolphin pairwise-interactions. ;
% Now there is only a 0.15 correlation between the all-dolphin and single-dolphin fullwise-interactions. ;
%%%%%%%%;
flag_plot=0;
if flag_plot;
figure(1);clf;
A_Z_0__ = A_full_Z___(:,:,1+0); A_Z_0__ = A_Z_0__ - diag(diag(A_Z_0__));
A_Z_1__ = mean(A_full_Z___(:,:,1+[1:n_dXX-1]),3); A_Z_1__ = A_Z_1__ - diag(diag(A_Z_1__));
colormap(colormap_beach());
subplot(2,2,1); imagesc(A_Z_0__,[-4,+4]); axis image; title('full all');
subplot(2,2,2); imagesc(A_Z_1__,[-4,+4]); axis image; title('full ind');
figbig;
disp(sprintf(' %% full: ndXX %d <-- dXX %d: corr %0.2f',ndXX,dXX,corr(A_Z_0__(:),A_Z_1__(:))));
%%%%%%%%;
A_Z_0__ = A_pair_Z___(:,:,1+0); A_Z_0__ = A_Z_0__ - diag(diag(A_Z_0__));
A_Z_1__ = mean(A_pair_Z___(:,:,1+[1:n_dXX-1]),3); A_Z_1__ = A_Z_1__ - diag(diag(A_Z_1__));
colormap(colormap_beach());
subplot(2,2,3); imagesc(A_Z_0__,[-4,+4]); axis image; title('pair all');
subplot(2,2,4); imagesc(A_Z_1__,[-4,+4]); axis image; title('pair ind');
figbig;
disp(sprintf(' %% pair: ndXX %d <-- dXX %d: corr %0.2f',ndXX,dXX,corr(A_Z_0__(:),A_Z_1__(:))));
end;%if flag_plot;

%%%%%%%%;
% Now try and determine which individual dolphins are significantly different from the rest. ;
% For each dolphin we look only at the significant off-diagonal pairwise-interactions. ;
% We construct a (sparsified) pairwise-interaction matrix with +1/-1 entries for each significant pairwise-interaction. ;
% We measure the fnorm difference between this (sparsified) pairwise-interaction-matrix S ;
% and that accumulated across all dolphins. ;
% This by itself is not too useful, because the individual dolphins express different levels of significance. ;
% Some show many significant pairwise-interactions, other show few. ;
% So we also measure the number of agreements nSp, disagreements nSn, and mismatches nS0. ;
%%%%%%%%;
flag_plot=1;
if flag_plot;
S_Z___ = zeros(n_var,n_var,n_dXX);
for ndXX=n_dXX-1:-1:0;
dXX = dXX_(1+ndXX);
A_pair_Z__ = A_pair_Z___(:,:,1+ndXX);
A_pair_nlp__ = -z_to_p_twosided_0(A_pair_Z__);
tmp_index_ = efind(A_pair_nlp__>=-log(0.05));
tmp_S__ = zeros(n_var,n_var);
%tmp_S__(1+tmp_index_) = A_pair_Z__(1+tmp_index_);
tmp_S__(1+tmp_index_) = sign(A_pair_Z__(1+tmp_index_));
for nvar=0:n_var-1; tmp_S__(1+nvar,1+nvar) = 0; end;
S_Z___(:,:,1+ndXX) = tmp_S__; clear tmp_S__;
end;%for ndXX=0:n_dXX-1;
dS_Z_ = zeros(n_dXX,1);
nSp_Z_ = zeros(n_dXX,1);
nSn_Z_ = zeros(n_dXX,1);
nS0_Z_ = zeros(n_dXX,1);
nS1_Z_ = zeros(n_dXX,1);
for ndXX=0:n_dXX-1;
dS_Z_(1+ndXX) = fnorm(S_Z___(:,:,1+0)-S_Z___(:,:,1+ndXX)); %<-- fnorm of difference. ;
nSp_Z_(1+ndXX) = sum(abs( ( S_Z___(:,:,1+0) == +1*S_Z___(:,:,1+ndXX) ) & (S_Z___(:,:,1+0)~=0) ),'all'); %<-- number of agreements. ;
nSn_Z_(1+ndXX) = sum(abs( ( S_Z___(:,:,1+0) == -1*S_Z___(:,:,1+ndXX) ) & (S_Z___(:,:,1+0)~=0) ),'all'); %<-- number of disagreements. ;
nS0_Z_(1+ndXX) = sum(abs( (S_Z___(:,:,1+0)~=0) &  (S_Z___(:,:,1+ndXX)==0) ),'all'); %<-- number of differences. ;
nS1_Z_(1+ndXX) = sum(abs( (S_Z___(:,:,1+0)==0) &  (S_Z___(:,:,1+ndXX)~=0) ),'all'); %<-- number of differences. ;
end;%for ndXX=0:n_dXX-1;
figure(1);clf;
plot(1:n_dXX,nSp_Z_,'rs',1:n_dXX,nSn_Z_,'bx',1:n_dXX,nS0_Z_,'go',1:n_dXX,-nS1_Z_,'go',1:n_dXX,nSn_Z_+nSp_Z_+nS0_Z_,'k.');
legend({'same','diff','miss0','miss1','sum'});
xlabel('dXX');ylabel('#');
%%%%%%%%;
figure(2);clf;
colormap(colormap_pm());
for ndXX=0:n_dXX-1;
dXX = dXX_(1+ndXX);
subplot(8,16,1+ndXX);
imagesc(S_Z___(:,:,1+ndXX));
axisnotick; axis image;
title(sprintf('%d',dXX));
end;%for ndXX=0:n_dXX-1;
figbig;
%%%%%%%%;
figure(3);clf;
colormap(colormap_beach());
for ndXX=0:n_dXX-1;
dXX = dXX_(1+ndXX);
subplot(8,16,1+ndXX);
imagesc(A_pair_nlp___(:,:,1+ndXX),[0,6]);
axisnotick; axis image;
title(sprintf('%d',dXX));
end;%for ndXX=0:n_dXX-1;
figbig;
%%%%%%%%;
end;%if flag_plot;




