clear;
setup_OptiPlex;
dir_trunk = '/home/rangan/dir_bcc/dir_dolphin';
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);
fname_data = sprintf('%s/Dolphin_Data_201918755_s2.xlsx',dir_trunk);
T_ = readtable(fname_data);
aid_ = T_{:,1};
age_ = T_{:,4};
nvar_base = 7;
dat__ = T_{:,(1+nvar_base):end};
n_var = size(dat__,2);
string_dat_name_ = cell(n_var,1);
for nvar=0:n_var-1;
string_dat_name_{1+nvar} = T_.Properties.VariableNames{1+nvar_base+nvar};
end;%for nvar=0:n_var-1;
u_aid_ = unique(aid_);
n_aid = numel(u_aid_);
n_aid_ = zeros(n_aid,1);
index_aid__ = cell(n_aid,1);
for naid=0:n_aid-1;
index_aid__{1+naid} = efind(aid_==u_aid_(1+naid));
n_aid_(1+naid) = numel(index_aid__{1+naid});
end;%for naid=0:n_aid-1;

%{
  figure(1);
  clf;
  c_ = colormap_beach(); n_c = size(c_,1);
  n_plot_row = 5;
  n_plot_col = 10;
  nplot=0;
  for nvar=0:24;%for nvar=0:n_var-1;
  for naid=0:n_aid-1;
  nc = max(0,min(n_c-1,floor(n_c*naid/n_aid)));
  tmp_index_finite_ = efind(isfinite(dat__(1+index_aid__{1+naid},1+nvar)));
  tmp_index_aid_ = index_aid__{1+naid}(1+tmp_index_finite_);
  tmp_age_ = age_(1+tmp_index_aid_);
  [tmp_age_,tmp_index_] = sort(tmp_age_,'ascend'); tmp_index_ = tmp_index_-1;
  tmp_var_ = dat__(1+tmp_index_aid_,1+nvar); tmp_var_ = tmp_var_(1+tmp_index_);
  dt_ = diff(tmp_age_);
  dv_ = diff(tmp_var_);
  subplot(n_plot_row,n_plot_col,1+nplot+0);
  hold on;
  plot(dt_,dv_,'.','Color',c_(1+nc,:));
  hold off;
  subplot(n_plot_row,n_plot_col,1+nplot+1);
  hold on;
  plot(tmp_age_,tmp_var_,'.-','Color',c_(1+nc,:));
  hold off;
  end;%for naid=0:n_aid-1;
  subplot(n_plot_row,n_plot_col,1+nplot+0); title(sprintf('%s',string_dat_name_{1+nvar}));
  subplot(n_plot_row,n_plot_col,1+nplot+1); title(sprintf('%s',string_dat_name_{1+nvar}));
  nplot=nplot+2;
  end;%for nvar=0:n_var-1;
  figbig;
  %}

flag_replot=1;
fname_fig = sprintf('%s/dolphin_dt_scatter',dir_jpg);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig));

figure(1);
clf;
c_ = colormap_beach(); n_c = size(c_,1);
n_plot_row = 5;
n_plot_col = 10;
nplot=0;
for nvar=0:24;%for nvar=0:n_var-1;
dt_all_ = [];
dv_all_ = [];
for naid=0:n_aid-1;
nc = max(0,min(n_c-1,floor(n_c*naid/n_aid)));
tmp_index_finite_ = efind(isfinite(dat__(1+index_aid__{1+naid},1+nvar)));
tmp_index_aid_ = index_aid__{1+naid}(1+tmp_index_finite_);
tmp_age_ = age_(1+tmp_index_aid_);
[tmp_age_,tmp_index_] = sort(tmp_age_,'ascend'); tmp_index_ = tmp_index_-1;
tmp_var_ = dat__(1+tmp_index_aid_,1+nvar); tmp_var_ = tmp_var_(1+tmp_index_);
dt_ = diff(tmp_age_);
dv_ = diff(tmp_var_);
dt_all_ = [dt_all_;dt_];
dv_all_ = [dv_all_;dv_];
subplot(n_plot_row,n_plot_col,1+nplot+0);
hold on;
plot(sqrt(dt_),dv_,'.','Color',c_(1+nc,:));
hold off;
end;%for naid=0:n_aid-1;
xlim_ = sqrt([0,5]);
ylim_ = prctile(dv_all_,[1,99]);
%subplot(n_plot_row,n_plot_col,1+nplot+1);
%plot(tmp_age_,tmp_var_,'.-','Color',c_(1+nc,:));
subplot(n_plot_row,n_plot_col,1+nplot+0);
xlim(xlim_); ylim(ylim_); title(sprintf('%s',string_dat_name_{1+nvar}));
subplot(n_plot_row,n_plot_col,1+nplot+1);
n_h = 32;
tmp_h__ = hist2d_0(sqrt(dt_all_),dv_all_,n_h,n_h,xlim_,ylim_);
tmp_e_ = linspace(ylim_(1),ylim_(2),n_h);
tmp_b_ = 1:n_h;
tmp_avg_ = zeros(n_h,1);
tmp_std_ = zeros(n_h,1);
for nh=0:n_h-1;
tmp_h__(:,1+nh) = tmp_h__(:,1+nh)/max(1,sum(tmp_h__(:,1+nh)));
tmp_avg_(1+nh) = dot(tmp_b_,tmp_h__(:,1+nh));
tmp_std_(1+nh) = sqrt(dot(tmp_b_.*tmp_b_,tmp_h__(:,1+nh)) - tmp_avg_(1+nh).^2);
end;%for nh=0:31;
hold on;
imagesc(tmp_h__,[0.02,0.20]);
colormap(colormap_beach());
plot(tmp_b_,tmp_avg_,'k.');
plot(tmp_b_,tmp_avg_+1.0*tmp_std_,'k.');
plot(tmp_b_,tmp_avg_-1.0*tmp_std_,'k.');
hold off;
xlim([1,n_h]); ylim([1,n_h]);
axisnotick;
title(sprintf('%s',string_dat_name_{1+nvar}));
nplot=nplot+2;
end;%for nvar=0:n_var-1;
figbig;

sgtitle('sqrt(dt) horizontal, dv vertical')
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

