clear;

setup_OptiPlex; dir_trunk = '/home/rangan/dir_bcc/dir_dolphin';
%setup_access1; dir_trunk = '/data/rangan/dir_bcc/dir_dolphin';

dir_R = sprintf('%s/dir_R',dir_trunk);
dir_irg_csv = sprintf('%s/dir_irg_csv',dir_R);
dir_irg_mat = sprintf('%s/dir_irg_mat',dir_R);
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);

dt_avg = 0.257; %<-- matches d00 data. ;
relative_variation = 0.8973; %<-- matches d00 data. ;

n_T_0in_ = [128,256,512,1024]; n_n_T_0in = numel(n_T_0in_);
snr_ = 2.^[-3:+0.5:+3]; n_snr = numel(snr_);
rseed_ = 0:16; n_rseed = numel(rseed_);

n_var = 2;

flag_replot = 1;

found_flag_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
found_flag_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
found_flag_irg_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_c0_est_ofd_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_a_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_BB_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_CC_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
pvalue_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
nlpvalue_c0_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_c1_est_ofd_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_a_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_BB_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_CC_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
pvalue_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
nlpvalue_c1_est_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
corr_A_irg_ofd_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
pvalue_irg_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
nlpvalue_irg_snr___ = zeros(n_snr,n_n_T_0in,n_rseed);
for nn_T_0in=0:n_n_T_0in-1;
n_T_0in = n_T_0in_(1+nn_T_0in);
for nrseed=0:n_rseed-1;
rseed = rseed_(1+nrseed);
for nsnr=0:n_snr-1;
snr = snr_(1+nsnr);
%dolphin_test_6(rseed,n_var,dt_avg,n_T_0in,relative_variation,snr);
string_infix = dolphin_test_6_infix(rseed,n_var,dt_avg,n_T_0in,relative_variation,snr);
fname_dat_mat = sprintf('%s/%s_dat__.mat',dir_irg_mat,string_infix);
fname_age_csv = sprintf('%s/%s_age_.csv',dir_irg_csv,string_infix);
fname_dat_csv = sprintf('%s/%s_dat__.csv',dir_irg_csv,string_infix);
fname_c0_out_mat = sprintf('%s/%s_c0_out.mat',dir_irg_mat,string_infix);
fname_c1_out_mat = sprintf('%s/%s_c1_out.mat',dir_irg_mat,string_infix);
fname_irg_R = sprintf('%s/%s_irg.R',dir_R,string_infix);
fname_irg_out = sprintf('%s/%s_irg_out__.csv',dir_irg_csv,string_infix);
%%%%%%%%;
if ( exist(fname_c0_out_mat,'file') );
found_flag_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = 1;
tmp_mat_ = load(fname_c0_out_mat);
tmp_a_tru_ = tmp_mat_.tru_.a_tru_;
tmp_a_est_ = tmp_mat_.est_.a_est_;
tmp_A_tru__ = tmp_mat_.tru_.A_tru__;
tmp_A_est__ = tmp_mat_.est_.A_est__;
tmp_BB_tru__ = tmp_mat_.tru_.BB_tru__;
tmp_BB_est__ = tmp_mat_.est_.BB_est__;
tmp_CC_tru__ = tmp_mat_.tru_.CC_tru__;
tmp_CC_est__ = tmp_mat_.est_.CC_est__;
tmp_A_tru_ofd__ = tmp_A_tru__ - diag(diag(tmp_A_tru__));
tmp_A_est_ofd__ = tmp_A_est__ - diag(diag(tmp_A_est__));
corr_A_c0_est_ofd = corr(tmp_A_tru_ofd__(:),tmp_A_est_ofd__(:));
corr_a_c0_est = corr(tmp_a_tru_(:),tmp_a_est_(:));
corr_A_c0_est = corr(tmp_A_tru__(:),tmp_A_est__(:));
corr_BB_c0_est = corr(tmp_BB_tru__(:),tmp_BB_est__(:));
corr_CC_c0_est = corr(tmp_CC_tru__(:),tmp_CC_est__(:));
pvalue_c0_est = exp(-tmp_mat_.null_.L_nlp);
nlpvalue_c0_est = tmp_mat_.null_.L_nlp;
corr_A_c0_est_ofd_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_c0_est_ofd;
corr_a_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_a_c0_est;
corr_A_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_c0_est;
corr_BB_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_BB_c0_est;
corr_CC_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_CC_c0_est;
pvalue_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = pvalue_c0_est;
nlpvalue_c0_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = nlpvalue_c0_est;
end;%if ( exist(fname_out_mat,'file') &  exist(fname_irg_out,'file') );
%%%%%%%%;
if ( exist(fname_c1_out_mat,'file') );
found_flag_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = 1;
tmp_mat_ = load(fname_c1_out_mat);
tmp_a_tru_ = tmp_mat_.tru_.a_tru_;
tmp_a_est_ = tmp_mat_.est_.a_est_;
tmp_A_tru__ = tmp_mat_.tru_.A_tru__;
tmp_A_est__ = tmp_mat_.est_.A_est__;
tmp_BB_tru__ = tmp_mat_.tru_.BB_tru__;
tmp_BB_est__ = tmp_mat_.est_.BB_est__;
tmp_CC_tru__ = tmp_mat_.tru_.CC_tru__;
tmp_CC_est__ = tmp_mat_.est_.CC_est__;
tmp_A_tru_ofd__ = tmp_A_tru__ - diag(diag(tmp_A_tru__));
tmp_A_est_ofd__ = tmp_A_est__ - diag(diag(tmp_A_est__));
corr_A_c1_est_ofd = corr(tmp_A_tru_ofd__(:),tmp_A_est_ofd__(:));
corr_a_c1_est = corr(tmp_a_tru_(:),tmp_a_est_(:));
corr_A_c1_est = corr(tmp_A_tru__(:),tmp_A_est__(:));
corr_BB_c1_est = corr(tmp_BB_tru__(:),tmp_BB_est__(:));
corr_CC_c1_est = corr(tmp_CC_tru__(:),tmp_CC_est__(:));
pvalue_c1_est = exp(-tmp_mat_.null_.L_nlp);
nlpvalue_c1_est = tmp_mat_.null_.L_nlp;
corr_A_c1_est_ofd_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_c1_est_ofd;
corr_a_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_a_c1_est;
corr_A_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_c1_est;
corr_BB_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_BB_c1_est;
corr_CC_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_CC_c1_est;
pvalue_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = pvalue_c1_est;
nlpvalue_c1_est_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = nlpvalue_c1_est;
end;%if ( exist(fname_out_mat,'file') &  exist(fname_irg_out,'file') );
%%%%%%%%;
if ( exist(fname_c0_out_mat,'file') & exist(fname_irg_out,'file') );
found_flag_irg_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = 1;
tmp_irg_ = textread(fname_irg_out); %<-- nvar0 nvar1 pval A01_v A01_t A10_v A10_t ;
tmp_irg_ = transpose(tmp_irg_); tmp_irg_ = tmp_irg_(:);
tmp_A_tru__ = tmp_mat_.tru_.A_tru__;
tmp_A_irg__ = [0 , tmp_irg_(1+3) ; tmp_irg_(1+5) , 0];
tmp_A_tru_ofd__ = tmp_A_tru__ - diag(diag(tmp_A_tru__));
tmp_A_irg_ofd__ = tmp_A_irg__ - diag(diag(tmp_A_irg__));
corr_A_irg_ofd = corr(tmp_A_tru_ofd__(:),tmp_A_irg_ofd__(:));
pvalue_irg = tmp_irg_(1+2);
nlpvalue_irg = -log(tmp_irg_(1+2));
corr_A_irg_ofd_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = corr_A_irg_ofd;
pvalue_irg_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = pvalue_irg;
nlpvalue_irg_snr___(1+nsnr,1+nn_T_0in,1+nrseed) = nlpvalue_irg;
end;%if ( exist(fname_out_mat,'file') &  exist(fname_irg_out,'file') );
%%%%%%%%;
end;%for nsnr=0:n_snr-1;
end;%for nrseed=0:n_rseed-1;
end;%for nn_T_0in=0:n_n_T_0in-1;

disp(sprintf(' %% c0_est: found %d/%d',sum(found_flag_c0_est_snr___(:)),n_snr*n_n_T_0in*n_rseed));
disp(sprintf(' %% c1_est: found %d/%d',sum(found_flag_c1_est_snr___(:)),n_snr*n_n_T_0in*n_rseed));
disp(sprintf(' %% irg: found %d/%d',sum(found_flag_irg_snr___(:)),n_snr*n_n_T_0in*n_rseed));

index_rseed_ = setdiff(0:n_rseed-1,[15]-1);
found_flag_c0_est_sn__ = sum(found_flag_c0_est_snr___(:,:,1+index_rseed_),3);
found_flag_c1_est_sn__ = sum(found_flag_c1_est_snr___(:,:,1+index_rseed_),3);
found_flag_irg_sn__ = sum(found_flag_irg_snr___(:,:,1+index_rseed_),3);
%%%%%%%%;
corr_A_c0_est_ofd_sn__ = sum(corr_A_c0_est_ofd_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
corr_a_c0_est_sn__ = sum(corr_a_c0_est_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
corr_A_c0_est_sn__ = sum(corr_A_c0_est_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
corr_BB_c0_est_sn__ = sum(corr_BB_c0_est_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
corr_CC_c0_est_sn__ = sum(corr_CC_c0_est_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
pvalue_c0_est_sn__ = sum(pvalue_c0_est_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
nlpvalue_c0_est_sn__ = sum(nlpvalue_c0_est_snr___(:,:,1+index_rseed_),3)./found_flag_c0_est_sn__;
okay_A_c0_est_ofd_sn__ = sum( corr_A_c0_est_ofd_snr___(:,:,1+index_rseed_).*(nlpvalue_c0_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c0_est_sn__;
okay_a_c0_est_sn__ = sum( corr_a_c0_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c0_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c0_est_sn__;
okay_A_c0_est_sn__ = sum( corr_A_c0_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c0_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c0_est_sn__;
okay_BB_c0_est_sn__ = sum( corr_BB_c0_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c0_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c0_est_sn__;
okay_CC_c0_est_sn__ = sum( corr_CC_c0_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c0_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c0_est_sn__;
%%%%%%%%;
corr_A_c1_est_ofd_sn__ = sum(corr_A_c1_est_ofd_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
corr_a_c1_est_sn__ = sum(corr_a_c1_est_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
corr_A_c1_est_sn__ = sum(corr_A_c1_est_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
corr_BB_c1_est_sn__ = sum(corr_BB_c1_est_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
corr_CC_c1_est_sn__ = sum(corr_CC_c1_est_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
pvalue_c1_est_sn__ = sum(pvalue_c1_est_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
nlpvalue_c1_est_sn__ = sum(nlpvalue_c1_est_snr___(:,:,1+index_rseed_),3)./found_flag_c1_est_sn__;
okay_A_c1_est_ofd_sn__ = sum( corr_A_c1_est_ofd_snr___(:,:,1+index_rseed_).*(nlpvalue_c1_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c1_est_sn__;
okay_a_c1_est_sn__ = sum( corr_a_c1_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c1_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c1_est_sn__;
okay_A_c1_est_sn__ = sum( corr_A_c1_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c1_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c1_est_sn__;
okay_BB_c1_est_sn__ = sum( corr_BB_c1_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c1_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c1_est_sn__;
okay_CC_c1_est_sn__ = sum( corr_CC_c1_est_snr___(:,:,1+index_rseed_).*(nlpvalue_c1_est_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_c1_est_sn__;
%%%%%%%%;
corr_A_irg_ofd_sn__ = sum(corr_A_irg_ofd_snr___(:,:,1+index_rseed_),3)./found_flag_irg_sn__;
pvalue_irg_sn__ = sum(pvalue_irg_snr___(:,:,1+index_rseed_),3)./found_flag_irg_sn__;
nlpvalue_irg_sn__ = sum(nlpvalue_irg_snr___(:,:,1+index_rseed_),3)./found_flag_irg_sn__;
okay_irg_sn__ = sum( corr_A_irg_ofd_snr___(:,:,1+index_rseed_).*(nlpvalue_irg_snr___(:,:,1+index_rseed_)>3.0) , 3)./found_flag_irg_sn__;


fname_fig = sprintf('%s/dolphin_test_6_collect_n%d_FIGA',dir_jpg,n_var);
if ( flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file')); 
disp(sprintf(' %% %s not found, creating',fname_fig));
figure(1);clf;figbig;np=0;
for nn_T_0in=0:n_n_T_0in-1;
n_T_0in = n_T_0in_(1+nn_T_0in);
%%%%%%%%;
subplot(4,5,1+np);np=np+1;
hold on;
plot(log2(snr_),okay_a_c0_est_sn__(:,1+nn_T_0in),'ro-','LineWidth',2);
plot(log2(snr_),okay_a_c1_est_sn__(:,1+nn_T_0in),'mo-','LineWidth',2);
hold off;
xlim([min(log2(snr_)),max(log2(snr_))]);
ylim([0,1]);
xlabel('log2(snr)');
ylabel('recovery');
title(sprintf('a %d samples',n_T_0in),'Interpreter','none');
%%%%%%%%;
subplot(4,5,1+np);np=np+1;
hold on;
plot(log2(snr_),okay_A_c0_est_ofd_sn__(:,1+nn_T_0in),'ro-','LineWidth',2);
plot(log2(snr_),okay_A_c1_est_ofd_sn__(:,1+nn_T_0in),'mo-','LineWidth',2);
%plot(log2(snr_),okay_irg_sn__(:,1+nn_T_0in),'bx-','LineWidth',2);
hold off;
xlim([min(log2(snr_)),max(log2(snr_))]);
ylim([0,1]);
xlabel('log2(snr)');
ylabel('recovery');
title(sprintf('A_ofd %d samples',n_T_0in),'Interpreter','none');
%%%%%%%%;
subplot(4,5,1+np);np=np+1;
hold on;
plot(log2(snr_),okay_A_c0_est_sn__(:,1+nn_T_0in),'ro-','LineWidth',2);
plot(log2(snr_),okay_A_c1_est_sn__(:,1+nn_T_0in),'mo-','LineWidth',2);
hold off;
xlim([min(log2(snr_)),max(log2(snr_))]);
ylim([0,1]);
xlabel('log2(snr)');
ylabel('recovery');
title(sprintf('A %d samples',n_T_0in),'Interpreter','none');
%%%%%%%%;
subplot(4,5,1+np);np=np+1;
hold on;
plot(log2(snr_),okay_BB_c0_est_sn__(:,1+nn_T_0in),'ro-','LineWidth',2);
plot(log2(snr_),okay_BB_c1_est_sn__(:,1+nn_T_0in),'mo-','LineWidth',2);
hold off;
xlim([min(log2(snr_)),max(log2(snr_))]);
ylim([0,1]);
xlabel('log2(snr)');
ylabel('recovery');
title(sprintf('BB %d samples',n_T_0in),'Interpreter','none');
%%%%%%%%;
subplot(4,5,1+np);np=np+1;
hold on;
plot(log2(snr_),okay_CC_c0_est_sn__(:,1+nn_T_0in),'ro-','LineWidth',2);
plot(log2(snr_),okay_CC_c1_est_sn__(:,1+nn_T_0in),'mo-','LineWidth',2);
hold off;
xlim([min(log2(snr_)),max(log2(snr_))]);
ylim([0,1]);
xlabel('log2(snr)');
ylabel('recovery');
title(sprintf('CC %d samples',n_T_0in),'Interpreter','none');
%%%%%%%%;
end;%for nn_T_0in=0:n_n_T_0in-1;
sgtitle(sprintf('n_var %d',n_var),'Interpreter','none');
figbig;
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if ( ~exist(sprintf('%s.jpg',fname_fig),'file'));

%{
fname_fig = sprintf('%s/dolphin_test_6_collect_n%d_FIGC',dir_jpg,n_var);
if ( flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file')); 
disp(sprintf(' %% %s not found, creating',fname_fig));
%%%%%%%%;
figure(2);clf;
for nn_T_0in=0:n_n_T_0in-1;
n_T_0in = n_T_0in_(1+nn_T_0in);
subplot(2,2,1+nn_T_0in);
hold on;
plot([0,1],[0,1],'k-');
plot([0,0],[0,1],'k-');
plot([0,1],[0,0],'k-');
tmp_irg_ = corr_A_irg_ofd_snr___(:,1+nn_T_0in,1+index_rseed_).*(nlpvalue_irg_snr___(:,1+nn_T_0in,1+index_rseed_)>3.0); tmp_irg_ = tmp_irg_(:);
tmp_est_ = corr_A_est_ofd_snr___(:,1+nn_T_0in,1+index_rseed_).*(nlpvalue_est_snr___(:,1+nn_T_0in,1+index_rseed_)>3.0); tmp_est_ = tmp_est_(:);
tmp_irg_win = numel(find(tmp_irg_>tmp_est_)); tmp_est_win = numel(find(tmp_est_>tmp_irg_));
plot(tmp_irg_,tmp_est_,'k.','MarkerSize',25);
hold off;
xlim([0,1]);
ylim([0,1]);
axis square;
xlabel('recovery irg');
ylabel('recovery sde');
title(sprintf('%d samples (sde %d vs irg %d)',n_T_0in,tmp_est_win,tmp_irg_win),'Interpreter','none');
end;%for nn_T_0in=0:n_n_T_0in-1;
sgtitle(sprintf('n_var %d',n_var),'Interpreter','none');
figbig;
%%%%%%%%;
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if ( ~exist(sprintf('%s.jpg',fname_fig),'file'));
%}
