function dolphin_dXX_bootstrap_4_collect();
%{
note that age-range is 0.64 --> 54.35. ;
%}

dXX = 0; n_shuffle = 256;
age_percentile_range_ = [];

setup_OptiPlex; dir_trunk = '/home/rangan/dir_bcc/dir_dolphin';
%setup_access1; dir_trunk = '/data/rangan/dir_bcc/dir_dolphin';
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);
dir_mat = sprintf('%s/dir_mat',dir_trunk);
dir_bootstrap_mat = sprintf('%s/dir_bootstrap_mat',dir_trunk);
dir_shuffle_mat = sprintf('%s/dir_shuffle_mat',dir_trunk);

flag_replot=1;

flag_drift0=1;
flag_a_is_0=0;
flag_center=1;

if ( isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2dd%dc%d',dXX,flag_drift0,flag_center);
end;%if ( isempty(age_percentile_range_));
if (~isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2d_age%.2d%.2d_d%dc%d',dXX,min(age_percentile_range_),min(99,max(age_percentile_range_)),flag_drift0,flag_center);
end;%if (~isempty(age_percentile_range_));
disp(sprintf(' %% fname_infix %s',fname_infix));

dolphin_dXX_load_3;

%%%%%%%%;
% select age range. ;
%%%%%%%%;
if (~isempty(age_percentile_range_));
tmp_index_ = efind(age_>=prctile(age_,min(age_percentile_range_)) & age_<=prctile(age_,max(age_percentile_range_)));
disp(sprintf(' %% age_percentile_range_ [%0.2f %0.2f] --> [%0.2f %0.2f] <-- %d found',age_percentile_range_,prctile(age_,age_percentile_range_),numel(tmp_index_)));
aid_ = aid_(1+tmp_index_);
age_ = age_(1+tmp_index_);
dat__ = dat__(1+tmp_index_,:);
end;%if (~isempty(age_percentile_range_));

index_mss_ = efind(~isfinite(dat__));

fname_infix_0099 = sprintf('aid%.2dd%dc%d',dXX,flag_drift0,flag_center);
fname_infix_0050 = sprintf('aid%.2d_age%.2d%.2d_d%dc%d',dXX, 0,50,flag_drift0,flag_center);
fname_infix_2575 = sprintf('aid%.2d_age%.2d%.2d_d%dc%d',dXX,25,75,flag_drift0,flag_center);
fname_infix_5099 = sprintf('aid%.2d_age%.2d%.2d_d%dc%d',dXX,50,99,flag_drift0,flag_center);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 0099 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_0099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0099);
if ( exist(fname_mat_0099_o,'file'));
tmp_ = load(fname_mat_0099_o);
a_0099_o_ = tmp_.a_;
A_0099_o__ = tmp_.A__;
BB_0099_o__ = tmp_.BB__;
CC_0099_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_0099_s,'file'));
%%%%%%%%;
a_avg_0099_ = zeros(n_var,1); a_std_0099_ = zeros(n_var,1);
A_avg_0099__ = zeros(n_var,n_var); A_std_0099__ = zeros(n_var,n_var);
BB_avg_0099__ = zeros(n_var,n_var); BB_std_0099__ = zeros(n_var,n_var);
CC_avg_0099__ = zeros(n_var,n_var); CC_std_0099__ = zeros(n_var,n_var);
n_found_0099 = 0;
for nshuffle=1:n_shuffle;
fname_mat_0099_s = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_0099,nshuffle);
if ( exist(fname_mat_0099_s,'file'));
tmp_ = load(fname_mat_0099_s);
a_s_ = tmp_.a_; a_avg_0099_ = a_avg_0099_ + a_s_.^1; a_std_0099_ = a_std_0099_ + a_s_.^2;
A_s__ = tmp_.A__; A_avg_0099__ = A_avg_0099__ + A_s__.^1; A_std_0099__ = A_std_0099__ + A_s__.^2;
BB_s__ = tmp_.BB__; BB_avg_0099__ = BB_avg_0099__ + BB_s__.^1; BB_std_0099__ = BB_std_0099__ + BB_s__.^2;
CC_s__ = tmp_.CC__; CC_avg_0099__ = CC_avg_0099__ + CC_s__.^1; CC_std_0099__ = CC_std_0099__ + CC_s__.^2;
n_found_0099 = n_found_0099+1;
end;%if ( exist(fname_mat_0099_s,'file'));
end;%for nshuffle=1:n_shuffle;
a_avg_0099_ = a_avg_0099_/n_found_0099; a_std_0099_ = sqrt(a_std_0099_/n_found_0099 - a_avg_0099_.^2); a_nlp_0099_ = -z_to_p_twosided_0((a_0099_o_ - a_avg_0099_)./a_std_0099_);
A_avg_0099__ = A_avg_0099__/n_found_0099; A_std_0099__ = sqrt(A_std_0099__/n_found_0099 - A_avg_0099__.^2); A_nlp_0099__ = -z_to_p_twosided_0((A_0099_o__ - A_avg_0099__)./A_std_0099__);
BB_avg_0099__ = BB_avg_0099__/n_found_0099; BB_std_0099__ = sqrt(BB_std_0099__/n_found_0099 - BB_avg_0099__.^2); BB_nlp_0099__ = -z_to_p_twosided_0((BB_0099_o__ - BB_avg_0099__)./BB_std_0099__);
CC_avg_0099__ = CC_avg_0099__/n_found_0099; CC_std_0099__ = sqrt(CC_std_0099__/n_found_0099 - CC_avg_0099__.^2); CC_nlp_0099__ = -z_to_p_twosided_0((CC_0099_o__ - CC_avg_0099__)./CC_std_0099__);
%%%%%%%%;
disp(sprintf(' %% n_found_0099 %d',n_found_0099'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_0099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_0099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_0099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_0099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = sign(a_avg_0099_(1+nvar)).*a_nlp_0099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_0099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(A_avg_0099__).*A_nlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(sign(BB_avg_0099__).*BB_nlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(CC_avg_0099__).*CC_nlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 0050 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_0050_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0050);
if ( exist(fname_mat_0050_o,'file'));
tmp_ = load(fname_mat_0050_o);
a_0050_o_ = tmp_.a_;
A_0050_o__ = tmp_.A__;
BB_0050_o__ = tmp_.BB__;
CC_0050_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_0050_s,'file'));
%%%%%%%%;
a_avg_0050_ = zeros(n_var,1); a_std_0050_ = zeros(n_var,1);
A_avg_0050__ = zeros(n_var,n_var); A_std_0050__ = zeros(n_var,n_var);
BB_avg_0050__ = zeros(n_var,n_var); BB_std_0050__ = zeros(n_var,n_var);
CC_avg_0050__ = zeros(n_var,n_var); CC_std_0050__ = zeros(n_var,n_var);
n_found_0050 = 0;
for nshuffle=1:n_shuffle;
fname_mat_0050_s = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_0050,nshuffle);
if ( exist(fname_mat_0050_s,'file'));
tmp_ = load(fname_mat_0050_s);
a_s_ = tmp_.a_; a_avg_0050_ = a_avg_0050_ + a_s_.^1; a_std_0050_ = a_std_0050_ + a_s_.^2;
A_s__ = tmp_.A__; A_avg_0050__ = A_avg_0050__ + A_s__.^1; A_std_0050__ = A_std_0050__ + A_s__.^2;
BB_s__ = tmp_.BB__; BB_avg_0050__ = BB_avg_0050__ + BB_s__.^1; BB_std_0050__ = BB_std_0050__ + BB_s__.^2;
CC_s__ = tmp_.CC__; CC_avg_0050__ = CC_avg_0050__ + CC_s__.^1; CC_std_0050__ = CC_std_0050__ + CC_s__.^2;
n_found_0050 = n_found_0050+1;
end;%if ( exist(fname_mat_0050_s,'file'));
end;%for nshuffle=1:n_shuffle;
a_avg_0050_ = a_avg_0050_/n_found_0050; a_std_0050_ = sqrt(a_std_0050_/n_found_0050 - a_avg_0050_.^2); a_nlp_0050_ = -z_to_p_twosided_0((a_0050_o_ - a_avg_0050_)./a_std_0050_);
A_avg_0050__ = A_avg_0050__/n_found_0050; A_std_0050__ = sqrt(A_std_0050__/n_found_0050 - A_avg_0050__.^2); A_nlp_0050__ = -z_to_p_twosided_0((A_0050_o__ - A_avg_0050__)./A_std_0050__);
BB_avg_0050__ = BB_avg_0050__/n_found_0050; BB_std_0050__ = sqrt(BB_std_0050__/n_found_0050 - BB_avg_0050__.^2); BB_nlp_0050__ = -z_to_p_twosided_0((BB_0050_o__ - BB_avg_0050__)./BB_std_0050__);
CC_avg_0050__ = CC_avg_0050__/n_found_0050; CC_std_0050__ = sqrt(CC_std_0050__/n_found_0050 - CC_avg_0050__.^2); CC_nlp_0050__ = -z_to_p_twosided_0((CC_0050_o__ - CC_avg_0050__)./CC_std_0050__);
%%%%%%%%;
disp(sprintf(' %% n_found_0050 %d',n_found_0050'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_0050);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_0050_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_0050_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_0050_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_0050_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = sign(a_avg_0050_(1+nvar)).*a_nlp_0050_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_0050_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(A_avg_0050__).*A_nlp_0050__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0050),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_0050);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(sign(BB_avg_0050__).*BB_nlp_0050__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(CC_avg_0050__).*CC_nlp_0050__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0050),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 2575 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_2575_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_2575);
if ( exist(fname_mat_2575_o,'file'));
tmp_ = load(fname_mat_2575_o);
a_2575_o_ = tmp_.a_;
A_2575_o__ = tmp_.A__;
BB_2575_o__ = tmp_.BB__;
CC_2575_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_2575_s,'file'));
%%%%%%%%;
a_avg_2575_ = zeros(n_var,1); a_std_2575_ = zeros(n_var,1);
A_avg_2575__ = zeros(n_var,n_var); A_std_2575__ = zeros(n_var,n_var);
BB_avg_2575__ = zeros(n_var,n_var); BB_std_2575__ = zeros(n_var,n_var);
CC_avg_2575__ = zeros(n_var,n_var); CC_std_2575__ = zeros(n_var,n_var);
n_found_2575 = 0;
for nshuffle=1:n_shuffle;
fname_mat_2575_s = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_2575,nshuffle);
if ( exist(fname_mat_2575_s,'file'));
tmp_ = load(fname_mat_2575_s);
a_s_ = tmp_.a_; a_avg_2575_ = a_avg_2575_ + a_s_.^1; a_std_2575_ = a_std_2575_ + a_s_.^2;
A_s__ = tmp_.A__; A_avg_2575__ = A_avg_2575__ + A_s__.^1; A_std_2575__ = A_std_2575__ + A_s__.^2;
BB_s__ = tmp_.BB__; BB_avg_2575__ = BB_avg_2575__ + BB_s__.^1; BB_std_2575__ = BB_std_2575__ + BB_s__.^2;
CC_s__ = tmp_.CC__; CC_avg_2575__ = CC_avg_2575__ + CC_s__.^1; CC_std_2575__ = CC_std_2575__ + CC_s__.^2;
n_found_2575 = n_found_2575+1;
end;%if ( exist(fname_mat_2575_s,'file'));
end;%for nshuffle=1:n_shuffle;
a_avg_2575_ = a_avg_2575_/n_found_2575; a_std_2575_ = sqrt(a_std_2575_/n_found_2575 - a_avg_2575_.^2); a_nlp_2575_ = -z_to_p_twosided_0((a_2575_o_ - a_avg_2575_)./a_std_2575_);
A_avg_2575__ = A_avg_2575__/n_found_2575; A_std_2575__ = sqrt(A_std_2575__/n_found_2575 - A_avg_2575__.^2); A_nlp_2575__ = -z_to_p_twosided_0((A_2575_o__ - A_avg_2575__)./A_std_2575__);
BB_avg_2575__ = BB_avg_2575__/n_found_2575; BB_std_2575__ = sqrt(BB_std_2575__/n_found_2575 - BB_avg_2575__.^2); BB_nlp_2575__ = -z_to_p_twosided_0((BB_2575_o__ - BB_avg_2575__)./BB_std_2575__);
CC_avg_2575__ = CC_avg_2575__/n_found_2575; CC_std_2575__ = sqrt(CC_std_2575__/n_found_2575 - CC_avg_2575__.^2); CC_nlp_2575__ = -z_to_p_twosided_0((CC_2575_o__ - CC_avg_2575__)./CC_std_2575__);
%%%%%%%%;
disp(sprintf(' %% n_found_2575 %d',n_found_2575'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_2575);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_2575_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_2575_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_2575_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_2575_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = sign(a_avg_2575_(1+nvar)).*a_nlp_2575_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_2575_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_2575__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_2575__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(A_avg_2575__).*A_nlp_2575__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_2575),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_2575);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_2575__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_2575__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(sign(BB_avg_2575__).*BB_nlp_2575__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_2575__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_2575__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(CC_avg_2575__).*CC_nlp_2575__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_2575__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_2575),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 5099 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_5099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_5099);
if ( exist(fname_mat_5099_o,'file'));
tmp_ = load(fname_mat_5099_o);
a_5099_o_ = tmp_.a_;
A_5099_o__ = tmp_.A__;
BB_5099_o__ = tmp_.BB__;
CC_5099_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_5099_s,'file'));
%%%%%%%%;
a_avg_5099_ = zeros(n_var,1); a_std_5099_ = zeros(n_var,1);
A_avg_5099__ = zeros(n_var,n_var); A_std_5099__ = zeros(n_var,n_var);
BB_avg_5099__ = zeros(n_var,n_var); BB_std_5099__ = zeros(n_var,n_var);
CC_avg_5099__ = zeros(n_var,n_var); CC_std_5099__ = zeros(n_var,n_var);
n_found_5099 = 0;
for nshuffle=1:n_shuffle;
fname_mat_5099_s = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_5099,nshuffle);
if ( exist(fname_mat_5099_s,'file'));
tmp_ = load(fname_mat_5099_s);
a_s_ = tmp_.a_; a_avg_5099_ = a_avg_5099_ + a_s_.^1; a_std_5099_ = a_std_5099_ + a_s_.^2;
A_s__ = tmp_.A__; A_avg_5099__ = A_avg_5099__ + A_s__.^1; A_std_5099__ = A_std_5099__ + A_s__.^2;
BB_s__ = tmp_.BB__; BB_avg_5099__ = BB_avg_5099__ + BB_s__.^1; BB_std_5099__ = BB_std_5099__ + BB_s__.^2;
CC_s__ = tmp_.CC__; CC_avg_5099__ = CC_avg_5099__ + CC_s__.^1; CC_std_5099__ = CC_std_5099__ + CC_s__.^2;
n_found_5099 = n_found_5099+1;
end;%if ( exist(fname_mat_5099_s,'file'));
end;%for nshuffle=1:n_shuffle;
a_avg_5099_ = a_avg_5099_/n_found_5099; a_std_5099_ = sqrt(a_std_5099_/n_found_5099 - a_avg_5099_.^2); a_nlp_5099_ = -z_to_p_twosided_0((a_5099_o_ - a_avg_5099_)./a_std_5099_);
A_avg_5099__ = A_avg_5099__/n_found_5099; A_std_5099__ = sqrt(A_std_5099__/n_found_5099 - A_avg_5099__.^2); A_nlp_5099__ = -z_to_p_twosided_0((A_5099_o__ - A_avg_5099__)./A_std_5099__);
BB_avg_5099__ = BB_avg_5099__/n_found_5099; BB_std_5099__ = sqrt(BB_std_5099__/n_found_5099 - BB_avg_5099__.^2); BB_nlp_5099__ = -z_to_p_twosided_0((BB_5099_o__ - BB_avg_5099__)./BB_std_5099__);
CC_avg_5099__ = CC_avg_5099__/n_found_5099; CC_std_5099__ = sqrt(CC_std_5099__/n_found_5099 - CC_avg_5099__.^2); CC_nlp_5099__ = -z_to_p_twosided_0((CC_5099_o__ - CC_avg_5099__)./CC_std_5099__);
%%%%%%%%;
disp(sprintf(' %% n_found_5099 %d',n_found_5099'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_5099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_5099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_5099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_5099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_5099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = sign(a_avg_5099_(1+nvar)).*a_nlp_5099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_5099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_5099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_5099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(A_avg_5099__).*A_nlp_5099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_5099),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_5099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_5099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_5099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(sign(BB_avg_5099__).*BB_nlp_5099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_5099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_5099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(CC_avg_5099__).*CC_nlp_5099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_5099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_5099),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% check distribution of shuffle coefficients. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
a_0099__ = zeros(n_var,2*n_shuffle);
A_0099__ = zeros(n_var^2,2*n_shuffle);
BB_0099__ = zeros(n_var^2,2*n_shuffle);
CC_0099__ = zeros(n_var^2,2*n_shuffle);
n_found_0099 = 0;
for nshuffle=1:n_shuffle;
fname_mat_0099_b0 = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_0099,nshuffle);
if ( exist(fname_mat_0099_b0,'file'));
tmp_ = load(fname_mat_0099_b0);
a_s = tmp_.a_; a_0099__(:,1+n_found_0099) = a_s(:);
A_s_ = tmp_.A__; A_0099__(:,1+n_found_0099) = A_s_(:);
BB_s_ = tmp_.BB__; BB_0099__(:,1+n_found_0099) = BB_s_(:);
CC_s_ = tmp_.CC__; CC_0099__(:,1+n_found_0099) = CC_s_(:);
n_found_0099 = n_found_0099+1;
end;%if ( exist(fname_mat_0099_b0,'file'));
end;%for nshuffle=1:n_shuffle;
%%%%%%%%;
disp(sprintf(' %% n_found_0099 %d',n_found_0099'));
%%%%%%%%;
a_0099__ = a_0099__(:,1:n_found_0099);
a_0099_nrm__ = (a_0099__ - repmat(mean(a_0099__,2),[1,n_found_0099]))./repmat(std(a_0099__,[],2),[1,n_found_0099]);
A_0099__ = A_0099__(:,1:n_found_0099);
A_0099_nrm__ = (A_0099__ - repmat(mean(A_0099__,2),[1,n_found_0099]))./repmat(std(A_0099__,[],2),[1,n_found_0099]);
BB_0099__ = BB_0099__(:,1:n_found_0099);
BB_0099_nrm__ = (BB_0099__ - repmat(mean(BB_0099__,2),[1,n_found_0099]))./repmat(std(BB_0099__,[],2),[1,n_found_0099]);
CC_0099__ = CC_0099__(:,1:n_found_0099);
CC_0099_nrm__ = (CC_0099__ - repmat(mean(CC_0099__,2),[1,n_found_0099]))./repmat(std(CC_0099__,[],2),[1,n_found_0099]);
%%%%%%%%;
% verdict: not exactly gaussian distributed; maybe we need another approach? ;
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% Now use the same approach to estimate the significant differences between 5099 and 0050. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_infix_5099_vs_0050 = sprintf('aid%.2d_age_5099_vs_0050_d%dc%d',dXX,flag_drift0,flag_center);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 5099_vs_0050 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
fname_mat_5099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_5099);
if ( exist(fname_mat_5099_o,'file'));
tmp_ = load(fname_mat_5099_o);
a_5099_o_ = tmp_.a_;
A_5099_o__ = tmp_.A__;
BB_5099_o__ = tmp_.BB__;
CC_5099_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_5099_s,'file'));
fname_mat_0050_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0050);
if ( exist(fname_mat_0050_o,'file'));
tmp_ = load(fname_mat_0050_o);
a_0050_o_ = tmp_.a_;
A_0050_o__ = tmp_.A__;
BB_0050_o__ = tmp_.BB__;
CC_0050_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_0050_s,'file'));
a_5099_vs_0050_o_ = a_5099_o_ - a_0050_o_;
A_5099_vs_0050_o__ = A_5099_o__ - A_0050_o__;
BB_5099_vs_0050_o__ = BB_5099_o__ - BB_0050_o__;
CC_5099_vs_0050_o__ = CC_5099_o__ - CC_0050_o__;
%%%%%%%%;
a_avg_5099_vs_0050_ = zeros(n_var,1); a_std_5099_vs_0050_ = zeros(n_var,1);
A_avg_5099_vs_0050__ = zeros(n_var,n_var); A_std_5099_vs_0050__ = zeros(n_var,n_var);
BB_avg_5099_vs_0050__ = zeros(n_var,n_var); BB_std_5099_vs_0050__ = zeros(n_var,n_var);
CC_avg_5099_vs_0050__ = zeros(n_var,n_var); CC_std_5099_vs_0050__ = zeros(n_var,n_var);
n_found_5099_vs_0050 = 0;
for nshuffle=1:n_shuffle;
%%%%;
fname_mat_5099_s = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_5099,nshuffle);
fname_mat_0050_s = sprintf('%s/dolphin_%s_s%.4d.mat',dir_shuffle_mat,fname_infix_0050,nshuffle);
if ( exist(fname_mat_5099_s,'file') &  exist(fname_mat_0050_s,'file'));
tmp_5099 = load(fname_mat_5099_s);
tmp_0050 = load(fname_mat_0050_s);
a_s = tmp_5099.a_ - tmp_0050.a_;
A_s_ = tmp_5099.A__ - tmp_0050.A__;
BB_s_ = tmp_5099.BB__ - tmp_0050.BB__; 
CC_s_ = tmp_5099.CC__ - tmp_0050.CC__; 
a_avg_5099_vs_0050_ = a_avg_5099_vs_0050_ + a_s.^1; a_std_5099_vs_0050_ = a_std_5099_vs_0050_ + a_s.^2;
A_avg_5099_vs_0050__ = A_avg_5099_vs_0050__ + A_s_.^1; A_std_5099_vs_0050__ = A_std_5099_vs_0050__ + A_s_.^2;
BB_avg_5099_vs_0050__ = BB_avg_5099_vs_0050__ + BB_s_.^1; BB_std_5099_vs_0050__ = BB_std_5099_vs_0050__ + BB_s_.^2;
CC_avg_5099_vs_0050__ = CC_avg_5099_vs_0050__ + CC_s_.^1; CC_std_5099_vs_0050__ = CC_std_5099_vs_0050__ + CC_s_.^2;
n_found_5099_vs_0050 = n_found_5099_vs_0050+1;
end;%if ( exist(fname_mat_5099_s,'file') &  exist(fname_mat_0050_s,'file'));
%%%%;
end;%for nshuffle=1:n_shuffle;
a_avg_5099_vs_0050_ = a_avg_5099_vs_0050_/n_found_5099_vs_0050; a_std_5099_vs_0050_ = sqrt(a_std_5099_vs_0050_/n_found_5099_vs_0050 - a_avg_5099_vs_0050_.^2); a_nlp_5099_vs_0050_ = -z_to_p_twosided_0((a_5099_vs_0050_o_ - a_avg_5099_vs_0050_)./a_std_5099_vs_0050_);
A_avg_5099_vs_0050__ = A_avg_5099_vs_0050__/n_found_5099_vs_0050; A_std_5099_vs_0050__ = sqrt(A_std_5099_vs_0050__/n_found_5099_vs_0050 - A_avg_5099_vs_0050__.^2); A_nlp_5099_vs_0050__ = -z_to_p_twosided_0((A_5099_vs_0050_o__ - A_avg_5099_vs_0050__)./A_std_5099_vs_0050__);
BB_avg_5099_vs_0050__ = BB_avg_5099_vs_0050__/n_found_5099_vs_0050; BB_std_5099_vs_0050__ = sqrt(BB_std_5099_vs_0050__/n_found_5099_vs_0050 - BB_avg_5099_vs_0050__.^2); BB_nlp_5099_vs_0050__ = -z_to_p_twosided_0((BB_5099_vs_0050_o__ - BB_avg_5099_vs_0050__)./BB_std_5099_vs_0050__);
CC_avg_5099_vs_0050__ = CC_avg_5099_vs_0050__/n_found_5099_vs_0050; CC_std_5099_vs_0050__ = sqrt(CC_std_5099_vs_0050__/n_found_5099_vs_0050 - CC_avg_5099_vs_0050__.^2); CC_nlp_5099_vs_0050__ = -z_to_p_twosided_0((CC_5099_vs_0050_o__ - CC_avg_5099_vs_0050__)./CC_std_5099_vs_0050__);
%%%%%%%%;
disp(sprintf(' %% n_found_5099_vs_0050 %d',n_found_5099_vs_0050'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_5099_vs_0050);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_5099_vs_0050_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_5099_vs_0050_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_5099_vs_0050_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_5099_vs_0050_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = sign(a_avg_5099_vs_0050_(1+nvar)).*a_nlp_5099_vs_0050_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_5099_vs_0050_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_5099_vs_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_5099_vs_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(A_avg_5099_vs_0050__).*A_nlp_5099_vs_0050__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_5099_vs_0050),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_5099_vs_0050);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_5099_vs_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_5099_vs_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(sign(BB_avg_5099_vs_0050__).*BB_nlp_5099_vs_0050__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_5099_vs_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_5099_vs_0050__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(sign(CC_avg_5099_vs_0050__).*CC_nlp_5099_vs_0050__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_5099_vs_0050__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_5099_vs_0050),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));
