dXX = 0;
age_percentile_range_ = [];
n_shuffle = 64;

platform = 'access1';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
dir_trunk = sprintf('/%s/rangan/dir_bcc/dir_dolphin',string_root);
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);
dir_mat = sprintf('%s/dir_mat',dir_trunk);
dir_bootstrap_mat = sprintf('%s/dir_bootstrap_mat',dir_trunk);
dir_shuffle_mat = sprintf('%s/dir_shuffle_mat',dir_trunk);

flag_replot=0;
flag_recalc=0;

flag_drift0=1;
flag_center=1;
flag_constrain_CC=1;

if ( isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2dd%dc%dC%d',dXX,flag_drift0,flag_center,flag_constrain_CC);
end;%if ( isempty(age_percentile_range_));
if (~isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d',dXX,min(age_percentile_range_),min(99,max(age_percentile_range_)),flag_drift0,flag_center,flag_constrain_CC);
end;%if (~isempty(age_percentile_range_));
disp(sprintf(' %% fname_infix %s',fname_infix));

dolphin_dXX_load_3;

%%%%%%%%;
% select age range. ;
%%%%%%%%;
if (~isempty(age_percentile_range_));
tmp_index_ = efind(age_>=prctile(age_,min(age_percentile_range_)) & age_<=prctile(age_,max(age_percentile_range_)));
disp(sprintf(' %% age_percentile_range_ [%0.2f %0.2f] --> [%0.2f %0.2f] <-- %d found',age_percentile_range_,prctile(age_,age_percentile_range_),numel(tmp_index_)));
aid_ = aid_(1+tmp_index_);
age_ = age_(1+tmp_index_);
dat__ = dat__(1+tmp_index_,:);
end;%if (~isempty(age_percentile_range_));


for nvar=0:n_var-1;
%%%%%%%%;
n_h_x = 32;
n_h_y = 12;
string_dat_name = string_dat_name_{1+nvar};
nstep_ = 1:3; n_nstep = numel(nstep_);
dt_all__ = cell(n_nstep,1); dv_all__ = cell(n_nstep,1); tab_ = zeros(n_nstep,1);
for nnstep=0:n_nstep-1;
dt_all__{1+nnstep} = zeros(n_smp,1); dv_all__{1+nnstep} = zeros(n_smp,1);
end;%for nnstep=0:n_nstep-1;
for naid=0:n_aid-1;
tmp_index_finite_ = efind(isfinite(dat__(1+index_aid__{1+naid},1+nvar)));
tmp_index_finite_ = index_aid__{1+naid}(1+tmp_index_finite_);
tmp_age_ = age_(1+tmp_index_finite_);
[tmp_age_,tmp_index_srt_] = sort(tmp_age_,'ascend'); tmp_index_srt_ = tmp_index_srt_-1;
tmp_var_ = dat__(1+tmp_index_finite_,1+nvar); tmp_var_ = tmp_var_(1+tmp_index_srt_);
for nnstep=0:n_nstep-1;
nstep = nstep_(1+nnstep);
tab = tab_(1+nnstep);
dt_ = tmp_age_(1+nstep:end) - tmp_age_(1:end-nstep);
dv_ = tmp_var_(1+nstep:end) - tmp_var_(1:end-nstep);
tab_add = numel(dt_);
dt_all__{1+nnstep}(1+tab+[0:tab_add-1]) = dt_;
dv_all__{1+nnstep}(1+tab+[0:tab_add-1]) = dv_;
tab_(1+nnstep) = tab_(1+nnstep) + tab_add;
end;%for nnstep=0:n_nstep-1;
end;%for naid=0:n_aid-1;
for nnstep=0:n_nstep-1;
dt_all__{1+nnstep} = dt_all__{1+nnstep}(1:tab_(1+nnstep)); dv_all__{1+nnstep} = dv_all__{1+nnstep}(1:tab_(1+nnstep));
end;%for nnstep=0:n_nstep-1;
tab_sum = sum(tab_);
tab_csum_ = cumsum([0;tab_]);
dt_all_all_ = zeros(tab_sum,1); dv_all_all_ = zeros(tab_sum,1);
for nnstep=0:n_nstep-1;
dt_all_all_(1+tab_csum_(1+nnstep)+[0:tab_(1+nnstep)-1]) = dt_all__{1+nnstep};
dv_all_all_(1+tab_csum_(1+nnstep)+[0:tab_(1+nnstep)-1]) = dv_all__{1+nnstep};
end;%for nnstep=0:n_nstep-1;
xlim_ = [0,sqrt(max(dt_all_all_))];
ylim_ = prctile(dv_all_all_,[1,99]);
tmp_h___ = zeros(n_h_y,n_h_x,n_nstep+1);
tmp_avg__ = zeros(n_h_x,n_nstep+1);
tmp_std__ = zeros(n_h_x,n_nstep+1);
for nnstep=0:n_nstep+1-1;
if (nnstep< n_nstep); tmp_dt_all_ = dt_all__{1+nnstep}; tmp_dv_all_ = dv_all__{1+nnstep}; end;
if (nnstep==n_nstep); tmp_dt_all_ = dt_all_all_; tmp_dv_all_ = dv_all_all_; end;
tmp_h__ = hist2d_0(sqrt(tmp_dt_all_),tmp_dv_all_,n_h_x,n_h_y,xlim_,ylim_);
tmp_e_ = linspace(ylim_(1),ylim_(2),n_h_x);
tmp_b_ = 1:n_h_y;
tmp_avg_ = zeros(n_h_x,1);
tmp_std_ = zeros(n_h_x,1);
for nh=0:n_h_x-1;
tmp_h__(:,1+nh) = tmp_h__(:,1+nh)/max(1,sum(tmp_h__(:,1+nh)));
tmp_avg_(1+nh) = dot(tmp_b_,tmp_h__(:,1+nh));
tmp_std_(1+nh) = sqrt(dot(tmp_b_.*tmp_b_,tmp_h__(:,1+nh)) - tmp_avg_(1+nh).^2);
end;%for nh=0:n_h-1;
tmp_h___(:,:,1+nnstep) = tmp_h__;
tmp_avg__(:,1+nnstep) = tmp_avg_;
tmp_std__(:,1+nnstep) = tmp_std_;
end;%for nnstep=0:n_nstep+1-1;
%%%%%%%%;
fname_fig = sprintf('%s/dolphin_drift0_dt_scatter_%s_C',dir_jpg,string_dat_name);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig));
figure(1); clf; figbig; fig80s();
markersize_use = 32;
n_plot_row = 2;
n_plot_col = n_nstep+1;
for nnstep=0:n_nstep+1-1;
if (nnstep< n_nstep); tmp_dt_all_ = dt_all__{1+nnstep}; tmp_dv_all_ = dv_all__{1+nnstep}; end;
if (nnstep==n_nstep); tmp_dt_all_ = dt_all_all_; tmp_dv_all_ = dv_all_all_; end;
subplot(n_plot_row,n_plot_col,1+nnstep+0*n_plot_col);
plot(sqrt(tmp_dt_all_),tmp_dv_all_,'k.');
xlim(xlim_);ylim(ylim_); xlabel('sqrt(dt)'); ylabel('dv');
if (nnstep< n_nstep); title(sprintf('%d-step',nstep_(1+nnstep))); end;
if (nnstep==n_nstep); title(sprintf('sum-step')); end;
subplot(n_plot_row,n_plot_col,1+nnstep+1*n_plot_col);
hold on;
imagesc(tmp_h___(:,:,1+nnstep),[0.02,0.20]);
tmp_b_ = 1:n_h_x; tmp_avg_ = tmp_avg__(:,1+nnstep); tmp_std_ = tmp_std__(:,1+nnstep);
plot(tmp_b_,tmp_avg_,'w.','MarkerSize',markersize_use);
plot(tmp_b_,tmp_avg_+1.0*tmp_std_,'y.','MarkerSize',markersize_use);
plot(tmp_b_,tmp_avg_-1.0*tmp_std_,'y.','MarkerSize',markersize_use);
hold off;
xlim([1,n_h_x]); ylim([1,n_h_y]);
axisnotick;
xlabel('sqrt(dt)'); ylabel('dv');
end;%for nnstep=0:n_nstep+1-1;
sgtitle(sprintf('%s',string_dat_name));
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
end;%for nvar=0:n_var-1;

disp('returning'); return;

