function dolphin_dXX_6_collect();
%{
note that age-range is 0.64 --> 54.35. ;
%}

dXX = 0; n_shuffle = 256;
age_percentile_range_ = [];

setup_OptiPlex; dir_trunk = '/home/rangan/dir_bcc/dir_dolphin';
%setup_access1; dir_trunk = '/data/rangan/dir_bcc/dir_dolphin';
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);
dir_mat = sprintf('%s/dir_mat',dir_trunk);
dir_bootstrap_mat = sprintf('%s/dir_bootstrap_mat',dir_trunk);
dir_shuffle_mat = sprintf('%s/dir_shuffle_mat',dir_trunk);

flag_replot=1;

flag_drift0=1;
flag_center=1;
flag_constrain_CC=1;

if ( isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2dd%dc%dC%d',dXX,flag_drift0,flag_center,flag_constrain_CC);
end;%if ( isempty(age_percentile_range_));
if (~isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d',dXX,min(age_percentile_range_),min(99,max(age_percentile_range_)),flag_drift0,flag_center,flag_constrain_CC);
end;%if (~isempty(age_percentile_range_));
disp(sprintf(' %% fname_infix %s',fname_infix));

dolphin_dXX_load_3;

%%%%%%%%;
% select age range. ;
%%%%%%%%;
if (~isempty(age_percentile_range_));
tmp_index_ = efind(age_>=prctile(age_,min(age_percentile_range_)) & age_<=prctile(age_,max(age_percentile_range_)));
disp(sprintf(' %% age_percentile_range_ [%0.2f %0.2f] --> [%0.2f %0.2f] <-- %d found',age_percentile_range_,prctile(age_,age_percentile_range_),numel(tmp_index_)));
aid_ = aid_(1+tmp_index_);
age_ = age_(1+tmp_index_);
dat__ = dat__(1+tmp_index_,:);
end;%if (~isempty(age_percentile_range_));

index_mss_ = efind(~isfinite(dat__));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% find individual dolphins. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
n_found_dXX = 0;
dXX_found_ = [];
n_aid_found_ = [];
for tmp_dXX=1:160;
tmp_fname_infix_0099 = sprintf('aid%.2dd%dc%dC%d',tmp_dXX,flag_drift0,flag_center,flag_constrain_CC);
tmp_fname_mat_0099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,tmp_fname_infix_0099);
tmp_fname_mat_0099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,tmp_fname_infix_0099);
if ( exist(tmp_fname_mat_0099_o,'file') &  exist(tmp_fname_mat_0099_s,'file'));
dXX_found_(1+n_found_dXX) = tmp_dXX;
tmp_ij = find(u_aid_==tmp_dXX);
n_aid_found_(1+n_found_dXX) = n_aid_(tmp_ij);
%%%%%%%%;
tmp_ = load(tmp_fname_mat_0099_o);
a_0099_o__{1+n_found_dXX} = tmp_.a_;
A_0099_o___{1+n_found_dXX} = tmp_.A__;
BB_0099_o___{1+n_found_dXX} = tmp_.BB__;
CC_0099_o___{1+n_found_dXX} = tmp_.CC__;
%%%%%%%%;
tmp_ = load(tmp_fname_mat_0099_s);
n_found_0099_{1+n_found_dXX} = size(tmp_.L_prm_,1);
a_avg_0099__{1+n_found_dXX} = mean(tmp_.a_prm__(:,2:end),2); a_std_0099__{1+n_found_dXX} = std(tmp_.a_prm__(:,2:end),1,2);
A_avg_0099___{1+n_found_dXX} = mean(tmp_.A_prm___(:,:,2:end),3); A_std_0099___{1+n_found_dXX} = std(tmp_.A_prm___(:,:,2:end),1,3);
BB_avg_0099___{1+n_found_dXX} = mean(tmp_.BB_prm___(:,:,2:end),3); BB_std_0099___{1+n_found_dXX} = std(tmp_.BB_prm___(:,:,2:end),1,3);
CC_avg_0099___{1+n_found_dXX} = mean(tmp_.CC_prm___(:,:,2:end),3); CC_std_0099___{1+n_found_dXX} = std(tmp_.CC_prm___(:,:,2:end),1,3);
%%%%%%%%;
a_nlp_0099__{1+n_found_dXX} = -z_to_p_twosided_0((a_0099_o__{1+n_found_dXX} - a_avg_0099__{1+n_found_dXX})./a_std_0099__{1+n_found_dXX});
A_nlp_0099___{1+n_found_dXX} = -z_to_p_twosided_0((A_0099_o___{1+n_found_dXX} - A_avg_0099___{1+n_found_dXX})./A_std_0099___{1+n_found_dXX});
BB_nlp_0099___{1+n_found_dXX} = -z_to_p_twosided_0((BB_0099_o___{1+n_found_dXX} - BB_avg_0099___{1+n_found_dXX})./BB_std_0099___{1+n_found_dXX});
CC_nlp_0099___{1+n_found_dXX} = -z_to_p_twosided_0((CC_0099_o___{1+n_found_dXX} - CC_avg_0099___{1+n_found_dXX})./CC_std_0099___{1+n_found_dXX});
a_snlp_0099__{1+n_found_dXX} = sign(a_0099_o__{1+n_found_dXX} - a_avg_0099__{1+n_found_dXX}).*a_nlp_0099__{1+n_found_dXX};
A_snlp_0099___{1+n_found_dXX} = sign(A_0099_o___{1+n_found_dXX} - A_avg_0099___{1+n_found_dXX}).*A_nlp_0099___{1+n_found_dXX};
BB_snlp_0099___{1+n_found_dXX} = sign(BB_0099_o___{1+n_found_dXX} - BB_avg_0099___{1+n_found_dXX}).*BB_nlp_0099___{1+n_found_dXX};
CC_snlp_0099___{1+n_found_dXX} = sign(CC_0099_o___{1+n_found_dXX} - CC_avg_0099___{1+n_found_dXX}).*CC_nlp_0099___{1+n_found_dXX};
a_sbnlp_0099__{1+n_found_dXX} = sign(a_0099_o__{1+n_found_dXX} - a_avg_0099__{1+n_found_dXX}).*max(0,a_nlp_0099__{1+n_found_dXX}-log(n_var));
A_sbnlp_0099___{1+n_found_dXX} = sign(A_0099_o___{1+n_found_dXX} - A_avg_0099___{1+n_found_dXX}).*max(0,A_nlp_0099___{1+n_found_dXX}-log(n_var*(n_var-1)));
BB_sbnlp_0099___{1+n_found_dXX} = sign(BB_0099_o___{1+n_found_dXX} - BB_avg_0099___{1+n_found_dXX}).*max(0,BB_nlp_0099___{1+n_found_dXX}-log(n_var*(n_var-1)/2));
CC_sbnlp_0099___{1+n_found_dXX} = sign(CC_0099_o___{1+n_found_dXX} - CC_avg_0099___{1+n_found_dXX}).*max(0,CC_nlp_0099___{1+n_found_dXX}-log(n_var*(n_var-1)/2));
%%%%%%%%;
n_found_dXX = n_found_dXX+1;
end;%if ( exist(tmp_fname_mat_0099_o,'file') &  exist(tmp_fname_mat_0099_s,'file'));
%%%%%%%%;
end;%for dXX=1:160;
disp(sprintf(' %% n_found_dXX %d',n_found_dXX));

fname_infix_0099 = sprintf('aid%.2dd%dc%dC%d',dXX,flag_drift0,flag_center,flag_constrain_CC);
fname_infix_0050 = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d',dXX, 0,50,flag_drift0,flag_center,flag_constrain_CC);
fname_infix_5099 = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d',dXX,50,99,flag_drift0,flag_center,flag_constrain_CC);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 0099 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_0099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0099);
if ( exist(fname_mat_0099_o,'file'));
tmp_ = load(fname_mat_0099_o);
a_0099_o_ = tmp_.a_;
A_0099_o__ = tmp_.A__;
BB_0099_o__ = tmp_.BB__;
CC_0099_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_0099_s,'file'));
%%%%%%%%;
a_avg_0099_ = zeros(n_var,1); a_std_0099_ = zeros(n_var,1);
A_avg_0099__ = zeros(n_var,n_var); A_std_0099__ = zeros(n_var,n_var);
BB_avg_0099__ = zeros(n_var,n_var); BB_std_0099__ = zeros(n_var,n_var);
CC_avg_0099__ = zeros(n_var,n_var); CC_std_0099__ = zeros(n_var,n_var);
n_found_0099 = 0;
fname_mat_0099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_0099);
if ( exist(fname_mat_0099_s,'file'));
tmp_ = load(fname_mat_0099_s);
n_found_0099 = size(tmp_.L_prm_,1);
a_avg_0099_ = mean(tmp_.a_prm__(:,2:end),2); a_std_0099_ = std(tmp_.a_prm__(:,2:end),1,2);
A_avg_0099__ = mean(tmp_.A_prm___(:,:,2:end),3); A_std_0099__ = std(tmp_.A_prm___(:,:,2:end),1,3);
BB_avg_0099__ = mean(tmp_.BB_prm___(:,:,2:end),3); BB_std_0099__ = std(tmp_.BB_prm___(:,:,2:end),1,3);
CC_avg_0099__ = mean(tmp_.CC_prm___(:,:,2:end),3); CC_std_0099__ = std(tmp_.CC_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_0099_s,'file'));
a_nlp_0099_ = -z_to_p_twosided_0((a_0099_o_ - a_avg_0099_)./a_std_0099_);
A_nlp_0099__ = -z_to_p_twosided_0((A_0099_o__ - A_avg_0099__)./A_std_0099__);
BB_nlp_0099__ = -z_to_p_twosided_0((BB_0099_o__ - BB_avg_0099__)./BB_std_0099__);
CC_nlp_0099__ = -z_to_p_twosided_0((CC_0099_o__ - CC_avg_0099__)./CC_std_0099__);
a_snlp_0099_ = sign(a_0099_o_ - a_avg_0099_).*a_nlp_0099_;
A_snlp_0099__ = sign(A_0099_o__ - A_avg_0099__).*A_nlp_0099__;
BB_snlp_0099__ = sign(BB_0099_o__ - BB_avg_0099__).*BB_nlp_0099__;
CC_snlp_0099__ = sign(CC_0099_o__ - CC_avg_0099__).*CC_nlp_0099__;
a_sbnlp_0099_ = sign(a_0099_o_ - a_avg_0099_).*max(0,a_nlp_0099_-log(n_var));
A_sbnlp_0099__ = sign(A_0099_o__ - A_avg_0099__).*max(0,A_nlp_0099__-log(n_var*(n_var-1)));
BB_sbnlp_0099__ = sign(BB_0099_o__ - BB_avg_0099__).*max(0,BB_nlp_0099__-log(n_var*(n_var-1)/2));
CC_sbnlp_0099__ = sign(CC_0099_o__ - CC_avg_0099__).*max(0,CC_nlp_0099__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_0099 %d',n_found_0099'));
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 0050 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_0050_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0050);
if ( exist(fname_mat_0050_o,'file'));
tmp_ = load(fname_mat_0050_o);
a_0050_o_ = tmp_.a_;
A_0050_o__ = tmp_.A__;
BB_0050_o__ = tmp_.BB__;
CC_0050_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_0050_s,'file'));
%%%%%%%%;
a_avg_0050_ = zeros(n_var,1); a_std_0050_ = zeros(n_var,1);
A_avg_0050__ = zeros(n_var,n_var); A_std_0050__ = zeros(n_var,n_var);
BB_avg_0050__ = zeros(n_var,n_var); BB_std_0050__ = zeros(n_var,n_var);
CC_avg_0050__ = zeros(n_var,n_var); CC_std_0050__ = zeros(n_var,n_var);
n_found_0050 = 0;
fname_mat_0050_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_0050);
if ( exist(fname_mat_0050_s,'file'));
tmp_ = load(fname_mat_0050_s);
n_found_0050 = size(tmp_.L_prm_,1);
a_avg_0050_ = mean(tmp_.a_prm__(:,2:end),2); a_std_0050_ = std(tmp_.a_prm__(:,2:end),1,2);
A_avg_0050__ = mean(tmp_.A_prm___(:,:,2:end),3); A_std_0050__ = std(tmp_.A_prm___(:,:,2:end),1,3);
BB_avg_0050__ = mean(tmp_.BB_prm___(:,:,2:end),3); BB_std_0050__ = std(tmp_.BB_prm___(:,:,2:end),1,3);
CC_avg_0050__ = mean(tmp_.CC_prm___(:,:,2:end),3); CC_std_0050__ = std(tmp_.CC_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_0050_s,'file'));
a_nlp_0050_ = -z_to_p_twosided_0((a_0050_o_ - a_avg_0050_)./a_std_0050_);
A_nlp_0050__ = -z_to_p_twosided_0((A_0050_o__ - A_avg_0050__)./A_std_0050__);
BB_nlp_0050__ = -z_to_p_twosided_0((BB_0050_o__ - BB_avg_0050__)./BB_std_0050__);
CC_nlp_0050__ = -z_to_p_twosided_0((CC_0050_o__ - CC_avg_0050__)./CC_std_0050__);
a_snlp_0050_ = sign(a_0050_o_ - a_avg_0050_).*a_nlp_0050_;
A_snlp_0050__ = sign(A_0050_o__ - A_avg_0050__).*A_nlp_0050__;
BB_snlp_0050__ = sign(BB_0050_o__ - BB_avg_0050__).*BB_nlp_0050__;
CC_snlp_0050__ = sign(CC_0050_o__ - CC_avg_0050__).*CC_nlp_0050__;
a_sbnlp_0050_ = sign(a_0050_o_ - a_avg_0050_).*max(0,a_nlp_0050_-log(n_var));
A_sbnlp_0050__ = sign(A_0050_o__ - A_avg_0050__).*max(0,A_nlp_0050__-log(n_var*(n_var-1)));
BB_sbnlp_0050__ = sign(BB_0050_o__ - BB_avg_0050__).*max(0,BB_nlp_0050__-log(n_var*(n_var-1)/2));
CC_sbnlp_0050__ = sign(CC_0050_o__ - CC_avg_0050__).*max(0,CC_nlp_0050__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_0050 %d',n_found_0050'));
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 5099 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_5099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_5099);
if ( exist(fname_mat_5099_o,'file'));
tmp_ = load(fname_mat_5099_o);
a_5099_o_ = tmp_.a_;
A_5099_o__ = tmp_.A__;
BB_5099_o__ = tmp_.BB__;
CC_5099_o__ = tmp_.CC__;
end;%if ( exist(fname_mat_5099_s,'file'));
%%%%%%%%;
a_avg_5099_ = zeros(n_var,1); a_std_5099_ = zeros(n_var,1);
A_avg_5099__ = zeros(n_var,n_var); A_std_5099__ = zeros(n_var,n_var);
BB_avg_5099__ = zeros(n_var,n_var); BB_std_5099__ = zeros(n_var,n_var);
CC_avg_5099__ = zeros(n_var,n_var); CC_std_5099__ = zeros(n_var,n_var);
n_found_5099 = 0;
fname_mat_5099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_5099);
if ( exist(fname_mat_5099_s,'file'));
tmp_ = load(fname_mat_5099_s);
n_found_5099 = size(tmp_.L_prm_,1);
a_avg_5099_ = mean(tmp_.a_prm__(:,2:end),2); a_std_5099_ = std(tmp_.a_prm__(:,2:end),1,2);
A_avg_5099__ = mean(tmp_.A_prm___(:,:,2:end),3); A_std_5099__ = std(tmp_.A_prm___(:,:,2:end),1,3);
BB_avg_5099__ = mean(tmp_.BB_prm___(:,:,2:end),3); BB_std_5099__ = std(tmp_.BB_prm___(:,:,2:end),1,3);
CC_avg_5099__ = mean(tmp_.CC_prm___(:,:,2:end),3); CC_std_5099__ = std(tmp_.CC_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_5099_s,'file'));
a_nlp_5099_ = -z_to_p_twosided_0((a_5099_o_ - a_avg_5099_)./a_std_5099_);
A_nlp_5099__ = -z_to_p_twosided_0((A_5099_o__ - A_avg_5099__)./A_std_5099__);
BB_nlp_5099__ = -z_to_p_twosided_0((BB_5099_o__ - BB_avg_5099__)./BB_std_5099__);
CC_nlp_5099__ = -z_to_p_twosided_0((CC_5099_o__ - CC_avg_5099__)./CC_std_5099__);
a_snlp_5099_ = sign(a_5099_o_ - a_avg_5099_).*a_nlp_5099_;
A_snlp_5099__ = sign(A_5099_o__ - A_avg_5099__).*A_nlp_5099__;
BB_snlp_5099__ = sign(BB_5099_o__ - BB_avg_5099__).*BB_nlp_5099__;
CC_snlp_5099__ = sign(CC_5099_o__ - CC_avg_5099__).*CC_nlp_5099__;
a_sbnlp_5099_ = sign(a_5099_o_ - a_avg_5099_).*max(0,a_nlp_5099_-log(n_var));
A_sbnlp_5099__ = sign(A_5099_o__ - A_avg_5099__).*max(0,A_nlp_5099__-log(n_var*(n_var-1)));
BB_sbnlp_5099__ = sign(BB_5099_o__ - BB_avg_5099__).*max(0,BB_nlp_5099__-log(n_var*(n_var-1)/2));
CC_sbnlp_5099__ = sign(CC_5099_o__ - CC_avg_5099__).*max(0,CC_nlp_5099__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_5099 %d',n_found_5099'));
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% Now visualize dolphins in pca-space. Note that 2 pcs is reasonable for interaction matrix. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_fig = sprintf('%s/dolphin_dXX_6_collect_FIGAB_snlp_corr',dir_jpg);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;markersize_use = 64;A_lim_ = [-1,+1];
%%%%%%%%;
dXX_A_0099_ = zeros(n_found_dXX,1);
dXX_B_0099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_A_0099__ = A_snlp_0099___{1+nfound_dXX};
dXX_B_0099__ = BB_snlp_0099___{1+nfound_dXX};
dXX_A_0099_(1+nfound_dXX) = corr(dXX_A_0099__(:),A_snlp_0099__(:));
dXX_B_0099_(1+nfound_dXX) = corr(dXX_B_0099__(:),BB_snlp_0099__(:));
end;%for nfound_dXX=0:n_found_dXX-1;
%%%%%%%%;
subplot_(1) = subplot(1,3,1); 
imagesc(A_snlp_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image; %colorbar;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot_(2) = subplot(1,3,2); 
imagesc(BB_snlp_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image; %colorbar;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot_(3) = subplot(1,3,3);
scatter(dXX_A_0099_,dXX_B_0099_,markersize_use,n_aid_found_,'filled','MarkerEdgeColor','k'); grid on;
xlabel('correlation with A');
ylabel('correlation with BB');
title('individual dolphins');
axis equal;
%%%%%%%%;
colormap(subplot_(1),colormap_nlpvt_twosided());
colormap(subplot_(2),colormap_nlpvt_twosided());
colormap(subplot_(3),colormap_beach());
%%%%%%%%;
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;


fname_fig = sprintf('%s/dolphin_dXX_6_collect_FIGAB_o_corr',dir_jpg);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;markersize_use = 64;A_lim_ = [-1,+1];
%%%%%%%%;
dXX_A_0099_ = zeros(n_found_dXX,1);
dXX_B_0099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_A_0099__ = A_0099_o___{1+nfound_dXX} - diag(diag(A_0099_o___{1+nfound_dXX}));
dXX_B_0099__ = BB_0099_o___{1+nfound_dXX} - diag(diag(BB_0099_o___{1+nfound_dXX}));
tmp_ = A_0099_o__ - diag(diag(A_0099_o__));
dXX_A_0099_(1+nfound_dXX) = corr(dXX_A_0099__(:),tmp_(:));
tmp_ = BB_0099_o__ - diag(diag(BB_0099_o__));
dXX_B_0099_(1+nfound_dXX) = corr(dXX_B_0099__(:),tmp_(:));
end;%for nfound_dXX=0:n_found_dXX-1;
%%%%%%%%;
subplot_(1) = subplot(1,3,1); 
imagesc(A_0099_o__,A_lim_); colormap(colormap_beach); axis image; %colorbar;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_0099_o__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot_(2) = subplot(1,3,2); 
imagesc(BB_0099_o__,A_lim_); colormap(colormap_beach); axis image; %colorbar;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_0099_o__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot_(3) = subplot(1,3,3);
scatter(dXX_A_0099_,dXX_B_0099_,markersize_use,n_aid_found_,'filled','MarkerEdgeColor','k'); grid on;
xlabel('correlation with A');
ylabel('correlation with BB');
title('individual dolphins');
axis equal;
%%%%%%%%;
colormap(subplot_(1),colormap_beach());
colormap(subplot_(2),colormap_beach());
colormap(subplot_(3),colormap_beach());
%%%%%%%%;
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%{

%%%%%%%%;
[tmp_U_A_0099__,tmp_S_A_0099__,tmp_V_A_0099__] = svds(A_snlp_0099__,2);
pc0_A_0099__ = tmp_U_A_0099__(:,1)*tmp_S_A_0099__(1,1)*transpose(tmp_V_A_0099__(:,1));
pc1_A_0099__ = tmp_U_A_0099__(:,2)*tmp_S_A_0099__(2,2)*transpose(tmp_V_A_0099__(:,2));
dXX_pc0_A_0099_ = zeros(n_found_dXX,1);
dXX_pc1_A_0099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_A_0099__ = A_snlp_0099___{1+nfound_dXX};
dXX_pc0_A_0099_(1+nfound_dXX) = corr(dXX_A_0099__(:),pc0_A_0099__(:));
dXX_pc1_A_0099_(1+nfound_dXX) = corr(dXX_A_0099__(:),pc1_A_0099__(:));
end;%for nfound_dXX=0:n_found_dXX-1;
figure(1);clf;figbig;markersize_use = 32;
%%%%%%%%;
subplot(2,2,1); 
imagesc(A_snlp_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,2); 
imagesc(pc0_A_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('first pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,3); 
imagesc(pc1_A_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('second pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,4);
scatter(dXX_pc0_A_0099_,dXX_pc1_A_0099_,markersize_use,'filled');
xlabel('correlation with pc1');
ylabel('correlation with pc2');
%%%%%%%%;

%%%%%%%%;
A_lim_ = [-1,+1];
[tmp_U_A_0099__,tmp_S_A_0099__,tmp_V_A_0099__] = svds(A_0099_o__ - diag(diag(A_0099_o__)),2);
pc0_A_0099__ = tmp_U_A_0099__(:,1)*tmp_S_A_0099__(1,1)*transpose(tmp_V_A_0099__(:,1));
pc1_A_0099__ = tmp_U_A_0099__(:,2)*tmp_S_A_0099__(2,2)*transpose(tmp_V_A_0099__(:,2));
dXX_pc0_A_0099_ = zeros(n_found_dXX,1);
dXX_pc1_A_0099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_A_0099__ = A_0099_o___{1+nfound_dXX} - diag(diag(A_0099_o___{1+nfound_dXX}));
dXX_pc0_A_0099_(1+nfound_dXX) = corr(dXX_A_0099__(:),pc0_A_0099__(:));
dXX_pc1_A_0099_(1+nfound_dXX) = corr(dXX_A_0099__(:),pc1_A_0099__(:));
end;%for nfound_dXX=0:n_found_dXX-1;
figure(2);clf;figbig;markersize_use = 32;
%%%%%%%%;
subplot(2,2,1); 
imagesc(A_0099_o__,A_lim_); colormap(colormap_beach); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_0099_o__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,2); 
imagesc(pc0_A_0099__,A_lim_); colormap(colormap_beach); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('first pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,3); 
imagesc(pc1_A_0099__,A_lim_); colormap(colormap_beach); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('second pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,4);
scatter(dXX_pc0_A_0099_,dXX_pc1_A_0099_,markersize_use,'filled');
xlabel('correlation with pc1');
ylabel('correlation with pc2');
%%%%%%%%;

%%%%%%%%;
[tmp_U_BB_0099__,tmp_S_BB_0099__,tmp_V_BB_0099__] = svds(BB_snlp_0099__,2);
pc0_BB_0099__ = tmp_U_BB_0099__(:,1)*tmp_S_BB_0099__(1,1)*transpose(tmp_V_BB_0099__(:,1));
pc1_BB_0099__ = tmp_U_BB_0099__(:,2)*tmp_S_BB_0099__(2,2)*transpose(tmp_V_BB_0099__(:,2));
dXX_pc0_BB_0099_ = zeros(n_found_dXX,1);
dXX_pc1_BB_0099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_BB_0099__ = BB_snlp_0099___{1+nfound_dXX};
dXX_pc0_BB_0099_(1+nfound_dXX) = corr(dXX_BB_0099__(:),pc0_BB_0099__(:));
dXX_pc1_BB_0099_(1+nfound_dXX) = corr(dXX_BB_0099__(:),pc1_BB_0099__(:));
end;%for nfound_dXX=0:n_found_dXX-1;
figure(3);clf;figbig;markersize_use = 32;
%%%%%%%%;
subplot(2,2,1); 
imagesc(BB_snlp_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,2); 
imagesc(pc0_BB_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('first pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,3); 
imagesc(pc1_BB_0099__,[-27,+27]); colormap(colormap_nlpvt_twosided); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('second pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,4);
scatter(dXX_pc0_BB_0099_,dXX_pc1_BB_0099_,markersize_use,'filled');
xlabel('correlation with pc1');
ylabel('correlation with pc2');
%%%%%%%%;

%%%%%%%%;
BB_lim_ = [-1,+1];
[tmp_U_BB_0099__,tmp_S_BB_0099__,tmp_V_BB_0099__] = svds(BB_0099_o__ - diag(diag(BB_0099_o__)),2);
pc0_BB_0099__ = tmp_U_BB_0099__(:,1)*tmp_S_BB_0099__(1,1)*transpose(tmp_V_BB_0099__(:,1));
pc1_BB_0099__ = tmp_U_BB_0099__(:,2)*tmp_S_BB_0099__(2,2)*transpose(tmp_V_BB_0099__(:,2));
dXX_pc0_BB_0099_ = zeros(n_found_dXX,1);
dXX_pc1_BB_0099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_BB_0099__ = BB_0099_o___{1+nfound_dXX} - diag(diag(BB_0099_o___{1+nfound_dXX}));
dXX_pc0_BB_0099_(1+nfound_dXX) = corr(dXX_BB_0099__(:),pc0_BB_0099__(:));
dXX_pc1_BB_0099_(1+nfound_dXX) = corr(dXX_BB_0099__(:),pc1_BB_0099__(:));
end;%for nfound_dXX=0:n_found_dXX-1;
figure(4);clf;figbig;markersize_use = 32;
%%%%%%%%;
subplot(2,2,1); 
imagesc(BB_0099_o__,BB_lim_); colormap(colormap_beach); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_0099_o__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,2); 
imagesc(pc0_BB_0099__,BB_lim_); colormap(colormap_beach); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('first pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,3); 
imagesc(pc1_BB_0099__,BB_lim_); colormap(colormap_beach); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('second pc','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot(2,2,4);
scatter(dXX_pc0_BB_0099_,dXX_pc1_BB_0099_,markersize_use,'filled');
xlabel('correlation with pc1');
ylabel('correlation with pc2');
%%%%%%%%;

%}

fname_fig = sprintf('%s/dolphin_dXX_6_collect_FIGAB_o_5099_corr',dir_jpg);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;markersize_use = 64;A_lim_ = [-1,+1];
%%%%%%%%;
dXX_A_5099_ = zeros(n_found_dXX,1);
dXX_B_5099_ = zeros(n_found_dXX,1);
for nfound_dXX=0:n_found_dXX-1;
dXX_A_0099__ = A_0099_o___{1+nfound_dXX} - diag(diag(A_0099_o___{1+nfound_dXX}));
dXX_B_0099__ = BB_0099_o___{1+nfound_dXX} - diag(diag(BB_0099_o___{1+nfound_dXX}));
tmp_ = A_5099_o__ - diag(diag(A_5099_o__));
dXX_A_5099_(1+nfound_dXX) = corr(dXX_A_0099__(:),tmp_(:));
tmp_ = BB_5099_o__ - diag(diag(BB_5099_o__));
dXX_B_5099_(1+nfound_dXX) = corr(dXX_B_0099__(:),tmp_(:));
end;%for nfound_dXX=0:n_found_dXX-1;
%%%%%%%%;
subplot_(1) = subplot(1,3,1); 
imagesc(A_5099_o__,A_lim_); colormap(colormap_beach); axis image; %colorbar;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_5099_o__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot_(2) = subplot(1,3,2); 
imagesc(BB_5099_o__,A_lim_); colormap(colormap_beach); axis image; %colorbar;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_5099_o__','Interpreter','none');
set(gca,'FontSize',8);
%%%%%%%%;
subplot_(3) = subplot(1,3,3);
scatter(dXX_A_5099_,dXX_B_5099_,markersize_use,n_aid_found_,'filled','MarkerEdgeColor','k'); grid on;
xlabel('correlation with A');
ylabel('correlation with BB');
title('individual dolphins');
axis equal;
%%%%%%%%;
colormap(subplot_(1),colormap_beach());
colormap(subplot_(2),colormap_beach());
colormap(subplot_(3),colormap_beach());
%%%%%%%%;
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));
