function dolphin_d00_cmb_7_collect(flag_constrain_CC);
%{
% note that age-range is 0.64 --> 54.35. ;

%%%%%%%%;
% Load results. ;
%%%%%%%%;
dXX = 0; n_shuffle = 256;
age_percentile_range_ = [];
flag_constrain_CC = [];
platform = 'access1';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
dir_trunk = sprintf('/%s/rangan/dir_bcc/dir_dolphin',string_root);
dir_jpg = sprintf('%s/dir_jpg4',dir_trunk);
if (~exist(dir_jpg,'dir')); disp(sprintf(' %% mkdir %s',dir_jpg)); mkdir(dir_jpg); end;
dir_mat = sprintf('%s/dir_mat4',dir_trunk);
if (~exist(dir_mat,'dir')); disp(sprintf(' %% mkdir %s',dir_mat)); mkdir(dir_mat); end;
dir_shuffle_mat = sprintf('%s/dir_shuffle%d_mat4',dir_trunk,n_shuffle);
if (~exist(dir_shuffle_mat,'dir')); disp(sprintf(' %% mkdir %s',dir_shuffle_mat)); mkdir(dir_shuffle_mat); end;
flag_drift0=1;
flag_center=1;
dolphin_dXX_load_4;
flag_constrain_CC = 0;
fname_C0_mat = sprintf('%s/dolphin_aid%.2dd%dc%dC%d_cmb_snlp.mat',dir_mat,dXX,flag_drift0,flag_center,flag_constrain_CC);
tmp_C0_ = load(fname_C0_mat);
flag_constrain_CC = 1;
fname_C1_mat = sprintf('%s/dolphin_aid%.2dd%dc%dC%d_cmb_snlp.mat',dir_mat,dXX,flag_drift0,flag_center,flag_constrain_CC);
tmp_C1_ = load(fname_C1_mat);

tmp_C0_A_sbnlp_0099__ = tmp_C0_.A_sbnlp_0099__ - diag(diag(tmp_C0_.A_sbnlp_0099__));
tmp_C1_A_sbnlp_0099__ = tmp_C1_.A_sbnlp_0099__ - diag(diag(tmp_C1_.A_sbnlp_0099__));
tmp_index_C0_A_pos_ = efind(tmp_C0_A_sbnlp_0099__>=+3);
tmp_index_C1_A_pos_ = efind(tmp_C1_A_sbnlp_0099__>=+3);
tmp_index_A_pos_ = intersect(tmp_index_C0_A_pos_,tmp_index_C1_A_pos_);
tmp_index_C0_A_neg_ = efind(tmp_C0_A_sbnlp_0099__<=-3);
tmp_index_C1_A_neg_ = efind(tmp_C1_A_sbnlp_0099__<=-3);
tmp_index_A_neg_ = intersect(tmp_index_C0_A_neg_,tmp_index_C1_A_neg_);
tmp_index_A_ = union(tmp_index_A_pos_,tmp_index_A_neg_);
tmp_A_sbnlp_0099__ = zeros(n_var,n_var);
tmp_A_sbnlp_0099__(1+tmp_index_A_pos_) = min(tmp_C0_A_sbnlp_0099__(1+tmp_index_A_pos_),tmp_C1_A_sbnlp_0099__(1+tmp_index_A_pos_));
tmp_A_sbnlp_0099__(1+tmp_index_A_neg_) = max(tmp_C0_A_sbnlp_0099__(1+tmp_index_A_neg_),tmp_C1_A_sbnlp_0099__(1+tmp_index_A_neg_));
%%%%;
tmp_C0_BB_sbnlp_0099__ = tmp_C0_.BB_sbnlp_0099__ - diag(diag(tmp_C0_.BB_sbnlp_0099__));
tmp_C1_BB_sbnlp_0099__ = tmp_C1_.BB_sbnlp_0099__ - diag(diag(tmp_C1_.BB_sbnlp_0099__));
tmp_index_C0_BB_pos_ = efind(tmp_C0_BB_sbnlp_0099__>=+3);
tmp_index_C1_BB_pos_ = efind(tmp_C1_BB_sbnlp_0099__>=+3);
tmp_index_BB_pos_ = intersect(tmp_index_C0_BB_pos_,tmp_index_C1_BB_pos_);
tmp_index_C0_BB_neg_ = efind(tmp_C0_BB_sbnlp_0099__<=-3);
tmp_index_C1_BB_neg_ = efind(tmp_C1_BB_sbnlp_0099__<=-3);
tmp_index_BB_neg_ = intersect(tmp_index_C0_BB_neg_,tmp_index_C1_BB_neg_);
tmp_index_BB_ = union(tmp_index_BB_pos_,tmp_index_BB_neg_);
tmp_BB_sbnlp_0099__ = zeros(n_var,n_var);
tmp_BB_sbnlp_0099__(1+tmp_index_BB_pos_) = min(tmp_C0_BB_sbnlp_0099__(1+tmp_index_BB_pos_),tmp_C1_BB_sbnlp_0099__(1+tmp_index_BB_pos_));
tmp_BB_sbnlp_0099__(1+tmp_index_BB_neg_) = max(tmp_C0_BB_sbnlp_0099__(1+tmp_index_BB_neg_),tmp_C1_BB_sbnlp_0099__(1+tmp_index_BB_neg_));
%%%%;
figure(1);clf;figmed;
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
colormap(c_nlpvt2__);
subplot(2,3,1+0*3);imagesc(tmp_C0_A_sbnlp_0099__,c_nlpvt2_lim_); title('A C0'); axis image; axisnotick;
subplot(2,3,2+0*3);imagesc(tmp_C1_A_sbnlp_0099__,c_nlpvt2_lim_); title('A C1'); axis image; axisnotick;
subplot(2,3,3+0*3);imagesc(tmp_A_sbnlp_0099__,c_nlpvt2_lim_); title('A (cap)'); axis image; axisnotick;
subplot(2,3,1+1*3);imagesc(tmp_C0_BB_sbnlp_0099__,c_nlpvt2_lim_); title('BB C0'); axis image; axisnotick;
subplot(2,3,2+1*3);imagesc(tmp_C1_BB_sbnlp_0099__,c_nlpvt2_lim_); title('BB C1'); axis image; axisnotick;
subplot(2,3,3+1*3);imagesc(tmp_BB_sbnlp_0099__,c_nlpvt2_lim_); title('BB (cap)'); axis image; axisnotick;
%%%%%%%%;
% Create table of results. ;
%%%%%%%%;
str_sign_ = {'neg';'pos'};
[tmp_index_v0_,tmp_index_v1_] = ind2sub([n_var,n_var],1+tmp_index_A_); tmp_index_v0_ = tmp_index_v0_ - 1; tmp_index_v1_ = tmp_index_v1_ - 1;
string_A_0099_cap_ = cell(numel(tmp_index_A_),1);
snlp_A_0099_cap_ = zeros(numel(tmp_index_A_),1);
for nl=0:numel(tmp_index_A_)-1;
tmp_index_v0 = tmp_index_v0_(1+nl);
tmp_index_v1 = tmp_index_v1_(1+nl);
tmp_A_sbnlp_0099 = tmp_A_sbnlp_0099__(1+tmp_index_v0,1+tmp_index_v1);
string_A_0099_cap_{1+nl} = sprintf('%s->%s (direct %s)',string_dat_name_{1+tmp_index_v1},string_dat_name_{1+tmp_index_v0},str_sign_{1+(tmp_A_sbnlp_0099> 0)});
snlp_A_0099_cap_(1+nl) = tmp_A_sbnlp_0099;
end;%for nl=0:numel(tmp_index_A_)-1;
[~,tmp_index_] = sort(abs(snlp_A_0099_cap_),'descend'); tmp_index_ = tmp_index_-1;
T_Label_ = string_A_0099_cap_(1+tmp_index_);
T_Pval_ = num2str(exp(-abs(snlp_A_0099_cap_(1+tmp_index_))),2);
T_A_0099_ = table(T_Label_,T_Pval_);
writetable(T_A_0099_,sprintf('%s/T_A_0099_.csv',dir_mat));
%%%%;
str_sign_ = {'anticorrelated';'correlated'};
[tmp_index_v0_,tmp_index_v1_] = ind2sub([n_var,n_var],1+tmp_index_BB_); tmp_index_v0_ = tmp_index_v0_ - 1; tmp_index_v1_ = tmp_index_v1_ - 1;
string_BB_0099_cap_ = cell(numel(tmp_index_BB_)/2,1);
snlp_BB_0099_cap_ = zeros(numel(tmp_index_BB_)/2,1);
nl2=0;
for nl=0:numel(tmp_index_BB_)-1;
tmp_index_v0 = tmp_index_v0_(1+nl);
tmp_index_v1 = tmp_index_v1_(1+nl);
if (tmp_index_v1> tmp_index_v0);
tmp_BB_sbnlp_0099 = tmp_BB_sbnlp_0099__(1+tmp_index_v0,1+tmp_index_v1);
string_BB_0099_cap_{1+nl2} = sprintf('%s<->%s (stochastic %s)',string_dat_name_{1+tmp_index_v1},string_dat_name_{1+tmp_index_v0},str_sign_{1+(tmp_BB_sbnlp_0099> 0)});
snlp_BB_0099_cap_(1+nl2) = tmp_BB_sbnlp_0099;
nl2=nl2+1;
end;%if (tmp_index_v1> tmp_index_v0);
end;%for nl=0:numel(tmp_index_BB_)-1;
[~,tmp_index_] = sort(abs(snlp_BB_0099_cap_),'descend'); tmp_index_ = tmp_index_-1;
T_Label_ = string_BB_0099_cap_(1+tmp_index_);
T_Pval_ = num2str(exp(-abs(snlp_BB_0099_cap_(1+tmp_index_))),2);
T_BB_0099_ = table(T_Label_,T_Pval_);
writetable(T_BB_0099_,sprintf('%s/T_BB_0099_.csv',dir_mat));
%%%%%%%%;

tmp_C0_A_sbnlp_7099_vs_0030__ = tmp_C0_.A_sbnlp_7099_vs_0030__ - diag(diag(tmp_C0_.A_sbnlp_7099_vs_0030__));
tmp_C1_A_sbnlp_7099_vs_0030__ = tmp_C1_.A_sbnlp_7099_vs_0030__ - diag(diag(tmp_C1_.A_sbnlp_7099_vs_0030__));
tmp_index_C0_A_pos_ = efind(tmp_C0_A_sbnlp_7099_vs_0030__>=+3);
tmp_index_C1_A_pos_ = efind(tmp_C1_A_sbnlp_7099_vs_0030__>=+3);
tmp_index_A_pos_ = intersect(tmp_index_C0_A_pos_,tmp_index_C1_A_pos_);
tmp_index_C0_A_neg_ = efind(tmp_C0_A_sbnlp_7099_vs_0030__<=-3);
tmp_index_C1_A_neg_ = efind(tmp_C1_A_sbnlp_7099_vs_0030__<=-3);
tmp_index_A_neg_ = intersect(tmp_index_C0_A_neg_,tmp_index_C1_A_neg_);
tmp_index_A_ = union(tmp_index_A_pos_,tmp_index_A_neg_);
tmp_A_sbnlp_7099_vs_0030__ = zeros(n_var,n_var);
tmp_A_sbnlp_7099_vs_0030__(1+tmp_index_A_pos_) = min(tmp_C0_A_sbnlp_7099_vs_0030__(1+tmp_index_A_pos_),tmp_C1_A_sbnlp_7099_vs_0030__(1+tmp_index_A_pos_));
tmp_A_sbnlp_7099_vs_0030__(1+tmp_index_A_neg_) = max(tmp_C0_A_sbnlp_7099_vs_0030__(1+tmp_index_A_neg_),tmp_C1_A_sbnlp_7099_vs_0030__(1+tmp_index_A_neg_));
%%%%;
tmp_C0_BB_sbnlp_7099_vs_0030__ = tmp_C0_.BB_sbnlp_7099_vs_0030__ - diag(diag(tmp_C0_.BB_sbnlp_7099_vs_0030__));
tmp_C1_BB_sbnlp_7099_vs_0030__ = tmp_C1_.BB_sbnlp_7099_vs_0030__ - diag(diag(tmp_C1_.BB_sbnlp_7099_vs_0030__));
tmp_index_C0_BB_pos_ = efind(tmp_C0_BB_sbnlp_7099_vs_0030__>=+3);
tmp_index_C1_BB_pos_ = efind(tmp_C1_BB_sbnlp_7099_vs_0030__>=+3);
tmp_index_BB_pos_ = intersect(tmp_index_C0_BB_pos_,tmp_index_C1_BB_pos_);
tmp_index_C0_BB_neg_ = efind(tmp_C0_BB_sbnlp_7099_vs_0030__<=-3);
tmp_index_C1_BB_neg_ = efind(tmp_C1_BB_sbnlp_7099_vs_0030__<=-3);
tmp_index_BB_neg_ = intersect(tmp_index_C0_BB_neg_,tmp_index_C1_BB_neg_);
tmp_index_BB_ = union(tmp_index_BB_pos_,tmp_index_BB_neg_);
tmp_BB_sbnlp_7099_vs_0030__ = zeros(n_var,n_var);
tmp_BB_sbnlp_7099_vs_0030__(1+tmp_index_BB_pos_) = min(tmp_C0_BB_sbnlp_7099_vs_0030__(1+tmp_index_BB_pos_),tmp_C1_BB_sbnlp_7099_vs_0030__(1+tmp_index_BB_pos_));
tmp_BB_sbnlp_7099_vs_0030__(1+tmp_index_BB_neg_) = max(tmp_C0_BB_sbnlp_7099_vs_0030__(1+tmp_index_BB_neg_),tmp_C1_BB_sbnlp_7099_vs_0030__(1+tmp_index_BB_neg_));
%%%%;
figure(1);clf;figmed;
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
colormap(c_nlpvt2__);
subplot(2,3,1+0*3);imagesc(tmp_C0_A_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); title('A C0'); axis image; axisnotick;
subplot(2,3,2+0*3);imagesc(tmp_C1_A_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); title('A C1'); axis image; axisnotick;
subplot(2,3,3+0*3);imagesc(tmp_A_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); title('A (cap)'); axis image; axisnotick;
subplot(2,3,1+1*3);imagesc(tmp_C0_BB_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); title('BB C0'); axis image; axisnotick;
subplot(2,3,2+1*3);imagesc(tmp_C1_BB_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); title('BB C1'); axis image; axisnotick;
subplot(2,3,3+1*3);imagesc(tmp_BB_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); title('BB (cap)'); axis image; axisnotick;
%%%%%%%%;
% Create table of results. ;
%%%%%%%%;
str_sign_ = {'neg';'pos'};
[tmp_index_v0_,tmp_index_v1_] = ind2sub([n_var,n_var],1+tmp_index_A_); tmp_index_v0_ = tmp_index_v0_ - 1; tmp_index_v1_ = tmp_index_v1_ - 1;
string_A_7099_vs_0030_cap_ = cell(numel(tmp_index_A_),1);
snlp_A_7099_vs_0030_cap_ = zeros(numel(tmp_index_A_),1);
for nl=0:numel(tmp_index_A_)-1;
tmp_index_v0 = tmp_index_v0_(1+nl);
tmp_index_v1 = tmp_index_v1_(1+nl);
tmp_A_sbnlp_7099_vs_0030 = tmp_A_sbnlp_7099_vs_0030__(1+tmp_index_v0,1+tmp_index_v1);
string_A_7099_vs_0030_cap_{1+nl} = sprintf('%s->%s (direct %s)',string_dat_name_{1+tmp_index_v1},string_dat_name_{1+tmp_index_v0},str_sign_{1+(tmp_A_sbnlp_7099_vs_0030> 0)});
snlp_A_7099_vs_0030_cap_(1+nl) = tmp_A_sbnlp_7099_vs_0030;
end;%for nl=0:numel(tmp_index_A_)-1;
[~,tmp_index_] = sort(abs(snlp_A_7099_vs_0030_cap_),'descend'); tmp_index_ = tmp_index_-1;
T_Label_ = string_A_7099_vs_0030_cap_(1+tmp_index_);
T_Pval_ = num2str(exp(-abs(snlp_A_7099_vs_0030_cap_(1+tmp_index_))),2);
T_A_7099_vs_0030_ = table(T_Label_,T_Pval_);
writetable(T_A_7099_vs_0030_,sprintf('%s/T_A_7099_vs_0030_.csv',dir_mat));
%%%%;
str_sign_ = {'anticorrelated';'correlated'};
[tmp_index_v0_,tmp_index_v1_] = ind2sub([n_var,n_var],1+tmp_index_BB_); tmp_index_v0_ = tmp_index_v0_ - 1; tmp_index_v1_ = tmp_index_v1_ - 1;
string_BB_7099_vs_0030_cap_ = cell(numel(tmp_index_BB_)/2,1);
snlp_BB_7099_vs_0030_cap_ = zeros(numel(tmp_index_BB_)/2,1);
nl2=0;
for nl=0:numel(tmp_index_BB_)-1;
tmp_index_v0 = tmp_index_v0_(1+nl);
tmp_index_v1 = tmp_index_v1_(1+nl);
if (tmp_index_v1> tmp_index_v0);
tmp_BB_sbnlp_7099_vs_0030 = tmp_BB_sbnlp_7099_vs_0030__(1+tmp_index_v0,1+tmp_index_v1);
string_BB_7099_vs_0030_cap_{1+nl2} = sprintf('%s<->%s (stochastic %s)',string_dat_name_{1+tmp_index_v1},string_dat_name_{1+tmp_index_v0},str_sign_{1+(tmp_BB_sbnlp_7099_vs_0030> 0)});
snlp_BB_7099_vs_0030_cap_(1+nl2) = tmp_BB_sbnlp_7099_vs_0030;
nl2=nl2+1;
end;%if (tmp_index_v1> tmp_index_v0);
end;%for nl=0:numel(tmp_index_BB_)-1;
[~,tmp_index_] = sort(abs(snlp_BB_7099_vs_0030_cap_),'descend'); tmp_index_ = tmp_index_-1;
T_Label_ = string_BB_7099_vs_0030_cap_(1+tmp_index_);
T_Pval_ = num2str(exp(-abs(snlp_BB_7099_vs_0030_cap_(1+tmp_index_))),2);
T_BB_7099_vs_0030_ = table(T_Label_,T_Pval_);
writetable(T_BB_7099_vs_0030_,sprintf('%s/T_BB_7099_vs_0030_.csv',dir_mat));
%}

dXX = 0; n_shuffle = 256;
age_percentile_range_ = [];

if (nargin<1); flag_constrain_CC = []; end;
if (isempty(flag_constrain_CC)); flag_constrain_CC = 1; end;

platform = 'access1';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
dir_trunk = sprintf('/%s/rangan/dir_bcc/dir_dolphin',string_root);
dir_jpg = sprintf('%s/dir_jpg4',dir_trunk);
if (~exist(dir_jpg,'dir')); disp(sprintf(' %% mkdir %s',dir_jpg)); mkdir(dir_jpg); end;
dir_mat = sprintf('%s/dir_mat4',dir_trunk);
if (~exist(dir_mat,'dir')); disp(sprintf(' %% mkdir %s',dir_mat)); mkdir(dir_mat); end;
dir_shuffle_mat = sprintf('%s/dir_shuffle%d_mat4',dir_trunk,n_shuffle);
if (~exist(dir_shuffle_mat,'dir')); disp(sprintf(' %% mkdir %s',dir_shuffle_mat)); mkdir(dir_shuffle_mat); end;

flag_replot=0;

flag_drift0=1;
flag_center=1;

if ( isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2dd%dc%dC%d_cmb',dXX,flag_drift0,flag_center,flag_constrain_CC);
end;%if ( isempty(age_percentile_range_));
if (~isempty(age_percentile_range_));
fname_infix = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d_cmb',dXX,min(age_percentile_range_),min(99,max(age_percentile_range_)),flag_drift0,flag_center,flag_constrain_CC);
end;%if (~isempty(age_percentile_range_));
disp(sprintf(' %% fname_infix %s',fname_infix));

dolphin_dXX_load_4;

%%%%%%%%;
% select age range. ;
%%%%%%%%;
if (~isempty(age_percentile_range_));
tmp_index_ = efind(age_>=prctile(age_,min(age_percentile_range_)) & age_<=prctile(age_,max(age_percentile_range_)));
disp(sprintf(' %% age_percentile_range_ [%0.2f %0.2f] --> [%0.2f %0.2f] <-- %d found',age_percentile_range_,prctile(age_,age_percentile_range_),numel(tmp_index_)));
aid_ = aid_(1+tmp_index_);
age_ = age_(1+tmp_index_);
dat__ = dat__(1+tmp_index_,:);
end;%if (~isempty(age_percentile_range_));

index_mss_ = efind(~isfinite(dat__));

fname_infix_0099 = sprintf('aid%.2dd%dc%dC%d_cmb',dXX,flag_drift0,flag_center,flag_constrain_CC);
fname_infix_0030 = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d_cmb',dXX, 0,30,flag_drift0,flag_center,flag_constrain_CC);
fname_infix_7099 = sprintf('aid%.2d_age%.2d%.2d_d%dc%dC%d_cmb',dXX,70,99,flag_drift0,flag_center,flag_constrain_CC);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 0099 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_0099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0099);
if ( exist(fname_mat_0099_o,'file'));
tmp_ = load(fname_mat_0099_o);
a_0099_o_ = tmp_.a_cmb_;
A_0099_o__ = tmp_.A_cmb__;
BB_0099_o__ = tmp_.BB_cmb__;
CC_0099_o__ = tmp_.CC_cmb__;
end;%if ( exist(fname_mat_0099_s,'file'));
%%%%%%%%;
a_avg_0099_ = zeros(n_var,1); a_std_0099_ = zeros(n_var,1);
A_avg_0099__ = zeros(n_var,n_var); A_std_0099__ = zeros(n_var,n_var);
BB_avg_0099__ = zeros(n_var,n_var); BB_std_0099__ = zeros(n_var,n_var);
CC_avg_0099__ = zeros(n_var,n_var); CC_std_0099__ = zeros(n_var,n_var);
n_found_0099 = 0;
fname_mat_0099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_0099);
if ( exist(fname_mat_0099_s,'file'));
tmp_ = load(fname_mat_0099_s);
n_found_0099 = size(tmp_.L_cmb_prm_,1);
a_avg_0099_ = mean(tmp_.a_cmb_prm__(:,2:end),2); a_std_0099_ = std(tmp_.a_cmb_prm__(:,2:end),1,2);
A_avg_0099__ = mean(tmp_.A_cmb_prm___(:,:,2:end),3); A_std_0099__ = std(tmp_.A_cmb_prm___(:,:,2:end),1,3);
BB_avg_0099__ = mean(tmp_.BB_cmb_prm___(:,:,2:end),3); BB_std_0099__ = std(tmp_.BB_cmb_prm___(:,:,2:end),1,3);
CC_avg_0099__ = mean(tmp_.CC_cmb_prm___(:,:,2:end),3); CC_std_0099__ = std(tmp_.CC_cmb_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_0099_s,'file'));
a_nlp_0099_ = -z_to_p_twosided_0((a_0099_o_ - a_avg_0099_)./a_std_0099_);
A_nlp_0099__ = -z_to_p_twosided_0((A_0099_o__ - A_avg_0099__)./A_std_0099__);
BB_nlp_0099__ = -z_to_p_twosided_0((BB_0099_o__ - BB_avg_0099__)./BB_std_0099__);
CC_nlp_0099__ = -z_to_p_twosided_0((CC_0099_o__ - CC_avg_0099__)./CC_std_0099__);
a_snlp_0099_ = sign(a_0099_o_ - a_avg_0099_).*a_nlp_0099_;
A_snlp_0099__ = sign(A_0099_o__ - A_avg_0099__).*A_nlp_0099__;
BB_snlp_0099__ = sign(BB_0099_o__ - BB_avg_0099__).*BB_nlp_0099__;
CC_snlp_0099__ = sign(CC_0099_o__ - CC_avg_0099__).*CC_nlp_0099__;
a_sbnlp_0099_ = sign(a_0099_o_ - a_avg_0099_).*max(0,a_nlp_0099_-log(n_var));
A_sbnlp_0099__ = sign(A_0099_o__ - A_avg_0099__).*max(0,A_nlp_0099__-log(n_var*(n_var-1)));
BB_sbnlp_0099__ = sign(BB_0099_o__ - BB_avg_0099__).*max(0,BB_nlp_0099__-log(n_var*(n_var-1)/2));
CC_sbnlp_0099__ = sign(CC_0099_o__ - CC_avg_0099__).*max(0,CC_nlp_0099__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_0099 %d',n_found_0099'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_fnet_A_FIGA',dir_jpg,fname_infix_0099);
if (0*flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
%%%%%%%%;
tmp__ = abs(A_sbnlp_0099__); tmp__ = tmp__ + transpose(tmp__);
z_out_ = fnet_0(tmp__);
%%%%;
figure(1);clf;figbig;fontsize_use = 8;
n_var_use = n_var;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
markersize_use = 32;
r_use = 0.25;
linewidth_use = 2;
str_symbol_ = {'o','^','s','p','h'};
%%%%;
hold on;
for nvar=0:n_var_use-1;
str_symbol = str_symbol_{1+mod(nvar,5)};
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach*nvar/n_var_use)));
plot(z_out_(1+nvar,1),z_out_(1+nvar,2),str_symbol,'MarkerSize',markersize_use,'MarkerFaceColor',c_beach__(1+nc_beach,:),'MarkerEdgeColor','k');
end;%for nvar=0:n_var_use-1;
hold off;
legend(string_dat_name_,'Location','NorthEast');
%%%%;
hold on;
for nvar0=0:n_var_use-1;
for nvar1=0:n_var_use-1;
A_sbnlp = A_sbnlp_0099__(1+nvar0,1+nvar1);
nc_nlpvt2 = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(A_sbnlp - min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
if (abs(A_sbnlp)>3);
l = plot_arc_0([z_out_(1+nvar1,1);z_out_(1+nvar1,2)],[z_out_(1+nvar0,1);z_out_(1+nvar0,2)],r_use);
set(l,'Color',c_nlpvt2__(1+nc_nlpvt2,:));
set(l,'LineWidth',linewidth_use);
end;%if (abs(A_sbnlp)>3);
end;%for nvar1=0:n_var_use-1;
end;%for nvar0=0:n_var_use-1;
hold off;
%%%%;
hold on;
for nvar=0:n_var_use-1;
str_symbol = str_symbol_{1+mod(nvar,5)};
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach*nvar/n_var_use)));
plot(z_out_(1+nvar,1),z_out_(1+nvar,2),str_symbol,'MarkerSize',markersize_use,'MarkerFaceColor',c_beach__(1+nc_beach,:),'MarkerEdgeColor','k');
end;%for nvar=0:n_var_use-1;
hold off;
%%%%;
axis equal; axisnotick;
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB2_FIGAB2',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,2,np);np=np+1; imagesc(A_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(1,2,np);np=np+1; imagesc(BB_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_A_FIGA',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(A_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_B_FIGB',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(BB_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_C_FIGC',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(CC_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_0099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_0099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_0099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_0099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_snlp_0099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_0099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(A_snlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(BB_snlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_0099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(CC_snlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB_FIGAB',dir_jpg,fname_infix_0099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,2,np);np=np+1; imagesc(A_snlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(2,2,np);np=np+1; imagesc(BB_snlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,2,np);np=np+1; imagesc(A_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,2) = subplot(2,2,np);np=np+1; imagesc(BB_sbnlp_0099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0099),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
colormap(subplot_(2,1),c_nlpvt2__);
colormap(subplot_(2,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 0030 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_0030_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0030);
if ( exist(fname_mat_0030_o,'file'));
tmp_ = load(fname_mat_0030_o);
a_0030_o_ = tmp_.a_cmb_;
A_0030_o__ = tmp_.A_cmb__;
BB_0030_o__ = tmp_.BB_cmb__;
CC_0030_o__ = tmp_.CC_cmb__;
end;%if ( exist(fname_mat_0030_s,'file'));
%%%%%%%%;
a_avg_0030_ = zeros(n_var,1); a_std_0030_ = zeros(n_var,1);
A_avg_0030__ = zeros(n_var,n_var); A_std_0030__ = zeros(n_var,n_var);
BB_avg_0030__ = zeros(n_var,n_var); BB_std_0030__ = zeros(n_var,n_var);
CC_avg_0030__ = zeros(n_var,n_var); CC_std_0030__ = zeros(n_var,n_var);
n_found_0030 = 0;
fname_mat_0030_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_0030);
if ( exist(fname_mat_0030_s,'file'));
tmp_ = load(fname_mat_0030_s);
n_found_0030 = size(tmp_.L_cmb_prm_,1);
a_avg_0030_ = mean(tmp_.a_cmb_prm__(:,2:end),2); a_std_0030_ = std(tmp_.a_cmb_prm__(:,2:end),1,2);
A_avg_0030__ = mean(tmp_.A_cmb_prm___(:,:,2:end),3); A_std_0030__ = std(tmp_.A_cmb_prm___(:,:,2:end),1,3);
BB_avg_0030__ = mean(tmp_.BB_cmb_prm___(:,:,2:end),3); BB_std_0030__ = std(tmp_.BB_cmb_prm___(:,:,2:end),1,3);
CC_avg_0030__ = mean(tmp_.CC_cmb_prm___(:,:,2:end),3); CC_std_0030__ = std(tmp_.CC_cmb_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_0030_s,'file'));
a_nlp_0030_ = -z_to_p_twosided_0((a_0030_o_ - a_avg_0030_)./a_std_0030_);
A_nlp_0030__ = -z_to_p_twosided_0((A_0030_o__ - A_avg_0030__)./A_std_0030__);
BB_nlp_0030__ = -z_to_p_twosided_0((BB_0030_o__ - BB_avg_0030__)./BB_std_0030__);
CC_nlp_0030__ = -z_to_p_twosided_0((CC_0030_o__ - CC_avg_0030__)./CC_std_0030__);
a_snlp_0030_ = sign(a_0030_o_ - a_avg_0030_).*a_nlp_0030_;
A_snlp_0030__ = sign(A_0030_o__ - A_avg_0030__).*A_nlp_0030__;
BB_snlp_0030__ = sign(BB_0030_o__ - BB_avg_0030__).*BB_nlp_0030__;
CC_snlp_0030__ = sign(CC_0030_o__ - CC_avg_0030__).*CC_nlp_0030__;
a_sbnlp_0030_ = sign(a_0030_o_ - a_avg_0030_).*max(0,a_nlp_0030_-log(n_var));
A_sbnlp_0030__ = sign(A_0030_o__ - A_avg_0030__).*max(0,A_nlp_0030__-log(n_var*(n_var-1)));
BB_sbnlp_0030__ = sign(BB_0030_o__ - BB_avg_0030__).*max(0,BB_nlp_0030__-log(n_var*(n_var-1)/2));
CC_sbnlp_0030__ = sign(CC_0030_o__ - CC_avg_0030__).*max(0,CC_nlp_0030__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_0030 %d',n_found_0030'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_0030_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_0030_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_0030_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_0030_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_snlp_0030_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_0030_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(A_snlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0030),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(BB_snlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(CC_snlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0030),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB_FIGAB',dir_jpg,fname_infix_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,2,np);np=np+1; imagesc(A_snlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(2,2,np);np=np+1; imagesc(BB_snlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,2,np);np=np+1; imagesc(A_sbnlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,2) = subplot(2,2,np);np=np+1; imagesc(BB_sbnlp_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_0030),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
colormap(subplot_(2,1),c_nlpvt2__);
colormap(subplot_(2,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 7099 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_7099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_7099);
if ( exist(fname_mat_7099_o,'file'));
tmp_ = load(fname_mat_7099_o);
a_7099_o_ = tmp_.a_cmb_;
A_7099_o__ = tmp_.A_cmb__;
BB_7099_o__ = tmp_.BB_cmb__;
CC_7099_o__ = tmp_.CC_cmb__;
end;%if ( exist(fname_mat_7099_s,'file'));
%%%%%%%%;
a_avg_7099_ = zeros(n_var,1); a_std_7099_ = zeros(n_var,1);
A_avg_7099__ = zeros(n_var,n_var); A_std_7099__ = zeros(n_var,n_var);
BB_avg_7099__ = zeros(n_var,n_var); BB_std_7099__ = zeros(n_var,n_var);
CC_avg_7099__ = zeros(n_var,n_var); CC_std_7099__ = zeros(n_var,n_var);
n_found_7099 = 0;
fname_mat_7099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_7099);
if ( exist(fname_mat_7099_s,'file'));
tmp_ = load(fname_mat_7099_s);
n_found_7099 = size(tmp_.L_cmb_prm_,1);
a_avg_7099_ = mean(tmp_.a_cmb_prm__(:,2:end),2); a_std_7099_ = std(tmp_.a_cmb_prm__(:,2:end),1,2);
A_avg_7099__ = mean(tmp_.A_cmb_prm___(:,:,2:end),3); A_std_7099__ = std(tmp_.A_cmb_prm___(:,:,2:end),1,3);
BB_avg_7099__ = mean(tmp_.BB_cmb_prm___(:,:,2:end),3); BB_std_7099__ = std(tmp_.BB_cmb_prm___(:,:,2:end),1,3);
CC_avg_7099__ = mean(tmp_.CC_cmb_prm___(:,:,2:end),3); CC_std_7099__ = std(tmp_.CC_cmb_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_7099_s,'file'));
a_nlp_7099_ = -z_to_p_twosided_0((a_7099_o_ - a_avg_7099_)./a_std_7099_);
A_nlp_7099__ = -z_to_p_twosided_0((A_7099_o__ - A_avg_7099__)./A_std_7099__);
BB_nlp_7099__ = -z_to_p_twosided_0((BB_7099_o__ - BB_avg_7099__)./BB_std_7099__);
CC_nlp_7099__ = -z_to_p_twosided_0((CC_7099_o__ - CC_avg_7099__)./CC_std_7099__);
a_snlp_7099_ = sign(a_7099_o_ - a_avg_7099_).*a_nlp_7099_;
A_snlp_7099__ = sign(A_7099_o__ - A_avg_7099__).*A_nlp_7099__;
BB_snlp_7099__ = sign(BB_7099_o__ - BB_avg_7099__).*BB_nlp_7099__;
CC_snlp_7099__ = sign(CC_7099_o__ - CC_avg_7099__).*CC_nlp_7099__;
a_sbnlp_7099_ = sign(a_7099_o_ - a_avg_7099_).*max(0,a_nlp_7099_-log(n_var));
A_sbnlp_7099__ = sign(A_7099_o__ - A_avg_7099__).*max(0,A_nlp_7099__-log(n_var*(n_var-1)));
BB_sbnlp_7099__ = sign(BB_7099_o__ - BB_avg_7099__).*max(0,BB_nlp_7099__-log(n_var*(n_var-1)/2));
CC_sbnlp_7099__ = sign(CC_7099_o__ - CC_avg_7099__).*max(0,CC_nlp_7099__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_7099 %d',n_found_7099'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_7099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_7099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_7099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_7099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_7099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_snlp_7099_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_7099_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_7099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_7099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(A_snlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_7099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_7099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_7099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(BB_snlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_7099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_7099__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(CC_snlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB_FIGAB',dir_jpg,fname_infix_7099);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,2,np);np=np+1; imagesc(A_snlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(2,2,np);np=np+1; imagesc(BB_snlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,2,np);np=np+1; imagesc(A_sbnlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,2) = subplot(2,2,np);np=np+1; imagesc(BB_sbnlp_7099__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
colormap(subplot_(2,1),c_nlpvt2__);
colormap(subplot_(2,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% check distribution of shuffle coefficients. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
fname_mat_0099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_0099);
if ( exist(fname_mat_0099_s,'file'));
tmp_ = load(fname_mat_0099_s);
n_found_0099 = size(tmp_.L_cmb_prm_,1) - 1;
a_0099__ = tmp_.a_cmb_prm__(:,2:end);
A_0099__ = reshape(tmp_.A_cmb_prm___(:,:,2:end),[n_var^2,n_found_0099]);
BB_0099__ = reshape(tmp_.BB_cmb_prm___(:,:,2:end),[n_var^2,n_found_0099]);
CC_0099__ = zeros(n_var,n_found_0099);
for nfound=0:n_found_0099-1;
CC_0099__(:,1+nfound)= diag(tmp_.CC_cmb_prm___(:,:,1+1+nfound));
end;%for nfound=0:n_found_0099-1;
disp(sprintf(' %% n_found_0099 %d',n_found_0099'));
a_0099_nrm__ = (a_0099__ - repmat(mean(a_0099__,2),[1,n_found_0099]))./repmat(std(a_0099__,[],2),[1,n_found_0099]);
A_0099_nrm__ = (A_0099__ - repmat(mean(A_0099__,2),[1,n_found_0099]))./repmat(std(A_0099__,[],2),[1,n_found_0099]);
BB_0099_nrm__ = (BB_0099__ - repmat(mean(BB_0099__,2),[1,n_found_0099]))./repmat(std(BB_0099__,[],2),[1,n_found_0099]);
CC_0099_nrm__ = (CC_0099__ - repmat(mean(CC_0099__,2),[1,n_found_0099]))./repmat(std(CC_0099__,[],2),[1,n_found_0099]);
figure(1);clf;figbig;
subplot(2,2,1); hist(a_0099_nrm__(:),128); title('a_0099_nrm__(:)','Interpreter','none');
subplot(2,2,2); hist(A_0099_nrm__(:),128); title('AA_0099_nrm__(:)','Interpreter','none');
subplot(2,2,3); hist(BB_0099_nrm__(:),128); title('BB_0099_nrm__(:)','Interpreter','none');
subplot(2,2,4); hist(CC_0099_nrm__(:),128); title('CC_0099_nrm__(:)','Interpreter','none');
end;%if ( exist(fname_mat_0099_s,'file'));
%%%%%%%%;
%%%%%%%%;
%%%%%%%%;
% verdict: a, A_ and BB_ and CC_ are close to gaussian distributed. ;
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% Now use the same approach to estimate the significant differences between 7099 and 0030. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_infix_7099_vs_0030 = sprintf('aid%.2d_age_7099_vs_0030_d%dc%dC%d_cmb',dXX,flag_drift0,flag_center,flag_constrain_CC);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% 7099_vs_0030 ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
fname_mat_7099_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_7099);
if ( exist(fname_mat_7099_o,'file'));
tmp_ = load(fname_mat_7099_o);
a_7099_o_ = tmp_.a_cmb_;
A_7099_o__ = tmp_.A_cmb__;
BB_7099_o__ = tmp_.BB_cmb__;
CC_7099_o__ = tmp_.CC_cmb__;
end;%if ( exist(fname_mat_7099_s,'file'));
fname_mat_0030_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_0030);
if ( exist(fname_mat_0030_o,'file'));
tmp_ = load(fname_mat_0030_o);
a_0030_o_ = tmp_.a_cmb_;
A_0030_o__ = tmp_.A_cmb__;
BB_0030_o__ = tmp_.BB_cmb__;
CC_0030_o__ = tmp_.CC_cmb__;
end;%if ( exist(fname_mat_0030_s,'file'));
a_7099_vs_0030_o_ = a_7099_o_ - a_0030_o_;
A_7099_vs_0030_o__ = A_7099_o__ - A_0030_o__;
BB_7099_vs_0030_o__ = BB_7099_o__ - BB_0030_o__;
CC_7099_vs_0030_o__ = CC_7099_o__ - CC_0030_o__;
%%%%%%%%;
a_avg_7099_vs_0030_ = zeros(n_var,1); a_std_7099_vs_0030_ = zeros(n_var,1);
A_avg_7099_vs_0030__ = zeros(n_var,n_var); A_std_7099_vs_0030__ = zeros(n_var,n_var);
BB_avg_7099_vs_0030__ = zeros(n_var,n_var); BB_std_7099_vs_0030__ = zeros(n_var,n_var);
CC_avg_7099_vs_0030__ = zeros(n_var,n_var); CC_std_7099_vs_0030__ = zeros(n_var,n_var);
%%%%;
fname_mat_7099_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_7099);
fname_mat_0030_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_0030);
if ( exist(fname_mat_7099_s,'file') &  exist(fname_mat_0030_s,'file'));
tmp_7099_ = load(fname_mat_7099_s);
tmp_0030_ = load(fname_mat_0030_s);
n_found_7099_vs_0030 = min(numel(tmp_7099_.L_cmb_prm_),numel(tmp_0030_.L_cmb_prm_)) - 1;
a_avg_7099_vs_0030_ = mean(tmp_7099_.a_cmb_prm__(:,2:end) - tmp_0030_.a_cmb_prm__(:,2:end),2);
a_std_7099_vs_0030_ = std(tmp_7099_.a_cmb_prm__(:,2:end) - tmp_0030_.a_cmb_prm__(:,2:end),1,2);
A_avg_7099_vs_0030__ = mean(tmp_7099_.A_cmb_prm___(:,:,2:end) - tmp_0030_.A_cmb_prm___(:,:,2:end),3);
A_std_7099_vs_0030__ = std(tmp_7099_.A_cmb_prm___(:,:,2:end) - tmp_0030_.A_cmb_prm___(:,:,2:end),1,3);
BB_avg_7099_vs_0030__ = mean(tmp_7099_.BB_cmb_prm___(:,:,2:end) - tmp_0030_.BB_cmb_prm___(:,:,2:end),3);
BB_std_7099_vs_0030__ = std(tmp_7099_.BB_cmb_prm___(:,:,2:end) - tmp_0030_.BB_cmb_prm___(:,:,2:end),1,3);
CC_avg_7099_vs_0030__ = mean(tmp_7099_.CC_cmb_prm___(:,:,2:end) - tmp_0030_.CC_cmb_prm___(:,:,2:end),3);
CC_std_7099_vs_0030__ = std(tmp_7099_.CC_cmb_prm___(:,:,2:end) - tmp_0030_.CC_cmb_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_7099_s,'file') &  exist(fname_mat_0030_s,'file'));
%%%%;
a_nlp_7099_vs_0030_ = -z_to_p_twosided_0((a_7099_vs_0030_o_ - a_avg_7099_vs_0030_)./a_std_7099_vs_0030_);
A_nlp_7099_vs_0030__ = -z_to_p_twosided_0((A_7099_vs_0030_o__ - A_avg_7099_vs_0030__)./A_std_7099_vs_0030__);
BB_nlp_7099_vs_0030__ = -z_to_p_twosided_0((BB_7099_vs_0030_o__ - BB_avg_7099_vs_0030__)./BB_std_7099_vs_0030__);
CC_nlp_7099_vs_0030__ = -z_to_p_twosided_0((CC_7099_vs_0030_o__ - CC_avg_7099_vs_0030__)./CC_std_7099_vs_0030__);
a_snlp_7099_vs_0030_ = sign(a_7099_vs_0030_o_ - a_avg_7099_vs_0030_).*a_nlp_7099_vs_0030_;
A_snlp_7099_vs_0030__ = sign(A_7099_vs_0030_o__ - A_avg_7099_vs_0030__).*A_nlp_7099_vs_0030__;
BB_snlp_7099_vs_0030__ = sign(BB_7099_vs_0030_o__ - BB_avg_7099_vs_0030__).*BB_nlp_7099_vs_0030__;
CC_snlp_7099_vs_0030__ = sign(CC_7099_vs_0030_o__ - CC_avg_7099_vs_0030__).*CC_nlp_7099_vs_0030__;
a_sbnlp_7099_vs_0030_ = sign(a_7099_vs_0030_o_ - a_avg_7099_vs_0030_).*max(0,a_nlp_7099_vs_0030_-log(n_var));
A_sbnlp_7099_vs_0030__ = sign(A_7099_vs_0030_o__ - A_avg_7099_vs_0030__).*max(0,A_nlp_7099_vs_0030__-log(n_var*(n_var-1)));
BB_sbnlp_7099_vs_0030__ = sign(BB_7099_vs_0030_o__ - BB_avg_7099_vs_0030__).*max(0,BB_nlp_7099_vs_0030__-log(n_var*(n_var-1)/2));
CC_sbnlp_7099_vs_0030__ = sign(CC_7099_vs_0030_o__ - CC_avg_7099_vs_0030__).*max(0,CC_nlp_7099_vs_0030__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_7099_vs_0030 %d',n_found_7099_vs_0030'));
%%%%%%%%;

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB2_FIGAB2',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,2,np);np=np+1; imagesc(A_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(1,2,np);np=np+1; imagesc(BB_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_A_FIGA',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(A_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_B_FIGB',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(BB_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_C_FIGC',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(CC_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_7099_vs_0030_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_7099_vs_0030_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_7099_vs_0030_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_7099_vs_0030_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_snlp_7099_vs_0030_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_7099_vs_0030_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_7099_vs_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_7099_vs_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(A_snlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_7099_vs_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_7099_vs_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(BB_snlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_7099_vs_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_7099_vs_0030__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(CC_snlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB_FIGAB',dir_jpg,fname_infix_7099_vs_0030);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,2,np);np=np+1; imagesc(A_snlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(2,2,np);np=np+1; imagesc(BB_snlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099_vs_0030__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,2,np);np=np+1; imagesc(A_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,2) = subplot(2,2,np);np=np+1; imagesc(BB_sbnlp_7099_vs_0030__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_7099_vs_0030__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_7099_vs_0030),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
colormap(subplot_(2,1),c_nlpvt2__);
colormap(subplot_(2,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%%%%%%%%;
% Save results.; 
%%%%%%%%;
fname_mat = sprintf('%s/dolphin_aid%.2dd%dc%dC%d_cmb_snlp.mat',dir_mat,dXX,flag_drift0,flag_center,flag_constrain_CC);
if (~exist(fname_mat,'file'));
disp(sprintf(' %% %s not found, creating',fname_mat));
save(fname_mat ...
,'a_0099_o_','a_avg_0099_','a_std_0099_' ...
,'A_0099_o__','A_avg_0099__','A_std_0099__' ...
,'BB_0099_o__','BB_avg_0099__','BB_std_0099__' ...
,'CC_0099_o__','CC_avg_0099__','CC_std_0099__' ...
,'a_nlp_0099_','a_snlp_0099_','a_sbnlp_0099_' ...
,'A_nlp_0099__','A_snlp_0099__','A_sbnlp_0099__' ...
,'BB_nlp_0099__','BB_snlp_0099__','BB_sbnlp_0099__' ...
,'CC_nlp_0099__','CC_snlp_0099__','CC_sbnlp_0099__' ...
,'a_0030_o_','a_avg_0030_','a_std_0030_' ...
,'A_0030_o__','A_avg_0030__','A_std_0030__' ...
,'BB_0030_o__','BB_avg_0030__','BB_std_0030__' ...
,'CC_0030_o__','CC_avg_0030__','CC_std_0030__' ...
,'a_nlp_0030_','a_snlp_0030_','a_sbnlp_0030_' ...
,'A_nlp_0030__','A_snlp_0030__','A_sbnlp_0030__' ...
,'BB_nlp_0030__','BB_snlp_0030__','BB_sbnlp_0030__' ...
,'CC_nlp_0030__','CC_snlp_0030__','CC_sbnlp_0030__' ...
,'a_7099_o_','a_avg_7099_','a_std_7099_' ...
,'A_7099_o__','A_avg_7099__','A_std_7099__' ...
,'BB_7099_o__','BB_avg_7099__','BB_std_7099__' ...
,'CC_7099_o__','CC_avg_7099__','CC_std_7099__' ...
,'a_nlp_7099_','a_snlp_7099_','a_sbnlp_7099_' ...
,'A_nlp_7099__','A_snlp_7099__','A_sbnlp_7099__' ...
,'BB_nlp_7099__','BB_snlp_7099__','BB_sbnlp_7099__' ...
,'CC_nlp_7099__','CC_snlp_7099__','CC_sbnlp_7099__' ...
,'a_7099_vs_0030_o_','a_avg_7099_vs_0030_','a_std_7099_vs_0030_' ...
,'A_7099_vs_0030_o__','A_avg_7099_vs_0030__','A_std_7099_vs_0030__' ...
,'BB_7099_vs_0030_o__','BB_avg_7099_vs_0030__','BB_std_7099_vs_0030__' ...
,'CC_7099_vs_0030_o__','CC_avg_7099_vs_0030__','CC_std_7099_vs_0030__' ...
,'a_nlp_7099_vs_0030_','a_snlp_7099_vs_0030_','a_sbnlp_7099_vs_0030_' ...
,'A_nlp_7099_vs_0030__','A_snlp_7099_vs_0030__','A_sbnlp_7099_vs_0030__' ...
,'BB_nlp_7099_vs_0030__','BB_snlp_7099_vs_0030__','BB_sbnlp_7099_vs_0030__' ...
,'CC_nlp_7099_vs_0030__','CC_snlp_7099_vs_0030__','CC_sbnlp_7099_vs_0030__' ...
);
end;%if (~exist(fname_mat,'file'));
