function ...
[ ...
 parameter ...
 ,n_found_zzzz ...
 ,a_zzzz_o_ ...
 ,A_zzzz_o__ ...
 ,BB_zzzz_o__ ...
 ,CC_zzzz_o__ ...
 ,a_sbnlp_zzzz_ ...
 ,A_sbnlp_zzzz__ ...
 ,BB_sbnlp_zzzz__ ...
 ,CC_sbnlp_zzzz__ ...
 ,a_snlp_zzzz_ ...
 ,A_snlp_zzzz__ ...
 ,BB_snlp_zzzz__ ...
 ,CC_snlp_zzzz__ ...
 ,a_nlp_zzzz_ ...
 ,A_nlp_zzzz__ ...
 ,BB_nlp_zzzz__ ...
 ,CC_nlp_zzzz__ ...
 ,a_avg_zzzz_ ...
 ,A_avg_zzzz__ ...
 ,BB_avg_zzzz__ ...
 ,CC_avg_zzzz__ ...
 ,a_std_zzzz_ ...
 ,A_std_zzzz__ ...
 ,BB_std_zzzz__ ...
 ,CC_std_zzzz__ ...
] = ...
dolphin_d00_cmb_collect_and_plot_1( ...
 parameter ...
 ,n_var ...
 ,string_dat_name_ ...
 ,dir_mat ...
 ,dir_shuffle_mat ...
 ,dir_jpg ...
 ,fname_infix_zzzz ...
);

verbose=1;
if (verbose); disp(sprintf(' %% [entering dolphin_d00_cmb_collect_and_plot_1]')); end;

if (isempty(parameter)); parameter = struct('type','parameter'); end;
if (~isfield(parameter,'flag_replot')); parameter.flag_replot = 0; end; %<-- parameter_bookmark. ;
if (~isfield(parameter,'flag_plot_fnet')); parameter.flag_plot_fnet = 0; end; %<-- parameter_bookmark. ;
flag_replot = parameter.flag_replot;
flag_plot_fnet = parameter.flag_plot_fnet;

fname_mat_zzzz_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_zzzz);
fname_mat_zzzz_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_zzzz);
flag_exist = exist(fname_mat_zzzz_o,'file') & exist(fname_mat_zzzz_s,'file');
if ~flag_exist;
disp(sprintf(' %% %s %s not found, skipping',fname_mat_zzzz_o,fname_mat_zzzz_s));
end;%if ~flag_exist;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_exist;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

fname_mat_zzzz_o = sprintf('%s/dolphin_%s_s0000.mat',dir_mat,fname_infix_zzzz);
if ( exist(fname_mat_zzzz_o,'file'));
tmp_ = load(fname_mat_zzzz_o);
a_zzzz_o_ = tmp_.a_cmb_;
A_zzzz_o__ = tmp_.A_cmb__;
BB_zzzz_o__ = tmp_.BB_cmb__;
CC_zzzz_o__ = tmp_.CC_cmb__;
end;%if ( exist(fname_mat_zzzz_s,'file'));
%%%%%%%%;
a_avg_zzzz_ = zeros(n_var,1); a_std_zzzz_ = zeros(n_var,1);
A_avg_zzzz__ = zeros(n_var,n_var); A_std_zzzz__ = zeros(n_var,n_var);
BB_avg_zzzz__ = zeros(n_var,n_var); BB_std_zzzz__ = zeros(n_var,n_var);
CC_avg_zzzz__ = zeros(n_var,n_var); CC_std_zzzz__ = zeros(n_var,n_var);
n_found_zzzz = 0;
fname_mat_zzzz_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_zzzz);
if ( exist(fname_mat_zzzz_s,'file'));
tmp_ = load(fname_mat_zzzz_s);
n_found_zzzz = size(tmp_.L_cmb_prm_,1);
a_avg_zzzz_ = mean(tmp_.a_cmb_prm__(:,2:end),2); a_std_zzzz_ = std(tmp_.a_cmb_prm__(:,2:end),1,2);
A_avg_zzzz__ = mean(tmp_.A_cmb_prm___(:,:,2:end),3); A_std_zzzz__ = std(tmp_.A_cmb_prm___(:,:,2:end),1,3);
BB_avg_zzzz__ = mean(tmp_.BB_cmb_prm___(:,:,2:end),3); BB_std_zzzz__ = std(tmp_.BB_cmb_prm___(:,:,2:end),1,3);
CC_avg_zzzz__ = mean(tmp_.CC_cmb_prm___(:,:,2:end),3); CC_std_zzzz__ = std(tmp_.CC_cmb_prm___(:,:,2:end),1,3);
end;%if ( exist(fname_mat_zzzz_s,'file'));
a_nlp_zzzz_ = -z_to_p_twosided_0((a_zzzz_o_ - a_avg_zzzz_)./a_std_zzzz_);
A_nlp_zzzz__ = -z_to_p_twosided_0((A_zzzz_o__ - A_avg_zzzz__)./A_std_zzzz__);
BB_nlp_zzzz__ = -z_to_p_twosided_0((BB_zzzz_o__ - BB_avg_zzzz__)./BB_std_zzzz__);
CC_nlp_zzzz__ = -z_to_p_twosided_0((CC_zzzz_o__ - CC_avg_zzzz__)./CC_std_zzzz__);
a_snlp_zzzz_ = sign(a_zzzz_o_ - a_avg_zzzz_).*a_nlp_zzzz_;
A_snlp_zzzz__ = sign(A_zzzz_o__ - A_avg_zzzz__).*A_nlp_zzzz__;
BB_snlp_zzzz__ = sign(BB_zzzz_o__ - BB_avg_zzzz__).*BB_nlp_zzzz__;
CC_snlp_zzzz__ = sign(CC_zzzz_o__ - CC_avg_zzzz__).*CC_nlp_zzzz__;
a_sbnlp_zzzz_ = sign(a_zzzz_o_ - a_avg_zzzz_).*max(0,a_nlp_zzzz_-log(n_var));
A_sbnlp_zzzz__ = sign(A_zzzz_o__ - A_avg_zzzz__).*max(0,A_nlp_zzzz__-log(n_var*(n_var-1)));
BB_sbnlp_zzzz__ = sign(BB_zzzz_o__ - BB_avg_zzzz__).*max(0,BB_nlp_zzzz__-log(n_var*(n_var-1)/2));
CC_sbnlp_zzzz__ = sign(CC_zzzz_o__ - CC_avg_zzzz__).*max(0,CC_nlp_zzzz__-log(n_var*(n_var-1)/2));
%%%%%%%%;
disp(sprintf(' %% n_found_zzzz %d',n_found_zzzz'));
%%%%%%%%;

%%%%%%%%;
% Test out holm-bonferroni test. ;
%%%%%%%%;
index_retain_ = 0:n_var-1;
n_retain = numel(index_retain_);
a_zzzz_prm__ = tmp_.a_cmb_prm__;
a_zzzz_avg_ = mean(a_zzzz_prm__(:,2:end),2); a_zzzz_std_ = std(a_zzzz_prm__(:,2:end),1,2);
a_zzzz_nlp__ = -z_to_p_twosided_0((a_zzzz_prm__ - a_zzzz_avg_)./a_zzzz_std_);
a_zzzz_snlp__ = sign(a_zzzz_prm__ - a_zzzz_avg_).*a_zzzz_nlp__;
a_zzzz_sbnlp__ = sign(a_zzzz_prm__ - a_zzzz_avg_).*max(0,a_zzzz_nlp__-log(n_retain));
figsml;clf;
subplot(3,1,1);
%plot(1:n_retain,a_zzzz_prm__(:,1),'ro',1:n_retain,a_zzzz_prm__(:,2:end),'kx');
plot(1:n_retain,a_zzzz_nlp__(:,1),'ro',1:n_retain,a_zzzz_nlp__(:,2:end),'kx');
xlim([0,n_retain]);
subplot(3,1,2);
plot(1:n_retain,a_snlp_zzzz_,'ro',1:n_retain,a_sbnlp_zzzz_,'go');
xlim([0,n_retain]);
subplot(3,1,3);
plot(1:n_retain,sort(a_zzzz_nlp__(:,1),'descend'),'ro',1:n_retain,sort(a_zzzz_nlp__(:,2:end),'descend'),'k.');
xlim([0,n_retain]);
%%%%%%%%;
% verdict: looks like elements of a_ are largely independent. ;
%%%%%%%%;

index_retain_ = efind(ones(n_var,n_var)-eye(n_var,n_var));
n_retain = numel(index_retain_);
tmp_A_prm__ = reshape(tmp_.A_cmb_prm___,[n_var^2,n_shuffle+1]);
A_zzzz_prm__ = tmp_A_prm__(1+index_retain_,:);
A_zzzz_avg_ = mean(A_zzzz_prm__(:,2:end),2); A_zzzz_std_ = std(A_zzzz_prm__(:,2:end),1,2);
A_zzzz_nlp__ = -z_to_p_twosided_0((A_zzzz_prm__ - A_zzzz_avg_)./A_zzzz_std_);
A_zzzz_snlp__ = sign(A_zzzz_prm__ - A_zzzz_avg_).*A_zzzz_nlp__;
A_zzzz_sbnlp__ = sign(A_zzzz_prm__ - A_zzzz_avg_).*max(0,A_zzzz_nlp__-log(n_retain));
figsml;clf;
subplot(3,1,1);
%plot(1:n_retain,A_zzzz_prm__(:,1),'ro',1:n_retain,A_zzzz_prm__(:,2:end),'kx');
plot(1:n_retain,A_zzzz_nlp__(:,1),'ro',1:n_retain,A_zzzz_nlp__(:,2:end),'kx');
xlim([0,n_retain]);
subplot(3,1,2);
plot(1:n_retain,A_snlp_zzzz__(1+index_retain_),'ro',1:n_retain,A_sbnlp_zzzz__(1+index_retain_),'go');
xlim([0,n_retain]);
subplot(3,1,3);
plot(1:n_retain,sort(A_zzzz_nlp__(:,1),'descend'),'ro',1:n_retain,sort(A_zzzz_nlp__(:,2:end),'descend'),'k.');
xlim([0,n_retain]);
%%%%%%%%;
% verdict: entries of A__ are quite interdependent: bonferroni correction is an underestimate. ;
%%%%%%%%;

index_retain_ = efind(ones(n_var,n_var)--tril(ones(n_var,n_var)));
n_retain = numel(index_retain_);
tmp_BB_prm__ = reshape(tmp_.BB_cmb_prm___,[n_var^2,n_shuffle+1]);
BB_zzzz_prm__ = tmp_BB_prm__(1+index_retain_,:);
BB_zzzz_avg_ = mean(BB_zzzz_prm__(:,2:end),2); BB_zzzz_std_ = std(BB_zzzz_prm__(:,2:end),1,2);
BB_zzzz_nlp__ = -z_to_p_twosided_0((BB_zzzz_prm__ - BB_zzzz_avg_)./BB_zzzz_std_);
BB_zzzz_snlp__ = sign(BB_zzzz_prm__ - BB_zzzz_avg_).*BB_zzzz_nlp__;
BB_zzzz_sbnlp__ = sign(BB_zzzz_prm__ - BB_zzzz_avg_).*max(0,BB_zzzz_nlp__-log(n_retain));
figsml;clf;
subplot(3,1,1);
%plot(1:n_retain,BB_zzzz_prm__(:,1),'ro',1:n_retain,BB_zzzz_prm__(:,2:end),'kx');
plot(1:n_retain,BB_zzzz_nlp__(:,1),'ro',1:n_retain,BB_zzzz_nlp__(:,2:end),'kx');
xlim([0,n_retain]);
subplot(3,1,2);
plot(1:n_retain,BB_snlp_zzzz__(1+index_retain_),'ro',1:n_retain,BB_sbnlp_zzzz__(1+index_retain_),'go');
xlim([0,n_retain]);
subplot(3,1,3);
plot(1:n_retain,sort(BB_zzzz_nlp__(:,1),'descend'),'ro',1:n_retain,sort(BB_zzzz_nlp__(:,2:end),'descend'),'k.');
xlim([0,n_retain]);
%%%%%%%%;
% verdict: entries of BB__ are quite interdependent: bonferroni correction is an underestimate. ;
%%%%%%%%;

if flag_plot_fnet;
fname_fig = sprintf('%s/dolphin_%s_fnet_A_FIGA',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
%%%%%%%%;
tmp__ = abs(A_sbnlp_zzzz__); tmp__ = tmp__ + transpose(tmp__);
z_out_ = fnet_0(tmp__);
%%%%;
figure(1);clf;figbig;fontsize_use = 8;
n_var_use = n_var;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
markersize_use = 32;
r_use = 0.25;
linewidth_use = 2;
str_symbol_ = {'o','^','s','p','h'};
%%%%;
hold on;
for nvar=0:n_var_use-1;
str_symbol = str_symbol_{1+mod(nvar,5)};
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach*nvar/n_var_use)));
plot(z_out_(1+nvar,1),z_out_(1+nvar,2),str_symbol,'MarkerSize',markersize_use,'MarkerFaceColor',c_beach__(1+nc_beach,:),'MarkerEdgeColor','k');
end;%for nvar=0:n_var_use-1;
hold off;
legend(string_dat_name_,'Location','NorthEast');
%%%%;
hold on;
for nvar0=0:n_var_use-1;
for nvar1=0:n_var_use-1;
A_sbnlp = A_sbnlp_zzzz__(1+nvar0,1+nvar1);
nc_nlpvt2 = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(A_sbnlp - min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
if (abs(A_sbnlp)>3);
l = plot_arc_0([z_out_(1+nvar1,1);z_out_(1+nvar1,2)],[z_out_(1+nvar0,1);z_out_(1+nvar0,2)],r_use);
set(l,'Color',c_nlpvt2__(1+nc_nlpvt2,:));
set(l,'LineWidth',linewidth_use);
end;%if (abs(A_sbnlp)>3);
end;%for nvar1=0:n_var_use-1;
end;%for nvar0=0:n_var_use-1;
hold off;
%%%%;
hold on;
for nvar=0:n_var_use-1;
str_symbol = str_symbol_{1+mod(nvar,5)};
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach*nvar/n_var_use)));
plot(z_out_(1+nvar,1),z_out_(1+nvar,2),str_symbol,'MarkerSize',markersize_use,'MarkerFaceColor',c_beach__(1+nc_beach,:),'MarkerEdgeColor','k');
end;%for nvar=0:n_var_use-1;
hold off;
%%%%;
axis equal; axisnotick;
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));
end;%if flag_plot_fnet;

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB2_FIGAB2',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,2,np);np=np+1; imagesc(A_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(1,2,np);np=np+1; imagesc(BB_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_A_FIGA',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(A_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_B_FIGB',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(BB_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_C_FIGC',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;set(gcf,'Position',1+[0,0,1024,1024]);fontsize_use = 12;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(1,1,np);np=np+1; imagesc(CC_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
hold on;
l_x_ = +0.5 + (n_var)*[zeros(1,n_var);ones(1,n_var)];
l_y_ = +0.5 + repmat([0:n_var-1],[2,1]);
line(l_x_,l_y_,'Color',0.85*[1,1,1],'LineWidth',0.5);
line(l_y_,l_x_,'Color',0.85*[1,1,1],'LineWidth',0.5);
hold off;
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_aA_FIGaA',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_avg_zzzz_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_avg_zzzz_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,2) = subplot(2,3,np);np=np+1; 
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_std_zzzz_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_beach-1,floor(n_c_beach*(tmp_y-min(c_beach_lim_))/diff(c_beach_lim_))));
tmp_c_(1,1+nvar,:) = c_beach__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(0.125*c_beach_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('a_std_zzzz_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
subplot_(1,3) = subplot(2,3,np);np=np+1;
tmp_x_ = zeros(4,n_var); tmp_y_ = zeros(4,n_var); tmp_c_ = zeros(1,n_var,3);
for nvar=0:n_var-1; 
tmp_y = a_snlp_zzzz_(1+nvar); tmp_x_(:,1+nvar) = -0.5+1+nvar+[0;0;1;1]; tmp_y_(:,1+nvar) = [0;tmp_y;tmp_y;0]; 
tmp_nc = max(0,min(n_c_nlpvt2-1,floor(n_c_nlpvt2*(tmp_y-min(c_nlpvt2_lim_))/diff(c_nlpvt2_lim_))));
tmp_c_(1,1+nvar,:) = c_nlpvt2__(1+tmp_nc,:);
end;%for nvar=0:n_var-1; 
patch(tmp_x_,tmp_y_,tmp_c_,'EdgeColor','k');
xlim([0,n_var+1]);ylim(c_nlpvt2_lim_);
%set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source/target'); ylabel('magnitude'); title('signed a_nlp_zzzz_','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(A_avg_zzzz__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_avg_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(A_std_zzzz__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('A_std_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(A_snlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_BC_FIGBC',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,3,np);np=np+1; imagesc(BB_avg_zzzz__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_avg_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,2) = subplot(2,3,np);np=np+1; imagesc(BB_std_zzzz__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('BB_std_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(1,3) = subplot(2,3,np);np=np+1; imagesc(BB_snlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,3,np);np=np+1; imagesc(CC_avg_zzzz__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_avg_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,2) = subplot(2,3,np);np=np+1; imagesc(CC_std_zzzz__,c_beach_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('CC_std_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
subplot_(2,3) = subplot(2,3,np);np=np+1; imagesc(CC_snlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed CC_nlp_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(1,1),colormap_beach);
colormap(subplot_(1,2),colormap_beach);
colormap(subplot_(1,3),c_nlpvt2__);
colormap(subplot_(2,1),colormap_beach);
colormap(subplot_(2,2),colormap_beach);
colormap(subplot_(2,3),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

fname_fig = sprintf('%s/dolphin_%s_shuffle_AB_FIGAB',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
c_beach__ = colormap_beach(); n_c_beach = size(c_beach__,1);
c_beach_lim_ = [-1,+1];
c_nlpvt2__ = colormap_nlpvt_twosided(); n_c_nlpvt2 = size(c_nlpvt2__,1);
c_nlpvt2_lim_ = [-27,+27];
np = 1;
%%%%%%%%;
subplot_(1,1) = subplot(2,2,np);np=np+1; imagesc(A_snlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(1,2) = subplot(2,2,np);np=np+1; imagesc(BB_snlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_zzzz__','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,1) = subplot(2,2,np);np=np+1; imagesc(A_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed A_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
subplot_(2,2) = subplot(2,2,np);np=np+1; imagesc(BB_sbnlp_zzzz__,c_nlpvt2_lim_); axis image;
set(gca,'YTick',1:n_var,'YTickLabel',string_dat_name_);
set(gca,'XTick',1:n_var,'XTickLabel',string_dat_name_); xtickangle(90);
xlabel('source'); ylabel('target'); title('signed BB_nlp_zzzz__ (bonferroni)','Interpreter','none');
set(gca,'TickLength',[0,0]); set(gca,'fontsize',fontsize_use);
colorbar();
%%%%%%%%;
sgtitle(sprintf('%s',fname_infix_zzzz),'Interpreter','none');
colormap(subplot_(1,1),c_nlpvt2__);
colormap(subplot_(1,2),c_nlpvt2__);
colormap(subplot_(2,1),c_nlpvt2__);
colormap(subplot_(2,2),c_nlpvt2__);
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% check distribution of shuffle coefficients. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
fname_mat_zzzz_s = sprintf('%s/dolphin_%s_sxxxx.mat',dir_shuffle_mat,fname_infix_zzzz);
if ( exist(fname_mat_zzzz_s,'file'));
tmp_ = load(fname_mat_zzzz_s);
n_found_zzzz = size(tmp_.L_cmb_prm_,1) - 1;
a_zzzz__ = tmp_.a_cmb_prm__(:,2:end);
A_zzzz__ = reshape(tmp_.A_cmb_prm___(:,:,2:end),[n_var^2,n_found_zzzz]);
BB_zzzz__ = reshape(tmp_.BB_cmb_prm___(:,:,2:end),[n_var^2,n_found_zzzz]);
CC_zzzz__ = zeros(n_var,n_found_zzzz);
for nfound=0:n_found_zzzz-1;
CC_zzzz__(:,1+nfound)= diag(tmp_.CC_cmb_prm___(:,:,1+1+nfound));
end;%for nfound=0:n_found_zzzz-1;
disp(sprintf(' %% n_found_zzzz %d',n_found_zzzz'));
a_zzzz_nrm__ = (a_zzzz__ - repmat(mean(a_zzzz__,2),[1,n_found_zzzz]))./repmat(std(a_zzzz__,[],2),[1,n_found_zzzz]);
A_zzzz_nrm__ = (A_zzzz__ - repmat(mean(A_zzzz__,2),[1,n_found_zzzz]))./repmat(std(A_zzzz__,[],2),[1,n_found_zzzz]);
BB_zzzz_nrm__ = (BB_zzzz__ - repmat(mean(BB_zzzz__,2),[1,n_found_zzzz]))./repmat(std(BB_zzzz__,[],2),[1,n_found_zzzz]);
CC_zzzz_nrm__ = (CC_zzzz__ - repmat(mean(CC_zzzz__,2),[1,n_found_zzzz]))./repmat(std(CC_zzzz__,[],2),[1,n_found_zzzz]);
%%%%%%%%;
fname_fig = sprintf('%s/dolphin_%s_shuffle_coefficient_distribution',dir_jpg,fname_infix_zzzz);
if (flag_replot | ~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig)); figure(1);
figure(1);clf;figbig;fontsize_use = 8;
subplot(2,2,1); hist(a_zzzz_nrm__(:),128); title('a_zzzz_nrm__(:)','Interpreter','none');
subplot(2,2,2); hist(A_zzzz_nrm__(:),128); title('AA_zzzz_nrm__(:)','Interpreter','none');
subplot(2,2,3); hist(BB_zzzz_nrm__(:),128); title('BB_zzzz_nrm__(:)','Interpreter','none');
subplot(2,2,4); hist(CC_zzzz_nrm__(:),128); title('CC_zzzz_nrm__(:)','Interpreter','none');
%%%%%%%%;
disp(sprintf(' %% writing %s',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
if ( exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s found, not creating',fname_fig));
end;%if ( exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
end;%if ( exist(fname_mat_zzzz_s,'file'));
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%if flag_exist;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

if (verbose); disp(sprintf(' %% [finished dolphin_d00_cmb_collect_and_plot_1]')); end;
