function [mu_A_,sg_A_] = gaussian_iso__0(A_);
% calculates the parameters for the isotropic gaussian associated with A_. ;
% The mean mu_A_ is simply the mean of the rows of A_. ;
% The sg_A_ is a vector where sg_A_(j) stores the standard-deviation associated with A_(:,1:j). ;
[n_A,d] = size(A_);
mu_A_ = mean(A_,1);
B_ = A_ - repmat(mu_A_,n_A,1);
B_ = abs(B_).^2;
B_ = cumsum(B_,2)./repmat(1:d,n_A,1);
sg_A_ = max(1e-12,sqrt(sum(B_,1)/n_A));
