function [gamma_z_out,log_likelihood_ratio,label_,gamma_z_,llr_] = gsplit_gamma_z(d_,n_gamma_z);
% Uses gsplit for each projection of 2-dimensional data d_. ;
if (nargin<1);
M = 1781; N = 2; d_ = zeros(M,N);
M1 = floor(M/3); M2 = M-M1;
%mu_A_ = [+0.75,0]; mu_B_ = [-0.75,0]; eps_A = 0.25; eps_B = 0.25;
mu_A_ = [+0.35,0]; mu_B_ = [-0.35,0]; eps_A = 0.5; eps_B = 0.5;
tmp_A_ = randn(M1,N); [tmp_U_,tmp_S_,tmp_V_] = svds(tmp_A_,2); tmp_S_(2,2) = tmp_S_(1,1)*eps_A; tmp_A_ = tmp_U_*tmp_S_*transpose(tmp_V_);
d_(1:M1,1:N) = tmp_A_ + repmat(mu_A_,M1,1);
tmp_B_ = randn(M2,N); [tmp_U_,tmp_S_,tmp_V_] = svds(tmp_B_,2); tmp_S_(2,2) = tmp_S_(1,1)*eps_B; tmp_B_ = tmp_U_*tmp_S_*transpose(tmp_V_);
d_(M1+(1:M2),1:N) = tmp_B_ + repmat(mu_B_,M2,1);
label_true_ = ones(M,1); label_true_(M1+(1:M2)) = 2;
n_gamma_z = 64;
[gamma_z_out,log_likelihood_ratio,label_,gamma_z_,llr_] = gsplit_gamma_z(d_,n_gamma_z);
subplot(1,3,1); scatter(d_(:,1),d_(:,2),25,label_true_); xlabel('pc1'); ylabel('pc2'); title('true label');
subplot(1,3,2); scatter(d_(:,1),d_(:,2),25,label_); xlabel('pc1'); ylabel('pc2'); title('gsplit label');
subplot(1,3,3); 
hold on;
plot(gamma_z_,llr_,'ko-'); 
plot(gamma_z_out,log_likelihood_ratio,'rx');
hold off;
xlim([0,pi]); xlabel('gamma_z'); ylabel('llr'); title('llr vs gamma_z');
colormap('lines');
disp('returning'); return;
end;%if (nargin<1);

verbose = 0;
if (verbose>0); disp(sprintf(' %% [entering gsplit_gamma_z]')); end;

if nargin<2; n_gamma_z = 16; end;
gamma_z_ = linspace(0,pi,n_gamma_z+1); gamma_z_ = gamma_z_(1:end-1);
llr_ = zeros(n_gamma_z,1);
for ngamma_z=1:n_gamma_z;
gamma_z = gamma_z_(ngamma_z);
if (verbose>0); disp(sprintf(' %% ngamma_z %d/%d',ngamma_z,n_gamma_z)); end;
llr_(ngamma_z) = -gsplit_nllr(verbose,d_,gamma_z);
end;%for ngamma_z=1:n_gamma_z;
if (verbose>0); plot(gamma_z_,llr_,'k.-'); end;
[~,tmp_ij] = max(llr_);
gamma_z = gamma_z_(tmp_ij);
if (verbose<=0); gamma_z = fminsearch(@(gamma_z) gsplit_nllr(verbose,d_,gamma_z),gamma_z); end;
if (verbose>=1); gamma_z = fminsearch(@(gamma_z) gsplit_nllr(verbose,d_,gamma_z),gamma_z,optimset('Display','iter')); end;
gamma_z_out = gamma_z;
tmp_nu_ = [cos(gamma_z);sin(gamma_z)];
tmp_d_ = d_(:,1)*tmp_nu_(1) + d_(:,2)*tmp_nu_(2);
[tmp_s,tmp_d_lo_,tmp_d_hi_,tmp_llr,tmp_s_,tmp_llr_] = gsplit(tmp_d_);
log_likelihood_ratio = tmp_llr;
label_ = zeros(size(tmp_d_));
label_(find(tmp_d_< tmp_s))='A';
label_(find(tmp_d_>=tmp_s))='B';

if (verbose>0); disp(sprintf(' %% [finished gsplit_gamma_z]')); end;

function output = gsplit_nllr(verbose,d_,gamma_z);
if (verbose>0); disp(sprintf(' %% [entering gsplit_nllr] gamma_z %0.2f',gamma_z)); end;
tmp_nu_ = [cos(gamma_z);sin(gamma_z)];
tmp_d_ = d_(:,1)*tmp_nu_(1) + d_(:,2)*tmp_nu_(2);
[~,~,~,output,~,~] = gsplit(tmp_d_);
output = -output;
if (verbose>0); disp(sprintf(' %% [finished gsplit_nllr] gamma_z %0.2f',gamma_z)); end;
