function [s,d_lo_,d_hi_,llr,s_,llr_] = gsplit_slow(d_);
% splits 1-dimensional data d_, ;
% maximizing the log-likelihood-ratio between: ;
% P(data | 2 gaussians) / P(data | 1 gaussian). ;
if (nargin<1);
tmp_ = [randn(81,1);randn(291,1)+4.2]; 
[s,d_lo_,d_hi_,llr,s_,llr_] = gsplit_slow(tmp_); 
subplot(1,2,1);
hold on; stairs(sort(tmp_),1:length(tmp_)); plot(zeros(length(tmp_),1)+s,1:length(tmp_),'k-');
xlim([min(tmp_),max(tmp_)]); ylim([1,length(tmp_)]);
xlabel('random variable'); ylabel('rank');
title('cumulative-distribution-function');
subplot(1,2,2);
plot(s_,llr_,'k.');
xlim([min(tmp_),max(tmp_)]); 
xlabel('random variable'); ylabel('log-likelihood-ratio');
title('log-likelihood-ratio');
figbig;
disp('returning');return;
end;%if (nargin<1);

d_ = sort(d_(:)); n_d = length(d_);
mu_1g = mean(d_); sg_1g = std(d_,1);
ll_1g = log(1/(sqrt(2*pi)*sg_1g)) - sum((d_-mu_1g).^2/(2*sg_1g^2));
[u_,d_to_u_,u_to_d_] = unique(d_); n_u = length(u_);
s=u_(1); d_lo_ = d_; d_hi_ = []; llr=1; llr_=[]; s_=[];
if (n_u>3);
llr_ = zeros(n_u-3,1); s = zeros(n_u-3,1);
for nu=2:n_u-2;
s_(-1+nu) = (u_(nu+0) + u_(nu+1))/2.0;
d_lo_ = d_(1:d_to_u_(nu+0));
d_md_ = d_(d_to_u_(nu+0)+1:d_to_u_(nu+1)-1);
d_hi_ = d_(d_to_u_(nu+1):end);
d_lo_ = [d_lo_;d_md_(find(d_md_<=u_(nu+0)))];
d_hi_ = [d_md_(find(d_md_>=u_(nu+1)));d_hi_];
mu_lo = mean(d_lo_); sg_lo = std(d_lo_,1);
mu_hi = mean(d_hi_); sg_hi = std(d_hi_,1);
l_lo = length(d_lo_)/n_d;
l_hi = length(d_hi_)/n_d;
g_lo_ = l_lo*(1/(sqrt(2*pi)*sg_lo)*exp(-(d_-mu_lo).^2/(2*sg_lo^2)));
g_hi_ = l_hi*(1/(sqrt(2*pi)*sg_hi)*exp(-(d_-mu_hi).^2/(2*sg_hi^2)));
llr_(-1+nu) = sum(log(g_lo_ + g_hi_)) - ll_1g;
end;%for nu=2:n_u-2;
[llr,nu] = max(llr_);
s = s_(nu); nu = 1+nu;
d_lo_ = d_(1:d_to_u_(nu+0));
d_md_ = d_(d_to_u_(nu+0)+1:d_to_u_(nu+1)-1);
d_hi_ = d_(d_to_u_(nu+1):end);
d_lo_ = [d_lo_;d_md_(find(d_md_<=u_(nu+0)))];
d_hi_ = [d_md_(find(d_md_>=u_(nu+1)));d_hi_];
end;%if (n_u>3);
