function [g_opt_,nlp_opt_,nlp_emp_,p_opt_,p_emp_] = gumbel_fit(A_,a_);
% Fits gumbel distribution to the data in A_. ;
% If a_ is provided, estimates one-sided p-value of a_ relative to A_. ;
if (nargin<1);
A_ = 0.5 + (0:7);
a_ = [6,7];
[g_opt_,nlp_opt_,nlp_emp_,p_opt_,p_emp_] = gumbel_fit(A_,a_);
disp(sprintf(' %% g_opt_ %0.16f %0.16f',g_opt_));
disp(sprintf(' %% nlp_opt_ %0.16f %0.16f',nlp_opt_));
disp(sprintf(' %% nlp_emp_ %0.16f %0.16f',nlp_emp_));
disp(sprintf(' %% p_opt_ %0.16f %0.16f',p_opt_));
disp(sprintf(' %% p_emp_ %0.16f %0.16f',p_emp_));
disp('returning');return;
end;%if (nargin<1);

verbose=0;
%%%%%%%%;
g_ori_ = [ 0 ; 1 ]; %<-- mu, sqrt(beta) for gumbel. ;
A_ = A_(:);
n_u = numel(A_);
B_ = (A_ - mean(A_))/std(A_,1); %<-- center and normalize A_. ;
tmp_gumbel_nll = @(g_) sum(gumbel_nll(B_(:),g_));
g_opt_ = g_ori_;
g_opt_ = fminsearch(tmp_gumbel_nll,g_ori_,optimset('MaxIter',1e4,'MaxFunEvals',1e4));
if (verbose);
figure(1);clf;
n_h = 32;
h_x_lim_ = mean(B_) + std(B_,1)*3.5*[-1,+1];
h_x_ = linspace(min(h_x_lim_),max(h_x_lim_),n_h);
h_B_ = hist(B_,h_x_);
h_B_ = h_B_/sum(h_B_)/mean(diff(h_x_));
x_ = linspace(min(h_x_lim_),max(h_x_lim_),1024);
rho_ = gumbel_pdf(x_,g_opt_);
hold on;
stairs(h_x_,h_B_,'k-','LineWidth',2);
plot(x_,rho_,'r-','LineWidth',2);
hold off;
xlabel('x');
ylabel('dist');
title('gumbel_fit','Interpreter','none');
end;%if (verbose);
%%%%%%%%;
nlp_opt_ = 0; nlp_emp_ = 0;
if (nargin>1);
n_a = numel(a_);
nlp_opt_ = zeros(n_a,1);
nlp_emp_ = zeros(n_a,1);
p_opt_ = zeros(n_a,1);
p_emp_ = zeros(n_a,1);
for na=0:n_a-1;
a = a_(1+na);
p_emp = ( numel(find(A_>a)) + 0.5*numel(find(A_==a)) )/n_u;
nlp_emp = -log(p_emp);
b = (a - mean(A_))/std(A_,1);
p_opt = 1 - gumbel_cdf(b,g_opt_);
nlp_opt = -log(p_opt);
p_emp_(1+na) = p_emp;
nlp_emp_(1+na) = nlp_emp;
p_opt_(1+na) = p_opt;
nlp_opt_(1+na) = nlp_opt;
end;%for na=0:n_a-1;
end;%if (nargin>1);
