function output_label__ = label_tree_output_label_from_leaf_0(label_tree,output_label__);
if isempty(label_tree.parent); output_label__ = cell(numel(label_tree.item_index_),1); end;
if ( isempty(label_tree.childA) & isempty(label_tree.childB) );
n_item = numel(label_tree.item_index_);
for nitem=0:n_item-1;
item_index = label_tree.item_index_(1+nitem);
output_label__{1+item_index} = label_tree.label_string;
end;%for nitem=0:n_item-1;
end;%if ( isempty(label_tree.childA) & isempty(label_tree.childB) );
if ( ~isempty(label_tree.childA) & ~isempty(label_tree.childB) );
output_label__ = label_tree_output_label_from_leaf_0(label_tree.childA,output_label__);
output_label__ = label_tree_output_label_from_leaf_0(label_tree.childB,output_label__);
end;%if ( ~isempty(label_tree.childA) & ~isempty(label_tree.childB) );
