lisa_cra = textread('/data/rangan/dir_bcc/dir_PGC_20180304/lisa_cra_0.txt'); 
fname_ = {...
'v1/bip_bonn_eur_sr-qc.bim',...
'v1/bip_dub1_eur_sr-qc.bim',...
'v1/bip_edi1_eur_sr-qc.bim',...
'v1/bip_fat2_eur_sr-qc.bim',...
'v1/bip_fran_eur_sr-qc.bim',...
'v1/bip_gsk1_eur_sr-qc.bim',...
'v1/bip_icuk_eur_sr-qc.bim',...
'v1/bip_may1_eur_sr-qc.bim',...
'v1/bip_mich_eur_sr-qc.bim',...
'v1/bip_st2c_eur_sr-qc.bim',...
'v1/bip_stp1_eur_sr-qc.bim',...
'v1/bip_swa2_eur_sr-qc.bim',...
'v1/bip_swei_eur_sr-qc.bim',...
'v1/bip_top7_eur_sr-qc.bim',...
'v1/bip_top8_eur_sr-qc2.bim',...
'v1/bip_ucl2_eur_sr-qc2.bim',...
'v1/bip_uclo_eur_sr-qc.bim',...
'v1/bip_ume4_eur_sr-qc.bim',...
'v1/bip_usc2_eur_sr-qc.bim',...
'v1/bip_wtcc_eur_sr-qc.bim',...
'v1/ms.bip_butr_eur-qc.bim',...
'v1/ms.bip_uktr_eur-qc.bim',...
'v1_boma/bip_bmau_eur_sr-qc.bim',...
'v1_boma/bip_bmg2_eur_sr-qc.bim',...
'v1_boma/bip_bmg3_eur_sr-qc.bim',...
'v1_boma/bip_bmpo_eur_sr-qc.bim',...
'v1_boma/bip_bmsp_eur_sr-qc2.bim',...
'v1_boma/bip_hal2_eur_sr-qc.bim',...
'v1_boma/bip_rom3_eur_sr-qc.bim',...
'v1_gain/bip_gain_eur_sr-qc.bim'};
fname_label_ = {...
'bonn',...
'dub1',...
'edi1',...
'fat2',...
'fran',...
'gsk1',...
'icuk',...
'may1',...
'mich',...
'st2c',...
'stp1',...
'swa2',...
'swei',...
'top7',...
'top8',...
'ucl2',...
'uclo',...
'ume4',...
'usc2',...
'wtcc',...
'butr',...
'uktr',...
'bmau',...
'bmg2',...
'bmg3',...
'bmpo',...
'bmsp',...
'hal2',...
'rom3',...
'gain'};

lisa_cra = reshape(lisa_cra,30,30);
[u,s,v] = svds(lisa_cra,1); [tmp,ij] = sort(abs(u),'descend'); 
ij = [ij(1:17);ij(23:24);ij(18:22);ij(25:30)];
ij = [ij(1:17);ij([20,19,18]);ij(21:30)];
ij = [ij(1:19);ij(25);ij(20:24);ij(26:30)];
ij = [ij(1:12);ij(18);ij(14:17);ij(13);ij(19:30)];
ij = [ij(1:14);ij([18,15,16,17]);ij(19:30)];
imagesc(lisa_cra(ij,ij));colorbar;
set(gca,'XTick',1:30,'XTickLabel',fname_label_(ij),'XTickLabelRotation',90);
set(gca,'YTick',1:30,'YTickLabel',fname_label_(ij),'YTickLabelRotation', 0);
set(gcf,'Position',1+[0,0,1024,1024]);
print('-djpeg','/data/rangan/dir_bcc/dir_PGC_20180304/lisa_cra_0.jpg');
for ni=1:length(ij);disp(fname_{ij(ni)});end;%for ni=1:length(ij);
