function [out_perm_xxx_] = lisa_dosage_pca_helper_4(dud_,eu1_,dud_by_eu1_xref_,bu1_by_eu1_xref_,out_xxx_);
out_perm_xxx_ = zeros(length(dud_),size(out_xxx_,2));
for neu1=1:length(eu1_);
%if (mod(neu1,1000)==0); disp(sprintf(' %% neu1 %d/%d',neu1,length(eu1_))); end;
tmp_dud_ = find(sum(dud_by_eu1_xref_(:,neu1),2));
if (length(tmp_dud_)>1); disp(sprintf(' %% Warning! tmp_dud_ length %d in lisa_dosage_pca_ver8',length(tmp_dud_))); end;
ndud = tmp_dud_(1);
tmp_bu1_ = find(sum(bu1_by_eu1_xref_(:,neu1),2));
if (length(tmp_bu1_)>1); disp(sprintf(' %% Warning! tmp_bu1_ length %d in lisa_dosage_pca_ver8',length(tmp_bu1_))); end;
nbu1 = tmp_bu1_(1);
out_perm_xxx_(ndud,:) = out_xxx_(nbu1,:);
end;%for neu1=1:length(eu1_);
