function [study_dosage_trunk_,study_dosage_name_,study_fam_name_,n_study] = lisa_define_study_dosage_ver1(cl_num);

if cl_num==1;
n_study = 9; ns = 1;
study_fam_name_{ns} = '/home/grouther/v1/bip_may1_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_may1_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
%study_fam_name_{ns} = '/home/grouther/v1/ms.bip_butr_eur-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_butr_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_top8_eur_sr-qc2.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_top8_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
%study_fam_name_{ns} = '/home/grouther/v1/ms.bip_uktr_eur-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_uktr_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_bmg2_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_bmg2_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_ume4_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_ume4_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_ucl2_eur_sr-qc2.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_ucl2_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_usc2_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_usc2_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_rom3_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_rom3_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_swei_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_swei_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_hal2_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_hal2_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
ns = ns-1; assert(ns==n_study);
end;% cl1;
if cl_num==2;
n_study = 7; ns = 1;
study_fam_name_{ns} = '/home/grouther/v1/bip_mich_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_mich_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_gsk1_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_gsk1_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_bonn_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_bonn_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_bmau_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_bmau_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_bmg3_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_bmg3_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_fran_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_fran_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_bmpo_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_bmpo_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
ns = ns-1; assert(ns==n_study);
end;%cl2;
if cl_num==3;
n_study = 10; ns = 1;
study_fam_name_{ns} = '/home/grouther/v1/bip_fat2_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_fat2_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1_gain/bip_gain_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_gain_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_dub1_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_dub1_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_top7_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_top7_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_swa2_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_swa2_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_wtcc_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_wtcc_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_edi1_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_edi1_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_uclo_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_uclo_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_stp1_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_stp1_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
study_fam_name_{ns} = '/home/grouther/v1/bip_st2c_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_st2c_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
ns = ns-1; assert(ns==n_study);
end;%cl3;
if cl_num==4;
n_study = 1; ns = 1;
study_fam_name_{ns} = '/home/grouther/v1/bip_icuk_eur_sr-qc.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_icuk_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
ns = ns-1; assert(ns==n_study);
end;%cl4;
if cl_num==5;
n_study = 1; ns = 1;
study_fam_name_{ns} = '/home/grouther/v1_boma/bip_bmsp_eur_sr-qc2.fam'; study_dosage_trunk_{ns} = '/home/grouther/dir_study_genolist_in_dosage'; study_dosage_name_{ns} = 'bip_bmsp_eur_sr-qc_trans_to_dos.out.dosage'; ns = ns+1;
ns = ns-1; assert(ns==n_study);
end;%cl5;
if cl_num==6; %<-- testing ;
n_study = 1; ns = 1;
study_dosage_trunk_{ns} = '/data/rangan/dir_bcc/dir_PGC_20180304/dir_misc'; 
study_dosage_name_{ns} = 'top8_eur_sr-qc.hg19.ch.fl.out.dosage_PGC_cl4_maf01_dex_p25_D_m2r2_g004_out_cdrop_ni275.out.dosage.cropped'; 
study_fam_name_{ns} = '/data/rangan/dir_bcc/dir_PGC_20180304/v1/bip_top8_eur_sr-qc2.fam';
ns = ns+1;
ns = ns-1; assert(ns==n_study);
end;%cl6;
