function lisa_bed_to_b16_ver4(cl_num,flag_stop,flag_crop,flag_bim,flag_fam);
% extract/convert some information from bed files to b16 files. ;
% scp -p rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/dir_lakcluster_c/lakcluster_ver18 /home/arangan/dir_lakcluster_c/ ;
% scp -rp rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/lakcluster_ver18_20180401.tar.gz /home/arangan/ ;
% scp -p rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/dir_PGC_20180304/mds.mat /home/arangan/dir_PGC_20180304/ ;
% scp -p rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/dir_PGC_20180304/dir_m/?*.m /home/arangan/dir_PGC_20180304/dir_m/ ;
% scp -p rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/dir_PGC_20180304/dir_m/lisa_define_study_ver0.m /home/arangan/dir_PGC_20180304/dir_m/lisa_define_study_ver0.m ;
% scp -p rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/dir_PGC_20180304/dir_m/lisa_bed_to_b16_ver4.m /home/arangan/dir_PGC_20180304/dir_m/lisa_bed_to_b16_ver4.m ;
%
%{
  flag_stop = 1;
  flag_crop = 0;
  flag_bim = 0;
  flag_fam = 0;
  for cl_num=1:4;
  lisa_bed_to_b16_ver4(cl_num,flag_stop,flag_crop,flag_bim,flag_fam);
  end;% for cl_num=1:4;
  %}
if nargin<1; cl_num = input('cluster number? [i.e., 1,2,...]'); end;
if nargin<2; flag_stop = input(' set flag_stop? [3=after mds, 2=after bim&fam, 1=after shuffled An&At, 0=after original An&At]'); end;
if nargin<3; flag_crop = input(' set flag_crop so that only a subset of ~1000 snps are considered? [1=yes, 0=no]'); end;
if nargin<4; flag_bim = input(' generate bim file? [1=yes, 0=no]'); end;
if nargin<5; flag_fam = input(' generate fam file? [1=yes, 0=no]'); end;
% cl_num = 3; flag_stop = 0; flag_crop = 0; flag_bim=0; flag_fam=0; 

path(path,'~/dir_lakcluster_c/dir_m');
male_tag=1; fema_tag=2; case_tag=2; ctrl_tag=1; nkhr=22; 
bitj=16; bit8=8; bit4=4; snp_and_tag=3; snp_xor_tag=2; snp_nor_tag=0; snp_mss_tag=1; snp_not_tag=5;

ent_cutoff = 0.03; frq_cutoff = 0.01; mss_cutoff = 0.02;

[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num);

if (flag_crop==0);
tmp = sprintf('PGC_cl%d_maf%.2d',cl_num,floor(100*frq_cutoff));
end;%if (flag_crop==0);
if (flag_crop==1);
tmp = sprintf('PGC_cl%d_maf%.2d_crop',cl_num,floor(100*frq_cutoff));
end;%if (flag_crop==0);
snp_pre = sprintf('%s_',tmp);
dir_pre = sprintf('%s','/home/arangan/dir_PGC_20180304');
dir_out = sprintf('%s/dir_%s',dir_pre,tmp); if ~exist(dir_out,'dir'); mkdir(dir_out); end;
disp(sprintf('%% snp_pre %s\n%% dir_out %s\n%% tmp_char %s/%s\n',snp_pre,dir_out,dir_out,snp_pre));

if (flag_crop);
n_snp_crop_ = 1000 + [1:n_study];
end;%if (flag_crop);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Loading mds.mat ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load(sprintf('%s/mds.mat',dir_pre));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Loading data ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fn_fam_ = cell(n_study,1); fp_fam_ = cell(n_study,1); 
fn_bim_ = cell(n_study,1); fp_bim_ = cell(n_study,1); 
fn_bed_ = cell(n_study,1); fp_bed_ = cell(n_study,1); 
fam_ = cell(n_study,1); fam_name_ = cell(n_study,1);
bim_ = cell(n_study,1); khrdist_ = cell(n_study,1);
n_patient_ = zeros(n_study,1); n_patient_rup_ = zeros(n_study,1); n_patient_keep_ = zeros(n_study,1);
rij_male_ = cell(n_study,1);
rij_fema_ = cell(n_study,1);
rij_case_ = cell(n_study,1);
rij_ctrl_ = cell(n_study,1);
rij_keep_ = cell(n_study,1);
n_and_ = cell(n_study,1); n_xor_ = cell(n_study,1); n_nor_ = cell(n_study,1); n_mss_ = cell(n_study,1);
m_and_ = cell(n_study,1);;m_xor_ = cell(n_study,1);;m_nor_ = cell(n_study,1);;m_mss_ = cell(n_study,1);;
for ns=1:n_study;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ns %d: Reading fam file %s/%s.fam (patients) ;',ns,study_trunk_{ns},study_name_{ns}));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fn_fam_{ns} = sprintf('~/%s/%s.fam',study_trunk_{ns},study_name_{ns});
%[status,n_patient_tmp] = system(sprintf('wc -l %s | cut -f 1 -d '' ''',fn_fam_{ns})); n_patient_(ns) = str2num(n_patient_tmp); 
%tmp_rem = mod(n_patient_(ns),bit4); tmp_quo = (n_patient_(ns)-tmp_rem)/bit4;
%n_patient_rup_(ns) = tmp_quo + (tmp_rem>0);
fp_fam_{ns} = fopen(fn_fam_{ns}); fam_{ns} = textscan(fp_fam_{ns},'%s %s %s %s %d %d'); fclose(fp_fam_{ns});
n_patient_(ns) = length(fam_{ns}{1}); 
tmp_rem = mod(n_patient_(ns),bit4); tmp_quo = (n_patient_(ns)-tmp_rem)/bit4;
n_patient_rup_(ns) = tmp_quo + (tmp_rem>0);
rij_male_{ns} = find(fam_{ns}{5}==male_tag);rij_fema_{ns} = find(fam_{ns}{5}==fema_tag);
rij_case_{ns} = find(fam_{ns}{6}==case_tag);rij_ctrl_{ns} = find(fam_{ns}{6}==ctrl_tag);
for np=1:n_patient_(ns);
fam_name_{ns}{np} = sprintf('%s%s%s',fam_{ns}{1}{np},'&',fam_{ns}{2}{np});
end;%for np=1:n_patient_(ns);
[~,rij_keep_{ns}] = setdiff(fam_name_{ns},famex_name_former_,'stable');
n_patient_keep_(ns) = length(rij_keep_{ns});
disp(sprintf(' %% found total: n_patient %d (%d males, %d femas, %d cases, %d ctrls) --> %d',n_patient_(ns),length(rij_male_{ns}),length(rij_fema_{ns}),length(rij_case_{ns}),length(rij_ctrl_{ns}),n_patient_rup_(ns)));
disp(sprintf(' %% will keep:   n_patient %d (%d males, %d femas, %d cases, %d ctrls) --> %d',length(rij_keep_{ns}),length(intersect(rij_keep_{ns},rij_male_{ns})),length(intersect(rij_keep_{ns},rij_fema_{ns})),length(intersect(rij_keep_{ns},rij_case_{ns})),length(intersect(rij_keep_{ns},rij_ctrl_{ns})),n_patient_rup_(ns)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ns %d: Reading bim file %s/%s.bim (snp names) ;',ns,study_trunk_{ns},study_name_{ns}));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fn_bim_{ns} = sprintf('~/%s/%s.bim',study_trunk_{ns},study_name_{ns});
%[status,n_snp_tmp] = system(sprintf('wc -l %s | cut -f 1 -d '' ''',fn_bim_{ns})); n_snp_(ns) = str2num(n_snp_tmp);
fp_bim{ns} = fopen(fn_bim_{ns}); bim_{ns} = textscan(fp_bim{ns},'%d %s %d %d %s %s'); fclose(fp_bim{ns});
n_snp_(ns) = length(bim_{ns}{1});
if (flag_crop);
for nl=1:6; bim_{ns}{nl} = bim_{ns}{nl}(1:n_snp_crop_(ns),:); end;
n_snp_(ns) = n_snp_crop_(ns); 
end%if (flag_crop);
tmp=zeros(nkhr,1); for nk=1:nkhr; tmp(nk) = length(find(bim_{ns}{1}==nk)); end;%for nk=1:nkhr;
khrdist_{ns} = tmp;
disp(sprintf(' %% n_snp_(%d) --> chromosome distribution: [%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d]',n_snp_(ns),khrdist_{ns}));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ns %d: Reading bed file %s/%s.bed (binarized snp data) ;',ns,study_trunk_{ns},study_name_{ns}));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fn_bed_{ns} = sprintf('~/%s/%s.bed',study_trunk_{ns},study_name_{ns});
fp_bed_{ns} = fopen(fn_bed_{ns}); 
key1 = fread(fp_bed_{ns},1,'uint8'); key2 = fread(fp_bed_{ns},1,'uint8'); key3 = fread(fp_bed_{ns},1,'uint8'); assert(key1==108); assert(key2==27); assert(key3==1);
ver_flag=0;
if ver_flag==0;
disp(sprintf(' %% version 0: simultaneous read (assuming more than 8G of ram)...'));tic;
n_and_{ns} = zeros(1,n_snp_(ns));n_xor_{ns} = zeros(1,n_snp_(ns));n_nor_{ns} = zeros(1,n_snp_(ns));n_mss_{ns} = zeros(1,n_snp_(ns));
m_and_{ns} = zeros(1,4*n_patient_rup_(ns));m_xor_{ns} = zeros(1,4*n_patient_rup_(ns));m_nor_{ns} = zeros(1,4*n_patient_rup_(ns));m_mss_{ns} = zeros(1,4*n_patient_rup_(ns));
uchar_11111111 = transpose(fread(fp_bed_{ns},[n_patient_rup_(ns),n_snp_(ns)],'uint8=>uint8'));
t_tmp = toc; disp(sprintf(' %% read input: time %0.2f seconds',t_tmp)); 
disp(sprintf(' %% reading 4 allele pairs per byte... ')); tic;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% these commands use mod, which is very slow. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%uchar_00000011 = mod(uchar_11111111,  4);
%uchar_00001111 = mod(uchar_11111111, 16); uchar_00001100 = idivide(uchar_00001111 - uchar_00000011, 4) ; 
%uchar_00111111 = mod(uchar_11111111, 64); uchar_00110000 = idivide(uchar_00111111 - uchar_00001111,16) ; clear uchar_00001111;
%                                          uchar_11000000 = idivide(uchar_11111111 - uchar_00111111,64) ; clear uchar_00111111;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% these commands use bitshifts, which are much faster. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
uchar_00000011 = bitshift(bitshift(uchar_11111111,+6),-6);
uchar_00001100 = bitshift(bitshift(bitshift(uchar_11111111,-2),+6),-6);
uchar_00110000 = bitshift(bitshift(bitshift(uchar_11111111,-4),+6),-6);
uchar_11000000 = bitshift(uchar_11111111,-6);
clear uchar_11111111;
t_tmp = toc; disp(sprintf(' %% bitshift: time %0.2f seconds',t_tmp)); 
disp(sprintf(' %% reading 4 tags per allele pair... ')); tic;
stride1 = 1:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride1,rij_keep_{ns},'stable'); uchar_00000011(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride2 = 2:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride2,rij_keep_{ns},'stable'); uchar_00001100(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride3 = 3:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride3,rij_keep_{ns},'stable'); uchar_00110000(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride4 = 4:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride4,rij_keep_{ns},'stable'); uchar_11000000(:,tmp_ij)=snp_not_tag; clear tmp_ij;
clear uchar_tmp;
uchar_tmp = uchar_00000011==snp_and_tag; sum1_and_00000011 = sum(uchar_tmp,1); sum2_and_00000011 = sum(uchar_tmp,2);
uchar_tmp = uchar_00000011==snp_xor_tag; sum1_xor_00000011 = sum(uchar_tmp,1); sum2_xor_00000011 = sum(uchar_tmp,2);
uchar_tmp = uchar_00000011==snp_nor_tag; sum1_nor_00000011 = sum(uchar_tmp,1); sum2_nor_00000011 = sum(uchar_tmp,2);
uchar_tmp = uchar_00000011==snp_mss_tag; sum1_mss_00000011 = sum(uchar_tmp,1); sum2_mss_00000011 = sum(uchar_tmp,2);
clear uchar_tmp;
uchar_tmp = uchar_00001100==snp_and_tag; sum1_and_00001100 = sum(uchar_tmp,1); sum2_and_00001100 = sum(uchar_tmp,2);
uchar_tmp = uchar_00001100==snp_xor_tag; sum1_xor_00001100 = sum(uchar_tmp,1); sum2_xor_00001100 = sum(uchar_tmp,2);
uchar_tmp = uchar_00001100==snp_nor_tag; sum1_nor_00001100 = sum(uchar_tmp,1); sum2_nor_00001100 = sum(uchar_tmp,2);
uchar_tmp = uchar_00001100==snp_mss_tag; sum1_mss_00001100 = sum(uchar_tmp,1); sum2_mss_00001100 = sum(uchar_tmp,2);
clear uchar_tmp;
uchar_tmp = uchar_00110000==snp_and_tag; sum1_and_00110000 = sum(uchar_tmp,1); sum2_and_00110000 = sum(uchar_tmp,2);
uchar_tmp = uchar_00110000==snp_xor_tag; sum1_xor_00110000 = sum(uchar_tmp,1); sum2_xor_00110000 = sum(uchar_tmp,2);
uchar_tmp = uchar_00110000==snp_nor_tag; sum1_nor_00110000 = sum(uchar_tmp,1); sum2_nor_00110000 = sum(uchar_tmp,2);
uchar_tmp = uchar_00110000==snp_mss_tag; sum1_mss_00110000 = sum(uchar_tmp,1); sum2_mss_00110000 = sum(uchar_tmp,2);
clear uchar_tmp;
uchar_tmp = uchar_11000000==snp_and_tag; sum1_and_11000000 = sum(uchar_tmp,1); sum2_and_11000000 = sum(uchar_tmp,2);
uchar_tmp = uchar_11000000==snp_xor_tag; sum1_xor_11000000 = sum(uchar_tmp,1); sum2_xor_11000000 = sum(uchar_tmp,2);
uchar_tmp = uchar_11000000==snp_nor_tag; sum1_nor_11000000 = sum(uchar_tmp,1); sum2_nor_11000000 = sum(uchar_tmp,2);
uchar_tmp = uchar_11000000==snp_mss_tag; sum1_mss_11000000 = sum(uchar_tmp,1); sum2_mss_11000000 = sum(uchar_tmp,2);
clear uchar_tmp;
clear uchar_00000011;clear uchar_00001100;clear uchar_00110000;clear uchar_11000000;
t_tmp = toc; disp(sprintf(' %% sums: time %0.2f seconds',t_tmp)); 
disp(sprintf(' %% totalling sum2...')); tic;
n_and_{ns} = sum2_and_00000011 + sum2_and_00001100 + sum2_and_00110000 + sum2_and_11000000;
n_xor_{ns} = sum2_xor_00000011 + sum2_xor_00001100 + sum2_xor_00110000 + sum2_xor_11000000;
n_nor_{ns} = sum2_nor_00000011 + sum2_nor_00001100 + sum2_nor_00110000 + sum2_nor_11000000;
n_mss_{ns} = sum2_mss_00000011 + sum2_mss_00001100 + sum2_mss_00110000 + sum2_mss_11000000;
t_tmp = toc; disp(sprintf(' %% n_xxx: time %0.2f seconds',t_tmp)); 
disp(sprintf(' %% totalling sum1...')); tic;
m_and_{ns}(stride1) = m_and_{ns}(stride1) + sum1_and_00000011;
m_and_{ns}(stride2) = m_and_{ns}(stride2) + sum1_and_00001100;
m_and_{ns}(stride3) = m_and_{ns}(stride3) + sum1_and_00110000;
m_and_{ns}(stride4) = m_and_{ns}(stride4) + sum1_and_11000000;
m_xor_{ns}(stride1) = m_xor_{ns}(stride1) + sum1_xor_00000011;
m_xor_{ns}(stride2) = m_xor_{ns}(stride2) + sum1_xor_00001100;
m_xor_{ns}(stride3) = m_xor_{ns}(stride3) + sum1_xor_00110000;
m_xor_{ns}(stride4) = m_xor_{ns}(stride4) + sum1_xor_11000000;
m_nor_{ns}(stride1) = m_nor_{ns}(stride1) + sum1_nor_00000011;
m_nor_{ns}(stride2) = m_nor_{ns}(stride2) + sum1_nor_00001100;
m_nor_{ns}(stride3) = m_nor_{ns}(stride3) + sum1_nor_00110000;
m_nor_{ns}(stride4) = m_nor_{ns}(stride4) + sum1_nor_11000000;
m_mss_{ns}(stride1) = m_mss_{ns}(stride1) + sum1_mss_00000011;
m_mss_{ns}(stride2) = m_mss_{ns}(stride2) + sum1_mss_00001100;
m_mss_{ns}(stride3) = m_mss_{ns}(stride3) + sum1_mss_00110000;
m_mss_{ns}(stride4) = m_mss_{ns}(stride4) + sum1_mss_11000000;
t_tmp = toc; disp(sprintf(' %% m_xxx: time %0.2f seconds',t_tmp)); tic;
clear sum1_and_00000011;clear sum1_and_00001100;clear sum1_and_00110000;clear sum1_and_11000000;
clear sum1_xor_00000011;clear sum1_xor_00001100;clear sum1_xor_00110000;clear sum1_xor_11000000;
clear sum1_nor_00000011;clear sum1_nor_00001100;clear sum1_nor_00110000;clear sum1_nor_11000000;
clear sum1_mss_00000011;clear sum1_mss_00001100;clear sum1_mss_00110000;clear sum1_mss_11000000;
clear sum2_and_00000011;clear sum2_and_00001100;clear sum2_and_00110000;clear sum2_and_11000000;
clear sum2_xor_00000011;clear sum2_xor_00001100;clear sum2_xor_00110000;clear sum2_xor_11000000;
clear sum2_nor_00000011;clear sum2_nor_00001100;clear sum2_nor_00110000;clear sum2_nor_11000000;
clear sum2_mss_00000011;clear sum2_mss_00001100;clear sum2_mss_00110000;clear sum2_mss_11000000;
clear stride1 stride2 stride3 stride4;
end;%if ver_flag==0;
if ver_flag==1;
disp(sprintf(' %% version 1: sequential read'));
data_snp = zeros(1,4*n_patient_rup_(ns),'uint8');
n_zz_and_{ns} = zeros(1,n_snp_(ns));n_zz_xor_{ns} = zeros(1,n_snp_(ns));n_zz_nor_{ns} = zeros(1,n_snp_(ns));n_zz_mss_{ns} = zeros(1,n_snp_(ns));
m_zz_and_{ns} = zeros(1,n_patient_(ns));m_zz_xor_{ns} = zeros(1,n_patient_(ns));m_zz_nor_{ns} = zeros(1,n_patient_(ns));m_zz_mss_{ns} = zeros(1,n_patient_(ns));
t_tmp_tot=0; tic;
for nl=1:n_snp_(ns);
if (mod(nl,1000)==0); 
t_tmp = toc; t_tmp_tot = t_tmp_tot + t_tmp; t_tmp_full = t_tmp_tot*n_snp_(ns)/nl; t_tmp_rem = t_tmp_full - t_tmp_tot;
disp(sprintf(' %% nl %d/%d, %0.2f seconds elapsed (%0.2f estimated, %0.2f remaining)',nl,n_snp_(ns),t_tmp,t_tmp_full,t_tmp_rem));
end;%if (mod(nl,1000)==0); 
uchar_11111111 = transpose(uint8(fread(fp_bed_{ns},n_patient_rup_(ns),'uint8')));
uchar_00000011 = mod(uchar_11111111,  4);
uchar_00001111 = mod(uchar_11111111, 16); uchar_00001100 = idivide(uchar_00001111 - uchar_00000011, 4) ;
uchar_00111111 = mod(uchar_11111111, 64); uchar_00110000 = idivide(uchar_00111111 - uchar_00001111,16) ;
uchar_11111111 = mod(uchar_11111111,256); uchar_11000000 = idivide(uchar_11111111 - uchar_00111111,64) ;
data_snp = zeros(1,4*n_patient_rup_(ns));
data_snp(1:4:4*n_patient_rup_(ns)) = uchar_00000011;
data_snp(2:4:4*n_patient_rup_(ns)) = uchar_00001100;
data_snp(3:4:4*n_patient_rup_(ns)) = uchar_00110000;
data_snp(4:4:4*n_patient_rup_(ns)) = uchar_11000000;
data_snp_tmp = data_snp(1:n_patient_(ns));
n_zz_and_{ns}(nl) = sum(data_snp_tmp(rij_keep_{ns})==snp_and_tag);
n_zz_xor_{ns}(nl) = sum(data_snp_tmp(rij_keep_{ns})==snp_xor_tag);
n_zz_nor_{ns}(nl) = sum(data_snp_tmp(rij_keep_{ns})==snp_nor_tag);
n_zz_mss_{ns}(nl) = sum(data_snp_tmp(rij_keep_{ns})==snp_mss_tag);
m_zz_and_{ns}(rij_keep_{ns}) = m_zz_and_{ns}(rij_keep_{ns}) + (data_snp_tmp(rij_keep_{ns})==snp_and_tag);
m_zz_xor_{ns}(rij_keep_{ns}) = m_zz_xor_{ns}(rij_keep_{ns}) + (data_snp_tmp(rij_keep_{ns})==snp_xor_tag);
m_zz_nor_{ns}(rij_keep_{ns}) = m_zz_nor_{ns}(rij_keep_{ns}) + (data_snp_tmp(rij_keep_{ns})==snp_nor_tag);
m_zz_mss_{ns}(rij_keep_{ns}) = m_zz_mss_{ns}(rij_keep_{ns}) + (data_snp_tmp(rij_keep_{ns})==snp_mss_tag);
end;%for nl=1:n_snp_(ns);
end;%if ver_flag==1;
fclose(fp_bed_{ns});
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Calculating relative-entropy (i.e., KL-divergence) for each snp within study. ;'));
disp(sprintf('%% If we assume that a snp has minor allele frequency q and major allele frequency p, ;'));
disp(sprintf('%% then the distribution of (n_and,n_xor,n_nor) should be proportional to: ;'));
disp(sprintf('%% (p*p, 2*p*q, q*q), respectively. ;'));
disp(sprintf('%% If the true distribution is given by (frq_and,frq_xor,frq_nor) = (n_and,n_xor,n_nor)/n_patient_keep, ;'));
disp(sprintf('%% then the relative entropy between the true distribution and the expected distribution is: ;'));
disp(sprintf('%% I = frq_and*log(frq_and/p^2) + frq_xor*log(frq_xor/(2*p*q)) + frq_nor*log(frq_nor/q^2). ;'));
disp(sprintf('%% The derivative of I with respect to p is: ;'));
disp(sprintf('%% dI/dp = -2*frq_and/p - (q-p)*frq_xor/(p*q) + 2*frq_nor/q. ;'));
disp(sprintf('%% Setting this to 0, we see that the optimal p and q are given by: ;'));
disp(sprintf('%% 2*p*frq_nor - 2*q*frq_and = (q-p)*frq_xor, ;'));
disp(sprintf('%% p*(2*frq_nor+2*frq_and+2*frq_xor) = 2*frq_and + frq_xor, ;'));
disp(sprintf('%% or simply: ;'));
disp(sprintf('%% p_opt = frq_and + 0.5*frq_xor, '));
disp(sprintf('%% q_opt = frq_nor + 0.5*frq_xor. ,'));
disp(sprintf('%% I_opt = frq_and*log(frq_and/p_opt^2) + frq_xor*log(frq_xor/(2*p_opt*q_opt)) + frq_nor*log(frq_nor/q_opt^2). ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for ns=1:n_study;
frq_and = n_and_{ns}/n_patient_keep_(ns); frq_xor = n_xor_{ns}/n_patient_keep_(ns); frq_nor = n_nor_{ns}/n_patient_keep_(ns);
p_opt_{ns} = frq_and + 0.5*frq_xor; q_opt_{ns} = frq_nor + 0.5*frq_xor;
I_opt_{ns} = frq_and.*log(frq_and./(p_opt_{ns}.^2)) + ...
             frq_xor.*log(frq_xor./(2*p_opt_{ns}.*q_opt_{ns})) + ...
             frq_nor.*log(frq_nor./(q_opt_{ns}.^2)) ;
disp(sprintf(' %% ns %d: [05 25 50 75 95] percentile: ',ns));
tmp = [prctile(p_opt_{ns}, 5) , prctile(p_opt_{ns},25) , prctile(p_opt_{ns},50) , prctile(p_opt_{ns},75) , prctile(p_opt_{ns},95) ] ; 
disp(sprintf(' %% p_opt_ [%0.2f,%0.2f,%0.2f,%0.2f,%0.2f]',tmp));
tmp = [prctile(q_opt_{ns}, 5) , prctile(q_opt_{ns},25) , prctile(q_opt_{ns},50) , prctile(q_opt_{ns},75) , prctile(q_opt_{ns},95) ] ; 
disp(sprintf(' %% q_opt_ [%0.2f,%0.2f,%0.2f,%0.2f,%0.2f]',tmp));
tmp = [prctile(I_opt_{ns}, 5) , prctile(I_opt_{ns},25) , prctile(I_opt_{ns},50) , prctile(I_opt_{ns},75) , prctile(I_opt_{ns},95) ] ; 
disp(sprintf(' %% I_opt_ [%0.2f,%0.2f,%0.2f,%0.2f,%0.2f]',tmp));
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Calculating intersection (i.e., cap) of snps ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
snp__id_ = cell(n_study,1); snp_pos_ = cell(n_study,1); for ns=1:n_study; snp__id_{ns} = bim_{ns}{2}; snp_pos_{ns} = bim_{ns}{4}; end;
[snp_cap] = intersectall(snp__id_); snp_cap_length = length(snp_cap);
snp_cap_ = cell(n_study,1);
for ns=1:n_study; [~,~,snp_cap_{ns}] = intersect(snp_cap,snp__id_{ns},'stable'); end;%for ns=1:n_study;
disp(sprintf(' %% snp_cap_length %d',snp_cap_length));
disp_flag=0;
if disp_flag;
figure;cla; 
for ns1=1:n_study;
for ns2=ns1+1:n_study;
subplot(1,2,1); hold on;
plot(1:snp_cap_length,snp_pos_{ns1}(snp_cap_{ns1}),'ro',1:snp_cap_length,snp_pos_{ns2}(snp_cap_{ns2}),'b.'); xlabel('snp index number'); ylabel('snp pos'); title('snp ij vs pos');
subplot(1,2,2); hold on;
plot(snp_pos_{ns1}(snp_cap_{ns1}),snp_pos_{ns2}(snp_cap_{ns2}),'.'); xlabel('snp pos'); ylabel('snp pos'); title('pos vs pos');
end;%for ns2=ns1+1:n_study;
end;%for ns1=1:n_study;
end;%if disp_flag;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Calculating p_opt_, q_opt_ and entropy I_opt_ for each snp across studies ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
n_and_tot_ = zeros(snp_cap_length,1); n_xor_tot_ = zeros(snp_cap_length,1); n_nor_tot_ = zeros(snp_cap_length,1); n_mss_tot_ = zeros(snp_cap_length,1); I_opt_max_ = zeros(snp_cap_length,1);
for ns=1:n_study; 
n_and_tot_ = n_and_tot_ + n_and_{ns}(snp_cap_{ns}); n_xor_tot_ = n_xor_tot_ + n_xor_{ns}(snp_cap_{ns}); n_nor_tot_ = n_nor_tot_ + n_nor_{ns}(snp_cap_{ns}); n_mss_tot_ = n_mss_tot_ + n_mss_{ns}(snp_cap_{ns}); 
I_opt_max_ = max(I_opt_max_,I_opt_{ns}(snp_cap_{ns}));
end;%for ns=1:n_study;
frq_and_tot_ = n_and_tot_ / sum(n_patient_keep_); frq_xor_tot_ = n_xor_tot_ / sum(n_patient_keep_); frq_nor_tot_ = n_nor_tot_ / sum(n_patient_keep_); frq_mss_tot_ = n_mss_tot_ / sum(n_patient_keep_);
fr2_and_tot_ = frq_and_tot_; fr2_xor_tot_ = frq_xor_tot_; fr2_nor_tot_ = frq_nor_tot_; fr2_mode_ = zeros(snp_cap_length,1);
tmp_ij = find(frq_and_tot_ >frq_xor_tot_ & frq_and_tot_ >frq_nor_tot_); fr2_mode_(tmp_ij) = snp_and_tag; fr2_and_tot_(tmp_ij) = fr2_and_tot_(tmp_ij) + frq_mss_tot_(tmp_ij);
tmp_ij = find(frq_xor_tot_>=frq_and_tot_ & frq_xor_tot_>=frq_nor_tot_); fr2_mode_(tmp_ij) = snp_xor_tag; fr2_xor_tot_(tmp_ij) = fr2_xor_tot_(tmp_ij) + frq_mss_tot_(tmp_ij);
tmp_ij = find(frq_nor_tot_>=frq_and_tot_ & frq_nor_tot_ >frq_xor_tot_); fr2_mode_(tmp_ij) = snp_nor_tag; fr2_nor_tot_(tmp_ij) = fr2_nor_tot_(tmp_ij) + frq_mss_tot_(tmp_ij);
clear tmp_ij;
p_opt_tot_ = fr2_and_tot_ + 0.5*fr2_xor_tot_;
q_opt_tot_ = fr2_nor_tot_ + 0.5*fr2_xor_tot_;
I_opt_tot_ = fr2_nor_tot_.*log(fr2_nor_tot_./(q_opt_tot_.^2)) ...
  + fr2_xor_tot_.*log(fr2_xor_tot_./(2*p_opt_tot_.*q_opt_tot_)) ...
  + fr2_and_tot_.*log(fr2_and_tot_./(p_opt_tot_.^2));
I_opt_tot_(find(fr2_nor_tot_==0))=0;
disp(sprintf(' %% all studies: [05 25 50 75 95] percentile: ',ns));
tmp = [prctile(p_opt_tot_, 5) , prctile(p_opt_tot_,25) , prctile(p_opt_tot_,50) , prctile(p_opt_tot_,75) , prctile(p_opt_tot_,95) ] ; 
disp(sprintf(' %% p_opt_tot_ [%0.2f,%0.2f,%0.2f,%0.2f,%0.2f]',tmp));
tmp = [prctile(q_opt_tot_, 5) , prctile(q_opt_tot_,25) , prctile(q_opt_tot_,50) , prctile(q_opt_tot_,75) , prctile(q_opt_tot_,95) ] ; 
disp(sprintf(' %% q_opt_tot_ [%0.2f,%0.2f,%0.2f,%0.2f,%0.2f]',tmp));
tmp = [prctile(I_opt_tot_, 5) , prctile(I_opt_tot_,25) , prctile(I_opt_tot_,50) , prctile(I_opt_tot_,75) , prctile(I_opt_tot_,95) ] ; 
disp(sprintf(' %% I_opt_tot_ [%0.2f,%0.2f,%0.2f,%0.2f,%0.2f]',tmp));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Calculating subset of col-intersection which satisfies cutoffs. ; '));
disp(sprintf('%% This calculation does not involve patients which are excluded via famex. ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
snp_cap_sub = find(I_opt_tot_ < ent_cutoff & I_opt_max_ < ent_cutoff & min(p_opt_tot_,q_opt_tot_) > frq_cutoff & frq_mss_tot_ < mss_cutoff); snp_cap_sub_length = length(snp_cap_sub);
disp(sprintf(' %% retaining %d/%d snps',length(snp_cap_sub),length(snp_cap)));
snp_cap_sub_ = cell(n_study,1);
for ns=1:n_study; snp_cap_sub_{ns} = snp_cap_{ns}(snp_cap_sub); end;%for ns=1:n_study;
disp_flag=0;
if disp_flag;
figure;cla; 
for ns1=1:n_study;
for ns2=ns1+1:n_study;
subplot(1,2,1); hold on;
plot(1:snp_cap_sub_length,snp_pos_{ns1}(snp_cap_sub_{ns1}),'ro',1:snp_cap_sub_length,snp_pos_{ns2}(snp_cap_sub_{ns2}),'b.'); xlabel('snp index number'); ylabel('snp pos'); title('snp cij vs pos');
subplot(1,2,2); hold on;
plot(snp_pos_{ns1}(snp_cap_sub_{ns1}),snp_pos_{ns2}(snp_cap_sub_{ns2}),'.'); xlabel('snp pos'); ylabel('snp pos'); title('pos vs pos');
end;%for ns2=ns1+1:n_study;
end;%for ns1=1:n_study;
end;%if disp_flag;

brk=3; col_fr2 = n_study+1; col_srt = n_study+2; col_trs = n_study+3;
%cij_index_array_ = zeros(2*snp_cap_sub_length,n_study+brk);
cij_index_array_ = zeros(3*snp_cap_sub_length,n_study+brk);
cij_and = 0*snp_cap_sub_length + transpose(1:snp_cap_sub_length);
cij_xor = 1*snp_cap_sub_length + transpose(1:snp_cap_sub_length);
cij_nor = 2*snp_cap_sub_length + transpose(1:snp_cap_sub_length);
for ns=1:n_study; 
cij_index_array_(cij_and,ns) = snp_cap_sub_{ns}; 
cij_index_array_(cij_xor,ns) = snp_cap_sub_{ns}; 
cij_index_array_(cij_nor,ns) = snp_cap_sub_{ns}; 
end;% for ns=1:n_study;
cij_index_array_(cij_and,col_fr2) = fr2_and_tot_(snp_cap_sub);
%cij_index_array_(cij_xor,col_fr2) = fr2_and_tot_(snp_cap_sub) + fr2_xor_tot_(snp_cap_sub);
cij_index_array_(cij_xor,col_fr2) = fr2_xor_tot_(snp_cap_sub);
cij_index_array_(cij_nor,col_fr2) = fr2_nor_tot_(snp_cap_sub);
[~,tmp_r] = sort(cij_index_array_(:,col_fr2),'ascend');
cij_index_array_(:,col_srt) = tmp_r;
[~,tmp_s] = sort(tmp_r,'ascend');
cij_index_array_(:,col_trs) = tmp_s;
cij_and_rpl_ = cij_index_array_(cij_and,col_trs);
cij_xor_rpl_ = cij_index_array_(cij_xor,col_trs);
cij_nor_rpl_ = cij_index_array_(cij_nor,col_trs);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Calculating subset of rows which satisfies cutoffs. ; '));
disp(sprintf('%% This calculation does involve all the snps when calculating missing fraction, ;'));
disp(sprintf('%% including those which have been excluded above. ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
rij_cap_ = cell(n_study,1);
rij_cap_length_ = zeros(n_study,1);
for ns=1:n_study; 
rij_tmp_ = zeros(1,n_patient_(ns)); rij_tmp_(rij_keep_{ns})=1;
rij_cap_{ns} = find((m_mss_{ns}(1,1:n_patient_(ns))/n_snp_(ns) < mss_cutoff) & rij_tmp_); 
rij_cap_length_(ns) = length(rij_cap_{ns});
disp(sprintf(' %% ns %d: retaining %d/%d/%d patients',ns,rij_cap_length_(ns),n_patient_keep_(ns),n_patient_(ns)));
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Grabbing mds_ components ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nrows_T_full=0; ncols_Tn = 1 + size(mds_,2);
for ns=1:n_study;
tmp_fam_ = cell(rij_cap_length_(ns),1);
for np=1:rij_cap_length_(ns); 
tmp_fam_{np} = sprintf('%s%s%s',fam_{ns}{1}{rij_cap_{ns}(np)},'&',fam_{ns}{2}{rij_cap_{ns}(np)}); 
end;%for np=1:rij_cap_length_(ns);
[~,tmp_r,tmp_m] = intersect(tmp_fam_,mds_name_,'stable');
if length(tmp_r)<rij_cap_length_(ns); 
disp(sprintf(' %% Warning! ns %d, tmp_r length %d/%d',ns,length(tmp_r),rij_cap_length_(ns))); 
rij_cap_{ns} = rij_cap_{ns}(tmp_r);
else; disp(sprintf(' %% ns %d, tmp_r %d == rij_cap_length_(ns) %d',ns,length(tmp_r),rij_cap_length_(ns)));
end;%if length(tmp_r)<rij_cap_length_(ns); 
T_{ns} = mds_(tmp_m,:);
nrows_T_full = nrows_T_full + length(tmp_r);
end;%for ns=1:n_study;
T_full_ = zeros(nrows_T_full,size(mds_,2));
nrows_T_sum=0;
for ns=1:n_study;
T_full_(nrows_T_sum + (1:size(T_{ns},1)),1:size(T_{ns},2)) = T_{ns};
nrows_T_sum = nrows_T_sum + size(T_{ns},1);
end;%for ns=1:n_study;
T_med_ = median(T_full_);
T_full_ = T_full_ - repmat(T_med_,nrows_T_sum,1);
for ns=1:n_study;
T_{ns} = T_{ns} - repmat(T_med_,rij_cap_length_(ns),1);
end;%for ns=1:n_study;
mc_T = ones(ncols_Tn,1);
tmpchar = sprintf('%s/%smc_T.b16',dir_out,snp_pre); tutorial_binary_compress(bitj,mc_T(:)>0,tmpchar); 
tmpchar = sprintf('%s/%sT_full_n.b16',dir_out,snp_pre);tutorial_binary_compress(bitj,[ones(nrows_T_sum,1) , (T_full_>0)],tmpchar);
tmpchar = sprintf('%s/%sT_full_t.b16',dir_out,snp_pre);tutorial_binary_compress(bitj,transpose([ones(nrows_T_sum,1) , (T_full_>0)]),tmpchar);
for ns=1:n_study;
tmpchar = sprintf('%s/%sT_%.2d_n.b16',dir_out,snp_pre,ns);tutorial_binary_compress(bitj,[ones(rij_cap_length_(ns),1) , (T_{ns}>0)],tmpchar);
tmpchar = sprintf('%s/%sT_%.2d_t.b16',dir_out,snp_pre,ns);tutorial_binary_compress(bitj,transpose([ones(rij_cap_length_(ns),1) , (T_{ns}>0)]),tmpchar);
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% creating mds_m2rx ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
T_m2rz_med_ = transpose(adi_median(transpose(T_full_(:,1:2)),1e-9,1));
disp(sprintf('T_m2rz_med_: %0.6f,%0.6f',T_m2rz_med_));
T_m2rz_full_ = T_full_(:,1:2) - repmat(T_m2rz_med_,nrows_T_sum,1);
for ns=1:n_study;
T_m2rz_{ns} = T_{ns}(:,1:2) - repmat(T_m2rz_med_,rij_cap_length_(ns),1);
end;%for ns=1:n_study;
n_z=4;
for nz=1:n_z;
T_m2rx_full_ = zeros(size(T_m2rz_full_,1),size(T_m2rz_full_,2)*nz);
T_m2rx_full_(:,1:2) = T_m2rz_full_;
for ns=1:n_study;
T_m2rx_{ns} = zeros(size(T_m2rz_{ns},1),size(T_m2rz_{ns},2)*nz);
T_m2rx_{ns}(:,1:2) = T_m2rz_{ns};
end;%for ns=1:n_study;
w_tmp = pi/2/nz; R_tmp = [cos(w_tmp),+sin(w_tmp);-sin(w_tmp),cos(w_tmp)];
for nx=2:nz;
T_m2rx_full_(:,(1:2) + (nx-1)*2) = T_m2rx_full_(:,(1:2) + (nx-2)*2)*R_tmp;
for ns=1:n_study;
T_m2rx_{ns}(:,(1:2) + (nx-1)*2) = T_m2rx_{ns}(:,(1:2) + (nx-2)*2)*R_tmp;
end;%for ns=1:n_study;
end;%for nx=2:nz;
mc_T_m2rx = ones(1 + 2*nz,1);
tmpchar = sprintf('%s/%smc_T_m2r%d.b16',dir_out,snp_pre,nz); disp(sprintf(' %% Writing %s of size %d sum %d',tmpchar,length(mc_T_m2rx),sum(mc_T_m2rx>0))); tutorial_binary_compress(bitj,mc_T_m2rx(:)>0,tmpchar);
tmpchar = sprintf('%s/%sT_m2r%d_full_n.b16',dir_out,snp_pre,nz); disp(sprintf(' %% Writing %s of size %d-x%d',tmpchar,size(T_m2rx_full_,1),1+size(T_m2rx_full_,2))); tutorial_binary_compress(bitj,[ones(nrows_T_sum,1) , (T_m2rx_full_>0)],tmpchar);
tmpchar = sprintf('%s/%sT_m2r%d_full_t.b16',dir_out,snp_pre,nz); disp(sprintf(' %% Writing %s of size %d-x%d',tmpchar,1+size(T_m2rx_full_,2),size(T_m2rx_full_,1))); tutorial_binary_compress(bitj,transpose([ones(nrows_T_sum,1) , (T_m2rx_full_>0)]),tmpchar);
save(sprintf('%s/%sT_m2r%d_full_n.mat',dir_out,snp_pre,nz),'T_m2rz_med_','T_m2rz_full_','T_m2rx_full_','w_tmp','R_tmp');
for ns=1:n_study;
tmpchar = sprintf('%s/%sT_m2r%d_%.2d_n.b16',dir_out,snp_pre,nz,ns); disp(sprintf(' %% Writing %s of size %d-x%d',tmpchar,size(T_m2rx_{ns},1),1+size(T_m2rx_{ns},2))); tutorial_binary_compress(bitj,[ones(rij_cap_length_(ns),1) , (T_m2rx_{ns}>0)],tmpchar);
tmpchar = sprintf('%s/%sT_m2r%d_%.2d_t.b16',dir_out,snp_pre,nz,ns); disp(sprintf(' %% Writing %s of size %d-x%d',tmpchar,1+size(T_m2rx_{ns},2),size(T_m2rx_{ns},1))); tutorial_binary_compress(bitj,transpose([ones(rij_cap_length_(ns),1) , (T_m2rx_{ns}>0)]),tmpchar);
end;%for ns=1:n_study;
save(sprintf('%s/%sT_m2r%d_xx_n.mat',dir_out,snp_pre,nz),'T_m2rz_med_','T_m2rz_','T_m2rx_','w_tmp','R_tmp');
tmp_M = size(T_m2rz_full_,1); tmp_NT = size(T_m2rx_full_,2);
tmp_b_ = 2*(T_m2rx_full_>0)-1;
tmp_d = sum(sum(tmp_b_(:,:),1).^2)/(tmp_M*tmp_M*tmp_NT);
tmp_c_ = zeros(tmp_M,1);
for nr=1:tmp_M;
u_ = T_m2rz_full_(nr,:); u_ = u_/norm(u_);
tmp_ij = find((T_m2rz_full_*transpose(u_))>0); tmp_m = length(tmp_ij);
tmp_c_(nr) = sum(sum(tmp_b_(tmp_ij,:),1).^2)/(tmp_m*tmp_m*tmp_NT);
end;%for nr=1:tmp_M;
tmpchar = sprintf('%s/%sT_m2r%d_kappa.txt',dir_out,snp_pre,nz);
tmp_fp = fopen(tmpchar,'w'); fprintf(tmp_fp,'%0.16f\n',mean(tmp_c_)); fclose(tmp_fp);
disp(sprintf(' %% nx %d: kappa^2 = %0.6f (versus %0.6f) --> writing to %s',nz,mean(tmp_c_),tmp_d,tmpchar));
end;%for nz=1:n_z;

if flag_stop>2;
disp('returning at line 454'); return; 
end;%if flag_stop>2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% defining ncols_An, nrows_An_ and nrows_A_n_full_ ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%ncols_An = 2*snp_cap_sub_length; 
ncols_An = 3*snp_cap_sub_length; 
ncols_An_extend = mod(bitj - mod(ncols_An,bitj),bitj); lcols_An = (ncols_An + ncols_An_extend)/bit8;
nrows_An_ = zeros(1,n_study);
for ns=1:n_study;
nrows_An_(ns) = rij_cap_length_(ns); nrows_An_extend_(ns) = mod(bitj - mod(nrows_An_(ns),bitj),bitj); lrows_An_(ns) = (nrows_An_(ns) + nrows_An_extend_(ns))/bit8;
disp(sprintf(' %% nrows_An_(%d): %d',ns,nrows_An_(ns)));
end;%for ns=1:n_study;
nrows_An_full = sum(nrows_An_); nrows_An_full_extend = mod(bitj - mod(nrows_An_full,bitj),bitj); lrows_An_full = (nrows_An_full + nrows_An_full_extend)/bit8;
disp(sprintf(' %% nrows_An_full: %d',nrows_An_full));
nrows_An_csum_ = cumsum([0,nrows_An_]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Writing extended bim and fam files (i.e., bim.ext and fam.ext). ; '));
disp(sprintf('%% ; '));
disp(sprintf('%% Bim: ; '));
disp(sprintf('%% This has the same structure as a typical bim file, ; '));
disp(sprintf('%% with five extra fields. ; '));
disp(sprintf('%% field 6+1: allele type. ; '));
disp(sprintf('%% field 6+2: total relative entropy across (nonexcluded) patients. ; '));
disp(sprintf('%% field 6+3: frequency of allele type (i.e., sparsity of column). ; '));
disp(sprintf('%% field 6+4: frequency of missing data for that snp. ; '));
disp(sprintf('%% field 6+5: minor-allele-frequency of that snp. ; '));
disp(sprintf('%% Moreover, the allele-ordering should be sorted in terms of column-sparsity. ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if flag_bim;
tmp_bim_ = cell(6 + 5);
tmp_bim_{ 1} = zeros(ncols_An,1);
tmp_bim_{ 2} = cell(ncols_An,1);
tmp_bim_{ 3} = zeros(ncols_An,1);
tmp_bim_{ 4} = zeros(ncols_An,1);
tmp_bim_{ 5} = cell(ncols_An,1);
tmp_bim_{ 6} = cell(ncols_An,1);
tmp_bim_{ 7} = cell(ncols_An,1);
tmp_bim_{ 8} = zeros(ncols_An,1);
tmp_bim_{ 9} = zeros(ncols_An,1);
tmp_bim_{10} = zeros(ncols_An,1);
tmp_bim_{11} = zeros(ncols_An,1);
for nl3=1:snp_cap_sub_length; 
nl2 = snp_cap_sub(nl3);
ns=1; nla = snp_cap_sub_{ns}(nl3); nlb = snp_cap_{ns}(nl2); assert(nla==nlb); nl1=nla;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
tmp_bim_{ 1}(cij_and_rpl_(nl3)) = bim_{ns}{1}(nl1);
tmp_bim_{ 2}(cij_and_rpl_(nl3)) = bim_{ns}{2}(nl1);
tmp_bim_{ 3}(cij_and_rpl_(nl3)) = bim_{ns}{3}(nl1);
tmp_bim_{ 4}(cij_and_rpl_(nl3)) = bim_{ns}{4}(nl1);
tmp_bim_{ 5}(cij_and_rpl_(nl3)) = bim_{ns}{5}(nl1);
tmp_bim_{ 6}(cij_and_rpl_(nl3)) = bim_{ns}{6}(nl1);
tmp_bim_{ 7}(cij_and_rpl_(nl3)) = {'and'};
tmp_bim_{ 8}(cij_and_rpl_(nl3)) = I_opt_tot_(nl2);
tmp_bim_{ 9}(cij_and_rpl_(nl3)) = fr2_and_tot_(nl2);
tmp_bim_{10}(cij_and_rpl_(nl3)) = frq_mss_tot_(nl2);
tmp_bim_{11}(cij_and_rpl_(nl3)) = min(p_opt_tot_(nl2),q_opt_tot_(nl2));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
tmp_bim_{ 1}(cij_xor_rpl_(nl3)) = bim_{ns}{1}(nl1);
tmp_bim_{ 2}(cij_xor_rpl_(nl3)) = bim_{ns}{2}(nl1);
tmp_bim_{ 3}(cij_xor_rpl_(nl3)) = bim_{ns}{3}(nl1);
tmp_bim_{ 4}(cij_xor_rpl_(nl3)) = bim_{ns}{4}(nl1);
tmp_bim_{ 5}(cij_xor_rpl_(nl3)) = bim_{ns}{5}(nl1);
tmp_bim_{ 6}(cij_xor_rpl_(nl3)) = bim_{ns}{6}(nl1);
tmp_bim_{ 7}(cij_xor_rpl_(nl3)) = {'xor'};
tmp_bim_{ 8}(cij_xor_rpl_(nl3)) = I_opt_tot_(nl2);
%tmp_bim_{ 9}(cij_xor_rpl_(nl3)) = fr2_and_tot_(nl2) + fr2_xor_tot_(nl2);
tmp_bim_{ 9}(cij_xor_rpl_(nl3)) = fr2_xor_tot_(nl2);
tmp_bim_{10}(cij_xor_rpl_(nl3)) = frq_mss_tot_(nl2);
tmp_bim_{11}(cij_xor_rpl_(nl3)) = min(p_opt_tot_(nl2),q_opt_tot_(nl2));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
tmp_bim_{ 1}(cij_nor_rpl_(nl3)) = bim_{ns}{1}(nl1);
tmp_bim_{ 2}(cij_nor_rpl_(nl3)) = bim_{ns}{2}(nl1);
tmp_bim_{ 3}(cij_nor_rpl_(nl3)) = bim_{ns}{3}(nl1);
tmp_bim_{ 4}(cij_nor_rpl_(nl3)) = bim_{ns}{4}(nl1);
tmp_bim_{ 5}(cij_nor_rpl_(nl3)) = bim_{ns}{5}(nl1);
tmp_bim_{ 6}(cij_nor_rpl_(nl3)) = bim_{ns}{6}(nl1);
tmp_bim_{ 7}(cij_nor_rpl_(nl3)) = {'nor'};
tmp_bim_{ 8}(cij_nor_rpl_(nl3)) = I_opt_tot_(nl2);
tmp_bim_{ 9}(cij_nor_rpl_(nl3)) = fr2_nor_tot_(nl2);
tmp_bim_{10}(cij_nor_rpl_(nl3)) = frq_mss_tot_(nl2);
tmp_bim_{11}(cij_nor_rpl_(nl3)) = min(p_opt_tot_(nl2),q_opt_tot_(nl2));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%for nl3=1:snp_cap_sub_length;
tmpchar = sprintf('%s/%sbim.ext',dir_out,snp_pre);
fid = fopen(tmpchar,'w');
for nc=1:ncols_An;
fprintf(fid,'%d\t%s\t%d\t%d\t%s\t%s\t%s\t%f\t%f\t%f\t%f\n',tmp_bim_{ 1}(nc),tmp_bim_{ 2}{nc},tmp_bim_{ 3}(nc),tmp_bim_{ 4}(nc),tmp_bim_{ 5}{nc},tmp_bim_{ 6}{nc},tmp_bim_{ 7}{nc},tmp_bim_{ 8}(nc),tmp_bim_{ 9}(nc),tmp_bim_{10}(nc),tmp_bim_{11}(nc));
end;%for nc=1:ncols_An;
fclose(fid);
end;% if flag_bim;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Fam: ; '));
disp(sprintf('%% This has the same structure as a typical fam file, ; '));
disp(sprintf('%% with one extra field. ; '));
disp(sprintf('%% field 6+1: directory and filename from which fam file was drawn . ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if flag_fam;
tmp_fam = cell(6 + 1);
tmp_fam{1} = cell(nrows_An_full,1);
tmp_fam{2} = cell(nrows_An_full,1);
tmp_fam{3} = cell(nrows_An_full,1);
tmp_fam{4} = cell(nrows_An_full,1);
tmp_fam{5} = zeros(nrows_An_full,1);
tmp_fam{6} = zeros(nrows_An_full,1);
tmp_fam{7} = cell(nrows_An_full,1);
nr=1;
for ns=1:n_study;
for np2=1:nrows_An_(ns);
np1 = rij_cap_{ns}(np2);
tmp_fam{1}(nr) = fam_{ns}{1}(np1);
tmp_fam{2}(nr) = fam_{ns}{2}(np1);
tmp_fam{3}(nr) = fam_{ns}{3}(np1);
tmp_fam{4}(nr) = fam_{ns}{4}(np1);
tmp_fam{5}(nr) = fam_{ns}{5}(np1);
tmp_fam{6}(nr) = fam_{ns}{6}(np1);
tmp_fam{7}(nr) = {sprintf('~/%s/%s.fam',study_trunk_{ns},study_name_{ns})};
%disp(sprintf('%s %s %s %s %d %d %s',fam_{ns}{1}{np1},fam_{ns}{2}{np1},fam_{ns}{3}{np1},fam_{ns}{4}{np1},fam_{ns}{5}(np1),fam_{ns}{6}(np1),sprintf('~/%s/%s',study_trunk_{ns},study_name_{ns})));
nr = nr+1;
end;%for np2=1:nrows_An_(ns);
end;%for ns=1:n_study;
tmpchar = sprintf('%s/%sfam.ext',dir_out,snp_pre);
fid = fopen(tmpchar,'w');
for nr=1:nrows_An_full;
fprintf(fid,'%s\t%s\t%s\t%s\t%d\t%d\t%s\n',tmp_fam{1}{nr},tmp_fam{2}{nr},tmp_fam{3}{nr},tmp_fam{4}{nr},tmp_fam{5}(nr),tmp_fam{6}(nr),tmp_fam{7}{nr});
end;%for nr=1:nrows_An_full;
fclose(fid);
end;%if flag_fam;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Writing mc and mr masks ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
mc_A = ones(ncols_An,1);
tmpchar = sprintf('%s/%smc_A.b16',dir_out,snp_pre); tutorial_binary_compress(bitj,mc_A(:)>0,tmpchar); 
mr_A_full = zeros(nrows_An_full,1); mr_Z_full = zeros(nrows_An_full,1); 
for ns=1:n_study;
mr_A_{ns} = zeros(nrows_An_(ns),1); mr_Z_{ns} = zeros(nrows_An_(ns),1);
tmp_ij = find(fam_{ns}{6}(rij_cap_{ns})==case_tag);
mr_A_{ns}(tmp_ij) = 1; mr_A_full(nrows_An_csum_(ns) + tmp_ij) = 1;
tmp_ij = find(fam_{ns}{6}(rij_cap_{ns})==ctrl_tag);
mr_Z_{ns}(tmp_ij) = 1; mr_Z_full(nrows_An_csum_(ns) + tmp_ij) = 1;
end;%for ns=1:n_study;
tmpchar = sprintf('%s/%smr_A_full.b16',dir_out,snp_pre);disp(sprintf(' %% Writing %s of size %d sum %d',tmpchar,length(mr_A_full),sum(mr_A_full>0)));tutorial_binary_compress(bitj,mr_A_full(:)>0,tmpchar); pause(1);
tmpchar = sprintf('%s/%smr_Z_full.b16',dir_out,snp_pre);disp(sprintf(' %% Writing %s of size %d sum %d',tmpchar,length(mr_Z_full),sum(mr_Z_full>0)));tutorial_binary_compress(bitj,mr_Z_full(:)>0,tmpchar); pause(1);
for ns=1:n_study;
tmpchar = sprintf('%s/%smr_A_%.2d.b16',dir_out,snp_pre,ns);disp(sprintf(' %% Writing %s of size %d sum %d',tmpchar,length(mr_A_{ns}),sum(mr_A_{ns}>0)));tutorial_binary_compress(bitj,mr_A_{ns}(:)>0,tmpchar); pause(1);
tmpchar = sprintf('%s/%smr_Z_%.2d.b16',dir_out,snp_pre,ns);disp(sprintf(' %% Writing %s of size %d sum %d',tmpchar,length(mr_Z_{ns}),sum(mr_Z_{ns}>0)));tutorial_binary_compress(bitj,mr_Z_{ns}(:)>0,tmpchar); pause(1);
end;%for ns=1:n_study;

if flag_stop>1;
disp('returning at line 619'); return; 
end;%if flag_stop>1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Initializing An_ and At_ ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear A_n_ A_n_full A_t_ A_t_full;
An_full = zeros(lrows_An_full,ncols_An,'uint8');
At_full = zeros(lcols_An,nrows_An_full,'uint8');
for ns=1:n_study;
An_{ns} = zeros(lrows_An_(ns),ncols_An,'uint8');
At_{ns} = zeros(lcols_An,nrows_An_(ns),'uint8');
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% creating shuffled permutations for An_ and At_ ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nz=4;
load(sprintf('%s/%sT_m2r%d_xx_n.mat',dir_out,snp_pre,nz),'T_m2rx_');
nshuffle = 65535;
clear mr_A_prm_ mr_Z_prm_ X_prm_;
mr_A_prm_ = cell(n_study,1);
mr_Z_prm_ = cell(n_study,1);
for ns=1:n_study;
[mr_A_tmp_,mr_Z_tmp_] = xxxcluster_uADZSZDA_shuffle_ver2(nshuffle,[nrows_An_(ns)],ncols_An,{find(mr_A_{ns})},find(mc_A),{find(mr_Z_{ns})},size(T_m2rx_{ns},2),{T_m2rx_{ns}},1:size(T_m2rx_{ns},2));
mr_A_prm_{ns} = mr_A_tmp_{1};
mr_Z_prm_{ns} = mr_Z_tmp_{1};
tmp = zeros(nrows_An_(ns),1); tmp(find(mr_A_{ns})) = 1; tmp(find(mr_Z_{ns})) = 0; [~,tmp_p] = sort(tmp,'ascend'); 
tmp = zeros(nrows_An_(ns),1); tmp(find(mr_A_prm_{ns})) = 1; tmp(find(mr_Z_prm_{ns})) = 0; [~,tmp_q] = sort(tmp,'ascend'); [~,tmp_r] = sort(tmp_q,'ascend'); 
tmp_s = tmp_p(tmp_r);
X_prm_{ns} = tmp_s;
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Writing shuffled versions of An_ and At_ ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for ns=1:n_study;
disp(sprintf(' %% ns %d: %s/%s',ns,study_trunk_{ns},study_name_{ns}));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% reading bed file (binarized snp data) ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fp_bed_{ns} = fopen(fn_bed_{ns}); 
key1 = fread(fp_bed_{ns},1,'uint8'); key2 = fread(fp_bed_{ns},1,'uint8'); key3 = fread(fp_bed_{ns},1,'uint8'); assert(key1==108); assert(key2==27); assert(key3==1);
ver_flag=0;
if ver_flag==0;
disp(sprintf(' %% version 0: simultaneous read (assuming more than 8G of ram)... '));tic;
uchar_11111111 = transpose(fread(fp_bed_{ns},[n_patient_rup_(ns),n_snp_(ns)],'uint8=>uint8')); fclose(fp_bed_{ns});
t_tmp = toc; disp(sprintf(' %% read input: time %0.2f seconds',t_tmp)); 
disp(sprintf(' %% reading 4 allele pairs per byte... ')); tic;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% these commands use mod, which is very slow. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%uchar_00000011 = mod(uchar_11111111,  4);
%uchar_00001111 = mod(uchar_11111111, 16); uchar_00001100 = idivide(uchar_00001111 - uchar_00000011, 4) ; 
%uchar_00111111 = mod(uchar_11111111, 64); uchar_00110000 = idivide(uchar_00111111 - uchar_00001111,16) ; clear uchar_00001111;
%                                          uchar_11000000 = idivide(uchar_11111111 - uchar_00111111,64) ; clear uchar_00111111;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% these commands use bitshifts, which are much faster. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
uchar_00000011 = bitshift(bitshift(uchar_11111111,+6),-6);
uchar_00001100 = bitshift(bitshift(bitshift(uchar_11111111,-2),+6),-6);
uchar_00110000 = bitshift(bitshift(bitshift(uchar_11111111,-4),+6),-6);
uchar_11000000 = bitshift(uchar_11111111,-6);
clear uchar_11111111;
stride1 = 1:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride1,rij_keep_{ns},'stable'); uchar_00000011(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride2 = 2:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride2,rij_keep_{ns},'stable'); uchar_00001100(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride3 = 3:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride3,rij_keep_{ns},'stable'); uchar_00110000(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride4 = 4:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride4,rij_keep_{ns},'stable'); uchar_11000000(:,tmp_ij)=snp_not_tag; clear tmp_ij;
disp(sprintf(' %% writing binary files... ')); t_start = tic; t_sub = tic;
br_u = zeros(1,bit8,'uint8'); br_u = cast(2.^(bit8-1:-1:0),'uint8');
br_d = zeros(1,bit8,'double'); br_d = cast(2.^(bit8-1:-1:0),'double');
for nl3=1:snp_cap_sub_length; 
bl3_and = 1+mod((cij_and_rpl_(nl3)-1),bit8); al3_and = 1+floor((cij_and_rpl_(nl3)-1)/bit8); cl3_and = 1+(cij_and_rpl_(nl3)-1);
bl3_xor = 1+mod((cij_xor_rpl_(nl3)-1),bit8); al3_xor = 1+floor((cij_xor_rpl_(nl3)-1)/bit8); cl3_xor = 1+(cij_xor_rpl_(nl3)-1);
bl3_nor = 1+mod((cij_nor_rpl_(nl3)-1),bit8); al3_nor = 1+floor((cij_nor_rpl_(nl3)-1)/bit8); cl3_nor = 1+(cij_nor_rpl_(nl3)-1);
nl2 = snp_cap_sub(nl3);
nla = snp_cap_sub_{ns}(nl3); nlb = snp_cap_{ns}(nl2); assert(nla==nlb); nl1=nla;
if (mod(nl3,1000)==0); 
t_tmp = toc(t_sub); t_tot_tmp = t_tmp/nl3*snp_cap_sub_length; 
disp(sprintf(' %% nl3 %d/%d nl2 %d/%d nl1 %d/%d; time %0.2f seconds; estimated total time %0.2f seconds (%0.2f hours)',nl3,snp_cap_sub_length,nl2,snp_cap_length,nl1,n_snp_(ns),t_tmp,t_tot_tmp,t_tot_tmp/3600)); 
end;%if (mod(nl3,1000)==0); 
data_snp = zeros(1,4*n_patient_rup_(ns));
data_snp(stride1) = uchar_00000011(nl1,:);
data_snp(stride2) = uchar_00001100(nl1,:);
data_snp(stride3) = uchar_00110000(nl1,:);
data_snp(stride4) = uchar_11000000(nl1,:);
data_snp = data_snp(1,1:n_patient_(ns));
tmp_ij = find(data_snp==snp_mss_tag); data_snp(1,tmp_ij) = fr2_mode_(nl2); clear tmp_ij;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
data_snp_and = (data_snp==snp_and_tag) ; 
data_snp_and_sub = data_snp_and(1,rij_cap_{ns}); 
data_snp_and_sub = data_snp_and_sub(X_prm_{ns});
data_snp_and_bin_u = cast(data_snp_and_sub(1,:),'uint8');
data_snp_and_sub_full = zeros(1,nrows_An_full); data_snp_and_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_and_sub;
data_snp_and_bin_d = cast(data_snp_and_sub(1,:),'double'); 
data_snp_and_full_bin_d = cast(data_snp_and_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_and) = An_full(1:lrows_An_full,cl3_and) + cast(transpose(br_d*reshape([data_snp_and_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_and,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_and,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_and)*data_snp_and_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_and) = An_{ns}(1:lrows_An_(ns),cl3_and) + cast(transpose(br_d*reshape([data_snp_and_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_and,(1:nrows_An_(ns))) = At_{ns}(al3_and,(1:nrows_An_(ns))) + br_u(bl3_and)*data_snp_and_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%data_snp_xor = (data_snp==snp_and_tag) | (data_snp==snp_xor_tag) ;
data_snp_xor = (data_snp==snp_xor_tag) ;
data_snp_xor_sub = data_snp_xor(1,rij_cap_{ns});
data_snp_xor_sub = data_snp_xor_sub(X_prm_{ns});
data_snp_xor_bin_u = cast(data_snp_xor_sub(1,:),'uint8');
data_snp_xor_sub_full = zeros(1,nrows_An_full); data_snp_xor_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_xor_sub;
data_snp_xor_bin_d = cast(data_snp_xor_sub(1,:),'double'); 
data_snp_xor_full_bin_d = cast(data_snp_xor_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_xor) = An_full(1:lrows_An_full,cl3_xor) + cast(transpose(br_d*reshape([data_snp_xor_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_xor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_xor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_xor)*data_snp_xor_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_xor) = An_{ns}(1:lrows_An_(ns),cl3_xor) + cast(transpose(br_d*reshape([data_snp_xor_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_xor,(1:nrows_An_(ns))) = At_{ns}(al3_xor,(1:nrows_An_(ns))) + br_u(bl3_xor)*data_snp_xor_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
data_snp_nor = (data_snp==snp_nor_tag) ;
data_snp_nor_sub = data_snp_nor(1,rij_cap_{ns}); 
data_snp_nor_sub = data_snp_nor_sub(X_prm_{ns});
data_snp_nor_bin_u = cast(data_snp_nor_sub(1,:),'uint8');
data_snp_nor_sub_full = zeros(1,nrows_An_full); data_snp_nor_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_nor_sub;
data_snp_nor_bin_d = cast(data_snp_nor_sub(1,:),'double'); 
data_snp_nor_full_bin_d = cast(data_snp_nor_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_nor) = An_full(1:lrows_An_full,cl3_nor) + cast(transpose(br_d*reshape([data_snp_nor_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_nor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_nor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_nor)*data_snp_nor_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_nor) = An_{ns}(1:lrows_An_(ns),cl3_nor) + cast(transpose(br_d*reshape([data_snp_nor_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_nor,(1:nrows_An_(ns))) = At_{ns}(al3_nor,(1:nrows_An_(ns))) + br_u(bl3_nor)*data_snp_nor_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
end;%for nl3=1:snp_cap_sub_length;
t_tmp = toc(t_start); disp(sprintf(' %% bin: time %0.2f seconds',t_tmp)); 
clear uchar_00000011;clear uchar_00001100;clear uchar_00110000;clear uchar_11000000;
clear stride1 stride2 stride3 stride4;
end;%if ver_flag==0;
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% writing A_shuffle_n.b16 and A_shuffle_t.b16 ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tic;
tmpAnchar = sprintf('%s/%sA_shuffle_full_n.b16',dir_out,snp_pre);
fid = fopen(tmpAnchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,nrows_An_full,'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,An_full(:),'uint8');
fclose(fid);
tmpAtchar = sprintf('%s/%sA_shuffle_full_t.b16',dir_out,snp_pre);
fid = fopen(tmpAtchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,nrows_An_full,'int');
fwrite(fid,At_full(:),'uint8');
fclose(fid);
for ns=1:n_study;
tmpAnchar = sprintf('%s/%sA_shuffle_%.2d_n.b16',dir_out,snp_pre,ns);
fid = fopen(tmpAnchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,nrows_An_(ns),'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,An_{ns}(:),'uint8');
fclose(fid);
tmpAtchar = sprintf('%s/%sA_shuffle_%.2d_t.b16',dir_out,snp_pre,ns);
fid = fopen(tmpAtchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,nrows_An_(ns),'int');
fwrite(fid,At_{ns}(:),'uint8');
fclose(fid);
end;%for ns=1:n_study;
t_tmp = toc; disp(sprintf(' %% b16: time %0.2f seconds',t_tmp)); 

if flag_stop>0;
disp('returning at line 755'); return; 
end;%if flag_stop>0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Initializing An_ and At_ ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear A_n_ A_n_full A_t_ A_t_full;
An_full = zeros(lrows_An_full,ncols_An,'uint8');
At_full = zeros(lcols_An,nrows_An_full,'uint8');
for ns=1:n_study;
An_{ns} = zeros(lrows_An_(ns),ncols_An,'uint8');
At_{ns} = zeros(lcols_An,nrows_An_(ns),'uint8');
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% Writing An_ and At_ ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for ns=1:n_study;
disp(sprintf(' %% ns %d: %s/%s',ns,study_trunk_{ns},study_name_{ns}));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% reading bed file (binarized snp data) ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fp_bed_{ns} = fopen(fn_bed_{ns}); 
key1 = fread(fp_bed_{ns},1,'uint8'); key2 = fread(fp_bed_{ns},1,'uint8'); key3 = fread(fp_bed_{ns},1,'uint8'); assert(key1==108); assert(key2==27); assert(key3==1);
ver_flag=0;
if ver_flag==0;
disp(sprintf(' %% version 0: simultaneous read (assuming more than 8G of ram)... '));tic;
uchar_11111111 = transpose(fread(fp_bed_{ns},[n_patient_rup_(ns),n_snp_(ns)],'uint8=>uint8')); fclose(fp_bed_{ns});
t_tmp = toc; disp(sprintf(' %% read input: time %0.2f seconds',t_tmp)); 
disp(sprintf(' %% reading 4 allele pairs per byte... ')); tic;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% these commands use mod, which is very slow. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%uchar_00000011 = mod(uchar_11111111,  4);
%uchar_00001111 = mod(uchar_11111111, 16); uchar_00001100 = idivide(uchar_00001111 - uchar_00000011, 4) ; 
%uchar_00111111 = mod(uchar_11111111, 64); uchar_00110000 = idivide(uchar_00111111 - uchar_00001111,16) ; clear uchar_00001111;
%                                          uchar_11000000 = idivide(uchar_11111111 - uchar_00111111,64) ; clear uchar_00111111;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% these commands use bitshifts, which are much faster. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
uchar_00000011 = bitshift(bitshift(uchar_11111111,+6),-6);
uchar_00001100 = bitshift(bitshift(bitshift(uchar_11111111,-2),+6),-6);
uchar_00110000 = bitshift(bitshift(bitshift(uchar_11111111,-4),+6),-6);
uchar_11000000 = bitshift(uchar_11111111,-6);
clear uchar_11111111;
stride1 = 1:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride1,rij_keep_{ns},'stable'); uchar_00000011(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride2 = 2:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride2,rij_keep_{ns},'stable'); uchar_00001100(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride3 = 3:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride3,rij_keep_{ns},'stable'); uchar_00110000(:,tmp_ij)=snp_not_tag; clear tmp_ij;
stride4 = 4:4:4*n_patient_rup_(ns); [~,tmp_ij] = setdiff(stride4,rij_keep_{ns},'stable'); uchar_11000000(:,tmp_ij)=snp_not_tag; clear tmp_ij;
disp(sprintf(' %% writing binary files... ')); t_start = tic; t_sub = tic;
br_u = zeros(1,bit8,'uint8'); br_u = cast(2.^(bit8-1:-1:0),'uint8');
br_d = zeros(1,bit8,'double'); br_d = cast(2.^(bit8-1:-1:0),'double');
for nl3=1:snp_cap_sub_length; 
bl3_and = 1+mod((cij_and_rpl_(nl3)-1),bit8); al3_and = 1+floor((cij_and_rpl_(nl3)-1)/bit8); cl3_and = 1+(cij_and_rpl_(nl3)-1);
bl3_xor = 1+mod((cij_xor_rpl_(nl3)-1),bit8); al3_xor = 1+floor((cij_xor_rpl_(nl3)-1)/bit8); cl3_xor = 1+(cij_xor_rpl_(nl3)-1);
bl3_nor = 1+mod((cij_nor_rpl_(nl3)-1),bit8); al3_nor = 1+floor((cij_nor_rpl_(nl3)-1)/bit8); cl3_nor = 1+(cij_nor_rpl_(nl3)-1);
nl2 = snp_cap_sub(nl3);
nla = snp_cap_sub_{ns}(nl3); nlb = snp_cap_{ns}(nl2); assert(nla==nlb); nl1=nla;
if (mod(nl3,1000)==0); 
t_tmp = toc(t_sub); t_tot_tmp = t_tmp/nl3*snp_cap_sub_length; 
disp(sprintf(' %% nl3 %d/%d nl2 %d/%d nl1 %d/%d; time %0.2f seconds; estimated total time %0.2f seconds (%0.2f hours)',nl3,snp_cap_sub_length,nl2,snp_cap_length,nl1,n_snp_(ns),t_tmp,t_tot_tmp,t_tot_tmp/3600)); 
end;%if (mod(nl3,1000)==0); 
data_snp = zeros(1,4*n_patient_rup_(ns));
data_snp(stride1) = uchar_00000011(nl1,:);
data_snp(stride2) = uchar_00001100(nl1,:);
data_snp(stride3) = uchar_00110000(nl1,:);
data_snp(stride4) = uchar_11000000(nl1,:);
data_snp = data_snp(1,1:n_patient_(ns));
tmp_ij = find(data_snp==snp_mss_tag); data_snp(1,tmp_ij) = fr2_mode_(nl2); clear tmp_ij;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
data_snp_and = (data_snp==snp_and_tag) ; 
data_snp_and_sub = data_snp_and(1,rij_cap_{ns}); data_snp_and_bin_u = cast(data_snp_and_sub(1,:),'uint8');
data_snp_and_sub_full = zeros(1,nrows_An_full); data_snp_and_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_and_sub;
data_snp_and_bin_d = cast(data_snp_and_sub(1,:),'double'); 
data_snp_and_full_bin_d = cast(data_snp_and_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_and) = An_full(1:lrows_An_full,cl3_and) + cast(transpose(br_d*reshape([data_snp_and_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_and,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_and,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_and)*data_snp_and_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_and) = An_{ns}(1:lrows_An_(ns),cl3_and) + cast(transpose(br_d*reshape([data_snp_and_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_and,(1:nrows_An_(ns))) = At_{ns}(al3_and,(1:nrows_An_(ns))) + br_u(bl3_and)*data_snp_and_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%data_snp_xor = (data_snp==snp_and_tag) | (data_snp==snp_xor_tag) ;
data_snp_xor = (data_snp==snp_xor_tag) ;
data_snp_xor_sub = data_snp_xor(1,rij_cap_{ns}); data_snp_xor_bin_u = cast(data_snp_xor_sub(1,:),'uint8');
data_snp_xor_sub_full = zeros(1,nrows_An_full); data_snp_xor_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_xor_sub;
data_snp_xor_bin_d = cast(data_snp_xor_sub(1,:),'double'); 
data_snp_xor_full_bin_d = cast(data_snp_xor_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_xor) = An_full(1:lrows_An_full,cl3_xor) + cast(transpose(br_d*reshape([data_snp_xor_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_xor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_xor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_xor)*data_snp_xor_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_xor) = An_{ns}(1:lrows_An_(ns),cl3_xor) + cast(transpose(br_d*reshape([data_snp_xor_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_xor,(1:nrows_An_(ns))) = At_{ns}(al3_xor,(1:nrows_An_(ns))) + br_u(bl3_xor)*data_snp_xor_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
data_snp_nor = (data_snp==snp_nor_tag) ;
data_snp_nor_sub = data_snp_nor(1,rij_cap_{ns}); data_snp_nor_bin_u = cast(data_snp_nor_sub(1,:),'uint8');
data_snp_nor_sub_full = zeros(1,nrows_An_full); data_snp_nor_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_nor_sub;
data_snp_nor_bin_d = cast(data_snp_nor_sub(1,:),'double'); 
data_snp_nor_full_bin_d = cast(data_snp_nor_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_nor) = An_full(1:lrows_An_full,cl3_nor) + cast(transpose(br_d*reshape([data_snp_nor_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_nor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_nor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_nor)*data_snp_nor_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_nor) = An_{ns}(1:lrows_An_(ns),cl3_nor) + cast(transpose(br_d*reshape([data_snp_nor_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_nor,(1:nrows_An_(ns))) = At_{ns}(al3_nor,(1:nrows_An_(ns))) + br_u(bl3_nor)*data_snp_nor_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
end;%for nl3=1:snp_cap_sub_length;
t_tmp = toc(t_start); disp(sprintf(' %% bin: time %0.2f seconds',t_tmp)); 
clear uchar_00000011;clear uchar_00001100;clear uchar_00110000;clear uchar_11000000;
clear stride1 stride2 stride3 stride4;
end;%if ver_flag==0;
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% ; '));
disp(sprintf('%% writing A_n.b16 and A_t.b16 ; '));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tic;
tmpAnchar = sprintf('%s/%sA_full_n.b16',dir_out,snp_pre);
fid = fopen(tmpAnchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,nrows_An_full,'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,An_full(:),'uint8');
fclose(fid);
tmpAtchar = sprintf('%s/%sA_full_t.b16',dir_out,snp_pre);
fid = fopen(tmpAtchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,nrows_An_full,'int');
fwrite(fid,At_full(:),'uint8');
fclose(fid);
for ns=1:n_study;
tmpAnchar = sprintf('%s/%sA_%.2d_n.b16',dir_out,snp_pre,ns);
fid = fopen(tmpAnchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,nrows_An_(ns),'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,An_{ns}(:),'uint8');
fclose(fid);
tmpAtchar = sprintf('%s/%sA_%.2d_t.b16',dir_out,snp_pre,ns);
fid = fopen(tmpAtchar,'w');
fwrite(fid,bitj,'int');
fwrite(fid,ncols_An,'int');
fwrite(fid,nrows_An_(ns),'int');
fwrite(fid,At_{ns}(:),'uint8');
fclose(fid);
end;%for ns=1:n_study;
t_tmp = toc; disp(sprintf(' %% b16: time %0.2f seconds',t_tmp)); 

flag_check = flag_crop;
if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(sprintf('%% checking .b16 files for consistency ;'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tmpAnchar = sprintf('%s/%sA_full_n.b16',dir_out,snp_pre);
Bn_full = tutorial_binary_uncompress(tmpAnchar,1:nrows_An_full,1:ncols_An);
tmpAtchar = sprintf('%s/%sA_full_t.b16',dir_out,snp_pre);
Bt_full = tutorial_binary_uncompress(tmpAtchar,1:ncols_An,1:nrows_An_full);
disp(sprintf(' %% ns all: error %f',norm(Bn_full-transpose(Bt_full))));
disp_flag=0;
if disp_flag;
subplot(1,2,1);imagesc(Bn_full,[-1,1]); subplot(1,2,2);imagesc(transpose(Bt_full),[-1,1]);
print('-djpeg',sprintf('%s/%sA_full_x.jpg',dir_out,snp_pre));
end;%if disp_flag;
for ns=1:n_study;
tmpAnchar = sprintf('%s/%sA_%.2d_n.b16',dir_out,snp_pre,ns);
Bn_{ns} = tutorial_binary_uncompress(tmpAnchar,1:nrows_An_(ns),1:ncols_An);
tmpAtchar = sprintf('%s/%sA_%.2d_t.b16',dir_out,snp_pre,ns);
Bt_{ns} = tutorial_binary_uncompress(tmpAtchar,1:ncols_An,1:nrows_An_(ns));
disp(sprintf(' %% ns %d: error %f',ns,norm(Bn_{ns}-transpose(Bt_{ns}))));
disp_flag=0;
if disp_flag;
subplot(1,2,1);imagesc(Bn_{ns},[-1,1]); subplot(1,2,2);imagesc(transpose(Bt_{ns}),[-1,1]);
print('-djpeg',sprintf('%s/%sA_%.2d_x.jpg',dir_out,snp_pre,ns));
end;%if disp_flag;
end;%for ns=1:n_study;
end;%if flag_check;






