function lisa = lisa_struct_nsg_ver0(lisa,annot,ontology);

pathway_name_ = ontology.pathway_name_;
niter_ = lisa.niter_;
n_percentile = lisa.n_percentile;
z_XX__ = lisa.z_XX__;
log_pval_up_XX__ = lisa.log_pval_up_XX__;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% plot z-score for neuron-specific enrichments. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
tmp_ij1_ = find( cellfun('length',strfind(pathway_name_,'neuro')) | cellfun('length',strfind(pathway_name_,'synap')) | cellfun('length',strfind(pathway_name_,'axon')) ) ;
figure;clf;
for npercentile=1:n_percentile;
tmp_z_XX__ = cell(length(tmp_ij1_),1); 
for nl1=1:length(tmp_ij1_); tmp_z_XX__{nl1} = z_XX__{tmp_ij1_(nl1),npercentile}; end;%for nl1=1:length(tmp_ij1_);
subplot(4,n_percentile,npercentile + 0*n_percentile); hold on;
plot(niter_,0*niter_,'k-'); 
for nl1=1:length(tmp_ij1_); plot(niter_,tmp_z_XX__{nl1},'r-'); end;%for nl1=1:length(tmp_ij1_);
hold off;
xlim([0,niter_(end)]);ylim([-5,5]);
xlabel('iteration'); ylabel('z-score'); title('z-score');
subplot(4,n_percentile,npercentile + 1*n_percentile); hold on;
colormap(colormap_beach());
imagesc( log(1+hist2d_0(repmat(niter_,1,length(tmp_ij1_)),cell2mat(transpose(tmp_z_XX__)),length(niter_),1+64,[0,niter_(end)],[-5,+5])) , [0,4] );
xlim([0,niter_(end)]);ylim([1,1+64]);
xlabel('iteration'); title('log(histogram)');
set(gca,'YTick',[]);
%colorbar;
tmp_log_pval_up_XX__ = cell(length(tmp_ij1_),1); 
for nl1=1:length(tmp_ij1_); tmp_log_pval_up_XX__{nl1} = log_pval_up_XX__{tmp_ij1_(nl1),npercentile}; end;%for nl1=1:length(tmp_ij1_);
subplot(4,n_percentile,npercentile + 2*n_percentile); hold on;
plot(niter_,0*niter_,'k-'); 
for nl1=1:length(tmp_ij1_); plot(niter_,-tmp_log_pval_up_XX__{nl1},'r-'); end;%for nl1=1:length(tmp_ij1_);
hold off;
xlim([0,niter_(end)]);ylim([-1,10]);
xlabel('iteration'); ylabel('- log pval up'); title('z-score');
subplot(4,n_percentile,npercentile + 3*n_percentile); hold on;
colormap(colormap_beach());
imagesc( log(1+hist2d_0(repmat(niter_,1,length(tmp_ij1_)),-cell2mat(transpose(tmp_log_pval_up_XX__)),length(niter_),1+64,[0,niter_(end)],[-1,+10])) , [0,4] );
xlim([0,niter_(end)]);ylim([1,1+64]);
xlabel('iteration'); title('log(histogram)');
set(gca,'YTick',[]);
%colorbar;
end;%for npercentile=1:n_percentile;
