function lisa_xdropplot_ver0() ;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% choose directory names. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c'); 
dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20180304');
path(path,sprintf('%s/dir_m',dir_code)); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% select parameters used during analysis. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
cl_num = 3; 
[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num);
string_prefix = sprintf('PGC_cl%d_maf01',cl_num);
flag_dex_vs_lak = 'dex'; p_threshold = 0.01; gamma = 0.004; B_MLT = 34; Ireq = 0; rev_flag = 0; n_mds = 20; mds_used = [1:2]; mds_repl = 1; 
flag_design = 'ADZSZDA';
n_shuffle = 8;
dir__in = sprintf('%s/dir_%s',dir_trunk,string_prefix);
dir_out = sprintf('%s/dir_%s_analyze',dir_trunk,string_prefix);
disp(sprintf(' %% dir_out: %s',dir_out));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract rdrop_a and cdrop_a. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
nshuffle=0;
if strcmp(flag_design,'uADZSZDA');
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver8('dex',p_threshold,rev_flag,n_mds,mds_used,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver8('dex',p_threshold,rev_flag,n_mds,mds_used,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
end;%if strcmp(flag_design,'uADZSZDA');
if strcmp(flag_design,'ADZSZDA');
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,dexcluster_PGC_xfix_gen_ver7(p_threshold,rev_flag,n_mds,mds_used,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,lakcluster_PGC_xfix_gen_ver7(p_threshold,rev_flag,n_mds,mds_used,gamma,B_MLT,Ireq,nshuffle)); end;
end;%if strcmp(flag_design,'ADZSZDA');
string_name_s0000 = string_name;
dir_out_s0000 = sprintf('%s/dir_%s',dir_out,string_name_s0000);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract rdrop_a and cdrop_a. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fname_tmp = sprintf('%s/out_xdrop_a.txt',dir_out_s0000);
out_xdrop_a_ = textread(fname_tmp); rdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,1)>-1),1)+1; cdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,2)>-1),2)+1;
fname_tmp = sprintf('%s/out_xdrop_b.txt',dir_out_s0000);
out_xdrop_b_ = textread(fname_tmp); rdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,1)>-1),1)+1; cdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,2)>-1),2)+1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% load mds and fam and bim file. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fid = fopen(sprintf('%s/%s_bim.ext',dir__in,string_prefix)); bim_ = textscan(fid,'%d\t%s\t%d\t%d\t%c\t%c\t%s\t%f\t%f\t%f\t%f\n','headerlines',0); fclose(fid);
n_snp = length(bim_{1});
load(sprintf('%s/mds.mat',dir_trunk));
fid = fopen(sprintf('%s/%s_fam.ext',dir__in,string_prefix)); fam_ = textscan(fid,'%s %s %s %s %d %d %s','headerlines',0); fclose(fid);
n_patient_F = length(fam_{1}); fam_name_ = cell(n_patient_F,1); for np=1:n_patient_F; fam_name_{np} = sprintf('%s%s%s',fam_{1}{np},'&',fam_{2}{np}); end;%for np=1:n_patient_F;
[~,ifam_,imds_] = intersect(fam_name_,mds_name_,'stable'); if (length(ifam_)<n_patient_F); disp('Warning! fam_name_ not a subset of mds_name_'); end; mds_sort_ = mds_(imds_,:);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% check to make sure that the mr_A_full lines up with the mr_A_%0.2d ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
mr_A_ = cell(n_study,1);
mr_Z_ = cell(n_study,1);
for ns=1:n_study;
tmpchar = sprintf('%s/%s_mr_A_%0.2d.b16',dir__in,string_prefix,ns);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_A_{ns} = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
tmpchar = sprintf('%s/%s_mr_Z_%0.2d.b16',dir__in,string_prefix,ns);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_Z_{ns} = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
end;%for ns=1:n_study;
tmpchar = sprintf('%s/%s_mr_A_full.b16',dir__in,string_prefix);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_A_full = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
tmpchar = sprintf('%s/%s_mr_Z_full.b16',dir__in,string_prefix);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_Z_full = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
mr_A_tmp = []; mr_Z_tmp = [];
for ns=1:n_study;
mr_A_tmp = [mr_A_tmp;mr_A_{ns}];
mr_Z_tmp = [mr_Z_tmp;mr_Z_{ns}];
end;% for ns=1:n_study;
disp(sprintf(' %% mr_A error %0.16f',norm(mr_A_tmp-mr_A_full)));
disp(sprintf(' %% mr_Z error %0.16f',norm(mr_Z_tmp-mr_Z_full)));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% determine which studies correspond to which patients. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
study_path_ = cell(n_study,1);
study_index_ = zeros(n_patient_F,1);
for ns=1:n_study;
study_path_{ns} = sprintf('~/%s/%s.fam',study_trunk_{ns},study_name_{ns});
study_index_(find(strcmp(fam_{7},study_path_{ns}))) = ns;
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract traces (original stored in s0000) ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
trace_found_ = zeros(n_shuffle+1,1);
for (nshuffle=0:n_shuffle)
if strcmp(flag_design,'uADZSZDA');
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver8('dex',p_threshold,rev_flag,n_mds,mds_used,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver8('dex',p_threshold,rev_flag,n_mds,mds_used,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
end;%if strcmp(flag_design,'uADZSZDA');
if strcmp(flag_design,'ADZSZDA');
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,dexcluster_PGC_xfix_gen_ver7(p_threshold,rev_flag,n_mds,mds_used,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,lakcluster_PGC_xfix_gen_ver7(p_threshold,rev_flag,n_mds,mds_used,gamma,B_MLT,Ireq,nshuffle)); end;
end;%if strcmp(flag_design,'ADZSZDA');
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',dir_out,string_name);
if (exist(fname_tmp,'file')); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); trace_found_(1+nshuffle)=1; else trace_found_(1+nshuffle)=0 ; end;
end;%for (nshuffle=0:n_shuffle)
disp(sprintf(' %% found %d/%d traces',sum(trace_found_),1+n_shuffle));
if (trace_found_(1)~=1); disp(sprintf(' %% Warning! trace for original data not found!')); end;
%%%%%%%%%%%%%%%%;
nshuffle=0;
fname_tmp = sprintf('%s/out_xdrop_a.txt',dir_out_s0000);
out_xdrop_a_ = textread(fname_tmp); rdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,1)>-1),1)+1; cdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,2)>-1),2)+1;
fname_tmp = sprintf('%s/out_xdrop_b.txt',dir_out_s0000);
out_xdrop_b_ = textread(fname_tmp); rdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,1)>-1),1)+1; cdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,2)>-1),2)+1;
%%%%%%%%%%%%%%%%;
n_shuffle_found = sum(trace_found_)-1;
trace_ = cell(1+n_shuffle_found,1);
for nshuffle=0:n_shuffle_found;
if strcmp(flag_design,'uADZSZDA');
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver8('dex',p_threshold,rev_flag,n_mds,mds_used,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver8('dex',p_threshold,rev_flag,n_mds,mds_used,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
end;%if strcmp(flag_design,'uADZSZDA');
if strcmp(flag_design,'ADZSZDA');
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,dexcluster_PGC_xfix_gen_ver7(p_threshold,rev_flag,n_mds,mds_used,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,lakcluster_PGC_xfix_gen_ver7(p_threshold,rev_flag,n_mds,mds_used,gamma,B_MLT,Ireq,nshuffle)); end;
end;%if strcmp(flag_design,'ADZSZDA');
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',dir_out,string_name);
trace_{1+nshuffle} = textread(fname_tmp);
end;%for nshuffle=0:n_shuffle_found;
%%%%%%%%%%%%%%%%;
trace_tmp_ = trace_{1};
[iteration_max,n_cols] = size(trace_tmp_);
if (iteration_max==1 | n_cols~=6); disp(sprintf(' %% Warning! iteration_max %d n_cols %d in first trace',iteration_max,n_cols)); end;
niter_ = trace_tmp_(:,1);
r_rem_ = (trace_tmp_(:,2));
c_rem_ = (trace_tmp_(:,3));
t_rem_ = (trace_tmp_(:,6)); t_ret_ = find(t_rem_>=Ireq);
%%%%%%%%%%%%%%%%;
trace_finished_ = zeros(1+n_shuffle_found,1); 
for nshuffle=0:n_shuffle_found;
trace_tmp_ = trace_{1+nshuffle};
[rtmp,ctmp] = size(trace_tmp_);
if (rtmp==iteration_max & ctmp==6); trace_finished_(1+nshuffle)=1; else trace_finished_(1+nshuffle)=0; end;
end;%for nshuffle=0:n_shuffle_found;
%%%%%%%%%%%%%%%%;
trace_finished_ij_ = find(trace_finished_);
n_finished = length(trace_finished_ij_); disp(sprintf(' %% found n_finished %d',n_finished));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot rdrop_a_ and cdrop_a_ ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
figure;clf;
subplot(2,2,1); plot(rdrop_a_,'.'); ll=size(mds_sort_,1); xlim([1,length(rdrop_a_)]);ylim([1,ll]); title('rdrop_a_ scatter','Interpreter','none');
subplot(2,2,3); ll=size(mds_sort_,1); imagesc(log2(1+adi_hist2d(1:length(rdrop_a_),rdrop_a_,[1,length(rdrop_a_)],256,[1,ll],256))); title('rdrop_a_ histogram','Interpreter','none');
subplot(2,2,2);plot(cdrop_a_,'.'); ll=n_snp; xlim([1,length(cdrop_a_)]);ylim([1,ll]); title('cdrop_a_ scatter','Interpreter','none');
subplot(2,2,4); ll=n_snp; imagesc(log2(1+adi_hist2d(1:length(cdrop_a_),cdrop_a_,[1,length(cdrop_a_)],256,[1,ll],256))); title('cdrop_a_ histogram','Interpreter','none');
set(gcf,'Position',1+[0,0,1024*1.5,768]);
print('-djpeg',sprintf('%s/%s_xdrop_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_xdrop_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot study stack ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
rem_r_ = interp1(r_rem_,1:length(r_rem_),length(rdrop_a_):-1:1); rem_r_(find(~isfinite(rem_r_)))=iteration_max;
rdrop_study_ = study_index_(rdrop_a_);
length_study_rdrop_ = zeros(length(rdrop_a_),n_study);
fraction_study_rdrop_ = zeros(length(rdrop_a_),n_study);
for ns=1:n_study; length_study_rdrop_(1,ns) = length(find(rdrop_study_==ns)); end;%for ns=1:n_study;
fraction_study_rdrop_(1,:) = length_study_rdrop_(1,:)/length(rdrop_a_); 
for nr=1:length(rdrop_a_)-1;
length_study_rdrop_(nr+1,:) = length_study_rdrop_(nr+0,:);
length_study_rdrop_(nr+1,rdrop_study_(nr)) = length_study_rdrop_(nr+1,rdrop_study_(nr))-1;
fraction_study_rdrop_(nr+1,:) = length_study_rdrop_(nr+1,:)/(length(rdrop_a_)-nr); 
end;%for nr=1:length(rdrop_a_)-1;
cra_study_rdrop_ = [zeros(length(rdrop_a_),1) , cumsum(fraction_study_rdrop_,2) , ones(length(rdrop_a_),1)];
rem_r_edge_ = [0 , 0.5*(rem_r_(1:end-1) + rem_r_(2:end+0)) , rem_r_(end)+0.5 ] ;
cra_hsv = colormap('hsv'); clen_hsv = size(cra_hsv,1);
cra = zeros(n_study,3); clen = size(cra,1);
tab=1; dtab = floor(clen_hsv * (1-1/n_study)/2);
for ns=1:n_study;
cra(ns,:) = cra_hsv(tab,:); tab = tab + dtab; if tab>clen_hsv; tab = tab-clen_hsv; end;
end;%for ns=1:n_study;
%figure;
clf;
subplot(2,1,1);
colormap(gca,cra);
ygap = 0.0125;
for ns=1:n_study;
x_ra_{ns} = zeros(5,length(rdrop_a_));
x_ra_{ns}(1,:) = rem_r_edge_(1:end-1);
x_ra_{ns}(2,:) = rem_r_edge_(2:end+0);
x_ra_{ns}(3,:) = rem_r_edge_(2:end+0);
x_ra_{ns}(4,:) = rem_r_edge_(1:end-1);
x_ra_{ns}(5,:) = rem_r_edge_(1:end-1);
y_ra_{ns} = zeros(5,length(rdrop_a_));
y_ra_{ns}(1,:) = cra_study_rdrop_(:,ns+0);
y_ra_{ns}(2,:) = cra_study_rdrop_(:,ns+0);
y_ra_{ns}(3,:) = cra_study_rdrop_(:,ns+1);
y_ra_{ns}(4,:) = cra_study_rdrop_(:,ns+1);
y_ra_{ns}(5,:) = cra_study_rdrop_(:,ns+0);
c_ra_{ns} = max(1,min(clen,round(clen*(ns+0.0)/n_study)))*ones(1,length(rdrop_a_));
hold on; p=patch(x_ra_{ns},y_ra_{ns} + (ns-1)*ygap,c_ra_{ns});set(p,'LineStyle','none','MarkerEdgeColor','none'); hold off;
end;%for ns=1:n_study;
xlim([0,rem_r_(end)+0.5]); ylim([0,1+(n_study-1)*ygap]); set(gca,'Ytick',[]);
xlabel('number of iterations remaining'); title('study distribution');
subplot(2,1,2);
colormap(gca,cra);
ygap = 0.0125;
for ns=1:n_study;
x_ra_{ns} = zeros(5,length(rdrop_a_));
x_ra_{ns}(1,:) = (1:length(rdrop_a_)) - 0.5;
x_ra_{ns}(2,:) = (1:length(rdrop_a_)) + 0.5;
x_ra_{ns}(3,:) = (1:length(rdrop_a_)) + 0.5;
x_ra_{ns}(4,:) = (1:length(rdrop_a_)) - 0.5;
x_ra_{ns}(5,:) = (1:length(rdrop_a_)) - 0.5;
y_ra_{ns} = zeros(5,length(rdrop_a_));
y_ra_{ns}(1,:) = cra_study_rdrop_(:,ns+0);
y_ra_{ns}(2,:) = cra_study_rdrop_(:,ns+0);
y_ra_{ns}(3,:) = cra_study_rdrop_(:,ns+1);
y_ra_{ns}(4,:) = cra_study_rdrop_(:,ns+1);
y_ra_{ns}(5,:) = cra_study_rdrop_(:,ns+0);
c_ra_{ns} = max(1,min(clen,round(clen*(ns+0.0)/n_study)))*ones(1,length(rdrop_a_));
hold on; p=patch(x_ra_{ns},y_ra_{ns} + (ns-1)*ygap,c_ra_{ns});set(p,'LineStyle','none','MarkerEdgeColor','none'); hold off;
end;%for ns=1:n_study;
xlim([0.5,length(rdrop_a_)+0.5]); ylim([0,1+(n_study-1)*ygap]); set(gca,'Ytick',[]);
xlabel('number of patients remaining'); title('study distribution');
set(gcf,'Position',1+[0,0,1024,768]);
print('-djpeg',sprintf('%s/%s_study_stack_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_study_stack_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot study distribution ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
clear cra_hsv clen_hsv cra clen tab dtab;
cra_hsv = colormap('hsv'); clen_hsv = size(cra_hsv,1);
cra = zeros(n_study,3); clen = size(cra,1);
tab=1; dtab = floor(clen_hsv * (1-1/n_study)/2);
for ns=1:n_study;
cra(ns,:) = cra_hsv(tab,:); tab = tab + dtab; if tab>clen_hsv; tab = tab-clen_hsv; end;
end;%for ns=1:n_study;
rcut_ = max(1,min(length(rdrop_a_),floor(length(rdrop_a_)./1.5.^((1:8)-1))));
figure;clf;
for np=1:8;
subplot(2,4,np);
clear iXX_ iXX
rcut = rcut_(np);
rij = rdrop_a_(max(1,length(rdrop_a_)-rcut):end); 
for ns=1:n_study; iXX(ns) = sum(rdrop_study_(max(1,length(rdrop_study_)-rcut):end)==ns); end;
n_prm = 1024*1.0;
iXX_ = zeros(n_study,n_prm);
for ni=1:n_prm;
prm_ = randperm(length(rdrop_study_)); rdrop_study_tmp_ = rdrop_study_(prm_(1:rcut));
for ns=1:n_study;iXX_(ns,ni) = sum(rdrop_study_tmp_==ns); end;
end;%for ni=1:n_prm;
iXX_avg = mean(iXX_,2);
iXX_50 = prctile(iXX_,50,2);
iXX_85 = prctile(iXX_,85,2);
iXX_15 = prctile(iXX_,15,2);
iXX_95 = prctile(iXX_,95,2);
iXX_05 = prctile(iXX_,05,2);
hold on;
for ns=1:n_study;
xvals = ns + [0;1;1;0] - 0.5; yvals = [0;0;1;1]*iXX(ns); p=patch(xvals,yvals,cra(ns,:)); set(p,'LineStyle','none','MarkerEdgeColor','none');
xvals = ns + [0.5;0.5] - 0.5; yvals = [iXX_15(ns),iXX_85(ns)]; l = line(xvals,yvals,'LineWidth',3,'LineStyle','-','Color',[0,0,0]);
xvals = ns + [0.25;0.75] - 0.5; yvals = [iXX_15(ns),iXX_15(ns)]; l = line(xvals,yvals,'LineWidth',3,'LineStyle','-','Color',[0,0,0]);
xvals = ns + [0.25;0.75] - 0.5; yvals = [iXX_85(ns),iXX_85(ns)]; l = line(xvals,yvals,'LineWidth',3,'LineStyle','-','Color',[0,0,0]);
xvals = ns + [0.5;0.5] - 0.5; yvals = [iXX_05(ns),iXX_95(ns)]; l = line(xvals,yvals,'LineWidth',1,'LineStyle','-','Color',[0,0,0]);
xvals = ns + [0.35;0.65] - 0.5; yvals = [iXX_05(ns),iXX_05(ns)]; l = line(xvals,yvals,'LineWidth',1,'LineStyle','-','Color',[0,0,0]);
xvals = ns + [0.35;0.65] - 0.5; yvals = [iXX_95(ns),iXX_95(ns)]; l = line(xvals,yvals,'LineWidth',1,'LineStyle','-','Color',[0,0,0]);
end;%for ns=1:n_study;
hold off;
set(gca,'Xtick',1:n_study); xlim([0,1+n_study]);
xlabel('study index'); ylabel('number of patients');
title(sprintf('patients remaining %d',length(rij)));
end;%for np=1:8;
set(gcf,'Position',1 + [0,0,1024*2,1024*1]);
print('-djpeg',sprintf('%s/%s_study_dist_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_study_dist_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract BD phenotype. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fid = fopen(sprintf('%s/PGC_BIP32b-BD1.20160612.pheno',dir_trunk)); BD1_ = textscan(fid,'%s %s %d','headerlines',1); fclose(fid);
n_patient_BD1 = length(BD1_{1}); BD1_name_ = cell(n_patient_BD1,1); for np=1:n_patient_BD1; BD1_name_{np} = sprintf('%s%s%s',BD1_{1}{np},'&',BD1_{2}{np}); end;%for np=1:n_patient_BD1;
BD1_pheno_ = BD1_{3};
BD1_status_ = zeros(n_patient_F,1); [~,ifam_,iB_] = intersect(fam_name_,BD1_name_,'stable'); BD1_status_(ifam_) = BD1_pheno_(iB_);
fid = fopen(sprintf('%s/PGC_BIP32b-BD2.20160612.pheno',dir_trunk)); BD2_ = textscan(fid,'%s %s %d','headerlines',1); fclose(fid);
n_patient_BD2 = length(BD2_{1}); BD2_name_ = cell(n_patient_BD2,1); for np=1:n_patient_BD2; BD2_name_{np} = sprintf('%s%s%s',BD2_{1}{np},'&',BD2_{2}{np}); end;%for np=1:n_patient_BD2_;
BD2_pheno_ = BD2_{3};
BD2_status_ = zeros(n_patient_F,1); [~,ifam_,iB_] = intersect(fam_name_,BD2_name_,'stable'); BD2_status_(ifam_) = BD2_pheno_(iB_);
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_==nb1 & BD2_status_==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for all patients: ')); disp(num2str(BDh));
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_(rdrop_a_)==nb1 & BD2_status_(rdrop_a_)==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for D-type patients: ')); disp(num2str(BDh));
% phenotype index: ;
% 1 = (BD1->0, BD2->0) ; 
% 2 = (BD1->1, BD2->0) ;
% 3 = (BD1->2, BD2->0) ;
% 4 = (BD1->1, BD2->1) ;
% 5 = (BD1->0, BD2->2) ;
pheno_index_ = zeros(n_patient_F,1);
pheno_index_(find(BD1_status_==0 & BD2_status_==0)) = 1;
pheno_index_(find(BD1_status_==1 & BD2_status_==0)) = 2;
pheno_index_(find(BD1_status_==2 & BD2_status_==0)) = 3;
pheno_index_(find(BD1_status_==1 & BD2_status_==1)) = 4;
pheno_index_(find(BD1_status_==0 & BD2_status_==2)) = 5;
n_pheno = 5;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot BD phenotype stack ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
rem_r_ = interp1(r_rem_,1:length(r_rem_),length(rdrop_a_):-1:1); rem_r_(find(~isfinite(rem_r_)))=iteration_max;
rdrop_pheno_ = pheno_index_(rdrop_a_);
length_pheno_rdrop_ = zeros(length(rdrop_a_),n_pheno);
fraction_pheno_rdrop_ = zeros(length(rdrop_a_),n_pheno);
for ns=1:n_pheno; length_pheno_rdrop_(1,ns) = length(find(rdrop_pheno_==ns)); end;%for ns=1:n_pheno;
fraction_pheno_rdrop_(1,:) = length_pheno_rdrop_(1,:)/length(rdrop_a_); 
for nr=1:length(rdrop_a_)-1;
length_pheno_rdrop_(nr+1,:) = length_pheno_rdrop_(nr+0,:);
length_pheno_rdrop_(nr+1,rdrop_pheno_(nr)) = length_pheno_rdrop_(nr+1,rdrop_pheno_(nr))-1;
fraction_pheno_rdrop_(nr+1,:) = length_pheno_rdrop_(nr+1,:)/(length(rdrop_a_)-nr); 
end;%for nr=1:length(rdrop_a_)-1;
cra_pheno_rdrop_ = [zeros(length(rdrop_a_),1) , cumsum(fraction_pheno_rdrop_,2) , ones(length(rdrop_a_),1)];
rem_r_edge_ = [0 , 0.5*(rem_r_(1:end-1) + rem_r_(2:end+0)) , rem_r_(end)+0.5 ] ;
cra_hsv = colormap('hsv'); clen_hsv = size(cra_hsv,1);
cra = zeros(n_pheno,3); clen = size(cra,1);
tab=1; dtab = floor(clen_hsv * (1-1/n_pheno)/2);
for ns=1:n_pheno;
cra(ns,:) = cra_hsv(tab,:); tab = tab + dtab; if tab>clen_hsv; tab = tab-clen_hsv; end;
end;%for ns=1:n_pheno;
%figure;
clf;
subplot(2,1,1);
colormap(cra);
ygap = 0.0125;
for ns=1:n_pheno;
x_ra_{ns} = zeros(5,length(rdrop_a_));
x_ra_{ns}(1,:) = rem_r_edge_(1:end-1);
x_ra_{ns}(2,:) = rem_r_edge_(2:end+0);
x_ra_{ns}(3,:) = rem_r_edge_(2:end+0);
x_ra_{ns}(4,:) = rem_r_edge_(1:end-1);
x_ra_{ns}(5,:) = rem_r_edge_(1:end-1);
y_ra_{ns} = zeros(5,length(rdrop_a_));
y_ra_{ns}(1,:) = cra_pheno_rdrop_(:,ns+0);
y_ra_{ns}(2,:) = cra_pheno_rdrop_(:,ns+0);
y_ra_{ns}(3,:) = cra_pheno_rdrop_(:,ns+1);
y_ra_{ns}(4,:) = cra_pheno_rdrop_(:,ns+1);
y_ra_{ns}(5,:) = cra_pheno_rdrop_(:,ns+0);
c_ra_{ns} = max(1,min(clen,round(clen*(ns+0.0)/n_pheno)))*ones(1,length(rdrop_a_));
hold on; p=patch(x_ra_{ns},y_ra_{ns} + (ns-1)*ygap,c_ra_{ns});set(p,'LineStyle','none','MarkerEdgeColor','none'); hold off;
end;%for ns=1:n_pheno;
xlim([0,rem_r_(end)+0.5]); ylim([0,1+(n_pheno-1)*ygap]); set(gca,'Ytick',[]);
xlabel('number of iterations remaining'); title('pheno distribution');
subplot(2,1,2);
colormap(cra);
ygap = 0.0125;
for ns=1:n_pheno;
x_ra_{ns} = zeros(5,length(rdrop_a_));
x_ra_{ns}(1,:) = (1:length(rdrop_a_)) - 0.5;
x_ra_{ns}(2,:) = (1:length(rdrop_a_)) + 0.5;
x_ra_{ns}(3,:) = (1:length(rdrop_a_)) + 0.5;
x_ra_{ns}(4,:) = (1:length(rdrop_a_)) - 0.5;
x_ra_{ns}(5,:) = (1:length(rdrop_a_)) - 0.5;
y_ra_{ns} = zeros(5,length(rdrop_a_));
y_ra_{ns}(1,:) = cra_pheno_rdrop_(:,ns+0);
y_ra_{ns}(2,:) = cra_pheno_rdrop_(:,ns+0);
y_ra_{ns}(3,:) = cra_pheno_rdrop_(:,ns+1);
y_ra_{ns}(4,:) = cra_pheno_rdrop_(:,ns+1);
y_ra_{ns}(5,:) = cra_pheno_rdrop_(:,ns+0);
c_ra_{ns} = max(1,min(clen,round(clen*(ns+0.0)/n_pheno)))*ones(1,length(rdrop_a_));
hold on; p=patch(x_ra_{ns},y_ra_{ns} + (ns-1)*ygap,c_ra_{ns});set(p,'LineStyle','none','MarkerEdgeColor','none'); hold off;
end;%for ns=1:n_pheno;
xlim([0.5,length(rdrop_a_)+0.5]); ylim([0,1+(n_pheno-1)*ygap]); set(gca,'Ytick',[]);
xlabel('number of patients remaining'); title('pheno distribution');
set(gcf,'Position',1+[0,0,1024,768]);
print('-djpeg',sprintf('%s/%s_pheno_stack_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_pheno_stack_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot mds distribution ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
xl = 0.1*[-0.5,1]; yl = 0.065*[-1,1];
v1=1;v2=2;
xm = median(mds_sort_(rdrop_a_,v1)); ym = median(mds_sort_(rdrop_a_,v2));
rcut_ = max(1,min(length(rdrop_a_),floor(length(rdrop_a_)./1.5.^((1:8)-1))));
figure;clf;
for np=1:8;
rcut = rcut_(np);
rij = rdrop_a_(max(1,length(rdrop_a_)-rcut):end); 
subplot(2,4,np); colormap(1-colormap('gray')); hold on;
ah = adi_hist2d(mds_sort_(rij,v1),mds_sort_(rij,v2),xl,96,yl,96);
imagesc(log2(1+log2(1+ah))); 
xlg = xlim(); ylg = ylim(); 
xlm = xlg(1) + diff(xlg)*(xm-xl(1))/diff(xl);
ylm = ylg(1) + diff(ylg)*(ym-yl(1))/diff(yl);
l=line(xlg,ylm*[1,1],'LineWidth',0.25,'Color',0.50*[1,1,1]);
l=line(xlm*[1,1],ylg,'LineWidth',0.25,'Color',0.50*[1,1,1]);
xlim(xlg);ylim(ylg);
set(gca,'Xtick',[],'Ytick',[]); axis square; hold off;
title(sprintf('patients %d',length(rij)));
end;%for np=1:8;
set(gcf,'Position',1+[0,0,1024,470]);
print('-djpeg',sprintf('%s/%s_mds_dist_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_mds_dist_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);
figure;clf;
for np=1:8;
rcut = rcut_(np);
rij = rdrop_a_(max(1,length(rdrop_a_)-rcut):end); 
subplot(2,4,np); cra = colormap('hot'); colormap(cra(end:-1:1,:)); hold on;
contourf(log2(1+adi_hist2d(mds_sort_(rij,v1),mds_sort_(rij,v2),xl,32,yl,32)),4); 
xlg = xlim(); ylg = ylim(); 
xlm = xlg(1) + diff(xlg)*(xm-xl(1))/diff(xl);
ylm = ylg(1) + diff(ylg)*(ym-yl(1))/diff(yl);
l=line(xlg,ylm*[1,1],'LineWidth',0.25,'Color',0.50*[1,1,1]);
l=line(xlm*[1,1],ylg,'LineWidth',0.25,'Color',0.50*[1,1,1]);
xlim(xlg);ylim(ylg);
set(gca,'Xtick',[],'Ytick',[]);  axis square; hold off;
title(sprintf('patients %d',length(rij)));
end;%for np=1:8;
set(gcf,'Position',1+[0,0,1024,470]);
print('-djpeg',sprintf('%s/%s_mds_dist_B.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_mds_dist_B.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot trace distribution ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
if (n_finished>2);
QR_ = zeros(n_finished,iteration_max);
QC_ = zeros(n_finished,iteration_max);
for nf=1:n_finished;
ns = trace_finished_ij_(nf); trace_tmp_ = trace_{ns};
QR_(nf,:) = transpose(trace_tmp_(:,4));
QC_(nf,:) = transpose(trace_tmp_(:,5));
end;%for nf=1:n_finished;
%%%%%%%%%%%%%%%% ;
PR_ = zeros(n_finished,iteration_max);
PC_ = zeros(n_finished,iteration_max);
for ni=1:iteration_max;
[~,tmp_ij] = sort(QR_(:,ni),'ascend'); [~,PR_(:,ni)] = sort(tmp_ij,'ascend');
[~,tmp_ij] = sort(QC_(:,ni),'ascend'); [~,PC_(:,ni)] = sort(tmp_ij,'ascend');
end;%for ni=1:iteration_max;
%%%%%%%%%%%%%%%% ;
QR_ = transpose(QR_); QC_ = transpose(QC_);
PR_ = transpose(PR_); PC_ = transpose(PC_);
QR_avg_ = mean(QR_,2); QR_std_ = std(QR_,[],2); QC_avg_ = mean(QC_,2); QC_std_ = std(QC_,[],2);
ZR_ = (QR_ - repmat(QR_avg_,1,n_finished))./repmat(QR_std_,1,n_finished); ZC_ = (QC_ - repmat(QC_avg_,1,n_finished))./repmat(QC_std_,1,n_finished);
%%%%%%%%%%%%%%%% ;
figure;clf;
disp(sprintf(' %% out_trace results; %d pats -x- %d snps ; %d iterations',max(rdrop_b_),max(cdrop_b_),max(t_ret_)));
subplot(2,4,1); plot(max(r_rem_)-r_rem_(t_ret_),ZR_(t_ret_,1),'ro-',max(r_rem_)-r_rem_(t_ret_),ZR_(t_ret_,2:end),'b-'); xlabel('rows eliminated'); ylabel('ZR_','Interpreter','none'); xlim([0,max(max(r_rem_)-r_rem_(t_ret_))+1]);
subplot(2,4,2); plot(max(r_rem_)-r_rem_(t_ret_),PR_(t_ret_,1),'ro-',max(r_rem_)-r_rem_(t_ret_),PR_(t_ret_,2:end),'b-');  xlabel('rows eliminated'); ylabel('PR_','Interpreter','none'); xlim([0,max(max(r_rem_)-r_rem_(t_ret_))+1]);ylim([0,n_finished+1]);
subplot(2,4,3); plot(max(t_ret_)-t_ret_(end:-1:1),ZR_(t_ret_,1),'ro-',max(t_ret_)-t_ret_(end:-1:1),ZR_(t_ret_,2:end),'b-'); xlabel('row iteration number'); ylabel('ZR_','Interpreter','none'); xlim([0,max((t_ret_))+1]);
subplot(2,4,4); plot(max(t_ret_)-t_ret_(end:-1:1),PR_(t_ret_,1),'ro-',max(t_ret_)-t_ret_(end:-1:1),PR_(t_ret_,2:end),'b-'); xlabel('row iteration number'); ylabel('PR_','Interpreter','none'); xlim([0,max((t_ret_))+1]);ylim([0,n_finished+1]);
subplot(2,4,5); plot(max(c_rem_)-c_rem_(t_ret_),ZC_(t_ret_,1),'ro-',max(c_rem_)-c_rem_(t_ret_),ZC_(t_ret_,2:end),'b-'); xlabel('cols eliminated'); ylabel('ZC_','Interpreter','none'); xlim([0,max(max(c_rem_)-c_rem_(t_ret_))+1]);
subplot(2,4,6); plot(max(c_rem_)-c_rem_(t_ret_),PC_(t_ret_,1),'ro-',max(c_rem_)-c_rem_(t_ret_),PC_(t_ret_,2:end),'b-'); xlabel('cols eliminated'); ylabel('PC_','Interpreter','none'); xlim([0,max(max(c_rem_)-c_rem_(t_ret_))+1]);ylim([0,n_finished+1]);
subplot(2,4,7); plot(max(t_ret_)-t_ret_(end:-1:1),ZC_(t_ret_,1),'ro-',max(t_ret_)-t_ret_(end:-1:1),ZC_(t_ret_,2:end),'b-'); xlabel('col iteration number'); ylabel('ZC_','Interpreter','none'); xlim([0,max((t_ret_))+1]);
subplot(2,4,8); plot(max(t_ret_)-t_ret_(end:-1:1),PC_(t_ret_,1),'ro-',max(t_ret_)-t_ret_(end:-1:1),PC_(t_ret_,2:end),'b-'); xlabel('col iteration number'); ylabel('PC_','Interpreter','none'); xlim([0,max((t_ret_))+1]);ylim([0,n_finished+1]);
set(gcf,'Position',1+[0,0,1024*2,768]);
print('-djpeg',sprintf('%s/%s_trace_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_trace_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);
%%%%%%%%%%%%%%%%;
figure;clf;
iteration_alo = max(1,floor(iteration_max*0.05));
iteration_ahi = min(iteration_max-1,floor(iteration_max*0.95));
iteration_avg_ = 1:iteration_ahi; 
dr_ = diff(r_rem_); dc_ = diff(c_rem_); 
dr2_ = transpose(dr_(iteration_avg_))/sum(dr_(iteration_avg_)); 
dc2_ = transpose(dc_(iteration_avg_))/sum(dc_(iteration_avg_));
iteration_top_ = iteration_alo:iteration_ahi;
subplot(2,2,1); title('top-vs-avg ZR_','Interpreter','none');
hold on;
plot(max(ZR_(iteration_top_,2:end),[],1),dr2_*ZR_(iteration_avg_,2:end),'bx');
plot(max(ZR_(iteration_top_,1    ),[],1),dr2_*ZR_(iteration_avg_,1    ),'rx');
hold off; xlabel('top'); ylabel('avg');
subplot(2,2,2); title('top-vs-avg ZC_','Interpreter','none');
hold on;
plot(max(ZC_(iteration_top_,2:end),[],1),dc2_*ZC_(iteration_avg_,2:end),'bx');
plot(max(ZC_(iteration_top_,1    ),[],1),dc2_*ZC_(iteration_avg_,1    ),'rx');
hold off; xlabel('top'); ylabel('avg');
subplot(2,2,3); title('top-vs-avg PR_','Interpreter','none');
hold on;
plot(max(PR_(iteration_top_,2:end),[],1),dr2_*PR_(iteration_avg_,2:end),'bx');
plot(max(PR_(iteration_top_,1    ),[],1),dr2_*PR_(iteration_avg_,1    ),'rx');
hold off; xlabel('top'); ylabel('avg');
subplot(2,2,4); title('top-vs-avg PC_','Interpreter','none');
hold on;
plot(max(PC_(iteration_top_,2:end),[],1),dc2_*PC_(iteration_avg_,2:end),'bx');
plot(max(PC_(iteration_top_,1    ),[],1),dc2_*PC_(iteration_avg_,1    ),'rx');
hold off; xlabel('top'); ylabel('avg');
set(gcf,'Position',1+[0,0,1024*1.5,768]);
print('-djpeg',sprintf('%s/%s_trace_B.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_trace_B.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);
end;%if (n_finished>2);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot colored scatterplot using ZR_ ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
if (n_finished>2);
iteration_alo = max(1,floor(iteration_max*0.05));
iteration_ahi = min(iteration_max-1,floor(iteration_max*0.95));
iteration_avg_ = 1:iteration_ahi; 
dr_ = diff(r_rem_); dc_ = diff(c_rem_); 
dr2_ = transpose(dr_(iteration_avg_))/sum(dr_(iteration_avg_)); 
dc2_ = transpose(dc_(iteration_avg_))/sum(dc_(iteration_avg_));
iteration_top_ = iteration_alo:iteration_ahi;
tr_avg_s0000 = dr2_*ZR_(iteration_avg_,1);
tr_avg_ = dr2_*ZR_(iteration_avg_,2:end);
tr_avg_p_ = zeros(n_finished-1,1);
tr_top_s0000 = max(ZR_(iteration_top_,1),[],1); disp(tr_top_s0000); %tr_top_s0000 = min(3.25,tr_top_s0000);
tr_top_ = max(ZR_(iteration_top_,2:end),[],1);
tr_top_p_ = zeros(n_finished-1,1);
p_ra_ = zeros(n_finished-1,1);
for np=(1:n_finished-1);
tr_top_p_(np) = (length(find(tr_top_>tr_top_(np))) + 0.5*length(find(tr_top_==tr_top_(np))))/(n_finished-1);
tr_avg_p_(np) = (length(find(tr_avg_>tr_avg_(np))) + 0.5*length(find(tr_avg_==tr_avg_(np))))/(n_finished-1);
tau_tmp = min([tr_top_p_(np),tr_avg_p_(np)]); tau_tmp = max(0.5/(n_finished-1),tau_tmp);
ls_rm = find(tr_top_(:)>=prctile(tr_top_(:),100*(1-tau_tmp)));
ls_ra = find(tr_avg_(:)>=prctile(tr_avg_(:),100*(1-tau_tmp)));
p_ra_(np) = length(unionall({ls_rm,ls_ra}))/(n_finished-1);
end;%for np=(1:n_finished-1);
tr_top_s0000_p = (length(find(tr_top_>tr_top_s0000)) + 0.5*length(find(tr_top_==tr_top_s0000)))/(n_finished-1);
tr_avg_s0000_p = (length(find(tr_avg_>tr_avg_s0000)) + 0.5*length(find(tr_avg_==tr_avg_s0000)))/(n_finished-1);
tau_tmp = min([tr_top_s0000_p,tr_avg_s0000_p]); tau_tmp = max(0.5/(n_finished-1),tau_tmp);
ls_rm = find(tr_top_(:)>=prctile(tr_top_(:),100*(1-tau_tmp)));
ls_ra = find(tr_avg_(:)>=prctile(tr_avg_(:),100*(1-tau_tmp)));
p_s0000 = length(unionall({ls_rm,ls_ra}))/(n_finished-1);
disp(sprintf('p_s0000 %0.3f',p_s0000));
figure;
hold on;
l10plim=[0,2];
cmap = colormap('jet'); clen = size(cmap,1); %cmap = cmap(end:-1:1,:);
Msize1 = 25; Msize2 = 35;
for np=1:(n_finished-1);
nc = max(1,min(clen,floor(clen*((-log10(p_ra_(np))-min(l10plim))/diff(l10plim)))));
plot(tr_top_(np),tr_avg_(np),'.','Color',cmap(nc,:),'MarkerSize',Msize1);
end;%for np=1:(n_finished-1);
for no_flag=0:0;%for no_flag=0:NO-1;
plot(tr_top_s0000,tr_avg_s0000,'x','Color',[0,0,0],'MarkerSize',Msize2);
plot(tr_top_s0000,tr_avg_s0000,'o','Color',[0,0,0],'MarkerSize',Msize2);
end;%for no_flag=0:NO-1;
hold off;
% use for PGC_cl3_D_m3;
xlim([-1.50,+3.25]);ylim([-1.75,+2.75]);
disp(sprintf('xlim %0.2f %0.2f ylim %0.2f %0.2f',xlim(),ylim()));
xlabel('row Z-score (top)'); ylabel('row Z-score (avg)'); 
title('scatterplot of distribution of top vs avg: bicluster (x) and permutations (dots)');
%set(gca,'Xtick',[],'Ytick',[]);
axis equal;
set(gcf,'Position',1+[0,0,1024,1024]);
print('-djpeg',sprintf('%s/%s_pval_scatter_A.jpg',dir_out_s0000,string_name_s0000));
print('-depsc',sprintf('%s/%s_pval_scatter_A.eps',dir_out_s0000,string_name_s0000));
drawnow();pause(1);
end;%if (n_finished>2);

disp('returning');return;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%{

 %}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%{
  % plot scatterplot of mds-components colored by rdrop_a_. ;
  nf=1;
  figure;clf;
  v1=1;v2=2;v3=3;cra = colormap('jet'); ncra=size(cra,1);
  hold on;
  for nr=1:length(rdrop_a_);
  nb = max(1,min(ncra,1+floor(ncra*nr/length(rdrop_a_))));
  plot3(mds_sort_(rdrop_a_(nr),v1),mds_sort_(rdrop_a_(nr),v2),mds_sort_(rdrop_a_(nr),v3),'.','Color',cra(nb,:));
  end;%for nr=1:length(rdrop_a_);
  hold off;
  axis vis3d;
 %}

%{
  % check consistency of row masks ;
  for ns=1:n_study; 
  tmpchar = sprintf('/home/arangan/dir_PGC_20180304/dir_PGC_cl3_maf01/PGC_cl3_maf01_mr_A_%.2d.b16',ns); 
  [~,nrows,ncols] = tutorial_binary_getsize(tmpchar); 
  mr_A_tmp = tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols); 
  tmpchar = sprintf('/home/arangan/dir_PGC_20180304/dir_PGC_cl3_maf01/PGC_cl3_maf01_mr_Z_%.2d.b16',ns); 
  [~,nrows,ncols] = tutorial_binary_getsize(tmpchar); 
  mr_Z_tmp = tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols); 
  disp(num2str([ns , sum(mr_A_tmp>0) , sum(mr_Z_tmp>0) , sum((mr_A_tmp>0) & (mr_Z_tmp>0)) ])); 
  end;%for ns=1:n_study; 
  %}

