if (~exist('flag_BD','var') | flag_BD==1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract BD phenotype. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fid = fopen(sprintf('%s/PGC_BIP32b-BD1.20160612.pheno',dir_trunk)); BD1_ = textscan(fid,'%s %s %d','headerlines',1); fclose(fid);
n_patient_BD1 = length(BD1_{1}); BD1_name_ = cell(n_patient_BD1,1); for np=1:n_patient_BD1; BD1_name_{np} = sprintf('%s%s%s',BD1_{1}{np},'&',BD1_{2}{np}); end;%for np=1:n_patient_BD1;
BD1_pheno_ = BD1_{3};
BD1_status_ = zeros(n_patient_F,1); [~,ifam_,iB_] = intersect(fam_name_,BD1_name_,'stable'); BD1_status_(ifam_) = BD1_pheno_(iB_);
fid = fopen(sprintf('%s/PGC_BIP32b-BD2.20160612.pheno',dir_trunk)); BD2_ = textscan(fid,'%s %s %d','headerlines',1); fclose(fid);
n_patient_BD2 = length(BD2_{1}); BD2_name_ = cell(n_patient_BD2,1); for np=1:n_patient_BD2; BD2_name_{np} = sprintf('%s%s%s',BD2_{1}{np},'&',BD2_{2}{np}); end;%for np=1:n_patient_BD2_;
BD2_pheno_ = BD2_{3};
BD2_status_ = zeros(n_patient_F,1); [~,ifam_,iB_] = intersect(fam_name_,BD2_name_,'stable'); BD2_status_(ifam_) = BD2_pheno_(iB_);
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_==nb1 & BD2_status_==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for all patients: ')); disp(num2str(BDh));
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_(rdrop_a_)==nb1 & BD2_status_(rdrop_a_)==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for D-type patients: ')); disp(num2str(BDh));
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_(setdiff(1:n_patient_F,rdrop_a_))==nb1 & BD2_status_(setdiff(1:n_patient_F,rdrop_a_))==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for X-type patients: ')); disp(num2str(BDh));
% phenotype index: ;
% 1 = (BD1->0, BD2->0) ; 
% 2 = (BD1->1, BD2->0) ;
% 3 = (BD1->2, BD2->0) ;
% 4 = (BD1->1, BD2->1) ;
% 5 = (BD1->0, BD2->2) ;
pheno_index_ = zeros(n_patient_F,1);
pheno_index_(find(BD1_status_==0 & BD2_status_==0)) = 1;
pheno_index_(find(BD1_status_==1 & BD2_status_==0)) = 2;
pheno_index_(find(BD1_status_==2 & BD2_status_==0)) = 3;
pheno_index_(find(BD1_status_==1 & BD2_status_==1)) = 4;
pheno_index_(find(BD1_status_==0 & BD2_status_==2)) = 5;
n_pheno = 5;
end;%if (~exist('flag_BD','var') | flag_BD==1);
