%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% run lisa_setprefix_ver2 first. ;
% run lisa_setnames_ver2 first. ;
% run lisa_xdropextract_ver2 first. ;
% run lisa_loadmdsfambim_ver2 first. ;
% run lisa_mxcheck_ver2 first. ;
% run lisa_studyindex_ver2 first. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract traces (original stored in s0000) ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
trace_found_ = zeros(n_shuffle+1,1);
for (nshuffle=0:n_shuffle);
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('dex',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('lak',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'dex')); string_name_r0 = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('dex',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,0,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name_r0 = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('lak',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,0,nshuffle)); end;
trace_found_(1+nshuffle)=0;
%%%%%%%%;
if (trace_found_(1+nshuffle)==0);
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',dir_out,string_name);
if (exist(fname_tmp,'file')); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); trace_found_(1+nshuffle)=1; end;
end;%if (trace_found_(1+nshuffle)==0);
%%%%%%%%;
if (trace_found_(1+nshuffle)==0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',dir_out_trace,nshuffle);
if (exist(fname_tmp,'file')); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); trace_found_(1+nshuffle)=1; end;
end;%if (trace_found_(1+nshuffle)==0);
%%%%%%%%;
if (trace_found_(1+nshuffle)==0 & nshuffle>0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',dir_out_trace_r0,nshuffle);
if (exist(fname_tmp,'file')); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); trace_found_(1+nshuffle)=1; end;
end;%if (trace_found_(1+nshuffle)==0 & nshuffle>0);
%%%%%%%%;
end;%for (nshuffle=0:n_shuffle);
disp(sprintf(' %% found %d/%d traces',sum(trace_found_),1+n_shuffle));
if (trace_found_(1)~=1); disp(sprintf(' %% Warning! trace for original data not found!')); end;
%%%%%%%%%%%%%%%%;
nshuffle=0;
fname_tmp = sprintf('%s/out_xdrop_a.txt',dir_out_s0000);
out_xdrop_a_ = textread(fname_tmp); rdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,1)>-1),1)+1; cdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,2)>-1),2)+1;
fname_tmp = sprintf('%s/out_xdrop_b.txt',dir_out_s0000);
out_xdrop_b_ = textread(fname_tmp); rdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,1)>-1),1)+1; cdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,2)>-1),2)+1;
%%%%%%%%%%%%%%%%;
n_shuffle_found = sum(trace_found_)-1;
tmp_ij = find(trace_found_);
trace_ = cell(1+n_shuffle_found,1);
for nshuffle=0:n_shuffle_found;
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('dex',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,tmp_ij(1+nshuffle)-1)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('lak',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,tmp_ij(1+nshuffle)-1)); end;
if (strcmp(flag_dex_vs_lak,'dex')); string_name_r0 = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('dex',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,0,tmp_ij(1+nshuffle)-1)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name_r0 = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver13('lak',maf_lo_threshold,maf_hi_threshold,mc_string,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,0,tmp_ij(1+nshuffle)-1)); end;
flag_found=0;
%%%%%%%%;
if (flag_found==0);
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',dir_out,string_name);
if (exist(fname_tmp,'file')); trace_{1+nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0);
%%%%%%%%;
if (flag_found==0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',dir_out_trace,nshuffle);
if (exist(fname_tmp,'file')); trace_{1+nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0);
%%%%%%%%;
if (flag_found==0 & nshuffle>0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',dir_out_trace_r0,nshuffle);
if (exist(fname_tmp,'file')); trace_{1+nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0 & nshuffle>0);
%%%%%%%%;
end;%for nshuffle=0:n_shuffle_found;
%%%%%%%%%%%%%%%%;
trace_tmp_ = trace_{1};
[iteration_max,n_cols] = size(trace_tmp_);
if (iteration_max==1 | n_cols~=6); disp(sprintf(' %% Warning! iteration_max %d n_cols %d in first trace',iteration_max,n_cols)); end;
niter_ = trace_tmp_(:,1);
r_rem_ = (trace_tmp_(:,2));
c_rem_ = (trace_tmp_(:,3));
t_rem_ = (trace_tmp_(:,6)); t_ret_ = find(t_rem_>=Ireq);
%%%%%%%%%%%%%%%%;
trace_finished_ = zeros(1+n_shuffle_found,1); 
for nshuffle=0:n_shuffle_found;
trace_tmp_ = trace_{1+nshuffle};
[rtmp,ctmp] = size(trace_tmp_);
if (rtmp==iteration_max & ctmp==6); trace_finished_(1+nshuffle)=1; else trace_finished_(1+nshuffle)=0; end;
end;%for nshuffle=0:n_shuffle_found;
%%%%%%%%%%%%%%%%;
trace_finished_ij_ = find(trace_finished_);
n_finished = length(trace_finished_ij_); disp(sprintf(' %% found n_finished %d',n_finished));
