function l = lisa_struct_trace_ver0(l);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract traces (original stored in s0) ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
l.trace_found_ = zeros(l.n_shuffle+1,1);
for (nshuffle=0:l.n_shuffle);
l.nshuffle = nshuffle;
l = lisa_struct_xfix_ver0(l);
string_name = sprintf('%s_%s',l.string_prefix,l.output_string);
string_name_r0 = sprintf('%s_%s',l.string_prefix,l.output_string_r0);
l.trace_found_(1+l.nshuffle)=0;
%%%%%%%%;
if (l.trace_found_(1+l.nshuffle)==0);
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',l.dir_out,string_name);
if (exist(fname_tmp,'file')); if (l.verbose>0); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); end; l.trace_found_(1+l.nshuffle)=1; end;
end;%if (l.trace_found_(1+l.nshuffle)==0);
%%%%%%%%;
if (l.trace_found_(1+l.nshuffle)==0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',l.dir_out_trace,l.nshuffle);
if (exist(fname_tmp,'file')); if (l.verbose>0); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); end; l.trace_found_(1+l.nshuffle)=1; end;
end;%if (l.trace_found_(1+l.nshuffle)==0);
%%%%%%%%;
if (l.trace_found_(1+l.nshuffle)==0 & l.nshuffle>0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',l.dir_out_trace_r0,l.nshuffle);
if (exist(fname_tmp,'file')); if (l.verbose>0); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); end; l.trace_found_(1+l.nshuffle)=1; end;
end;%if (l.trace_found_(1+l.nshuffle)==0 & l.nshuffle>0);
%%%%%%%%;
end;%for (l.nshuffle=0:l.n_shuffle);
l.nshuffle=0;
if (l.verbose>0); disp(sprintf(' %% found %d/%d traces',sum(l.trace_found_),1+l.n_shuffle)); end;
if (l.trace_found_(1)~=1); disp(sprintf(' %% Warning! trace for original data not found!')); end; 
%%%%%%%%%%%%%%%%;
l.n_shuffle_found = sum(l.trace_found_)-1;
tmp_ij = find(l.trace_found_);
l.trace_ = cell(1+l.n_shuffle_found,1);
for nshuffle=0:l.n_shuffle_found;
l.nshuffle = nshuffle;
l = lisa_struct_xfix_ver0(l);
string_name = sprintf('%s_%s',l.string_prefix,l.output_string);
string_name_r0 = sprintf('%s_%s',l.string_prefix,l.output_string_r0);
flag_found=0;
%%%%%%%%;
if (flag_found==0);
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',l.dir_out,string_name);
if (exist(fname_tmp,'file')); l.trace_{1+l.nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0);
%%%%%%%%;
if (flag_found==0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',l.dir_out_trace,l.nshuffle);
if (exist(fname_tmp,'file')); l.trace_{1+l.nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0);
%%%%%%%%;
if (flag_found==0 & l.nshuffle>0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',l.dir_out_trace_r0,l.nshuffle);
if (exist(fname_tmp,'file')); l.trace_{1+l.nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0 & l.nshuffle>0);
%%%%%%%%;
end;%for l.nshuffle=0:l.n_shuffle_found;
l.nshuffle=0;
%%%%%%%%%%%%%%%%;
trace_tmp_ = l.trace_{1};
[l.n_iteration,n_cols] = size(trace_tmp_);
if (l.n_iteration==1 | n_cols~=6); disp(sprintf(' %% Warning! l.n_iteration %d n_cols %d in first trace',l.n_iteration,n_cols)); end;
l.niter_ = (trace_tmp_(:,1));
l.r_rem_ = (trace_tmp_(:,2));
l.c_rem_ = (trace_tmp_(:,3));
l.t_rem_ = (trace_tmp_(:,6)); l.t_ret_ = find(l.t_rem_>=l.Ireq);
%%%%%%%%%%%%%%%%;
l.trace_finished_ = zeros(1+l.n_shuffle_found,1); 
for nshuffle=0:l.n_shuffle_found;
l.nshuffle = nshuffle;
trace_tmp_ = l.trace_{1+l.nshuffle};
[rtmp,ctmp] = size(trace_tmp_);
if (rtmp==l.n_iteration & ctmp==6); l.trace_finished_(1+l.nshuffle)=1; else l.trace_finished_(1+l.nshuffle)=0; end;
end;%for l.nshuffle=0:l.n_shuffle_found;
l.nshuffle=0;
%%%%%%%%%%%%%%%%;
l.trace_finished_ij_ = find(l.trace_finished_);
l.n_trace_finished = length(l.trace_finished_ij_); if (l.verbose>0); disp(sprintf(' %% found n_trace_finished %d',l.n_trace_finished)); end;
