function [lisa_arm1,lisa_arm2] = lisa_struct_pca_collect_ver2(specification) ;
%{

 %try: ;
  dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20190328');
  dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c_dev');
  flag_dex_vs_lak = 'dex'; %<-- differentially expressed clustering. ;
  cl_num_arm1 = 4; cl_num_arm2 = 1; %<-- train on platform 4, replicate on platform 1. ;
  cl_num_arm1_mc_A = []; cl_num_arm1_mr_A_full_ = []; cl_num_arm1_mr_Z_full_ = []; cl_num_arm1_string = []; 
  cl_num_arm2_mc_A = []; cl_num_arm2_mr_A_full_ = []; cl_num_arm2_mr_Z_full_ = []; cl_num_arm2_string = []; 
  flag_reverse = 0; %<-- forward bicluster (i.e., case-specific). ;
  gamma = [0.004]; %<-- gamma is the fraction eliminated per iteration. 000 implies a single patient eliminated per iteration. ;
  B_MLT = 34; n_mds = 20; %<-- accurate to 2^(-34), 20 total mds components (but only 2 used). ;
  mr_string_arm1 = '';mc_string_arm1 = ''; mr_string_arm2 = '';mc_string_arm2 = ''; %<-- No special mc_string. ;
  %mr_string_arm1 = 'BDX';mc_string_arm1 = 'BDX'; mr_string_arm2 = 'BDX';mc_string_arm2 = 'BDX'; %<-- No special mc_string. ;
  for n_maf = 5; %for n_maf = [1,6,4,5];%for n_maf = [1,6,4,5]; %<-- minor-allele-frequency cutoff 25-50 ;
  n_cov = 2; %<-- 2 covariates (mds-components) used, repeated twice. ;
  n_scramble = 0; n_shuffle = 0; %<-- no previous bicluster extracted/scrambled first, no random shuffling. ;
  flag_rerun=0; %<-- regenerate mat-file.; 
  pca_b_mlt = 44; pca_tolerance = 1e-2; pca_rank = 2;
  n_iteration_stride = 25/2;
  for n_scramble=0;
  for flag_reverse = [0];%for flag_reverse = [0:1];
  for cl_num_arm2 = 1;%for cl_num_arm2 = 1:3;
  specification = struct();
  specification.dir_trunk = dir_trunk;
  specification.dir_code = dir_code;
  specification.mr_string_arm1 = mr_string_arm1;
  specification.mc_string_arm1 = mc_string_arm1;
  specification.mr_string_arm2 = mr_string_arm2;
  specification.mc_string_arm2 = mc_string_arm2;
  specification.cl_num_arm1 = cl_num_arm1;
  specification.cl_num_arm1_mc_A = cl_num_arm1_mc_A;
  specification.cl_num_arm1_mr_A_full_ = cl_num_arm1_mr_A_full_;
  specification.cl_num_arm1_mr_Z_full_ = cl_num_arm1_mr_Z_full_;
  specification.cl_num_arm1_string = cl_num_arm1_string;
  specification.cl_num_arm2 = cl_num_arm2;
  specification.cl_num_arm2_mc_A = cl_num_arm2_mc_A;
  specification.cl_num_arm2_mr_A_full_ = cl_num_arm2_mr_A_full_;
  specification.cl_num_arm2_mr_Z_full_ = cl_num_arm2_mr_Z_full_;
  specification.cl_num_arm2_string = cl_num_arm2_string;
  specification.flag_dex_vs_lak = flag_dex_vs_lak;
  specification.gamma = gamma;
  specification.B_MLT = B_MLT;
  specification.n_mds = n_mds;
  specification.flag_reverse = flag_reverse;
  specification.n_maf = n_maf;
  specification.n_cov = n_cov;
  specification.n_scramble = n_scramble;
  specification.n_shuffle = n_shuffle;
  specification.flag_rerun = flag_rerun;
  specification.pca_b_mlt = pca_b_mlt;
  specification.pca_tolerance = pca_tolerance;
  specification.pca_rank = pca_rank;
  specification.n_iteration_stride = n_iteration_stride;
  lisa_struct_pca_collect_ver2(specification) ;
  end;%for cl_num_arm2 = 1:4;
  end;%for flag_reverse = 0:1;
  end;%for n_scramble=0:1;
  end;%for n_maf = [1,4,5,6]; %<-- minor-allele-frequency cutoff 25-50 ;

  %%%%%%%%;
  % exclude some columns from cl1. ;
  %%%%%%%%;
  dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20190328');
  dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c_dev');
  tmpchar_cap = sprintf('%s/dir_misc/p25_cap_cl%d_cl%d_mc_A_.b16',dir_trunk,1,3);
  tmp_mc_A_ = (tutorial_binary_uncompress(tmpchar_cap)>0);
  flag_dex_vs_lak = 'dex'; %<-- differentially expressed clustering. ;
  cl_num_arm1 = 4; cl_num_arm2 = 1; %<-- train on platform 4, replicate on platform 1. ;
  cl_num_arm1_mc_A = []; cl_num_arm1_mr_A_full_ = []; cl_num_arm1_mr_Z_full_ = []; cl_num_arm1_string = []; 
  cl_num_arm2_mc_A = tmp_mc_A_; cl_num_arm2_mr_A_full_ = []; cl_num_arm2_mr_Z_full_ = []; cl_num_arm2_string = 'cap3'; 
  flag_reverse = 0; %<-- forward bicluster (i.e., case-specific). ;
  gamma = [0.004]; %<-- gamma is the fraction eliminated per iteration. 000 implies a single patient eliminated per iteration. ;
  B_MLT = 34; n_mds = 20; mr_string_arm1 = '';mc_string_arm1 = ''; mr_string_arm2 = '';mc_string_arm2 = ''; %<-- accurate to 2^(-34), 20 total mds components (but only 2 used). ; No special mc_string. ;
  n_maf = 5; n_cov = 2; %<-- minor-allele-frequency cutoff 25-50, 2 covariates (mds-components) used, repeated twice. ;
  n_scramble = 1; n_shuffle = 0; %<-- no previous bicluster extracted/scrambled first, no random shuffling. ;
  flag_rerun=1; %<-- regenerate mat-file.; 
  pca_b_mlt = 44; pca_tolerance = 1e-2; pca_rank = 2;
  n_iteration_stride = 25/2;
  for flag_reverse = 0;
  for cl_num_arm2 = 1;
  specification = struct();
  specification.dir_trunk = dir_trunk;
  specification.dir_code = dir_code;
  specification.mr_string_arm1 = mr_string_arm1;
  specification.mc_string_arm1 = mc_string_arm1;
  specification.mr_string_arm2 = mr_string_arm2;
  specification.mc_string_arm2 = mc_string_arm2;
  specification.cl_num_arm1 = cl_num_arm1;
  specification.cl_num_arm1_mc_A = cl_num_arm1_mc_A;
  specification.cl_num_arm1_mr_A_full_ = cl_num_arm1_mr_A_full_;
  specification.cl_num_arm1_mr_Z_full_ = cl_num_arm1_mr_Z_full_;
  specification.cl_num_arm1_string = cl_num_arm1_string;
  specification.cl_num_arm2 = cl_num_arm2;
  specification.cl_num_arm2_mc_A = cl_num_arm2_mc_A;
  specification.cl_num_arm2_mr_A_full_ = cl_num_arm2_mr_A_full_;
  specification.cl_num_arm2_mr_Z_full_ = cl_num_arm2_mr_Z_full_;
  specification.cl_num_arm2_string = cl_num_arm2_string;
  specification.flag_dex_vs_lak = flag_dex_vs_lak;
  specification.gamma = gamma;
  specification.B_MLT = B_MLT;
  specification.n_mds = n_mds;
  specification.flag_reverse = flag_reverse;
  specification.n_maf = n_maf;
  specification.n_cov = n_cov;
  specification.n_scramble = n_scramble;
  specification.n_shuffle = n_shuffle;
  specification.flag_rerun = flag_rerun;
  specification.pca_b_mlt = pca_b_mlt;
  specification.pca_tolerance = pca_tolerance;
  specification.pca_rank = pca_rank;
  specification.n_iteration_stride = n_iteration_stride;
  lisa_struct_pca_collect_ver2(specification) ;
  end;%for cl_num_arm2 = 1:4;
  end;%for flag_reverse = 0:1;

  %%%%%%%%;
  % BX1. ;
  %%%%%%%%;
  dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20190328');
  dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c_dev');
  flag_dex_vs_lak = 'dex'; %<-- differentially expressed clustering. ;
  cl_num_arm1 = 1; cl_num_arm2 = 4; %<-- train on platform 4, replicate on platform 1. ;
  cl_num_arm1_mc_A = []; cl_num_arm1_mr_A_full_ = []; cl_num_arm1_mr_Z_full_ = []; cl_num_arm1_string = []; 
  cl_num_arm2_mc_A = []; cl_num_arm2_mr_A_full_ = []; cl_num_arm2_mr_Z_full_ = []; cl_num_arm2_string = []; 
  flag_reverse = 1; %<-- forward bicluster (i.e., case-specific). ;
  gamma = [0.004]; %<-- gamma is the fraction eliminated per iteration. 000 implies a single patient eliminated per iteration. ;
  B_MLT = 34; n_mds = 20; mr_string_arm1 = '';mc_string_arm1 = ''; mr_string_arm2 = '';mc_string_arm2 = ''; %<-- accurate to 2^(-34), 20 total mds components (but only 2 used). ; No special mc_string. ;
  n_maf = 5; n_cov = 2; %<-- minor-allele-frequency cutoff 25-50, 2 covariates (mds-components) used, repeated twice. ;
  n_scramble = 0; n_shuffle = 0; %<-- no previous bicluster extracted/scrambled first, no random shuffling. ;
  flag_rerun=0; %<-- regenerate mat-file.; 
  pca_b_mlt = 44; pca_tolerance = 1e-2; pca_rank = 2;
  n_iteration_stride = 25/2;
  mr_string_arm1 = 'BX1'; mc_string_arm1 = 'BX1';
  mr_string_arm2 = ''; mc_string_arm2 = '';
  for flag_reverse = 1;
  for cl_num_arm2 = 4;
  specification = struct();
  specification.dir_trunk = dir_trunk;
  specification.dir_code = dir_code;
  specification.mr_string_arm1 = mr_string_arm1;
  specification.mc_string_arm1 = mc_string_arm1;
  specification.mr_string_arm2 = mr_string_arm2;
  specification.mc_string_arm2 = mc_string_arm2;
  specification.cl_num_arm1 = cl_num_arm1;
  specification.cl_num_arm1_mc_A = cl_num_arm1_mc_A;
  specification.cl_num_arm1_mr_A_full_ = cl_num_arm1_mr_A_full_;
  specification.cl_num_arm1_mr_Z_full_ = cl_num_arm1_mr_Z_full_;
  specification.cl_num_arm1_string = cl_num_arm1_string;
  specification.cl_num_arm2 = cl_num_arm2;
  specification.cl_num_arm2_mc_A = cl_num_arm2_mc_A;
  specification.cl_num_arm2_mr_A_full_ = cl_num_arm2_mr_A_full_;
  specification.cl_num_arm2_mr_Z_full_ = cl_num_arm2_mr_Z_full_;
  specification.cl_num_arm2_string = cl_num_arm2_string;
  specification.flag_dex_vs_lak = flag_dex_vs_lak;
  specification.gamma = gamma;
  specification.B_MLT = B_MLT;
  specification.n_mds = n_mds;
  specification.flag_reverse = flag_reverse;
  specification.n_maf = n_maf;
  specification.n_cov = n_cov;
  specification.n_scramble = n_scramble;
  specification.n_shuffle = n_shuffle;
  specification.flag_rerun = flag_rerun;
  specification.pca_b_mlt = pca_b_mlt;
  specification.pca_tolerance = pca_tolerance;
  specification.pca_rank = pca_rank;
  specification.n_iteration_stride = n_iteration_stride;
  lisa_struct_pca_collect_ver2(specification) ;
  end;%for cl_num_arm2 = 1:4;
  end;%for flag_reverse = 0:1;

 %}

dir_trunk = specification.dir_trunk;
dir_code = specification.dir_code;
mr_string_arm1 = specification.mr_string_arm1;
mc_string_arm1 = specification.mc_string_arm1;
cl_num_arm1 = specification.cl_num_arm1;
cl_num_arm1_mc_A = specification.cl_num_arm1_mc_A;
cl_num_arm1_mr_A_full_ = specification.cl_num_arm1_mr_A_full_;
cl_num_arm1_mr_Z_full_ = specification.cl_num_arm1_mr_Z_full_;
cl_num_arm1_string = specification.cl_num_arm1_string;
mr_string_arm2 = specification.mr_string_arm2;
mc_string_arm2 = specification.mc_string_arm2;
cl_num_arm2 = specification.cl_num_arm2;
cl_num_arm2_mc_A = specification.cl_num_arm2_mc_A;
cl_num_arm2_mr_A_full_ = specification.cl_num_arm2_mr_A_full_;
cl_num_arm2_mr_Z_full_ = specification.cl_num_arm2_mr_Z_full_;
cl_num_arm2_string = specification.cl_num_arm2_string;
flag_dex_vs_lak = specification.flag_dex_vs_lak;
gamma = specification.gamma;
B_MLT = specification.B_MLT;
n_mds = specification.n_mds;
flag_reverse = specification.flag_reverse;
n_maf = specification.n_maf;
n_cov = specification.n_cov;
n_scramble = specification.n_scramble;
n_shuffle = specification.n_shuffle;
flag_rerun = specification.flag_rerun;
pca_b_mlt = specification.pca_b_mlt;
pca_tolerance = specification.pca_tolerance;
pca_rank = specification.pca_rank;
n_iteration_stride = specification.n_iteration_stride;

%%%%%%%%;
lisa_arm1 = lisa_struct_make_ver0(mr_string_arm1,mc_string_arm1,cl_num_arm1,flag_dex_vs_lak,gamma,B_MLT,n_mds,flag_reverse,n_maf,n_cov,n_scramble,n_shuffle) ;
lisa_arm1 = lisa_struct_prefix_ver0(lisa_arm1,dir_code,dir_trunk); 
lisa_arm1.nshuffle = 0;  lisa_arm1 = lisa_struct_names_ver0(lisa_arm1); 
lisa_arm1 = lisa_struct_xdrop_ver0(lisa_arm1); lisa_arm1 = lisa_struct_mdsfam_ver0(lisa_arm1); 
%lisa_arm1 = lisa_struct_bim_ver0(lisa_arm1); %<-- this is large and takes a while to load. ;
lisa_arm1 = lisa_struct_mx_ver0(lisa_arm1); lisa_arm1 = lisa_struct_studyindex_ver0(lisa_arm1); 
lisa_arm1 = lisa_struct_trace_ver0(lisa_arm1);
%%%%%%%%;
lisa_arm2 = lisa_struct_make_ver0(mr_string_arm2,mc_string_arm2,cl_num_arm2,flag_dex_vs_lak,gamma,B_MLT,n_mds,flag_reverse,n_maf,n_cov,0,n_shuffle) ;
lisa_arm2 = lisa_struct_prefix_ver0(lisa_arm2,dir_code,dir_trunk); 
lisa_arm2.nshuffle = 0;  lisa_arm2 = lisa_struct_names_ver0(lisa_arm2); 
lisa_arm2 = lisa_struct_xdrop_ver0(lisa_arm2); lisa_arm2 = lisa_struct_mdsfam_ver0(lisa_arm2); 
%lisa_arm2 = lisa_struct_bim_ver0(lisa_arm2); %<-- this is large and takes a while to load. ;
lisa_arm2 = lisa_struct_mx_ver0(lisa_arm2); lisa_arm2 = lisa_struct_studyindex_ver0(lisa_arm2); 
lisa_arm2 = lisa_struct_trace_ver0(lisa_arm2);
%%%%%%%%;

%%%%%%%%;
lisa_arm1.dir_out_s0_pca = sprintf('%s/dir_pca_trn%d%s_tst%d%s',lisa_arm1.dir_out_s0,lisa_arm1.cl_num,cl_num_arm1_string,lisa_arm2.cl_num,cl_num_arm2_string);
if (~exist(lisa_arm1.dir_out_s0_pca,'dir')); disp(sprintf(' %% mkdir %s',lisa_arm1.dir_out_s0_pca)); mkdir(lisa_arm1.dir_out_s0_pca); end;
%%%%%%%%;
lisa_arm1.dir_out_s0_pca_jpg = sprintf('%s/dir_pca_jpg',lisa_arm1.dir_out_s0_pca);
if (~exist(lisa_arm1.dir_out_s0_pca_jpg,'dir')); disp(sprintf(' %% creating %s',lisa_arm1.dir_out_s0_pca_jpg)); mkdir(lisa_arm1.dir_out_s0_pca_jpg); end;
%%%%%%%%;
lisa_arm1.dir_out_s0_pca_b16 = sprintf('%s/dir_pca_b16',lisa_arm1.dir_out_s0_pca);
if (~exist(lisa_arm1.dir_out_s0_pca_b16,'dir')); disp(sprintf(' %% creating %s',lisa_arm1.dir_out_s0_pca_b16)); mkdir(lisa_arm1.dir_out_s0_pca_b16); end;
%%%%%%%%;
lisa_arm1.dir_out_s0_pca_inp = sprintf('%s/dir_pca_inp',lisa_arm1.dir_out_s0_pca);
if (~exist(lisa_arm1.dir_out_s0_pca_inp,'dir')); disp(sprintf(' %% creating %s',lisa_arm1.dir_out_s0_pca_inp)); mkdir(lisa_arm1.dir_out_s0_pca_inp); end;
%%%%%%%%;
lisa_arm1.dir_out_s0_pca_mda = sprintf('%s/dir_pca_mda',lisa_arm1.dir_out_s0_pca);
if (~exist(lisa_arm1.dir_out_s0_pca_mda,'dir')); disp(sprintf(' %% creating %s',lisa_arm1.dir_out_s0_pca_mda)); mkdir(lisa_arm1.dir_out_s0_pca_mda); end;
%%%%%%%%;
lisa_arm1.dir_out_s0_pca_mat = sprintf('%s/dir_pca_mat',lisa_arm1.dir_out_s0_pca);
if (~exist(lisa_arm1.dir_out_s0_pca_mat,'dir')); disp(sprintf(' %% creating %s',lisa_arm1.dir_out_s0_pca_mat)); mkdir(lisa_arm1.dir_out_s0_pca_mat); end;
%%%%%%%%;

n_iteration = lisa_arm1.n_iteration;
niteration_ = round(0:n_iteration_stride:n_iteration); 
niteration_(1)=1; niteration_(end) = min(niteration_(end),n_iteration-1);
niteration_ = niteration_(length(niteration_):-1:1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
fname_pca_mat = sprintf('%s/%s_pca_collect_ver2_trn%d%s_tst%d%s.mat',lisa_arm1.dir_out_s0_pca_mat,lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm1_string,cl_num_arm2,cl_num_arm2_string); 
if (~flag_rerun &  exist(fname_pca_mat,'file')); disp(sprintf(' %% found %s, loading',fname_pca_mat)); load(fname_pca_mat); end;
if ( flag_rerun | ~exist(fname_pca_mat,'file')); 
disp(sprintf(' %% could not find %s, creating',fname_pca_mat));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% First we calculate cauc for all studies lumped together. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
%%%%%%%%%%%%%%%%;
% build libraries for cauc p-value ;
%%%%%%%%%%%%%%%%;
find_X_arm1_ = find(lisa_arm1.mr_X_); find_D_arm1_ = find(lisa_arm1.mr_D_);
[cauc19_arm1_avg_,cauc19_arm1_min_] = p_cauc_0(lisa_arm1.mds_sort_(find_X_arm1_,[1:6,19]),lisa_arm1.mds_sort_(find_D_arm1_,[1:6,19]),zeros(length(find_X_arm1_),1),zeros(length(find_D_arm1_),1),1024*8);
find_X_arm2_ = find(lisa_arm2.mr_X_); find_D_arm2_ = find(lisa_arm2.mr_D_);
[cauc19_arm2_avg_,cauc19_arm2_min_] = p_cauc_0(lisa_arm2.mds_sort_(find_X_arm2_,[1:6,19]),lisa_arm2.mds_sort_(find_D_arm2_,[1:6,19]),zeros(length(find_X_arm2_),1),zeros(length(find_D_arm2_),1),1024*8);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
pca_rank = 2; pca_b_mlt = 44;
auc19_arm1_ = zeros(length(niteration_),1);
auc19_arm2_ = zeros(length(niteration_),1);
logp_auc19_arm1_ = zeros(length(niteration_),1);
logp_auc19_arm2_ = zeros(length(niteration_),1);
%%%%%%%%;
for ni=1:length(niteration_);
niteration = niteration_(ni);
if (lisa_arm1.verbose>0); disp(sprintf(' %% ni %d niteration %d',ni,niteration)); end;
%%%%%%%%;
pca_proj_infix_arm1 = sprintf('pca_proj_arm1_ni%d_tst%d',niteration,cl_num_arm2); %<-- Note that here we use the projection of arm1, with snps limited by overlap with arm two ;
DnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm1,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
XnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm1,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
%if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm1_ = abs(DnV_arm1_); XnV_arm1_ = abs(XnV_arm1_); end;%if (strcmp(flag_dex_vs_lak,'lak'));
mr_D_rmv_arm1_ = lisa_arm1.mr_D_*0; mr_D_rmv_arm1_(lisa_arm1.rdrop_a_(1:end-lisa_arm1.trace_{1}(niteration,2)))=1;
mr_D_ret_arm1_ = lisa_arm1.mr_D_*0; mr_D_ret_arm1_(lisa_arm1.rdrop_a_(end-lisa_arm1.trace_{1}(niteration,2)+1:end))=1;
%%%%%%%%;
pca_proj_infix_arm2 = sprintf('pca_proj_arm2_ni%d_tst%d',niteration,cl_num_arm2); %<-- Note that here we use the projection of arm2, with snps limited by overlap with arm two ;
DnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm2,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
XnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm2,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
%if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm2_ = abs(DnV_arm2_); XnV_arm2_ = abs(XnV_arm2_); end;%if (strcmp(flag_dex_vs_lak,'lak'));
%%%%%%%%;
flag_disp=0;
if flag_disp;
%%%%%%%%;
figure(n_figure); clf; n_figure = n_figure+1;
%%%%%%%%;
subplot(1,2,1);hold on; 
plot(XnV_arm1_(find_X_arm1_,1),XnV_arm1_(find_X_arm1_,2),'k.','MarkerSize',15);
find_tmp_ = find(mr_D_rmv_arm1_); plot(DnV_arm1_(find_tmp_,1),DnV_arm1_(find_tmp_,2),'g.','MarkerSize',15);
find_tmp_ = find(mr_D_ret_arm1_); plot(DnV_arm1_(find_tmp_,1),DnV_arm1_(find_tmp_,2),'r.','MarkerSize',25);
hold off;
xlabel('PC1');ylabel('PC2'); title(sprintf('ni %d r0 arm1',niteration));
%%%%%%%%;
subplot(1,2,2); hold on;
plot(XnV_arm2_(find_X_arm2_,1),XnV_arm2_(find_X_arm2_,2),'k.','MarkerSize',15);
plot(DnV_arm2_(find_D_arm2_,1),DnV_arm2_(find_D_arm2_,2),'m.','MarkerSize',15);
hold off;
xlabel('PC1');ylabel('PC2'); title(sprintf('ni %d r0 arm2',niteration));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
set(gcf,'Position',1+[0,0,1024*2,1024]);
%%%%%%%%;
end;%if flag_disp;
%%%%%%%%;
tmp_auc19_arm1 = cauc_0(XnV_arm1_(find_X_arm1_,1),DnV_arm1_(find_D_arm1_,1),lisa_arm1.mds_sort_(find_X_arm1_,[1:6,19]),lisa_arm1.mds_sort_(find_D_arm1_,[1:6,19])); flag_flip_arm1_(ni) = (tmp_auc19_arm1<0.5);
if (lisa_arm1.verbose>0); disp(sprintf(' %% tmp_auc19_arm1 %0.2f flag_flip_arm1_(ni) %d',tmp_auc19_arm1,flag_flip_arm1_(ni))); end;
tmp_auc19_arm2 = cauc_0(XnV_arm2_(find_X_arm2_,1),DnV_arm2_(find_D_arm2_,1),lisa_arm2.mds_sort_(find_X_arm2_,[1:6,19]),lisa_arm2.mds_sort_(find_D_arm2_,[1:6,19])); flag_flip_arm2_(ni) = (tmp_auc19_arm2<0.5);
if (lisa_arm1.verbose>0); disp(sprintf(' %% tmp_auc19_arm2 %0.2f flag_flip_arm2_(ni) %d',tmp_auc19_arm2,flag_flip_arm2_(ni))); end;
%%%%%%%%;
if ~flag_flip_arm1_(ni); tmp_DnV_arm1_ = +DnV_arm1_; tmp_XnV_arm1_ = +XnV_arm1_; tmp_DnV_arm2_ = +DnV_arm2_; tmp_XnV_arm2_ = +XnV_arm2_; end;%if ~flag_flip_arm1_(ni);
if  flag_flip_arm1_(ni); tmp_DnV_arm1_ = -DnV_arm1_; tmp_XnV_arm1_ = -XnV_arm1_; tmp_DnV_arm2_ = -DnV_arm2_; tmp_XnV_arm2_ = -XnV_arm2_; end;%if  flag_flip_arm1_(ni);
%%%%%%%%;
tmp_mds_X_ = lisa_arm1.mds_sort_(find_X_arm1_,[1:6,19]); tmp_mds_D_ = lisa_arm1.mds_sort_(find_D_arm1_,[1:6,19]);
tmp_auc19_arm1 = cauc_0(tmp_XnV_arm1_(find_X_arm1_,1),tmp_DnV_arm1_(find_D_arm1_,1),tmp_mds_X_,tmp_mds_D_);
tmp_logp_auc19_arm1 = log(max(1,length(find(cauc19_arm1_avg_>tmp_auc19_arm1)))/length(cauc19_arm1_avg_));
auc19_arm1_(ni) = tmp_auc19_arm1;
logp_auc19_arm1_(ni) = tmp_logp_auc19_arm1;
%%%%%%%%;
tmp_mds_X_ = lisa_arm2.mds_sort_(find_X_arm2_,[1:6,19]); tmp_mds_D_ = lisa_arm2.mds_sort_(find_D_arm2_,[1:6,19]);
tmp_auc19_arm2 = cauc_0(tmp_XnV_arm2_(find_X_arm2_,1),tmp_DnV_arm2_(find_D_arm2_,1),tmp_mds_X_,tmp_mds_D_);
tmp_logp_auc19_arm2 = log(max(1,length(find(cauc19_arm2_avg_>tmp_auc19_arm2)))/length(cauc19_arm2_avg_));
auc19_arm2_(ni) = tmp_auc19_arm2;
logp_auc19_arm2_(ni) = tmp_logp_auc19_arm2;
%%%%%%%%;
clear tmp_X_ tmp_D_ tmp_mds_X_ tmp_mds_D_ tmp_auc19
clear tmp_DnV_arm1_; clear tmp_XnV_arm1_; clear tmp_DnV_arm2_; clear tmp_XnV_arm2_;
end;%for ni=1:length(niteration_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% Now we calculate cauc for individual studies. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
cauc19_arm1_avg__ = cell(lisa_arm1.n_study,1); cauc19_arm1_min__ = cell(lisa_arm1.n_study,1);
cauc19_arm2_avg__ = cell(lisa_arm2.n_study,1); cauc19_arm2_min__ = cell(lisa_arm2.n_study,1);
find_X_arm1__ = cell(lisa_arm1.n_study,1);
find_D_arm1__ = cell(lisa_arm1.n_study,1);
find_X_arm2__ = cell(lisa_arm2.n_study,1);
find_D_arm2__ = cell(lisa_arm2.n_study,1);
%%%%%%%%%%%%%%%%;
% build libraries for cauc p-value ;
%%%%%%%%%%%%%%%%;
for nstudy=1:lisa_arm1.n_study;
find_X_arm1__{nstudy} = intersect(find(lisa_arm1.mr_X_),find(lisa_arm1.study_index_==nstudy)); 
find_D_arm1__{nstudy} = intersect(find(lisa_arm1.mr_D_),find(lisa_arm1.study_index_==nstudy));
[cauc19_arm1_avg__{nstudy},cauc19_arm1_min__{nstudy}] = p_cauc_0(lisa_arm1.mds_sort_(find_X_arm1__{nstudy},[1:6,19]),lisa_arm1.mds_sort_(find_D_arm1__{nstudy},[1:6,19]),zeros(length(find_X_arm1__{nstudy}),1),zeros(length(find_D_arm1__{nstudy}),1),1024*8);
end;%for nstudy=1:lisa_arm1.n_study;
for nstudy=1:lisa_arm2.n_study;
find_X_arm2__{nstudy} = intersect(find(lisa_arm2.mr_X_),find(lisa_arm2.study_index_==nstudy)); 
find_D_arm2__{nstudy} = intersect(find(lisa_arm2.mr_D_),find(lisa_arm2.study_index_==nstudy));
[cauc19_arm2_avg__{nstudy},cauc19_arm2_min__{nstudy}] = p_cauc_0(lisa_arm2.mds_sort_(find_X_arm2__{nstudy},[1:6,19]),lisa_arm2.mds_sort_(find_D_arm2__{nstudy},[1:6,19]),zeros(length(find_X_arm2__{nstudy}),1),zeros(length(find_D_arm2__{nstudy}),1),1024*8);
end;%for nstudy=1:lisa_arm2.n_study;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
pca_rank = 2; pca_b_mlt = 44;
auc19_arm1__ = cell(lisa_arm1.n_study,1); logp_auc19_arm1__ = cell(lisa_arm1.n_study,1);
auc19_arm2__ = cell(lisa_arm2.n_study,1); logp_auc19_arm2__ = cell(lisa_arm2.n_study,1);
for nstudy=1:lisa_arm1.n_study;
auc19_arm1__{nstudy} = zeros(length(niteration_),1);
logp_auc19_arm1__{nstudy} = zeros(length(niteration_),1);
end;%for nstudy=1:lisa_arm1.n_study;
for nstudy=1:lisa_arm2.n_study;
auc19_arm2__{nstudy} = zeros(length(niteration_),1);
logp_auc19_arm2__{nstudy} = zeros(length(niteration_),1);
end;%for nstudy=1:lisa_arm2.n_study;
%%%%%%%%;
for ni=1:length(niteration_);
niteration = niteration_(ni);
if (lisa_arm1.verbose>0); disp(sprintf(' %% ni %d niteration %d',ni,niteration)); end;
%%%%%%%%;
pca_proj_infix_arm1 = sprintf('pca_proj_arm1_ni%d_tst%d',niteration,cl_num_arm2); %<-- Note that here we use the projection of arm1, with snps limited by overlap with arm two ;
DnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm1,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
XnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm1,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
%if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm1_ = abs(DnV_arm1_); XnV_arm1_ = abs(XnV_arm1_); end;%if (strcmp(flag_dex_vs_lak,'lak'));
mr_D_rmv_arm1_ = lisa_arm1.mr_D_*0; mr_D_rmv_arm1_(lisa_arm1.rdrop_a_(1:end-lisa_arm1.trace_{1}(niteration,2)))=1;
mr_D_ret_arm1_ = lisa_arm1.mr_D_*0; mr_D_ret_arm1_(lisa_arm1.rdrop_a_(end-lisa_arm1.trace_{1}(niteration,2)+1:end))=1;
%%%%%%%%;
pca_proj_infix_arm2 = sprintf('pca_proj_arm2_ni%d_tst%d',niteration,cl_num_arm2); %<-- Note that here we use the projection of arm2, with snps limited by overlap with arm two ;
DnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm2,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
XnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',lisa_arm1.dir_out_s0_pca_mda,pca_proj_infix_arm2,pca_rank,pca_b_mlt)); %<-- Note that we use dir_out_s0_pca from arm one, since this is where the bicluster is. ;
%if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm2_ = abs(DnV_arm2_); XnV_arm2_ = abs(XnV_arm2_); end;%if (strcmp(flag_dex_vs_lak,'lak'));
%%%%%%%%;
if ~flag_flip_arm1_(ni); tmp_DnV_arm1_ = +DnV_arm1_; tmp_XnV_arm1_ = +XnV_arm1_; tmp_DnV_arm2_ = +DnV_arm2_; tmp_XnV_arm2_ = +XnV_arm2_; end;%if ~flag_flip_arm1_(ni);
if  flag_flip_arm1_(ni); tmp_DnV_arm1_ = -DnV_arm1_; tmp_XnV_arm1_ = -XnV_arm1_; tmp_DnV_arm2_ = -DnV_arm2_; tmp_XnV_arm2_ = -XnV_arm2_; end;%if  flag_flip_arm1_(ni);
%%%%%%%%;
for nstudy=1:lisa_arm1.n_study;
tmp_mds_X_ = lisa_arm1.mds_sort_(find_X_arm1__{nstudy},[1:6,19]); tmp_mds_D_ = lisa_arm1.mds_sort_(find_D_arm1__{nstudy},[1:6,19]);
tmp_auc19_arm1 = cauc_0(tmp_XnV_arm1_(find_X_arm1__{nstudy},1),tmp_DnV_arm1_(find_D_arm1__{nstudy},1),tmp_mds_X_,tmp_mds_D_);
tmp_logp_auc19_arm1 = log(max(1,length(find(cauc19_arm1_avg__{nstudy}>tmp_auc19_arm1)))/length(cauc19_arm1_avg__{nstudy}));
auc19_arm1__{nstudy}(ni) = tmp_auc19_arm1;
logp_auc19_arm1__{nstudy}(ni) = tmp_logp_auc19_arm1;
end;%for nstudy=1:lisa_arm1.n_study;
%%%%%%%%;
for nstudy=1:lisa_arm2.n_study;
tmp_mds_X_ = lisa_arm2.mds_sort_(find_X_arm2__{nstudy},[1:6,19]); tmp_mds_D_ = lisa_arm2.mds_sort_(find_D_arm2__{nstudy},[1:6,19]);
tmp_auc19_arm2 = cauc_0(tmp_XnV_arm2_(find_X_arm2__{nstudy},1),tmp_DnV_arm2_(find_D_arm2__{nstudy},1),tmp_mds_X_,tmp_mds_D_);
tmp_logp_auc19_arm2 = log(max(1,length(find(cauc19_arm2_avg__{nstudy}>tmp_auc19_arm2)))/length(cauc19_arm2_avg__{nstudy}));
auc19_arm2__{nstudy}(ni) = tmp_auc19_arm2;
logp_auc19_arm2__{nstudy}(ni) = tmp_logp_auc19_arm2;
end;%for nstudy=1:lisa_arm2.n_study;
%%%%%%%%;
clear tmp_X_ tmp_D_ tmp_mds_X_ tmp_mds_D_ tmp_auc19
clear tmp_DnV_arm1_; clear tmp_XnV_arm1_; clear tmp_DnV_arm2_; clear tmp_XnV_arm2_;
end;%for ni=1:length(niteration_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
save(fname_pca_mat,...
'flag_flip_arm1_','flag_flip_arm2_',...
'cauc19_arm1_avg_','cauc19_arm1_min_',...
'cauc19_arm2_avg_','cauc19_arm2_min_',...
'niteration_',...
'auc19_arm1_',...
'auc19_arm2_',...
'logp_auc19_arm1_',...
'logp_auc19_arm2_',...
'cauc19_arm1_avg__','cauc19_arm1_min__',...
'cauc19_arm2_avg__','cauc19_arm2_min__',...
'auc19_arm1__',...
'auc19_arm2__',...
'logp_auc19_arm1__',...
'logp_auc19_arm2__');
end;%if ( flag_rerun | ~exist(fname_pca_mat,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
disp(sprintf(' %% cl_num_arm1 %d cl_num_arm2 %d',cl_num_arm1,cl_num_arm2));
disp(sprintf(' %% niteration_')); disp(num2str(niteration_));
%%%%%%%%;
disp(sprintf(' %% auc19_arm1_')); disp(num2str(transpose(auc19_arm1_)));
disp(sprintf(' %% logp_auc19_arm1_')); disp(num2str(transpose(logp_auc19_arm1_)));
disp(sprintf(' %% auc19_arm2_')); disp(num2str(transpose(auc19_arm2_)));
disp(sprintf(' %% logp_auc19_arm2_')); disp(num2str(transpose(logp_auc19_arm2_)));
%%%%%%%%;
for nstudy=1:lisa_arm1.n_study;
disp(sprintf(' %% nstudy %d/%d',nstudy,lisa_arm1.n_study));
disp(sprintf(' %% auc19_arm1__{nstudy}')); disp(num2str(transpose(auc19_arm1__{nstudy})));
disp(sprintf(' %% logp_auc19_arm1__{nstudy}')); disp(num2str(transpose(logp_auc19_arm1__{nstudy})));
end;%for nstudy=1:lisa_arm1.n_study;
%%%%%%%%;
for nstudy=1:lisa_arm2.n_study;
disp(sprintf(' %% nstudy %d/%d',nstudy,lisa_arm2.n_study));
disp(sprintf(' %% auc19_arm2__{nstudy}')); disp(num2str(transpose(auc19_arm2__{nstudy})));
disp(sprintf(' %% logp_auc19_arm2__{nstudy}')); disp(num2str(transpose(logp_auc19_arm2__{nstudy})));
end;%for nstudy=1:lisa_arm2.n_study;
%%%%%%%%;

figure;clf;
subplot(2,1,1);plot(niteration_,auc19_arm1_,'r.-',niteration_,auc19_arm2_,'b.-');
xlim([min(niteration_),max(niteration_)]); xlabel('iteration');
ylim([0.45,1.0]); ylabel('auc');
title(sprintf('%s trn%d tst %d',lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm2),'interpreter','none');
subplot(2,1,2);plot(niteration_,-logp_auc19_arm1_,'r.-',niteration_,-logp_auc19_arm2_,'b.-',niteration_,-log(0.05)*ones(size(niteration_)),'k--',niteration_,-log(0.01)*ones(size(niteration_)),'k:');
xlim([min(niteration_),max(niteration_)]); xlabel('iteration');
ylim([0,10]); ylabel('log(pval)');
title(sprintf('%s trn%d tst %d',lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm2),'interpreter','none');
set(gcf,'Position',1+[0,0,512,512]);
fname_pca_jpg = sprintf('%s/%s_pca_collect_ver2_trn%d%s_tst%d%s.jpg',lisa_arm1.dir_out_s0_pca_jpg,lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm1_string,cl_num_arm2,cl_num_arm2_string); 
if (~exist(fname_pca_jpg,'file')); disp(sprintf(' %% creating %s',fname_pca_jpg)); print('-djpeg',fname_pca_jpg); end;%if ~exist;
fname_pca_eps = sprintf('%s/%s_pca_collect_ver2_trn%d%s_tst%d%s.eps',lisa_arm1.dir_out_s0_pca_jpg,lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm1_string,cl_num_arm2,cl_num_arm2_string); 
if (~exist(fname_pca_eps,'file')); disp(sprintf(' %% creating %s',fname_pca_eps)); print('-depsc',fname_pca_eps); end;%if ~exist;

for nstudy=1:lisa_arm2.n_study;
figure;clf;
subplot(2,1,1);plot(niteration_,auc19_arm1_,'r.-',niteration_,auc19_arm2__{nstudy},'b.-');
xlim([min(niteration_),max(niteration_)]); xlabel('iteration');
ylim([0.45,1.0]); ylabel('auc');
title(sprintf('%s trn%d tst %d (%s)',lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm2,lisa_arm2.study_name_{nstudy}),'interpreter','none');
subplot(2,1,2);plot(niteration_,-logp_auc19_arm1_,'r.-',niteration_,-logp_auc19_arm2__{nstudy},'b.-',niteration_,-log(0.05)*ones(size(niteration_)),'k--',niteration_,-log(0.01)*ones(size(niteration_)),'k:');
xlim([min(niteration_),max(niteration_)]); xlabel('iteration');
ylim([0,10]); ylabel('log(pval)');
title(sprintf('%s trn%d tst %d (%s)',lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm2,lisa_arm2.study_name_{nstudy}),'interpreter','none');
set(gcf,'Position',1+[0,0,512,512]);
fname_pca_jpg = sprintf('%s/%s_pca_collect_ver2_trn%d%s_tst%d%s_xs%d.jpg',lisa_arm1.dir_out_s0_pca_jpg,lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm1_string,cl_num_arm2,cl_num_arm2_string,nstudy); 
if (0 || ~exist(fname_pca_jpg,'file')); disp(sprintf(' %% creating %s',fname_pca_jpg)); print('-djpeg',fname_pca_jpg); end;%if ~exist;
fname_pca_eps = sprintf('%s/%s_pca_collect_ver2_trn%d%s_tst%d%s_xs%d.eps',lisa_arm1.dir_out_s0_pca_jpg,lisa_arm1.string_name_s0,cl_num_arm1,cl_num_arm1_string,cl_num_arm2,cl_num_arm2_string,nstudy); 
if (0 || ~exist(fname_pca_eps,'file')); disp(sprintf(' %% creating %s',fname_pca_eps)); print('-depsc',fname_pca_eps); end;%if ~exist;
end;%for nstudy=1:lisa_arm2.n_study;
