disp(sprintf(' %% writing binary files... ')); tic;
br_u = zeros(1,bit8,'uint8'); br_u = cast(2.^(bit8-1:-1:0),'uint8');
br_d = zeros(1,bit8,'double'); br_d = cast(2.^(bit8-1:-1:0),'double');
for nl3=1:snp_cap_sub_length; 
bl3_and = 1+mod((cij_and_rpl_(nl3)-1),bit8); al3_and = 1+floor((cij_and_rpl_(nl3)-1)/bit8); cl3_and = 1+(cij_and_rpl_(nl3)-1);
bl3_xor = 1+mod((cij_xor_rpl_(nl3)-1),bit8); al3_xor = 1+floor((cij_xor_rpl_(nl3)-1)/bit8); cl3_xor = 1+(cij_xor_rpl_(nl3)-1);
bl3_nor = 1+mod((cij_nor_rpl_(nl3)-1),bit8); al3_nor = 1+floor((cij_nor_rpl_(nl3)-1)/bit8); cl3_nor = 1+(cij_nor_rpl_(nl3)-1);
nl2 = snp_cap_sub(nl3);
nla = snp_cap_sub_{ns}(nl3); nlb = snp_cap_{ns}(nl2); assert(nla==nlb); nl1=nla;
if (mod(nl3,1000)==0); disp(sprintf(' %% nl3 %d/%d nl2 %d/%d nl1 %d/%d',nl3,snp_cap_sub_length,nl2,snp_cap_length,nl1,n_snp_(ns))); end;
data_snp = zeros(1,4*n_patient_rup_(ns));
data_snp(stride1) = uchar_00000011(nl1,:);
data_snp(stride2) = uchar_00001100(nl1,:);
data_snp(stride3) = uchar_00110000(nl1,:);
data_snp(stride4) = uchar_11000000(nl1,:);
data_snp = data_snp(1,1:n_patient_(ns));
tmp_ij = find(data_snp==snp_mss_tag); data_snp(1,tmp_ij) = fr2_mode_(nl2); clear tmp_ij;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
data_snp_and = (data_snp==snp_and_tag) ; 
data_snp_and_sub = data_snp_and(1,rij_cap_{ns}); data_snp_and_bin_u = cast(data_snp_and_sub(1,:),'uint8');
data_snp_and_sub_full = zeros(1,nrows_An_full); data_snp_and_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_and_sub;
data_snp_and_bin_d = cast(data_snp_and_sub(1,:),'double'); 
data_snp_and_full_bin_d = cast(data_snp_and_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_and) = An_full(1:lrows_An_full,cl3_and) + cast(transpose(br_d*reshape([data_snp_and_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_and,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_and,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_and)*data_snp_and_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_and) = An_{ns}(1:lrows_An_(ns),cl3_and) + cast(transpose(br_d*reshape([data_snp_and_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_and,(1:nrows_An_(ns))) = At_{ns}(al3_and,(1:nrows_An_(ns))) + br_u(bl3_and)*data_snp_and_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%data_snp_xor = (data_snp==snp_and_tag) | (data_snp==snp_xor_tag) ;
data_snp_xor = (data_snp==snp_xor_tag) ;
data_snp_xor_sub = data_snp_xor(1,rij_cap_{ns}); data_snp_xor_bin_u = cast(data_snp_xor_sub(1,:),'uint8');
data_snp_xor_sub_full = zeros(1,nrows_An_full); data_snp_xor_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_xor_sub;
data_snp_xor_bin_d = cast(data_snp_xor_sub(1,:),'double'); 
data_snp_xor_full_bin_d = cast(data_snp_xor_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_xor) = An_full(1:lrows_An_full,cl3_xor) + cast(transpose(br_d*reshape([data_snp_xor_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_xor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_xor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_xor)*data_snp_xor_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_xor) = An_{ns}(1:lrows_An_(ns),cl3_xor) + cast(transpose(br_d*reshape([data_snp_xor_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_xor,(1:nrows_An_(ns))) = At_{ns}(al3_xor,(1:nrows_An_(ns))) + br_u(bl3_xor)*data_snp_xor_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
data_snp_nor = (data_snp==snp_nor_tag) ;
data_snp_nor_sub = data_snp_nor(1,rij_cap_{ns}); data_snp_nor_bin_u = cast(data_snp_nor_sub(1,:),'uint8');
data_snp_nor_sub_full = zeros(1,nrows_An_full); data_snp_nor_sub_full(1,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = data_snp_nor_sub;
data_snp_nor_bin_d = cast(data_snp_nor_sub(1,:),'double'); 
data_snp_nor_full_bin_d = cast(data_snp_nor_sub_full(1,:),'double'); 
An_full(1:lrows_An_full,cl3_nor) = An_full(1:lrows_An_full,cl3_nor) + cast(transpose(br_d*reshape([data_snp_nor_full_bin_d,zeros(1,nrows_An_full_extend)],bit8,lrows_An_full)),'uint8');
At_full(al3_nor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) = At_full(al3_nor,nrows_An_csum_(ns) + (1:nrows_An_(ns))) + br_u(bl3_nor)*data_snp_nor_bin_u;
An_{ns}(1:lrows_An_(ns),cl3_nor) = An_{ns}(1:lrows_An_(ns),cl3_nor) + cast(transpose(br_d*reshape([data_snp_nor_bin_d,zeros(1,nrows_An_extend_(ns))],bit8,lrows_An_(ns))),'uint8');
At_{ns}(al3_nor,(1:nrows_An_(ns))) = At_{ns}(al3_nor,(1:nrows_An_(ns))) + br_u(bl3_nor)*data_snp_nor_bin_u;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
end;%for nl3=1:snp_cap_sub_length;
tmp_t = toc; disp(sprintf(' %% b16: time %0.2f seconds',tmp_t)); 
