function [atfr_arm1_xxx_,A_p_arm1_xxx_,V_rx_trnx_arm1_xxx_,V_rx_tstx_arm1_xxx_] = lisa_dosage_pca_helper_2(string_alleletype,alleletype_arm1_,bo1_,bu1_,atfr_arm1_,A_p_arm1_,flag_check,bo1_by_bu1_xref_,V_rx_trnx_arm1_,V_rx_tstx_arm1_);
if nargin<9; V_rx_trnx_arm1_=[];V_rx_tstx_arm1_=[]; end;

co1_ = find(strcmp(alleletype_arm1_,string_alleletype));
[cu1_,co1_to_cu1_,cu1_to_co1_] = unique(bo1_(co1_));
co1_by_cu1_xref_ = sparse(1:length(co1_),cu1_to_co1_,1,length(co1_),length(cu1_));
[du1_,du1_to_bu1_,du1_to_cu1_] = intersect(bu1_,cu1_,'stable');
bu1_by_du1_xref_ = sparse(du1_to_bu1_,1:length(du1_),1,length(bu1_),length(du1_));
cu1_by_du1_xref_ = sparse(du1_to_cu1_,1:length(du1_),1,length(cu1_),length(du1_));
if (~isempty(V_rx_trnx_arm1_)); V_rx_trnx_arm1_xxx_ = zeros(length(bu1_),2); end;
if (~isempty(V_rx_tstx_arm1_)); V_rx_tstx_arm1_xxx_ = zeros(length(bu1_),2); end;
atfr_arm1_xxx_ = zeros(length(bu1_),1);
A_p_arm1_xxx_ = zeros(length(bu1_),1);
for ndu1=1:length(du1_);
nbu1 = find(sum(bu1_by_du1_xref_(:,ndu1),2));
ncu1 = find(sum(cu1_by_du1_xref_(:,ndu1),2));
nco1 = find(sum(co1_by_cu1_xref_(:,ncu1),2));
nbo1 = co1_(nco1);
if (~isempty(V_rx_trnx_arm1_)); V_rx_trnx_arm1_xxx_(nbu1,:) = V_rx_trnx_arm1_(nbo1,:); end;
if (~isempty(V_rx_tstx_arm1_)); V_rx_tstx_arm1_xxx_(nbu1,:) = V_rx_tstx_arm1_(nbo1,:); end;
atfr_arm1_xxx_(nbu1) = atfr_arm1_(nbo1);
A_p_arm1_xxx_(nbu1) = A_p_arm1_(nbo1);
end;%for ndu1=1:length(du1_);
if flag_check;
for nf=1:flag_check;
disp(sprintf(' %% checking alleletype %s: V_rx_trnx_arm1_xxx_ V_rx_tstx_arm1_xxx_',string_alleletype));
nbu1=max(1,min(length(bu1_),floor(length(bu1_)*rand())));
tmp_snp = bu1_{nbu1};
nbo1_xxx = find(strcmp(bo1_,tmp_snp) & strcmp(alleletype_arm1_,string_alleletype));
if ~isempty(nbo1_xxx);
assert(length(intersect(nbo1_xxx,find(sum(bo1_by_bu1_xref_(:,nbu1),2))))>0);
disp(sprintf(' %% tmp_snp %s <-- %s (%s)',tmp_snp,bo1_{nbo1_xxx},alleletype_arm1_{nbo1_xxx}));
if (~isempty(V_rx_trnx_arm1_)); disp(sprintf(' %% V_rx_trnx_arm1_ (%0.6f,%0.6f) , V_rx_trnx_arm1_xxx_ (%0.6f,%0.6f)',V_rx_trnx_arm1_(nbo1_xxx,:),V_rx_trnx_arm1_xxx_(nbu1,:))); end;
if (~isempty(V_rx_tstx_arm1_)); disp(sprintf(' %% V_rx_tstx_arm1_ (%0.6f,%0.6f) , V_rx_tstx_arm1_xxx_ (%0.6f,%0.6f)',V_rx_tstx_arm1_(nbo1_xxx,:),V_rx_tstx_arm1_xxx_(nbu1,:))); end;
end;%if ~isempty(nbo1_xxx);
end;%for nf=1:flag_check;
end;%if flag_check;
clear co1_ cu1_ co1_to_cu1_ cu1_to_co1_ du1_ du1_to_bu1_ du1_to_cu1_ bu1_by_du1_xref_ cu1_by_du1_xref_ ;
