%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% run lisa_xdropplot_initialize first. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% set names. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
nshuffle=0;
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver10('dex',maf_lo_threshold,maf_hi_threshold,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver10('lak',maf_lo_threshold,maf_hi_threshold,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
string_name_s0000 = string_name;
dir_out_s0000 = sprintf('%s/dir_%s',dir_out,string_name_s0000);
dir_out_trace = sprintf('%s/dir_trace',dir_out_s0000);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract rdrop_a and cdrop_a. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fname_tmp = sprintf('%s/out_xdrop_a.txt',dir_out_s0000); fcheck(fname_tmp);
out_xdrop_a_ = textread(fname_tmp); rdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,1)>-1),1)+1; cdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,2)>-1),2)+1;
fname_tmp = sprintf('%s/out_xdrop_b.txt',dir_out_s0000); fcheck(fname_tmp);
out_xdrop_b_ = textread(fname_tmp); rdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,1)>-1),1)+1; cdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,2)>-1),2)+1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% load mds and fam and bim file. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fcheck(sprintf('%s/%s_bim.ext',dir__in,string_prefix));
fid = fopen(sprintf('%s/%s_bim.ext',dir__in,string_prefix)); bim_ = textscan(fid,'%d\t%s\t%d\t%d\t%c\t%c\t%s\t%f\t%f\t%f\t%f\n','headerlines',0); fclose(fid);
n_snp = length(bim_{1});
fcheck(sprintf('%s/mds.mat',dir_trunk));
load(sprintf('%s/mds.mat',dir_trunk));
fcheck(sprintf('%s/%s_fam.ext',dir__in,string_prefix));
fid = fopen(sprintf('%s/%s_fam.ext',dir__in,string_prefix)); fam_ = textscan(fid,'%s %s %s %s %d %d %s','headerlines',0); fclose(fid);
n_patient_F = length(fam_{1}); fam_name_ = cell(n_patient_F,1); for np=1:n_patient_F; fam_name_{np} = sprintf('%s%s%s',fam_{1}{np},'&',fam_{2}{np}); end;%for np=1:n_patient_F;
[~,ifam_,imds_] = intersect(fam_name_,mds_name_,'stable'); if (length(ifam_)<n_patient_F); disp('Warning! fam_name_ not a subset of mds_name_'); end; mds_sort_ = mds_(imds_,:);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% check to make sure that the mr_A_full lines up with the mr_A_%0.2d ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
mr_A_ = cell(n_study,1);
mr_Z_ = cell(n_study,1);
for ns=1:n_study;
tmpchar = sprintf('%s/%s_mr_A_%0.2d.b16',dir__in,string_prefix,ns);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_A_{ns} = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
tmpchar = sprintf('%s/%s_mr_Z_%0.2d.b16',dir__in,string_prefix,ns);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_Z_{ns} = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
end;%for ns=1:n_study;
tmpchar = sprintf('%s/%s_mr_A_full.b16',dir__in,string_prefix);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_A_full = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
tmpchar = sprintf('%s/%s_mr_Z_full.b16',dir__in,string_prefix);
[~,nrows,ncols] = tutorial_binary_getsize(tmpchar);
mr_Z_full = (tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0);
mr_A_tmp = []; mr_Z_tmp = [];
for ns=1:n_study;
mr_A_tmp = [mr_A_tmp;mr_A_{ns}];
mr_Z_tmp = [mr_Z_tmp;mr_Z_{ns}];
end;% for ns=1:n_study;
disp(sprintf(' %% mr_A error %0.16f',norm(mr_A_tmp-mr_A_full)));
disp(sprintf(' %% mr_Z error %0.16f',norm(mr_Z_tmp-mr_Z_full)));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% determine which studies correspond to which patients. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
study_path_ = cell(n_study,1);
study_index_ = zeros(n_patient_F,1);
for ns=1:n_study;
study_path_{ns} = sprintf('~/%s/%s.fam',study_trunk_{ns},study_name_{ns});
study_index_(find(strcmp(fam_{7},study_path_{ns}))) = ns;
end;%for ns=1:n_study;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract traces (original stored in s0000) ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
trace_found_ = zeros(n_shuffle+1,1);
for (nshuffle=0:n_shuffle);
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver10('dex',maf_lo_threshold,maf_hi_threshold,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver10('lak',maf_lo_threshold,maf_hi_threshold,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,nshuffle)); end;
trace_found_(1+nshuffle)=0;
if (trace_found_(1+nshuffle)==0);
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',dir_out,string_name);
if (exist(fname_tmp,'file')); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); trace_found_(1+nshuffle)=1; end;
end;%if (trace_found_(1+nshuffle)==0);
if (trace_found_(1+nshuffle)==0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',dir_out_trace,nshuffle);
if (exist(fname_tmp,'file')); disp(sprintf(' %% found fname_tmp: %s',fname_tmp)); trace_found_(1+nshuffle)=1; end;
end;%if (trace_found_(1+nshuffle)==0);
end;%for (nshuffle=0:n_shuffle);
disp(sprintf(' %% found %d/%d traces',sum(trace_found_),1+n_shuffle));
if (trace_found_(1)~=1); disp(sprintf(' %% Warning! trace for original data not found!')); end;
%%%%%%%%%%%%%%%%;
nshuffle=0;
fname_tmp = sprintf('%s/out_xdrop_a.txt',dir_out_s0000);
out_xdrop_a_ = textread(fname_tmp); rdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,1)>-1),1)+1; cdrop_a_ = out_xdrop_a_(find(out_xdrop_a_(:,2)>-1),2)+1;
fname_tmp = sprintf('%s/out_xdrop_b.txt',dir_out_s0000);
out_xdrop_b_ = textread(fname_tmp); rdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,1)>-1),1)+1; cdrop_b_ = out_xdrop_b_(find(out_xdrop_b_(:,2)>-1),2)+1;
%%%%%%%%%%%%%%%%;
n_shuffle_found = sum(trace_found_)-1;
tmp_ij = find(trace_found_);
trace_ = cell(1+n_shuffle_found,1);
for nshuffle=0:n_shuffle_found;
if (strcmp(flag_dex_vs_lak,'dex')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver10('dex',maf_lo_threshold,maf_hi_threshold,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,tmp_ij(1+nshuffle)-1)); end;
if (strcmp(flag_dex_vs_lak,'lak')); string_name = sprintf('%s_%s',string_prefix,xxxcluster_PGC_uADZSZDA_xfix_ver10('lak',maf_lo_threshold,maf_hi_threshold,flag_reverse,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,tmp_ij(1+nshuffle)-1)); end;
flag_found=0;
if (flag_found==0);
fname_tmp = sprintf('%s/dir_%s/out_trace.txt',dir_out,string_name);
if (exist(fname_tmp,'file')); trace_{1+nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0);
if (flag_found==0);
fname_tmp = sprintf('%s/out_trace_s%0.4d.txt',dir_out_trace,nshuffle);
if (exist(fname_tmp,'file')); trace_{1+nshuffle} = textread(fname_tmp); flag_found=1; end;
end;%if (flag_found==0);
end;%for nshuffle=0:n_shuffle_found;
%%%%%%%%%%%%%%%%;
trace_tmp_ = trace_{1};
[iteration_max,n_cols] = size(trace_tmp_);
if (iteration_max==1 | n_cols~=6); disp(sprintf(' %% Warning! iteration_max %d n_cols %d in first trace',iteration_max,n_cols)); end;
niter_ = trace_tmp_(:,1);
r_rem_ = (trace_tmp_(:,2));
c_rem_ = (trace_tmp_(:,3));
t_rem_ = (trace_tmp_(:,6)); t_ret_ = find(t_rem_>=Ireq);
%%%%%%%%%%%%%%%%;
trace_finished_ = zeros(1+n_shuffle_found,1); 
for nshuffle=0:n_shuffle_found;
trace_tmp_ = trace_{1+nshuffle};
[rtmp,ctmp] = size(trace_tmp_);
if (rtmp==iteration_max & ctmp==6); trace_finished_(1+nshuffle)=1; else trace_finished_(1+nshuffle)=0; end;
end;%for nshuffle=0:n_shuffle_found;
%%%%%%%%%%%%%%%%;
trace_finished_ij_ = find(trace_finished_);
n_finished = length(trace_finished_ij_); disp(sprintf(' %% found n_finished %d',n_finished));

if (~exist('flag_BD','var') | flag_BD==1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% extract BD phenotype. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
fid = fopen(sprintf('%s/PGC_BIP32b-BD1.20160612.pheno',dir_trunk)); BD1_ = textscan(fid,'%s %s %d','headerlines',1); fclose(fid);
n_patient_BD1 = length(BD1_{1}); BD1_name_ = cell(n_patient_BD1,1); for np=1:n_patient_BD1; BD1_name_{np} = sprintf('%s%s%s',BD1_{1}{np},'&',BD1_{2}{np}); end;%for np=1:n_patient_BD1;
BD1_pheno_ = BD1_{3};
BD1_status_ = zeros(n_patient_F,1); [~,ifam_,iB_] = intersect(fam_name_,BD1_name_,'stable'); BD1_status_(ifam_) = BD1_pheno_(iB_);
fid = fopen(sprintf('%s/PGC_BIP32b-BD2.20160612.pheno',dir_trunk)); BD2_ = textscan(fid,'%s %s %d','headerlines',1); fclose(fid);
n_patient_BD2 = length(BD2_{1}); BD2_name_ = cell(n_patient_BD2,1); for np=1:n_patient_BD2; BD2_name_{np} = sprintf('%s%s%s',BD2_{1}{np},'&',BD2_{2}{np}); end;%for np=1:n_patient_BD2_;
BD2_pheno_ = BD2_{3};
BD2_status_ = zeros(n_patient_F,1); [~,ifam_,iB_] = intersect(fam_name_,BD2_name_,'stable'); BD2_status_(ifam_) = BD2_pheno_(iB_);
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_==nb1 & BD2_status_==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for all patients: ')); disp(num2str(BDh));
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_(rdrop_a_)==nb1 & BD2_status_(rdrop_a_)==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for D-type patients: ')); disp(num2str(BDh));
BDh = zeros(3,3);
for nb1=0:2; for nb2=0:2;
BDh(1+nb1,1+nb2) = length(find(BD1_status_(setdiff(1:n_patient_F,rdrop_a_))==nb1 & BD2_status_(setdiff(1:n_patient_F,rdrop_a_))==nb2));
end;end;%for nb1=0:2; for nb2=0:2;
disp(sprintf(' %% distribution of BD phenotype for X-type patients: ')); disp(num2str(BDh));
% phenotype index: ;
% 1 = (BD1->0, BD2->0) ; 
% 2 = (BD1->1, BD2->0) ;
% 3 = (BD1->2, BD2->0) ;
% 4 = (BD1->1, BD2->1) ;
% 5 = (BD1->0, BD2->2) ;
pheno_index_ = zeros(n_patient_F,1);
pheno_index_(find(BD1_status_==0 & BD2_status_==0)) = 1;
pheno_index_(find(BD1_status_==1 & BD2_status_==0)) = 2;
pheno_index_(find(BD1_status_==2 & BD2_status_==0)) = 3;
pheno_index_(find(BD1_status_==1 & BD2_status_==1)) = 4;
pheno_index_(find(BD1_status_==0 & BD2_status_==2)) = 5;
n_pheno = 5;
end;%if (~exist('flag_BD','var') | flag_BD==1);
