function lisa_pca_collect_ver6(dir_code,dir_trunk,mc_string,cl_num,flag_dex_vs_lak,gamma,B_MLT,n_mds,flag_reverse,n_maf,n_cov,n_scramble,n_shuffle) ;
%{

% Single run;
dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c_dev'); 
dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20180304');
path(path,sprintf('%s/dir_m',dir_code)); 
cl_num = 1; 
[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num);
Ireq_half = floor(n_study/2); Icat_full = n_study;
string_prefix = sprintf('PGC_cl%d_maf01',cl_num);
flag_dex_vs_lak = 'dex'; 
if (strcmp(flag_dex_vs_lak,'dex')); gamma = 0.004; mc_string = ''; end; if (strcmp(flag_dex_vs_lak,'lak')); gamma = 0.001; mc_string = 'm20_p85'; end;
B_MLT=34;n_mds=20;
 for flag_reverse=0:1;
n_maf = 5; n_cov = 2; n_shuffle = 64; 
 for n_scramble = 1;
lisa_pca_collect_ver6(dir_code,dir_trunk,mc_string,cl_num,flag_dex_vs_lak,gamma,B_MLT,n_mds,flag_reverse,n_maf,n_cov,n_scramble,n_shuffle) ;
 end;% for n_scramble = 0:1;
 end;% for flag_reverse=0:1;

% Single run;
dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c_dev'); 
dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20180304');
path(path,sprintf('%s/dir_m',dir_code)); 
cl_num = 4; 
[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num);
Ireq_half = floor(n_study/2); Icat_full = n_study;
string_prefix = sprintf('PGC_cl%d_maf01',cl_num);
flag_dex_vs_lak = 'lak'; 
if (strcmp(flag_dex_vs_lak,'dex')); gamma = 0.004; end; if (strcmp(flag_dex_vs_lak,'lak')); gamma = 0.001; mc_string = 'm20_p85'; end;
B_MLT=34;n_mds=20;
flag_reverse=0;
n_maf = 5;
n_cov = 1;
n_shuffle = 64; n_scramble = 1;
lisa_pca_collect_ver6(dir_code,dir_trunk,mc_string,cl_num,flag_dex_vs_lak,gamma,B_MLT,n_mds,flag_reverse,n_maf,n_cov,n_scramble,n_shuffle) ;

% Multiple runs;
dir_code = sprintf('/data/rangan/dir_bcc/dir_lakcluster_c_dev'); 
dir_trunk = sprintf('/data/rangan/dir_bcc/dir_PGC_20180304');
path(path,sprintf('%s/dir_m',dir_code)); 
for cl_num = 4;%for cl_num = 3:4;
[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num);
Ireq_half = floor(n_study/2); Icat_full = n_study;
string_prefix = sprintf('PGC_cl%d_maf01',cl_num);
flag_dex_vs_lak = {'lak'}; 
if (strcmp(flag_dex_vs_lak{1},'dex')); gamma = 0.004; end; if (strcmp(flag_dex_vs_lak{1},'lak')); gamma = 0.001; mc_string = 'm20_p85'; end;
B_MLT=34;n_mds=20;
for flag_reverse = 0:1;%for flag_reverse = 0:1;
for n_maf = [4:5];%for n_maf = 4:5;
for n_cov=2;%for n_cov = 0:2;
n_shuffle = 64; n_scramble=0;
try;
lisa_pca_collect_ver6(dir_code,dir_trunk,mc_string,cl_num,flag_dex_vs_lak{1},gamma,B_MLT,n_mds,flag_reverse,n_maf,n_cov,n_scramble,n_shuffle) ;
catch; end;%try;
end;%for n_cov = 0:2;
end;%for n_maf = 4:5;
end;%for flag_reverse = 0:1;
end;%for cl_num = 3:4;

  %}

%%%%%%%%%%%%%%%%;
[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num);
Ireq_half = floor(n_study/2); Icat_full = n_study;
string_prefix = sprintf('PGC_cl%d_maf01',cl_num);
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if n_maf==1; maf_lo_threshold = 0.01; maf_hi_threshold = 0.50; end; % all (since we thresholded maf at 0.01 to start with) ;
if n_maf==2; maf_lo_threshold = 0.01; maf_hi_threshold = 0.05; end; % extreme snps (differential expression only, no loop-counting later on) ;
if n_maf==3; maf_lo_threshold = 0.01; maf_hi_threshold = 0.10; end; % extreme snps (differential expression only, no loop-counting later on) ;
if n_maf==4; maf_lo_threshold = 0.10; maf_hi_threshold = 0.50; end; % more balanced snps (differential expression to start, as well as loop-counting later on) ;
if n_maf==5; maf_lo_threshold = 0.25; maf_hi_threshold = 0.50; end; % more balanced snps (differential expression to start, as well as loop-counting later on) ;
%%%%%%%%%%%%%%%% ;
if n_cov==0; Ireq=0; Icat=1; mds_used_=[]; mds_repl=0; end; % do not correct for mds-components ;
if n_cov==1; Ireq=0; Icat=1; mds_used_=[1:2]; mds_repl=1; end; % only correct for mds-components [1:2], but replicated only once, so that each 'sector' is 90 degrees ;
if n_cov==2; Ireq=0; Icat=1; mds_used_=[1:2]; mds_repl=2; end; % only correct for mds-components [1:2], but replicated twice, so that each 'sector' is 45 degrees ;
if n_cov==3; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[]; mds_repl=0; end; % correct for study, requiring at least Ireq_half, but not for mds-components. ;
if n_cov==4; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[1:2]; mds_repl=1; end; % correct for study, requiring at least Ireq_half, as well as correct for mds-components [1:2], but replicated only once, so that each 'sector' is 90 degrees ;
if n_cov==5; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[1:2]; mds_repl=2; end; % correct for study, requiring at least Ireq_half, as well as correct for mds-components [1:2], replicated twice, so that each 'sector' is 45 degrees ;
%%%%%%%%%%%%%%%% ;
%n_shuffle = 64;
dir__in = sprintf('%s/dir_%s',dir_trunk,string_prefix);
dir_out = sprintf('%s/dir_%s_analyze',dir_trunk,string_prefix);
disp(sprintf(' %% dir__in: %s',dir__in));
disp(sprintf(' %% dir_out: %s',dir_out));
cl_num_arm1 = cl_num; 
%%%%%%%%%%%%%%%%;
lisa_xdropplot_loadtrace_ver2;
%%%%%%%%%%%%%%%%;
QR_ = zeros(n_finished,iteration_max);
QC_ = zeros(n_finished,iteration_max);
for nf=1:n_finished;
ns = trace_finished_ij_(nf); trace_tmp_ = trace_{ns};
QR_(nf,:) = transpose(trace_tmp_(:,4));
QC_(nf,:) = transpose(trace_tmp_(:,5));
end;%for nf=1:n_finished;
%%%%%%%%%%%%%%%% ;
PR_ = zeros(n_finished,iteration_max);
PC_ = zeros(n_finished,iteration_max);
for ni=1:iteration_max;
[~,tmp_ij] = sort(QR_(:,ni),'ascend'); [~,PR_(:,ni)] = sort(tmp_ij,'ascend');
[~,tmp_ij] = sort(QC_(:,ni),'ascend'); [~,PC_(:,ni)] = sort(tmp_ij,'ascend');
end;%for ni=1:iteration_max;
%%%%%%%%%%%%%%%% ;
QR_ = transpose(QR_); QC_ = transpose(QC_);
PR_ = transpose(PR_); PC_ = transpose(PC_);
QR_avg_ = mean(QR_,2); QR_std_ = std(QR_,[],2); QC_avg_ = mean(QC_,2); QC_std_ = std(QC_,[],2);
ZR_ = (QR_ - repmat(QR_avg_,1,n_finished))./repmat(QR_std_,1,n_finished); ZC_ = (QC_ - repmat(QC_avg_,1,n_finished))./repmat(QC_std_,1,n_finished);
%%%%%%%%%%%%%%%%;
dir__in_arm1 = dir__in;
string_prefix_arm1 = string_prefix;
cl_num_arm1 = cl_num;
nshuffle=0;
string_name_s0000_arm1 = string_name_s0000;
dir_out_s0000_arm1 = dir_out_s0000;
dir_out_s0000_pca_arm1 = sprintf('%s/dir_pca',dir_out_s0000_arm1);
if (~exist(dir_out_s0000_pca_arm1,'dir')); disp(sprintf(' %% creating %s',dir_out_s0000_pca_arm1)); mkdir(dir_out_s0000_pca_arm1); end;
dir_out_trace_arm1 = dir_out_trace;
out_xdrop_a_arm1_ = out_xdrop_a_; rdrop_a_arm1_ = rdrop_a_; cdrop_a_arm1_ = cdrop_a_;
out_xdrop_b_arm1_ = out_xdrop_b_; rdrop_b_arm1_ = rdrop_b_; cdrop_b_arm1_ = cdrop_b_;
bim_arm1_ = bim_;
n_snp_arm1 = n_snp;
fam_arm1_ = fam_;
mr_A_arm1_ = mr_A_;
mr_A_arm1_full = mr_A_full;
mr_Z_arm1_ = mr_Z_;
mr_Z_arm1_full = mr_Z_full;
study_index_arm1_ = study_index_;
iteration_max_arm1 = iteration_max;
r_rem_arm1_ = r_rem_;
c_rem_arm1_ = c_rem_;
pca_b_mlt = 44; pca_tolerance = 1e-2; pca_rank = 2;
%%%%%%%%%%%%%%%%;
% mda components;
%%%%%%%%%%%%%%%%;
%fcheck(sprintf('%s/mds.mat',dir_trunk)); load(sprintf('%s/mds.mat',dir_trunk));
fcheck(sprintf('%s/%s_fam.ext',dir__in_arm1,string_prefix_arm1));
fid = fopen(sprintf('%s/%s_fam.ext',dir__in_arm1,string_prefix_arm1)); fam_arm1_ = textscan(fid,'%s %s %s %s %d %d %s','headerlines',0); fclose(fid);
n_patient_F = length(fam_arm1_{1}); fam_arm1_name_ = cell(n_patient_F,1); for np=1:n_patient_F; fam_arm1_name_{np} = sprintf('%s%s%s',fam_arm1_{1}{np},'&',fam_arm1_{2}{np}); end;%for np=1:n_patient_F;
[~,ifam_arm1_,imds_arm1_] = intersect(fam_arm1_name_,mds_name_,'stable'); if (length(ifam_arm1_)<n_patient_F); disp('Warning! fam_arm1_name_ not a subset of mds_name_'); end; mds_arm1_ = mds_(imds_arm1_,:);
%%%%%%%%%%%%%%%%;
niteration_ = 0:25:iteration_max_arm1; 
niteration_(1)=1; niteration_(end) = min(niteration_(end),iteration_max_arm1-1);
niteration_ = niteration_(length(niteration_):-1:1);

if (n_finished>2);
%%%%%%%%%%%%%%%%;
% generate plot. ;
%%%%%%%%%%%%%%%%;
figure(1); clf;
subplot(2,3,[1,4]);hold on; 
plot(max(t_ret_)-t_ret_(end:-1:1),c_rem_,'k-'); xlabel('iteration'); ylabel('col rem','Interpreter','none'); xlim([0,max((t_ret_))+1]);
title('columns remaining (iteration)');
subplot(2,3,2);hold on; 
plot(max(t_ret_)-t_ret_(end:-1:1),ZC_(t_ret_,1),'ro-',max(t_ret_)-t_ret_(end:-1:1),ZC_(t_ret_,2:end),'b-'); xlabel('iteration'); ylabel('ZC_','Interpreter','none'); xlim([0,max((t_ret_))+1]);
title('ZC(iteration)');
subplot(2,3,3);hold on; 
plot(max(t_ret_)-t_ret_(end:-1:1),ZR_(t_ret_,1),'ro-',max(t_ret_)-t_ret_(end:-1:1),ZR_(t_ret_,2:end),'b-'); xlabel('iteration'); ylabel('ZR_','Interpreter','none'); xlim([0,max((t_ret_))+1]);
title('ZR(iteration)');
subplot(2,3,5);hold on; 
plot(max(c_rem_)-c_rem_(t_ret_),ZC_(t_ret_,1),'ro-',max(c_rem_)-c_rem_(t_ret_),ZC_(t_ret_,2:end),'b-'); xlabel('cols eliminated'); ylabel('ZC_','Interpreter','none'); xlim([0,max(max(c_rem_)-c_rem_(t_ret_))+1]);
title('ZC(cols rem)');
subplot(2,3,6);hold on; 
plot(max(c_rem_)-c_rem_(t_ret_),ZR_(t_ret_,1),'ro-',max(c_rem_)-c_rem_(t_ret_),ZR_(t_ret_,2:end),'b-'); xlabel('cols eliminated'); ylabel('ZR_','Interpreter','none'); xlim([0,max(max(c_rem_)-c_rem_(t_ret_))+1]);
title('ZR(cols rem)');
set(gcf,'Position',1+[0,0,1024*2,1024]); drawnow();
fname_pre = sprintf('%s/%s_trace_collect',dir_out_s0000_pca_arm1,string_name_s0000);
print('-djpeg',sprintf('%s.jpg',fname_pre));
print('-depsc',sprintf('%s.eps',fname_pre));
end;%if (n_finished>2);

for cl_num_arm2 = [1:4];
if (cl_num_arm1~=cl_num_arm2);
for ni=1:length(niteration_);
niteration = niteration_(ni);
pca_fname_fig = sprintf('%s/%s_pca_proj_ni%d_tst%d.jpg',dir_out_s0000_pca_arm1,string_name_s0000_arm1,niteration,cl_num_arm2); 
if ( exist(pca_fname_fig,'file')); disp(sprintf(' %% found %s',pca_fname_fig)); end;
if (~exist(pca_fname_fig,'file'));
try;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot scatterplot. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
pca_proj_arm1_infix = sprintf('pca_proj_arm1_ni%d_tst%d',niteration,cl_num_arm2);
DnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm1_infix,pca_rank,pca_b_mlt));
XnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm1_infix,pca_rank,pca_b_mlt));
%if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm1_ = abs(DnV_arm1_); XnV_arm1_ = abs(XnV_arm1_); end;%if (strcmp(flag_dex_vs_lak,'lak'));
if (flag_reverse==0); mr_D_arm1_full = mr_A_arm1_full; mr_X_arm1_full = mr_Z_arm1_full; end;
if (flag_reverse==1); mr_D_arm1_full = mr_Z_arm1_full; mr_X_arm1_full = mr_A_arm1_full; end;
mr_D_arm1_tmp = mr_D_arm1_full*0; mr_D_arm1_tmp(rdrop_a_arm1_(length(rdrop_a_arm1_)-r_rem_arm1_(niteration)+1:length(rdrop_a_arm1_)))=1;
%%%%%%%%;
figure(1);clf;
%%%%%%%%;
subplot(2,2,1);hold on; 
plot(XnV_arm1_(find(mr_X_arm1_full),1),XnV_arm1_(find(mr_X_arm1_full),2),'k.','MarkerSize',15);
plot(DnV_arm1_(find(mr_D_arm1_full-mr_D_arm1_tmp),1),DnV_arm1_(find(mr_D_arm1_full-mr_D_arm1_tmp),2),'g.','MarkerSize',15);
plot(DnV_arm1_(find(mr_D_arm1_tmp),1),DnV_arm1_(find(mr_D_arm1_tmp),2),'r.','MarkerSize',25);
hold off;
xlabel('PC1');ylabel('PC2'); title(sprintf('ni %d arm1',niteration));
%%%%%%%%;
subplot(2,2,2); hold on;
tmp_ = XnV_arm1_ + DnV_arm1_; tmp_ = tmp_(find(mr_X_arm1_full + mr_D_arm1_full)); % all values used. ;
hlim = mean(tmp_) + [-1,1]*3.5*std(tmp_);
%if (strcmp(flag_dex_vs_lak,'dex')); hlim = mean(tmp_) + [-1,1]*3.5*std(tmp_); end;
%if (strcmp(flag_dex_vs_lak,'lak')); hlim = [0 , prctile(tmp_,95)]; end;
if (min(hlim)>=max(hlim)); hlim = mean(hlim) + [-1,+1]; end;
hbins=linspace(min(hlim),max(hlim),64);
h_X_arm1_full = hist(XnV_arm1_(find(mr_X_arm1_full),1),hbins); h_X_arm1_full = h_X_arm1_full/sum(mr_X_arm1_full);
h_D_arm1_full = hist(DnV_arm1_(find(mr_D_arm1_full),1),hbins); h_D_arm1_full = h_D_arm1_full/sum(mr_D_arm1_full);
h_D_arm1_exc = hist(DnV_arm1_(find(mr_D_arm1_full-mr_D_arm1_tmp),1),hbins); h_D_arm1_exc = h_D_arm1_exc/sum(mr_D_arm1_full);
h_D_arm1_tmp = hist(DnV_arm1_(find(mr_D_arm1_tmp),1),hbins); h_D_arm1_tmp = h_D_arm1_tmp/sum(mr_D_arm1_full);
stairs(hbins,h_X_arm1_full,'k-','LineWidth',2);
stairs(hbins,h_D_arm1_full,'m-','LineWidth',2);
stairs(hbins,h_D_arm1_exc,'g-','LineWidth',2);
stairs(hbins,h_D_arm1_tmp,'r-','LineWidth',2);
hold off;
xlim(hlim);xlabel('PC1');ylabel('hist'); title(sprintf('ni %d arm1',niteration));
%%%%%%%%;
string_prefix_arm2 = sprintf('PGC_cl%d_maf01',cl_num_arm2);
dir__in_arm2 = sprintf('%s/dir_%s',dir_trunk,string_prefix_arm2);
tmpchar = sprintf('%s/PGC_cl%d_maf01_mr_A_full.b16',dir__in_arm2,cl_num_arm2);
[bitj,nrows,ncols] = tutorial_binary_getsize(tmpchar); mr_A_arm2_full = tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0;
tmpchar = sprintf('%s/PGC_cl%d_maf01_mr_Z_full.b16',dir__in_arm2,cl_num_arm2);
[bitj,nrows,ncols] = tutorial_binary_getsize(tmpchar); mr_Z_arm2_full = tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0;
if (flag_reverse==0); mr_D_arm2_full = mr_A_arm2_full; mr_X_arm2_full = mr_Z_arm2_full; end;
if (flag_reverse==1); mr_D_arm2_full = mr_Z_arm2_full; mr_X_arm2_full = mr_A_arm2_full; end;
%%%%%%%%;
pca_proj_arm2_infix = sprintf('pca_proj_arm2_ni%d_tst%d',niteration,cl_num_arm2);
DnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm2_infix,pca_rank,pca_b_mlt));
XnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm2_infix,pca_rank,pca_b_mlt));
%if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm2_ = abs(DnV_arm2_); XnV_arm2_ = abs(XnV_arm2_); end;%if (strcmp(flag_dex_vs_lak,'lak'));
if (flag_reverse==0); mr_D_arm2_full = mr_A_arm2_full; mr_X_arm2_full = mr_Z_arm2_full; end;
if (flag_reverse==1); mr_D_arm2_full = mr_Z_arm2_full; mr_X_arm2_full = mr_A_arm2_full; end;
%%%%%%%%;
subplot(2,2,3);hold on; 
plot(XnV_arm2_(find(mr_X_arm2_full),1),XnV_arm2_(find(mr_X_arm2_full),2),'k.','MarkerSize',15);
plot(DnV_arm2_(find(mr_D_arm2_full),1),DnV_arm2_(find(mr_D_arm2_full),2),'m.','MarkerSize',15);
hold off;
xlabel('PC1');ylabel('PC2'); title(sprintf('ni %d arm2',niteration));
subplot(2,2,4); hold on;
tmp_ = XnV_arm2_ + DnV_arm2_; tmp_ = tmp_(find(mr_X_arm2_full + mr_D_arm2_full)); % all values used. ;
hlim = mean(tmp_) + [-1,1]*3.5*std(tmp_);
%if (strcmp(flag_dex_vs_lak,'dex')); hlim = mean(tmp_) + [-1,1]*3.5*std(tmp_); end;
%if (strcmp(flag_dex_vs_lak,'lak')); hlim = [0 , prctile(tmp_,95)]; end;
if (min(hlim)>=max(hlim)); hlim = mean(hlim) + [-1,+1]; end;
hbins=linspace(min(hlim),max(hlim),64);
h_X_arm2_full = hist(XnV_arm2_(find(mr_X_arm2_full),1),hbins); h_X_arm2_full = h_X_arm2_full/sum(mr_X_arm2_full);
h_D_arm2_full = hist(DnV_arm2_(find(mr_D_arm2_full),1),hbins); h_D_arm2_full = h_D_arm2_full/sum(mr_D_arm2_full);
stairs(hbins,h_X_arm2_full,'k-','LineWidth',2);
stairs(hbins,h_D_arm2_full,'m-','LineWidth',2);
hold off;
xlim(hlim);xlabel('PC1');ylabel('hist'); title(sprintf('ni %d arm2',niteration));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
set(gcf,'Position',1+[0,0,1024*2,1024]);
%%%%%%%%;
drawnow();
%%%%%%%%;
print('-djpeg',pca_fname_fig);
catch; disp(sprintf(' %% Warning! could not create %s',pca_fname_fig)); end;%try;
end;%if (~exist(pca_fname_fig,'file'));
end;%for ni=1:length(niteration_);
end;%if (cl_num_arm1~=cl_num_arm2);
end;%for cl_num_arm2 = [1:4];

fname_mat = sprintf('%s/%s_pca_collect_ver6.mat',dir_out_s0000_pca_arm1,string_name_s0000);
if ( exist(fname_mat,'file')); disp(sprintf(' %% loading %s',fname_mat)); load(fname_mat); end;%if ( exist(fname_mat,'file'));
if (~exist(fname_mat,'file')); 
disp(sprintf(' %% could not find %s, creating...',fname_mat)); 
%%%%%%%%%%%%%%%%
n_cl = 4;
auc00_arm1_ = zeros(length(niteration_),n_cl) + 0.5;
logp_auc00_arm1_ = zeros(length(niteration_),n_cl);
auc02_arm1_ = zeros(length(niteration_),n_cl) + 0.5;
logp_auc02_arm1_ = zeros(length(niteration_),n_cl);
auc20_arm1_ = zeros(length(niteration_),n_cl) + 0.5;
logp_auc20_arm1_ = zeros(length(niteration_),n_cl);
corr_arm1_ = zeros(length(niteration_),n_cl);
beta00_arm1_ = zeros(length(niteration_),n_cl);
logp_beta00_arm1_ = zeros(length(niteration_),n_cl);
beta02_arm1_ = zeros(length(niteration_),n_cl);
logp_beta02_arm1_ = zeros(length(niteration_),n_cl);
beta20_arm1_ = zeros(length(niteration_),n_cl);
logp_beta20_arm1_ = zeros(length(niteration_),n_cl);
flag_flip00_ = zeros(length(niteration_),n_cl);
flag_flip02_ = zeros(length(niteration_),n_cl);
flag_flip20_ = zeros(length(niteration_),n_cl);
auc00_arm2_ = zeros(length(niteration_),n_cl) + 0.5;
logp_auc00_arm2_ = zeros(length(niteration_),n_cl);
auc02_arm2_ = zeros(length(niteration_),n_cl) + 0.5;
logp_auc02_arm2_ = zeros(length(niteration_),n_cl);
auc20_arm2_ = zeros(length(niteration_),n_cl) + 0.5;
logp_auc20_arm2_ = zeros(length(niteration_),n_cl);
corr_arm2_ = zeros(length(niteration_),n_cl);
beta00_arm2_ = zeros(length(niteration_),n_cl);
logp_beta00_arm2_ = zeros(length(niteration_),n_cl);
beta02_arm2_ = zeros(length(niteration_),n_cl);
logp_beta02_arm2_ = zeros(length(niteration_),n_cl);
beta20_arm2_ = zeros(length(niteration_),n_cl);
logp_beta20_arm2_ = zeros(length(niteration_),n_cl);
if (flag_reverse==0); mr_D_arm1_full = mr_A_arm1_full; mr_X_arm1_full = mr_Z_arm1_full; end;
if (flag_reverse==1); mr_D_arm1_full = mr_Z_arm1_full; mr_X_arm1_full = mr_A_arm1_full; end;
[cauc02_arm1_avg_,cauc02_arm1_min_] = p_cauc_0(mds_arm1_(find(mr_X_arm1_full),1: 2),mds_arm1_(find(mr_D_arm1_full),1: 2),zeros(sum(mr_X_arm1_full),1),zeros(sum(mr_D_arm1_full),1),1024*8);
[cauc20_arm1_avg_,cauc20_arm1_min_] = p_cauc_0(mds_arm1_(find(mr_X_arm1_full),1:20),mds_arm1_(find(mr_D_arm1_full),1:20),zeros(sum(mr_X_arm1_full),1),zeros(sum(mr_D_arm1_full),1),1024*8);
%%%%%%%%%%%%%%%%;
for cl_num_arm2 = [1:4];
%%%%%%%%%%%%%%%%;
if (cl_num_arm2~=cl_num_arm1);
%disp(sprintf(' %% cl_num_arm1 %d cl_num_arm2 %d',cl_num_arm1,cl_num_arm2));
%%%%%%%%%%%%%%%%;
for ni=1:length(niteration_);
niteration = niteration_(ni);
disp(sprintf(' %% cl_num_arm1 %d cl_num_arm2 %d: arm1 ni %d/%d niteration %d',cl_num_arm1,cl_num_arm2,ni,length(niteration_),niteration));
pca_proj_arm1_infix = sprintf('pca_proj_arm1_ni%d_tst%d',niteration,cl_num_arm2);
try;
%%%%%%%%;
DnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm1_infix,pca_rank,pca_b_mlt));
XnV_arm1_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm1_infix,pca_rank,pca_b_mlt));
if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm1_ = sum(abs(DnV_arm1_),2); XnV_arm1_ = sum(abs(XnV_arm1_),2); end;%if (strcmp(flag_dex_vs_lak,'lak'));
if (flag_reverse==0); mr_D_arm1_full = mr_A_arm1_full; mr_X_arm1_full = mr_Z_arm1_full; end;
if (flag_reverse==1); mr_D_arm1_full = mr_Z_arm1_full; mr_X_arm1_full = mr_A_arm1_full; end;
%%%%%%%%;
auc00_arm1_(ni,cl_num_arm2) = auc_0(XnV_arm1_(find(mr_X_arm1_full),1),DnV_arm1_(find(mr_D_arm1_full),1));
if (auc00_arm1_(ni,cl_num_arm2)>=0.5); flag_flip00_(ni,cl_num_arm2)=0; end;
if (auc00_arm1_(ni,cl_num_arm2) <0.5); flag_flip00_(ni,cl_num_arm2)=1; end;
if (flag_flip00_(ni,cl_num_arm2)); auc00_arm1_(ni,cl_num_arm2) = 1.0 - auc00_arm1_(ni,cl_num_arm2); end;% if flag_flip00_(ni,cl_num_arm2);
logp_auc00_arm1_(ni,cl_num_arm2) = logp_auc_0(auc00_arm1_(ni,cl_num_arm2),min(sum(mr_D_arm1_full),sum(mr_X_arm1_full)));
%%%%%%%%;
auc02_arm1_(ni,cl_num_arm2) = cauc_0(XnV_arm1_(find(mr_X_arm1_full),1),DnV_arm1_(find(mr_D_arm1_full),1),mds_arm1_(find(mr_X_arm1_full),1: 2),mds_arm1_(find(mr_D_arm1_full),1: 2));
if (auc02_arm1_(ni,cl_num_arm2)>=0.5); flag_flip02_(ni,cl_num_arm2)=0; end;
if (auc02_arm1_(ni,cl_num_arm2) <0.5); flag_flip02_(ni,cl_num_arm2)=1; end;
if (flag_flip02_(ni,cl_num_arm2)); auc02_arm1_(ni,cl_num_arm2) = 1.0 - auc02_arm1_(ni,cl_num_arm2); end;% if flag_flip02_(ni,cl_num_arm2);
logp_auc02_arm1_(ni,cl_num_arm2) = log(max(1,length(find(cauc02_arm1_avg_>auc02_arm1_(ni,cl_num_arm2))))/length(cauc02_arm1_avg_));
%%%%%%%%;
auc20_arm1_(ni,cl_num_arm2) = cauc_0(XnV_arm1_(find(mr_X_arm1_full),1),DnV_arm1_(find(mr_D_arm1_full),1),mds_arm1_(find(mr_X_arm1_full),1:20),mds_arm1_(find(mr_D_arm1_full),1:20));
if (auc20_arm1_(ni,cl_num_arm2)>=0.5); flag_flip20_(ni,cl_num_arm2)=0; end;
if (auc20_arm1_(ni,cl_num_arm2) <0.5); flag_flip20_(ni,cl_num_arm2)=1; end;
if (flag_flip20_(ni,cl_num_arm2)); auc20_arm1_(ni,cl_num_arm2) = 1.0 - auc20_arm1_(ni,cl_num_arm2); end;% if flag_flip20_(ni,cl_num_arm2);
logp_auc20_arm1_(ni,cl_num_arm2) = log(max(1,length(find(cauc20_arm1_avg_>auc20_arm1_(ni,cl_num_arm2))))/length(cauc20_arm1_avg_));
%%%%%%%%;
[beta00_arm1,dev00_arm1,stats00_arm1] = mnrfit([DnV_arm1_(find(mr_D_arm1_full),1) ; XnV_arm1_(find(mr_X_arm1_full),1)],[ones(sum(mr_D_arm1_full),1) ; 1 + ones(sum(mr_X_arm1_full),1)]);
beta00_arm1_(ni,cl_num_arm2) = beta00_arm1(2);
logp_beta00_arm1_(ni,cl_num_arm2) = log(max(1e-255,stats00_arm1.p(2)));
if (flag_flip00_(ni,cl_num_arm2)); beta00_arm1_(ni,cl_num_arm2) = -beta00_arm1_(ni,cl_num_arm2); end;% if flag_flip00_(ni,cl_num_arm2);
%%%%%%%%;
[beta02_arm1,dev02_arm1,stats02_arm1] = mnrfit([DnV_arm1_(find(mr_D_arm1_full),1) , mds_arm1_(find(mr_D_arm1_full),1: 2) ; XnV_arm1_(find(mr_X_arm1_full),1) , mds_arm1_(find(mr_X_arm1_full),1: 2)],[ones(sum(mr_D_arm1_full),1) ; 1 + ones(sum(mr_X_arm1_full),1)]);
beta02_arm1_(ni,cl_num_arm2) = beta02_arm1(2);
logp_beta02_arm1_(ni,cl_num_arm2) = log(max(1e-255,stats02_arm1.p(2)));
if (flag_flip02_(ni,cl_num_arm2)); beta02_arm1_(ni,cl_num_arm2) = -beta02_arm1_(ni,cl_num_arm2); end;% if flag_flip02_(ni,cl_num_arm2);
%%%%%%%%;
[beta20_arm1,dev20_arm1,stats20_arm1] = mnrfit([DnV_arm1_(find(mr_D_arm1_full),1) , mds_arm1_(find(mr_D_arm1_full),1:20) ; XnV_arm1_(find(mr_X_arm1_full),1) , mds_arm1_(find(mr_X_arm1_full),1:20)],[ones(sum(mr_D_arm1_full),1) ; 1 + ones(sum(mr_X_arm1_full),1)]);
beta20_arm1_(ni,cl_num_arm2) = beta20_arm1(2);
logp_beta20_arm1_(ni,cl_num_arm2) = log(max(1e-255,stats20_arm1.p(2)));
if (flag_flip20_(ni,cl_num_arm2)); beta20_arm1_(ni,cl_num_arm2) = -beta20_arm1_(ni,cl_num_arm2); end;% if flag_flip20_(ni,cl_num_arm2);
%%%%%%%%;
corr_arm1_(ni,cl_num_arm2) = corr( [XnV_arm1_(find(mr_X_arm1_full),1) ; DnV_arm1_(find(mr_D_arm1_full),1)] , [zeros(sum(mr_X_arm1_full),1) ; ones(sum(mr_D_arm1_full),1)]);
if (flag_flip00_(ni,cl_num_arm2)); corr_arm1_(ni,cl_num_arm2) = -corr_arm1_(ni,cl_num_arm2); end;%if (flag_flip00_(ni,cl_num_arm2));
%%%%%%%%;
catch; disp(sprintf(' %% Warning! could not process AnV ZnV for %s',pca_proj_arm1_infix)); end;%try;
end;%for ni=1:length(niteration_);
%%%%%%%%%%%%%%%%;
string_prefix_arm2 = sprintf('PGC_cl%d_maf01',cl_num_arm2);
dir__in_arm2 = sprintf('%s/dir_%s',dir_trunk,string_prefix_arm2);
tmpchar = sprintf('%s/PGC_cl%d_maf01_mr_A_full.b16',dir__in_arm2,cl_num_arm2);
[bitj,nrows,ncols] = tutorial_binary_getsize(tmpchar); mr_A_arm2_full = tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0;
tmpchar = sprintf('%s/PGC_cl%d_maf01_mr_Z_full.b16',dir__in_arm2,cl_num_arm2);
[bitj,nrows,ncols] = tutorial_binary_getsize(tmpchar); mr_Z_arm2_full = tutorial_binary_uncompress(tmpchar,1:nrows,1:ncols)>0;
%%%%%%%%%%%%%%%%;
fcheck(sprintf('%s/%s_fam.ext',dir__in_arm2,string_prefix_arm2));
fid = fopen(sprintf('%s/%s_fam.ext',dir__in_arm2,string_prefix_arm2)); fam_arm2_ = textscan(fid,'%s %s %s %s %d %d %s','headerlines',0); fclose(fid);
n_patient_F = length(fam_arm2_{1}); fam_arm2_name_ = cell(n_patient_F,1); for np=1:n_patient_F; fam_arm2_name_{np} = sprintf('%s%s%s',fam_arm2_{1}{np},'&',fam_arm2_{2}{np}); end;%for np=1:n_patient_F;
[~,ifam_arm2_,imds_arm2_] = intersect(fam_arm2_name_,mds_name_,'stable'); if (length(ifam_arm2_)<n_patient_F); disp('Warning! fam_arm2_name_ not a subset of mds_name_'); end; mds_arm2_ = mds_(imds_arm2_,:);
%%%%%%%%%%%%%%%%;
if (flag_reverse==0); mr_D_arm2_full = mr_A_arm2_full; mr_X_arm2_full = mr_Z_arm2_full; end;
if (flag_reverse==1); mr_D_arm2_full = mr_Z_arm2_full; mr_X_arm2_full = mr_A_arm2_full; end;
[cauc02_arm2_avg_,cauc02_arm2_min_] = p_cauc_0(mds_arm2_(find(mr_X_arm2_full),1: 2),mds_arm2_(find(mr_D_arm2_full),1: 2),zeros(sum(mr_X_arm2_full),1),zeros(sum(mr_D_arm2_full),1),1024*8);
[cauc20_arm2_avg_,cauc20_arm2_min_] = p_cauc_0(mds_arm2_(find(mr_X_arm2_full),1:20),mds_arm2_(find(mr_D_arm2_full),1:20),zeros(sum(mr_X_arm2_full),1),zeros(sum(mr_D_arm2_full),1),1024*8);
%%%%%%%%%%%%%%%%;
for ni=1:length(niteration_);
niteration = niteration_(ni);
disp(sprintf(' %% cl_num_arm1 %d cl_num_arm2 %d: arm2 ni %d/%d niteration %d',cl_num_arm1,cl_num_arm2,ni,length(niteration_),niteration));
pca_proj_arm2_infix = sprintf('pca_proj_arm2_ni%d_tst%d',niteration,cl_num_arm2);
try;
DnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_AnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm2_infix,pca_rank,pca_b_mlt));
XnV_arm2_ = mda_read_r8(sprintf('%s/%s_k%d_B%d_ZnV_.mda',dir_out_s0000_pca_arm1,pca_proj_arm2_infix,pca_rank,pca_b_mlt));
if (strcmp(flag_dex_vs_lak,'lak')); DnV_arm2_ = sum(abs(DnV_arm2_),2); XnV_arm2_ = sum(abs(XnV_arm2_),2); end;%if (strcmp(flag_dex_vs_lak,'lak'));
if (flag_reverse==0); mr_D_arm2_full = mr_A_arm2_full; mr_X_arm2_full = mr_Z_arm2_full; end;
if (flag_reverse==1); mr_D_arm2_full = mr_Z_arm2_full; mr_X_arm2_full = mr_A_arm2_full; end;
%%%%%%%%;
auc00_arm2_(ni,cl_num_arm2) = auc_0(XnV_arm2_(find(mr_X_arm2_full),1),DnV_arm2_(find(mr_D_arm2_full),1));
if (flag_flip00_(ni,cl_num_arm2)); auc00_arm2_(ni,cl_num_arm2) = 1.0 - auc00_arm2_(ni,cl_num_arm2); end;%if (flag_flip00_(ni,cl_num_arm2)); 
logp_auc00_arm2_(ni,cl_num_arm2) = logp_auc_0(auc00_arm2_(ni,cl_num_arm2),min(sum(mr_D_arm2_full),sum(mr_X_arm2_full)));
%%%%%%%%;
auc02_arm2_(ni,cl_num_arm2) = cauc_0(XnV_arm2_(find(mr_X_arm2_full),1),DnV_arm2_(find(mr_D_arm2_full),1),mds_arm2_(find(mr_X_arm2_full),1: 2),mds_arm2_(find(mr_D_arm2_full),1: 2));
if (flag_flip02_(ni,cl_num_arm2)); auc02_arm2_(ni,cl_num_arm2) = 1.0 - auc02_arm2_(ni,cl_num_arm2); end;% if flag_flip02_(ni,cl_num_arm2);
logp_auc02_arm2_(ni,cl_num_arm2) = log(max(1,length(find(cauc02_arm2_avg_>auc02_arm2_(ni,cl_num_arm2))))/length(cauc02_arm2_avg_));
%%%%%%%%;
auc20_arm2_(ni,cl_num_arm2) = cauc_0(XnV_arm2_(find(mr_X_arm2_full),1),DnV_arm2_(find(mr_D_arm2_full),1),mds_arm2_(find(mr_X_arm2_full),1:20),mds_arm2_(find(mr_D_arm2_full),1:20));
if (flag_flip20_(ni,cl_num_arm2)); auc20_arm2_(ni,cl_num_arm2) = 1.0 - auc20_arm2_(ni,cl_num_arm2); end;% if flag_flip20_(ni,cl_num_arm2);
logp_auc20_arm2_(ni,cl_num_arm2) = log(max(1,length(find(cauc20_arm2_avg_>auc20_arm2_(ni,cl_num_arm2))))/length(cauc20_arm2_avg_));
%%%%%%%%;
[beta00_arm2,dev00_arm2,stats00_arm2] = mnrfit([DnV_arm2_(find(mr_D_arm2_full),1) ; XnV_arm2_(find(mr_X_arm2_full),1)],[ones(sum(mr_D_arm2_full),1) ; 1 + ones(sum(mr_X_arm2_full),1)]);
beta00_arm2_(ni,cl_num_arm2) = beta00_arm2(2);
logp_beta00_arm2_(ni,cl_num_arm2) = log(max(1e-255,stats00_arm2.p(2)));
if (flag_flip00_(ni,cl_num_arm2)); beta00_arm2_(ni,cl_num_arm2) = -beta00_arm2_(ni,cl_num_arm2); end;% if flag_flip00_(ni,cl_num_arm2);
%%%%%%%%;
[beta02_arm2,dev02_arm2,stats02_arm2] = mnrfit([DnV_arm2_(find(mr_D_arm2_full),1) , mds_arm2_(find(mr_D_arm2_full),1: 2) ; XnV_arm2_(find(mr_X_arm2_full),1) , mds_arm2_(find(mr_X_arm2_full),1: 2)],[ones(sum(mr_D_arm2_full),1) ; 1 + ones(sum(mr_X_arm2_full),1)]);
beta02_arm2_(ni,cl_num_arm2) = beta02_arm2(2);
logp_beta02_arm2_(ni,cl_num_arm2) = log(max(1e-255,stats02_arm2.p(2)));
if (flag_flip02_(ni,cl_num_arm2)); beta02_arm2_(ni,cl_num_arm2) = -beta02_arm2_(ni,cl_num_arm2); end;% if flag_flip02_(ni,cl_num_arm2);
%%%%%%%%;
[beta20_arm2,dev20_arm2,stats20_arm2] = mnrfit([DnV_arm2_(find(mr_D_arm2_full),1) , mds_arm2_(find(mr_D_arm2_full),1:20) ; XnV_arm2_(find(mr_X_arm2_full),1) , mds_arm2_(find(mr_X_arm2_full),1:20)],[ones(sum(mr_D_arm2_full),1) ; 1 + ones(sum(mr_X_arm2_full),1)]);
beta20_arm2_(ni,cl_num_arm2) = beta20_arm2(2);
logp_beta20_arm2_(ni,cl_num_arm2) = log(max(1e-255,stats20_arm2.p(2)));
if (flag_flip20_(ni,cl_num_arm2)); beta20_arm2_(ni,cl_num_arm2) = -beta20_arm2_(ni,cl_num_arm2); end;% if flag_flip20_(ni,cl_num_arm2);
%%%%%%%%;
corr_arm2_(ni,cl_num_arm2) = corr( [XnV_arm2_(find(mr_X_arm2_full),1) ; DnV_arm2_(find(mr_D_arm2_full),1)] , [zeros(sum(mr_X_arm2_full),1) ; ones(sum(mr_D_arm2_full),1)]);
if (flag_flip00_(ni,cl_num_arm2)); corr_arm2_(ni,cl_num_arm2) = -corr_arm2_(ni,cl_num_arm2); end;%if (flag_flip00_(ni,cl_num_arm2)); 
%%%%%%%%;
catch; disp(sprintf(' %% Warning! could not process AnV ZnV for %s',pca_proj_arm2_infix)); end;%try;
end;%for ni=1:length(niteration_);
%%%%%%%%%%%%%%%%;
end;%if (cl_num_arm2~=cl_num_arm1);
%%%%%%%%%%%%%%%%;
end;%for cl_num_arm2 = [1:4];
%%%%%%%%%%%%%%%%;
save(fname_mat,...
'n_cl',...
'auc00_arm1_',...
'logp_auc00_arm1_',...
'auc02_arm1_',...
'logp_auc02_arm1_',...
'auc20_arm1_',...
'logp_auc20_arm1_',...
'corr_arm1_',...
'beta00_arm1_',...
'logp_beta00_arm1_',...
'beta02_arm1_',...
'logp_beta02_arm1_',...
'beta20_arm1_',...
'logp_beta20_arm1_',...
'flag_flip00_',...
'flag_flip02_',...
'flag_flip20_',...
'auc00_arm2_',...
'logp_auc00_arm2_',...
'auc02_arm2_',...
'logp_auc02_arm2_',...
'auc20_arm2_',...
'logp_auc20_arm2_',...
'corr_arm2_',...
'beta00_arm2_',...
'logp_beta00_arm2_',...
'beta02_arm2_',...
'logp_beta02_arm2_',...
'beta20_arm2_',...
'logp_beta20_arm2_');
%%%%%%%%%%%%%%%%;
end;%if (~exist(fname_mat,'file')); 

figure(2); clf; lmax = 10;
Msize = 10;
%%%%%%%%%%%%%%%%;
for cl_num_arm2 = [1:4];
%%%%%%%%%%%%%%%%;
if (cl_num_arm2~=cl_num_arm1);
disp(sprintf(' %% cl_num_arm1 %d cl_num_arm2 %d column %d',cl_num_arm1,cl_num_arm2,cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)));
%%%%%%%%%%%%%%%%;
subplot(4,3,0*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,auc00_arm1_(:,cl_num_arm2),'ro-','MarkerSize',Msize); 
plot(niteration_,auc02_arm1_(:,cl_num_arm2),'rs-','MarkerSize',Msize); 
plot(niteration_,auc20_arm1_(:,cl_num_arm2),'r*-','MarkerSize',Msize); 
hold off;
xlabel('iteration'); ylabel('auc arm1'); xlim([min(niteration_),max(niteration_)]);
subplot(4,3,1*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,min(lmax,-logp_auc00_arm1_(:,cl_num_arm2)),'ro-','MarkerSize',Msize); 
plot(niteration_,min(lmax,-logp_auc02_arm1_(:,cl_num_arm2)),'rs-','MarkerSize',Msize); 
plot(niteration_,min(lmax,-logp_auc20_arm1_(:,cl_num_arm2)),'r*-','MarkerSize',Msize); 
plot(niteration_,0*niteration_ + -log(0.05),'k--');
plot(niteration_,0*niteration_ + -log(0.01),'k--');
hold off; ylim([0,lmax]);
xlabel('iteration'); ylabel('-logp arm1'); xlim([min(niteration_),max(niteration_)]);
subplot(4,3,2*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,beta00_arm1_(:,cl_num_arm2),'ro-','MarkerSize',Msize); 
plot(niteration_,beta02_arm1_(:,cl_num_arm2),'rs-','MarkerSize',Msize); 
plot(niteration_,beta20_arm1_(:,cl_num_arm2),'r*-','MarkerSize',Msize); 
hold off;
xlabel('iteration'); ylabel('beta arm1'); xlim([min(niteration_),max(niteration_)]);
subplot(4,3,3*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1));
hold on;
plot(niteration_,min(lmax,-logp_beta00_arm1_(:,cl_num_arm2)),'ro-','MarkerSize',Msize); 
plot(niteration_,min(lmax,-logp_beta02_arm1_(:,cl_num_arm2)),'rs-','MarkerSize',Msize); 
plot(niteration_,min(lmax,-logp_beta20_arm1_(:,cl_num_arm2)),'r*-','MarkerSize',Msize); 
plot(niteration_,0*niteration_ + -log(0.05),'k--');
plot(niteration_,0*niteration_ + -log(0.01),'k--');
hold off; ylim([0,lmax]);
xlabel('iteration'); ylabel('-logp beta arm1'); xlim([min(niteration_),max(niteration_)]);
%subplot(4,3,4*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1));plot(niteration_,corr_arm1_(:,cl_num_arm2),'rx-','MarkerSize',Msize); 
%xlabel('iteration'); ylabel('corr arm1'); xlim([min(niteration_),max(niteration_)]);
%%%%%%%%%%%%%%%%;
subplot(4,3,0*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,auc00_arm2_(:,cl_num_arm2),'bo-','MarkerSize',Msize); 
plot(niteration_,auc02_arm2_(:,cl_num_arm2),'bs-','MarkerSize',Msize); 
plot(niteration_,auc20_arm2_(:,cl_num_arm2),'b*-','MarkerSize',Msize); 
hold off;
xlabel('iteration'); ylabel('auc arm2'); xlim([min(niteration_),max(niteration_)]);
title(sprintf('trn%d tst%d: auc',cl_num_arm1,cl_num_arm2));
subplot(4,3,1*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,min(lmax,-logp_auc00_arm2_(:,cl_num_arm2)),'bo-','MarkerSize',Msize);
plot(niteration_,min(lmax,-logp_auc02_arm2_(:,cl_num_arm2)),'bs-','MarkerSize',Msize);
plot(niteration_,min(lmax,-logp_auc20_arm2_(:,cl_num_arm2)),'b*-','MarkerSize',Msize);
plot(niteration_,0*niteration_ + -log(0.05),'k--');
plot(niteration_,0*niteration_ + -log(0.01),'k--');
hold off; ylim([0,lmax]);
xlabel('iteration'); ylabel('-logp arm2'); xlim([min(niteration_),max(niteration_)]);
title(sprintf('trn%d tst%d: -logp(auc)',cl_num_arm1,cl_num_arm2));
subplot(4,3,2*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,beta00_arm2_(:,cl_num_arm2),'bo-','MarkerSize',Msize); 
plot(niteration_,beta02_arm2_(:,cl_num_arm2),'bs-','MarkerSize',Msize); 
plot(niteration_,beta20_arm2_(:,cl_num_arm2),'b*-','MarkerSize',Msize); 
hold off;
xlabel('iteration'); ylabel('beta arm2'); xlim([min(niteration_),max(niteration_)]);
title(sprintf('trn%d tst%d: beta',cl_num_arm1,cl_num_arm2));
subplot(4,3,3*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1)); 
hold on;
plot(niteration_,min(lmax,-logp_beta00_arm2_(:,cl_num_arm2)),'bo-','MarkerSize',Msize); 
plot(niteration_,min(lmax,-logp_beta02_arm2_(:,cl_num_arm2)),'bs-','MarkerSize',Msize); 
plot(niteration_,min(lmax,-logp_beta20_arm2_(:,cl_num_arm2)),'b*-','MarkerSize',Msize); 
plot(niteration_,0*niteration_ + -log(0.05),'k--');
plot(niteration_,0*niteration_ + -log(0.01),'k--');
hold off; ylim([0,lmax]);
xlabel('iteration'); ylabel('-logp beta arm2'); xlim([min(niteration_),max(niteration_)]);
title(sprintf('trn%d tst%d: -logp(beta)',cl_num_arm1,cl_num_arm2));
%subplot(5,3,4*3 + cl_num_arm2 - (cl_num_arm2>=cl_num_arm1));plot(niteration_,corr_arm2_(:,cl_num_arm2),'bo-','MarkerSize',Msize); 
%xlabel('iteration'); ylabel('corr arm2'); xlim([min(niteration_),max(niteration_)]);
%title(sprintf('trn%d tst%d: corr',cl_num_arm1,cl_num_arm2));
%%%%%%%%%%%%%%%%;
end;%if (cl_num_arm2~=cl_num_arm1);
%%%%%%%%%%%%%%%%;
end;%for cl_num_arm2 = [1:4];
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_pre = sprintf('%s/%s_pca_collect_ver6',dir_out_s0000_pca_arm1,string_name_s0000);
print('-djpeg',sprintf('%s.jpg',fname_pre));
print('-depsc',sprintf('%s.eps',fname_pre));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

