function output_ = rank_normalize_0(input_,str_margin);
% rank normalizes each column of input_. ;
%%%%%%%%;
if nargin<2; str_margin='row';end;
%%%%%%%%;
if (strcmp(str_margin,'row'));
[n_r,n_c] = size(input_);
output_ = zeros(n_r,n_c);
for nc=1:n_c;
tmp_i_ = input_(:,nc);
[tmp_u_,i_to_u_,u_to_i_] = unique(tmp_i_,'sorted');
if (length(tmp_u_)==n_r); output_(:,nc) = u_to_i_; end;
if (length(tmp_u_)<n_r);
[~,tmp_j_] = sort(tmp_i_); [~,tmp_j_] = sort(tmp_j_);
tmp_o_ = zeros(n_r,1);
for nl=1:length(tmp_u_);
tmp_u = tmp_u_(nl); 
tmp_l_ = find(u_to_i_==nl);
tmp_o_(tmp_l_) = mean(tmp_j_(tmp_l_));
end;%for nl=1:length(tmp_u_);
output_(:,nc) = tmp_o_;
end;%if (length(tmp_u_)<n_r);
end;%for nc=1:n_c;
end;%if (strcmp(str_margin,'row'));
%%%%%%%%;
if (strcmp(str_margin,'col'));
output_ = transpose(rank_normalize_0(transpose(input_),'row'));
end;%if (strcmp(str_margin,'col'));
