function A__ = read_mtx_0(fname);
if (~exist(fname,'file')); disp(sprintf(' %% Warning, %s not found in read_mtx_0',fname)); end;
verbose=1;
fp = fopen(fname,'r');
flag_continue=1; n_header=0; nline=0;
while flag_continue;
tmp_ = fgetl(fp);
if (verbose); disp(sprintf(' nline %d: %s',nline,tmp_)); end;
if (tmp_(1)=='%'); flag_continue=1; n_header = n_header+1; end;
if (tmp_(1)~='%'); flag_continue=0; end;
nline = nline+1;
end;%while flag_continue;
if (verbose); disp(sprintf(' %% n_header %d',n_header)); end;
if (verbose); disp(sprintf(' %% dimensions: %s',tmp_)); end;
tmp_n_ = str2num(tmp_);
n_row = tmp_n_(1);
n_col = tmp_n_(2);
n_nonzero = tmp_n_(3);
frewind(fp);
tmp_t = tic();
tmp_ = textscan(fp,'%d%d%d','headerlines',n_header+1);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% textscan: %0.4fs',tmp_t)); end;
tmp_n_row_ = tmp_{1};
tmp_n_col_ = tmp_{2};
tmp_n_val_ = tmp_{3};
tmp_t = tic();
A__ = sparse(tmp_n_row_,tmp_n_col_,cast(tmp_n_val_,'double'),n_row,n_col);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% sparse: %0.4fs',tmp_t)); end;
if (nnz(A__)~=n_nonzero); disp(sprintf(' %% Warning, nnz(A__) = %d ~= %d',nnz(A__),n_nonzero)); end;
fclose(fp);
