function output = shygecln(k_,N,K,n_);
% approximation to the log of the (upper) cumulative distribution of the hypergeometric-distribution. ;
%%%%%%%%;
if nargin<1;
N = 500; K = 200; M = N-K;
k_ = round(linspace(1,K,512)); m_ = min(M,round(1.25*k_+15)); n_ = m_+k_;
for nl=1:length(k_);
ln_1_(nl) = log(hygecdf(k_(nl),N,K,n_(nl),'upper'));
end;%for nl=1:length(k_);
ln_2_ = shygecln(k_,N,K,n_);
subplot(1,2,1);
plot(k_,ln_1_,'k.-',k_,ln_2_,'ro-');
xlabel('k');ylabel('log(hyge(k,N,K,n))');
subplot(1,2,2);
plot(k_,log10(abs(ln_1_-ln_2_)./abs(ln_1_)),'kx-');
xlabel('k');ylabel('log10(relative error in log(hyge(k,N,K,n))');
disp('returning');return;
end;%if nargin<1;
%%%%%%%%%%%%%%%%;
k_ = min(K,k_+0.5); %n_ = max(0,n_-0.5);
M = N-K; m_ = max(0,n_-k_);
shyge_ = shyge(k_,N,K,n_);
dtshyge_ = log(K-k_) - log(k_) - log(M-m_) + log(m_);
dttshyge_ = - ( M./(m_ .* (M - m_)) + K./(k_ .* (K - k_)) );
x_ = sqrt(-dttshyge_/2) .* ( 0  + dtshyge_ ./ (2*dttshyge_/2) ) ;
z_ = erfcln(x_);
shygecln_ = shyge_ + (-dtshyge_ .* dtshyge_ ./ (2*dttshyge_)) - 0.5*log(-dttshyge_/2) + log(sqrt(pi)/2) + z_;
output = shygecln_;
