function [C_,niteration] = svd_impute(B_,ij_missed_,n_rank,n_iteration,tolerance);
% simple svd-based imputation. ;
if nargin<1;
n_N = 128*4;
A_ = randn(n_N,3);
[tmp_U_,tmp_S_,tmp_V_] = svds(A_,3); tmp_S_ = diag(diag(tmp_S_).*[1;1;0.125]);
A_ = tmp_U_*tmp_S_*transpose(tmp_V_);
ij_missed_ = randperm(numel(A_)); ij_missed_ = ij_missed_(1:floor(numel(A_)/4));
B_ = A_; B_(ij_missed_) = 0;
tmp_nn_ = find(B_(:,1)==0 | B_(:,2)==0 | B_(:,3)==0);
[C_,niteration] = svd_impute(B_,ij_missed_,2);
figure;clf;
subplot(1,2,1); 
hold on;
plot3(B_(tmp_nn_,1),B_(tmp_nn_,2),B_(tmp_nn_,3),'ro','MarkerSize',15); 
plot3(B_(tmp_nn_,1),B_(tmp_nn_,2),B_(tmp_nn_,3),'rx','MarkerSize',15); 
plot3(A_(:,1),A_(:,2),A_(:,3),'b.','MarkerSize',25); 
for nij=1:length(tmp_nn_);
nN = tmp_nn_(nij);
plot3([A_(nN,1),B_(nN,1)],[A_(nN,2),B_(nN,2)],[A_(nN,3),B_(nN,3)],'r-');
end;%for nij=1:length(tmp_nn_);
hold off;
title('data missing (blue true)');
subplot(1,2,2); hold on; 
plot3(C_(tmp_nn_,1),C_(tmp_nn_,2),C_(tmp_nn_,3),'ro','MarkerSize',15); 
plot3(C_(tmp_nn_,1),C_(tmp_nn_,2),C_(tmp_nn_,3),'rx','MarkerSize',15); 
plot3(A_(:,1),A_(:,2),A_(:,3),'b.','MarkerSize',25); 
for nij=1:length(tmp_nn_);
nN = tmp_nn_(nij);
plot3([A_(nN,1),C_(nN,1)],[A_(nN,2),C_(nN,2)],[A_(nN,3),C_(nN,3)],'r-');
end;%for nij=1:length(tmp_nn_);
hold off;
title(sprintf('data imputed (ni%d) (blue true)',niteration));
figbig;
disp('returning'); return;
end;%if nargin<1;

if nargin<2; ij_missed_ = find(B_==0); end;
if nargin<3; n_rank = 1; end;
if nargin<4; n_iteration = 256; end;
if nargin<5; tolerance = 1e-6; end;

verbose_flag=0;
ij_filled_ = setdiff(1:numel(B_),ij_missed_);
e_ = zeros(n_iteration,1);
C_ = B_;
C_(ij_missed_) = median(B_(ij_filled_));
continue_flag=1;
niteration=0;
while continue_flag;
niteration = niteration+1;
[tmp_U_,tmp_S_,tmp_V_] = svds(C_,min(min(size(C_)),n_rank));
tmp_B_ = tmp_U_*tmp_S_*transpose(tmp_V_);
tmp_val_ = C_(ij_missed_);
C_(ij_missed_) = tmp_B_(ij_missed_);
e_(niteration) = norm(C_(ij_missed_)-tmp_val_,'fro')./norm(C_(ij_missed_),'fro');
if e_(niteration) < tolerance; continue_flag=0; end;
if niteration>=n_iteration; continue_flag=0; end;
end;%for niteration=1:n_iteration;

if (verbose_flag);
figure;clf;
subplot(1,2,1);
plot(1:niteration,e_(1:niteration),'k.-');
xlabel('iteration');ylabel('error');title('error in svd imputation');
subplot(1,2,2);
plot(1:niteration,log10(e_(1:niteration)),'k.-');
xlabel('iteration');ylabel('log10(error)');title('log10(error) in svd imputation');
end;%if (verbose_flag);
