%%%%%%%%;
% simple clustering, no covariate correction. ;
%%%%%%%%;
clear;
platform = 'access1';
%platform = 'OptiPlex';
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;

dir_trunk = sprintf('/%s/rangan/dir_bcc/dir_jamison',string_root);
dir_data = sprintf('%s/data_summary_20190730',dir_trunk);
dir_mat = sprintf('%s/dir_mat',dir_trunk);
dir_jpg = sprintf('%s/dir_jpg',dir_trunk);
dir_cluster = sprintf('%s/dir_loader_cluster',dir_trunk);
%%%%%%%%;
fp_label_A_ = fopen(sprintf('%s/dir_mat/str_CLabel_sub_.nsv',dir_trunk),'r');
str_label_A_ = textscan(fp_label_A_,'%s'); fclose(fp_label_A_);
n_u = numel(str_label_A_{1});
label_A_ = label_str_to_enum_0(str_label_A_{1});
%%%%%%%%;
for prefix_normalization_ = {'li16f','li16f_clogr','liXf','liXf_clogr','fill'};
E_xxxx_ = textread(sprintf('%s/dir_mat/E_%s_.tsv',dir_trunk,prefix_normalization_{1})); E_xxxx_ = E_xxxx_(:,1:end-1);
I_xxxx_ = textread(sprintf('%s/dir_mat/I_%s_.tsv',dir_trunk,prefix_normalization_{1})); I_xxxx_ = I_xxxx_(:,1:end-1);
test_loader_cluster_wrap_4(dir_trunk,label_A_,E_xxxx_,I_xxxx_,prefix_normalization_{1});
end;%for prefix_normalization_ = {'li16f','li16f_clogr','liXf','liXf_clogr','fill'};
