function ...
[] = ...
test_loader_cluster_wrap_4( ...
 dir_trunk ...
,str_label_A_ ...
,E_ ...
,I_ ...
,str_infix ...
,date_diff_threshold ...
,flag_force_create_mat ...
,flag_force_create_tmp ...
);
% simple clustering, no covariate correction. ;

%%%%%%%%;
na=0;
if (nargin<1+na); dir_trunk=pwd; end; na=na+1;
if (nargin<1+na); str_label_A_=[]; end; na=na+1;
if (nargin<1+na); E_=[]; end; na=na+1;
if (nargin<1+na); I_=[]; end; na=na+1;
if (nargin<1+na); str_infix=[]; end; na=na+1;
if (nargin<1+na); date_diff_threshold=[]; end; na=na+1;
if (nargin<1+na); flag_force_create_mat=[]; end; na=na+1;
if (nargin<1+na); flag_force_create_tmp=[]; end; na=na+1;
%%%%;
if ( isempty(date_diff_threshold)); date_diff_threshold = 1.5; end;
if ( isempty(flag_force_create_mat)); flag_force_create_mat = 0; end;
if ( isempty(flag_force_create_tmp)); flag_force_create_tmp = 0; end;
%%%%%%%%;

dir_base = sprintf('%s/dir_loader_cluster',dir_trunk);
if (~exist(dir_base,'dir')); disp(sprintf(' %% mkdir %s',dir_base)); mkdir(dir_base); end;
str_prefix = sprintf('E_%s',str_infix); dir_cluster = sprintf('%s/dir_%s_cluster',dir_base,str_prefix);
if (~exist(dir_cluster,'dir')); disp(sprintf(' %% mkdir %s',dir_cluster)); mkdir(dir_cluster); end;
test_loader_cluster_2( ...
 dir_cluster ...
,str_label_A_ ...
,E_ ...
,date_diff_threshold ...
,flag_force_create_mat ...
,flag_force_create_tmp ...
);
str_prefix = sprintf('I_%s',str_infix); dir_cluster = sprintf('%s/dir_%s_cluster',dir_base,str_prefix);
if (~exist(dir_cluster,'dir')); disp(sprintf(' %% mkdir %s',dir_cluster)); mkdir(dir_cluster); end;
test_loader_cluster_2( ...
 dir_cluster ...
,str_label_A_ ...
,I_ ...
,date_diff_threshold ...
,flag_force_create_mat ...
,flag_force_create_tmp ...
);
str_prefix = sprintf('EI_%s',str_infix); dir_cluster = sprintf('%s/dir_%s_cluster',dir_base,str_prefix);
if (~exist(dir_cluster,'dir')); disp(sprintf(' %% mkdir %s',dir_cluster)); mkdir(dir_cluster); end;
test_loader_cluster_2( ...
 dir_cluster ...
,str_label_A_ ...
,[E_ , I_] ...
,date_diff_threshold ...
,flag_force_create_mat ...
,flag_force_create_tmp ...
);
