  %%%%%%%%;
  %test umap on simple case ;
  %%%%%%%%;
  %M=178; N=2e3; n_cluster=1;
  M=1781; N=2e4; n_cluster=1;
  n_step = 12;
  snr_ = linspace(0.6,1.2,n_step);
  A_n_sub__ = cell(n_step,1);
  label_A__ = cell(n_step,1);
  label_B__ = cell(n_step,1);
  for nstep=1:n_step;
  snr = snr_(nstep);
  [A_n_,label_A__{nstep},n_label_A_,pf_,pi_,~] = random_matrix_planted_cluster_0(M,N,snr,n_cluster);
  [A_n_sub__{nstep}, ~, label_B__{nstep}]=run_umap(A_n_,'verbose','none');
  end;%for nstep=1:n_step;
  %%%%%%%%;
  figure(1);clf;
  c_ = colormap(colormap_beach()); c_ = c_(randperm(64),:);
  for nstep=1:n_step;
  snr = snr_(nstep);
  subplot(2,6,nstep);
  A_n_sub_ = A_n_sub__{nstep};
  label_B_ = label_B__{nstep};
  label_A_ = label_A__{nstep};
  hold on; scatter(A_n_sub_(:,1),A_n_sub_(:,2),10,label_B_,'filled');
  tmp_ij_ = find(label_A_==2);
  hold on; scatter(A_n_sub_(tmp_ij_,1),A_n_sub_(tmp_ij_,2),25,'ko');
  hold off; 
  %title(sprintf('umap: M%d N%d snr%0.2f n%d',M,N,snr,n_cluster));
  title(sprintf('snr %0.2f, u %d',snr,numel(unique(label_B_))));
  set(gca,'XTick',[],'YTick',[]);
  drawnow(); figbig;
  end;%for nstep=1:n_step;
  print('-depsc','/data/rangan/dir_bcc/dir_jamison/dir_jpg/umap_default_20200116b.eps');
  print('-djpeg','/data/rangan/dir_bcc/dir_jamison/dir_jpg/umap_default_20200116b.jpg');
  %%%%%%%%;
