function test_loader_plot_sort_list_0(AB_,nA,nB,u_CLabel_,C_VariableName_LC_,dir_trunk,infix);

n_CCOV = AB_.n_CCOV;
n_Z_GENE = AB_.n_Z_GENE;

%flag_test=1;
%if flag_test;
%%%%%%%;
% Now we can test a pair of labels: Plotting Covariates;
%%%%%%%%;
%if flag_Z;
figure(1);clf; hold on;
plot(squeeze(AB_.AB_C_sort_list_avg__(nA,nB,:)+2.0*AB_.AB_C_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_C_sort_list_avg__(nA,nB,:)+0.0*AB_.AB_C_sort_list_std__(nA,nB,:)),'k','LineWidth',1.0);
plot(squeeze(AB_.AB_C_sort_list_avg__(nA,nB,:)-2.0*AB_.AB_C_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_C_sort_list_ori__(nA,nB,:)),'r','LineWidth',2.0);
xlim([1,n_CCOV]); xlabel('covariate'); ylabel('rank difference (auc)'); title(sprintf('sorted auc of covariates influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(AB_.AB_C_sort_list_ij__(nA,nB,:)),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_C_sort_list_ori_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%%%%%%%%;
figure(2);clf; hold on;
plot(-log10(squeeze(AB_.AB_C_sort_list_p__(nA,nB,:))),'r','LineWidth',2.0);
plot(1:n_CCOV,-log10(0.05)*ones(n_CCOV,1),'k--','LineWidth',2);
plot(1:n_CCOV,-log10(0.001)*ones(n_CCOV,1),'k:','LineWidth',2);
xlim([1,n_CCOV]); xlabel('covariate'); ylim([0,15]); ylabel('-log10(p)'); title(sprintf('-log10(p-value) for sorted auc of covariates influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(AB_.AB_C_sort_list_ij__(nA,nB,:)),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_C_sort_list_p_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%%%%%%%%;
figure(3);clf; hold on;
plot(squeeze(AB_.AB_K_sort_list_avg__(nA,nB,:)+2.0*AB_.AB_K_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_K_sort_list_avg__(nA,nB,:)+0.0*AB_.AB_K_sort_list_std__(nA,nB,:)),'k','LineWidth',1.0);
plot(squeeze(AB_.AB_K_sort_list_avg__(nA,nB,:)-2.0*AB_.AB_K_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_K_sort_list_ori__(nA,nB,:)),'r','LineWidth',2.0);
xlim([1,n_CCOV]); xlabel('covariate'); ylabel('rank difference (auc)'); title(sprintf('sorted auc of covariates influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(AB_.AB_K_sort_list_ij__(nA,nB,:)),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_K_sort_list_ori_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%%%%%%%%;
figure(4);clf; hold on;
plot(-log10(squeeze(AB_.AB_K_sort_list_p__(nA,nB,:))),'r','LineWidth',2.0);
plot(1:n_CCOV,-log10(0.05)*ones(n_CCOV,1),'k--','LineWidth',2);
plot(1:n_CCOV,-log10(0.001)*ones(n_CCOV,1),'k:','LineWidth',2);
xlim([1,n_CCOV]); xlabel('covariate'); ylim([0,15]); ylabel('-log10(p)'); title(sprintf('-log10(p-value) for sorted auc of covariates influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(AB_.AB_K_sort_list_ij__(nA,nB,:)),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_K_sort_list_p_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%end;%if flag_Z;
%%%%%%%%;
%end;%if flag_test;

%flag_test=1;
%if flag_test;
%%%%%%%;
% Now we can test a pair of labels: Plotting Genes;
%%%%%%%%;
%if flag_Z;
figure(1);clf; hold on;
plot(squeeze(AB_.AB_Z_sort_list_avg__(nA,nB,:)+2.0*AB_.AB_Z_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_Z_sort_list_avg__(nA,nB,:)+0.0*AB_.AB_Z_sort_list_std__(nA,nB,:)),'k','LineWidth',1.0);
plot(squeeze(AB_.AB_Z_sort_list_avg__(nA,nB,:)-2.0*AB_.AB_Z_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_Z_sort_list_ori__(nA,nB,:)),'r','LineWidth',2.0);
xlim([1,n_Z_GENE]); xlabel('gene'); ylabel('rank difference (auc)'); title(sprintf('sorted auc of genes influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',[],'XTickLabel',[]);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_Z_sort_list_ori_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%%%%%%%%;
figure(2);clf; hold on;
plot(-log10(squeeze(AB_.AB_Z_sort_list_p__(nA,nB,:))),'r','LineWidth',2.0);
plot(1:n_Z_GENE,-log10(0.05)*ones(n_Z_GENE,1),'k--','LineWidth',2);
plot(1:n_Z_GENE,-log10(0.001)*ones(n_Z_GENE,1),'k:','LineWidth',2);
xlim([1,n_Z_GENE]); xlabel('gene'); ylim([0,15]); ylabel('-log10(p)'); title(sprintf('-log10(p-value) for sorted auc of genes influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',[],'XTickLabel',[]);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_Z_sort_list_p_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%%%%%%%%;
figure(3);clf; hold on;
plot(squeeze(AB_.AB_H_sort_list_avg__(nA,nB,:)+2.0*AB_.AB_H_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_H_sort_list_avg__(nA,nB,:)+0.0*AB_.AB_H_sort_list_std__(nA,nB,:)),'k','LineWidth',1.0);
plot(squeeze(AB_.AB_H_sort_list_avg__(nA,nB,:)-2.0*AB_.AB_H_sort_list_std__(nA,nB,:)),'k','LineWidth',0.5);
plot(squeeze(AB_.AB_H_sort_list_ori__(nA,nB,:)),'r','LineWidth',2.0);
xlim([1,n_Z_GENE]); xlabel('gene'); ylabel('rank difference (auc)'); title(sprintf('sorted auc of genes influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',[],'XTickLabel',[]);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_H_sort_list_ori_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%%%%%%%%;
figure(4);clf; hold on;
plot(-log10(squeeze(AB_.AB_H_sort_list_p__(nA,nB,:))),'r','LineWidth',2.0);
plot(1:n_Z_GENE,-log10(0.05)*ones(n_Z_GENE,1),'k--','LineWidth',2);
plot(1:n_Z_GENE,-log10(0.001)*ones(n_Z_GENE,1),'k:','LineWidth',2);
xlim([1,n_Z_GENE]); xlabel('gene'); ylim([0,15]); ylabel('-log10(p)'); title(sprintf('-log10(p-value) for sorted auc of genes influencing labels %s-vs-%s',u_CLabel_{nA},u_CLabel_{nB}));
set(gca,'XTick',[],'XTickLabel',[]);
set(gca,'FontSize',7);
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_H_sort_list_p_%s_vs_%s',dir_trunk,infix,u_CLabel_{nA},u_CLabel_{nB});
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
hold off;
%end;%if flag_Z;
%%%%%%%%;
%end;%if flag_test;

