function test_loader_plot_absZ_avg__0(AB_,C_VariableName_LC_,dir_trunk,infix);

n_CCOV = AB_.n_CCOV;
n_Z_GENE = AB_.n_Z_GENE;

%flag_disp=1;
%if flag_disp;
%if flag_Z;
figure(1);clf;
subplot(2,1,1);
[~,tmp_ij_] = sort(AB_.AB_C_absZ_avg__,'ascend');
plot(1:n_CCOV,sort(AB_.AB_C_absZ_avg__,'ascend'),'ko');
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_ij_),'TickLabelInterpreter','none'); xtickangle(90);
xlim([1,n_CCOV]); ylabel('accumulated abs(z-score)'); title('Covariates sorted by raw relevance, accumulated across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
subplot(2,1,2);
[~,tmp_ij_] = sort(AB_.AB_K_absZ_avg__,'ascend');
plot(1:n_CCOV,sort(AB_.AB_K_absZ_avg__,'ascend'),'ko');
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_ij_),'TickLabelInterpreter','none'); xtickangle(90);
xlim([1,n_CCOV]); ylabel('accumulated abs(z-score)'); title('Covariates sorted by relative relevance, accumulated across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_C_absZ_avg',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%end;%if flag_Z;
%end;%if flag_disp;

%flag_disp=1;
%if flag_disp;
%if flag_Z;
figure(1);clf;
subplot(2,1,1);
[~,tmp_ij_] = sort(AB_.AB_Z_absZ_avg__,'ascend');
plot(1:n_Z_GENE,sort(AB_.AB_Z_absZ_avg__,'ascend'),'ko');
set(gca,'XTick',[],'XTickLabel',[]);
xlim([1,n_Z_GENE]); ylabel('accumulated abs(z-score)'); title(sprintf('%s genes sorted by raw relevance, accumulated across all label-pairs',infix));
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
subplot(2,1,2);
[~,tmp_ij_] = sort(AB_.AB_H_absZ_avg__,'ascend');
plot(1:n_Z_GENE,sort(AB_.AB_H_absZ_avg__,'ascend'),'ko');
set(gca,'XTick',[],'XTickLabel',[]);
xlim([1,n_Z_GENE]); ylabel('accumulated abs(z-score)'); title(sprintf('%s genes sorted by relative relevance, accumulated across all label-pairs',infix));
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_Z_absZ_avg',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%end;%if flag_Z;
%end;%if flag_disp;

%flag_disp=1;
%if flag_disp;
%if flag_Z;
figure(1);clf;
subplot(2,1,1);
[~,tmp_ij_] = sort(AB_.AB_C_rawZ_avg__,'ascend');
plot(1:n_CCOV,sort(AB_.AB_C_rawZ_avg__,'ascend'),'ko');
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_ij_),'TickLabelInterpreter','none'); xtickangle(90);
xlim([1,n_CCOV]); ylabel('accumulated raw(z-score)'); title('Covariates sorted by raw relevance, accumulated across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
subplot(2,1,2);
[~,tmp_ij_] = sort(AB_.AB_K_rawZ_avg__,'ascend');
plot(1:n_CCOV,sort(AB_.AB_K_rawZ_avg__,'ascend'),'ko');
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_ij_),'TickLabelInterpreter','none'); xtickangle(90);
xlim([1,n_CCOV]); ylabel('accumulated raw(z-score)'); title('Covariates sorted by relative relevance, accumulated across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_C_rawZ_avg',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%end;%if flag_Z;
%end;%if flag_disp;

%flag_disp=1;
%if flag_disp;
%if flag_Z;
figure(1);clf;
subplot(2,1,1);
[~,tmp_ij_] = sort(AB_.AB_Z_rawZ_avg__,'ascend');
plot(1:n_Z_GENE,sort(AB_.AB_Z_rawZ_avg__,'ascend'),'ko');
set(gca,'XTick',[],'XTickLabel',[]);
xlim([1,n_Z_GENE]); ylabel('accumulated raw(z-score)'); title(sprintf('%s genes sorted by raw relevance, accumulated across all label-pairs',infix));
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
subplot(2,1,2);
[~,tmp_ij_] = sort(AB_.AB_H_rawZ_avg__,'ascend');
plot(1:n_Z_GENE,sort(AB_.AB_H_rawZ_avg__,'ascend'),'ko');
set(gca,'XTick',[],'XTickLabel',[]);
xlim([1,n_Z_GENE]); ylabel('accumulated raw(z-score)'); title(sprintf('%s genes sorted by relative relevance, accumulated across all label-pairs',infix));
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_Z_rawZ_avg',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%end;%if flag_Z;
%end;%if flag_disp;
