function ...
test_loader_helper_covariate_cluster_0( ...
 verbose ...
,flag_force_create ...
,dir_trunk ...
,dir_mat ...
,dir_jpg ...
,dir_cluster ...
,n_CCOV ...
,C_rank_ ...
,C_VariableName_ ...
,n_u ...
,X_infix ...
,rank_estimate_X ...
,X_ ...
,n_Sample_Label ...
,str_Sample_Label_ ...
,AB_ ...
);

[tmp_UC_,tmp_SC_,tmp_VC_] = svds(C_rank_,n_CCOV);
%[tmp_UX_,tmp_SX_,tmp_VX_] = svds(X_,n_u); %<-- use full rank of X_. ;
[tmp_UX_,tmp_SX_,tmp_VX_] = svds(X_,rank_estimate_X); %<-- use full rank of X_. ;
UX_C_ = inv(tmp_SX_)*transpose(tmp_UX_)*mean_center_0(C_rank_); %<-- explicit mean-centering not required for dexcluster, but perhaps for others. ;
[tmp_U_UX_C_,tmp_S_UX_C_,tmp_V_UX_C_] = svds(UX_C_,n_CCOV);
%%%%%%%%;
% Identify mahalanobis rank of C_rank_. ;
%%%%%%%%;
tmp_fname_mat = sprintf('%s/S_call_U%s_C_mahalanobis.mat',dir_mat,X_infix);
if (flag_force_create | ~exist(tmp_fname_mat,'file'));
disp(sprintf(' %% %s not found, creating',tmp_fname_mat));
[ ...
 rank_estimate_sample ...
,s_B_nlp_ ...
,svd_sample__ ...
,eig_tw__ ...
,eig_B_ ...
,kta_opt__ ...
,h_x__ ...
,h_eig__ ...
,h_opt__ ...
] = ...
rank_estimate_sample_0(UX_C_);
save(tmp_fname_mat ...
,'rank_estimate_sample' ...
,'s_B_nlp_' ...
,'svd_sample__' ...
,'eig_tw__' ...
,'eig_B_' ...
,'kta_opt__' ...
,'h_x__' ...
,'h_eig__' ...
,'h_opt__' ...
);
end;%if (~exist(tmp_fname_mat,'file'));
%%%%%%%%;
% spectral-->isosplit5;
%%%%%%%%;
fname_fig = sprintf('%s/U%s_C_spectral_scatter_FIGA',dir_jpg,X_infix);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
n_rank_CC = 6;
for nrank_CC=1:n_rank_CC;
opts_isosplit5 = struct('K_init',200,'isocut_threshold',1.0);
label_C__{nrank_CC} = transpose(isosplit5(transpose(tmp_V_UX_C_(:,1:nrank_CC)*tmp_S_UX_C_(1:nrank_CC,1:nrank_CC)),opts_isosplit5));
end;%for nrank_CC=1:n_rank_CC;
for nrank_CC=1:n_rank_CC;
subplot(2,3,nrank_CC); scatter(tmp_V_UX_C_(:,1),tmp_V_UX_C_(:,2),15,label_C__{nrank_CC}); colormap(colormap_beach());
end;%for nrank_CC=1:n_rank_CC;
figbig;
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
% dexnb;
%%%%%%%%;
gamma = 0.00; n_shuffle = 64; p_set = 0.05; n_member_lob = 2;
gamma_d = floor(gamma*1000); str_g = sprintf('_g%.3d',gamma_d);
p_set_d = floor(p_set*1000); str_p = sprintf('_p%.3d',p_set_d);
str_nml = sprintf('_nml%d',n_member_lob);
str_xfix = sprintf('dexcluster_nonbinary_trace_ZRimax%s%s%s',str_g,str_p,str_nml);
prefix_base = sprintf('U%s_C_%s',X_infix,str_xfix); 
dir_out = []; E_array_base_ = transpose(UX_C_); E_array_r_ij_ = []; E_array_c_ij_ = [];
test_loader_dexcluster_nonbinary_trace_ZRimax_recursive_3( ...
 dir_cluster ...
,dir_out ...
,prefix_base ...
,E_array_base_ ...
,E_array_r_ij_ ...
,E_array_c_ij_ ...
,gamma ...
,n_shuffle ...
,p_set ...
,n_member_lob ...
,flag_force_create ...
);
p_set_ = [0.05]*0.5.^[0:5];
for np=1:length(p_set_);
tmp_p_set = p_set_(np);
tmp_ZRimax_label_ = ...
test_loader_dexcluster_nonbinary_trace_ZRimax_recursive_3( ...
 dir_cluster ...
,dir_out ...
,prefix_base ...
,E_array_base_ ...
,E_array_r_ij_ ...
,E_array_c_ij_ ...
,gamma ...
,n_shuffle ...
,tmp_p_set ...
,n_member_lob ...
);
fname_fig = sprintf('%s/U%s_C_dexnb_scatter_FIGA',dir_jpg,X_infix);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
subplot(2,3,np);
scatter(tmp_V_UX_C_(:,1),tmp_V_UX_C_(:,2),15,label_str_to_enum_0(tmp_ZRimax_label_),'filled');
colormap(colormap_beach());
title(sprintf('p %0.6f #=%d',tmp_p_set,length(unique(tmp_ZRimax_label_))));
axisnotick;
end;%for np=1:length(p_set_);
figbig;
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
% Print output: ;
%%%%%%%%;
p_set = 0.05; 
[ ...
 ZRimax_output_label_ ...
,ZRimax_lpFmax_label_ ...
] = ...
test_loader_dexcluster_nonbinary_trace_ZRimax_recursive_3( ...
 dir_cluster ...
,dir_out ...
,prefix_base ...
,E_array_base_ ...
,E_array_r_ij_ ...
,E_array_c_ij_ ...
,gamma ...
,n_shuffle ...
,p_set ...
,n_member_lob ...
);
ZRimax_enum_ = label_str_to_enum_0(ZRimax_output_label_);
n_QCluster = length(unique(ZRimax_enum_));
fname_tsv = sprintf('%s/n_QCluster_U%s_C_mahalanobis.tsv',dir_mat,X_infix);
if (flag_force_create | ~exist(fname_tsv,'file'));
disp(sprintf(' %% %s not found, creating',fname_tsv));
save(fname_tsv ...
,'n_QCluster' ...
,'-ascii','-tabs' ...
);
end;%if (~exist(fname_tsv,'file'));
%%%%%%%%;
% plot QC-clusters. ;
%%%%%%%%;
fname_fig = sprintf('%s/U%s_C_dexnb_scatter_FIGA0',dir_jpg,X_infix);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
figure(1);clf;
label_plot_recursive_0(ZRimax_output_label_,ZRimax_lpFmax_label_,C_VariableName_);
title(sprintf('U%s_C_dexnb',X_infix),'Interpreter','none');
figbig;
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
% plot QC-clusters in PCA-space;
%%%%%%%%;
fname_fig = sprintf('%s/U%s_C_dexnb_scatter_FIGA1',dir_jpg,X_infix);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
figure(1);clf;
tmp_Legend_ = num2str(transpose(1:n_QCluster));
subplot(1,2,1);
colormap(colormap_beach());
hold on;
for nQCluster=0:n_QCluster-1;
tmp_ij_ = find(ZRimax_enum_==1+nQCluster);
scatter(tmp_VC_(tmp_ij_,1),tmp_VC_(tmp_ij_,2),65,ZRimax_enum_(tmp_ij_),'filled','MarkerEdgeColor','k');
end;%for nQCluster=0:n_QCluster-1;
title(sprintf('QC clusters (C orig)'));
axisnotick;
legend(tmp_Legend_,'Location','SouthWest');
subplot(1,2,2);
colormap(colormap_beach());
hold on;
for nQCluster=0:n_QCluster-1;
tmp_ij_ = find(ZRimax_enum_==1+nQCluster);
scatter(tmp_V_UX_C_(tmp_ij_,1),tmp_V_UX_C_(tmp_ij_,2),65,ZRimax_enum_(tmp_ij_),'filled','MarkerEdgeColor','k');
end;%for nQCluster=0:n_QCluster-1;
title(sprintf('QC clusters (U%s_C)',X_infix),'Interpreter','none');
axisnotick;
legend(tmp_Legend_,'Location','SouthEast');
set(gcf,'Position',1+[0,0,512*3,512*2]);
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
if (verbose>1);
disp(sprintf(' n_QCluster: %d',n_QCluster));
disp(sprintf(' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'));
for nQCluster=0:n_QCluster-1;
disp(sprintf(' QCluster #%d:',1+nQCluster));
disp(sprintf('\t%s\n',C_VariableName_{find(ZRimax_enum_==1+nQCluster)}));
disp(sprintf(' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'));
end;%for nQCluster=0:n_QCluster-1;
end;%if (verbose>1);
%%%%%%%%;
% Identify mahalanobis rank of each QC-cluster. ;
%%%%%%%%;
QCluster_rank_estimate_mahalanobis_ = zeros(n_QCluster,1);
for nQCluster=0:n_QCluster-1;
tmp_c_index_ = efind(ZRimax_enum_==1+nQCluster);
tmp_C_ = C_rank_(:,1+tmp_c_index_);
tmp_UXC_ = inv(tmp_SX_)*transpose(tmp_UX_)*mean_center_0(tmp_C_);
tmp_n_CCOV = numel(tmp_c_index_);
%%%%%%%%;
tmp_fname_mat = sprintf('%s/S_c%d_U%s_C_mahalanobis.mat',dir_mat,1+nQCluster,X_infix);
if (flag_force_create | ~exist(tmp_fname_mat,'file'));
disp(sprintf(' %% %s not found, creating',tmp_fname_mat));
[ ...
 rank_estimate_sample ...
,s_B_nlp_ ...
,svd_sample__ ...
,eig_tw__ ...
,eig_B_ ...
,kta_opt__ ...
,h_x__ ...
,h_eig__ ...
,h_opt__ ...
] = ...
rank_estimate_sample_0(tmp_UXC_);
save(tmp_fname_mat ...
,'nQCluster' ...
,'rank_estimate_sample' ...
,'s_B_nlp_' ...
,'svd_sample__' ...
,'eig_tw__' ...
,'eig_B_' ...
,'kta_opt__' ...
,'h_x__' ...
,'h_eig__' ...
,'h_opt__' ...
);
end;%if (~exist(tmp_fname_mat,'file'));
tmp_ = load(tmp_fname_mat);
QCluster_rank_estimate_mahalanobis_(1+nQCluster) = tmp_.rank_estimate_sample;
clear tmp_;
%%%%%%%%;
end;%for nQCluster=0:n_QCluster-1;
%%%%%%%%;
% Identify original rank of each QC-cluster. ;
%%%%%%%%;
QCluster_rank_estimate_original_ = zeros(n_QCluster,1);
for nQCluster=0:n_QCluster-1;
tmp_c_index_ = efind(ZRimax_enum_==1+nQCluster);
tmp_C_ = C_rank_(:,1+tmp_c_index_);
tmp_UXC_ = inv(tmp_SX_)*transpose(tmp_UX_)*mean_center_0(tmp_C_);
tmp_n_CCOV = numel(tmp_c_index_);
%%%%%%%%;
tmp_fname_mat = sprintf('%s/S_c%d_U%s_C_original.mat',dir_mat,1+nQCluster,X_infix);
if (flag_force_create | ~exist(tmp_fname_mat,'file'));
disp(sprintf(' %% %s not found, creating',tmp_fname_mat));
[ ...
 rank_estimate_sample ...
,s_B_nlp_ ...
,svd_sample__ ...
,eig_tw__ ...
,eig_B_ ...
,kta_opt__ ...
,h_x__ ...
,h_eig__ ...
,h_opt__ ...
] = ...
rank_estimate_sample_0(mean_center_0(tmp_C_));
save(tmp_fname_mat ...
,'nQCluster' ...
,'rank_estimate_sample' ...
,'s_B_nlp_' ...
,'svd_sample__' ...
,'eig_tw__' ...
,'eig_B_' ...
,'kta_opt__' ...
,'h_x__' ...
,'h_eig__' ...
,'h_opt__' ...
);
end;%if (~exist(tmp_fname_mat,'file'));
tmp_ = load(tmp_fname_mat);
QCluster_rank_estimate_original_(1+nQCluster) = tmp_.rank_estimate_sample;
clear tmp_;
%%%%%%%%;
end;%for nQCluster=0:n_QCluster-1;
%%%%%%%%;
% identify and store QC-clusters. ;
%%%%%%%%;
for nQCluster=0:n_QCluster-1;
disp(sprintf(' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'));
tmp_infix = sprintf('c%d_U%s__',1+nQCluster,X_infix);
tmp_c_index_ = efind(ZRimax_enum_==1+nQCluster);
tmp_n_CCOV = numel(tmp_c_index_);
disp(sprintf(' %% nQCluster %d/%d --> %s(%d)',nQCluster,n_QCluster,tmp_infix,tmp_n_CCOV));
disp(sprintf(' %s: QCluster #%d:',X_infix,1+nQCluster));
disp(sprintf('\t[rank: mahalanobis %d original %d]',QCluster_rank_estimate_mahalanobis_(1+nQCluster),QCluster_rank_estimate_original_(1+nQCluster)));
disp(sprintf('\t%s\n',C_VariableName_{1+tmp_c_index_}));
disp(sprintf(' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'));
tmp_C_ = C_rank_(:,1+tmp_c_index_);
fname_tsv = sprintf('%s/%s.tsv',dir_mat,tmp_infix);
if (flag_force_create | ~exist(fname_tsv,'file')); 
disp(sprintf(' %% writing %s',fname_tsv));
save(fname_tsv,'tmp_C_','-ascii','-tabs');
end;%if (~exist(fname_tsv,'file'));
clear tmp_C_;
end;%for nQCluster=0:n_QCluster-1;
%%%%%%%%;
fname_fig = sprintf('%s/Table_U%s_C_dexnb_FIGB',dir_jpg,X_infix);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
Table_UX_C_ = zeros(n_QCluster,n_Sample_Label);
for nQCluster=0:n_QCluster-1;
QCluster_ij_ = find(ZRimax_enum_==1+nQCluster);
n_l = length(QCluster_ij_);
for nl=1:n_l;
QC_ij = QCluster_ij_(nl);
ns=0;
for nSample_Label_A=1:n_Sample_Label;
for nSample_Label_B=1:n_Sample_Label;
tmp_lp = z_to_p_0(AB_.AB_C_absZ_(1+ns,QC_ij)); tmp_lp = -tmp_lp/(n_l*n_Sample_Label);
Table_UX_C_(1+nQCluster,nSample_Label_A) = Table_UX_C_(1+nQCluster,nSample_Label_A) + tmp_lp;
Table_UX_C_(1+nQCluster,nSample_Label_B) = Table_UX_C_(1+nQCluster,nSample_Label_B) + tmp_lp;
ns=ns+1;
end;%for nSample_Label_B=1:n_Sample_Label;
end;%for nSample_Label_A=1:n_Sample_Label;
end;%for nl=1:n_l;
end;%for nQCluster=0:n_QCluster-1;
subplot(1,1,1);
colormap(colormap_beach());
imagesc(Table_UX_C_); colorbar; figbig;
set(gca,'XTick',1:n_Sample_Label,'XTickLabel',unique(str_Sample_Label_)); xtickangle(90);
set(gca,'YTick',1:n_QCluster,'YTickLabel',1:n_QCluster);
title('QC-cluster vs sample-cluster -log(p-value)');
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
% tsne00-->isosplit5;
%%%%%%%%;
fname_fig = sprintf('%s/U%s_C_tsne00_scatter_FIGA',dir_jpg,X_infix);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
tmp_Q_ = eye(n_CCOV); %[tmp_Q_,~] = qr(randn(n_CCOV));
UX_C_sub_ = fast_tsne_dr_0(transpose(UX_C_*tmp_Q_),struct('rand_seed',1,'no_dims',2,'theta',0.0));
opts_isosplit5 = struct('K_init',n_CCOV,'isocut_threshold',1.0);
label_UX_C_ = transpose(isosplit5(transpose(UX_C_sub_),opts_isosplit5));
subplot(1,1,1); scatter(UX_C_sub_(:,1),UX_C_sub_(:,2),15,label_UX_C_); colormap(colormap_beach());
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
% tsne50-->isosplit5;
%%%%%%%%;
fname_fig = sprintf('%s/UX_C_tsne50_scatter_FIGA',dir_jpg);
if (flag_force_create | ~exist(sprintf('%s.jpg',fname_fig),'file'));
tmp_Q_ = eye(n_CCOV); %[tmp_Q_,~] = qr(randn(n_CCOV));
UX_C_sub_ = fast_tsne_dr_0(transpose(UX_C_*tmp_Q_),struct('rand_seed',1,'no_dims',2,'theta',0.5));
opts_isosplit5 = struct('K_init',n_CCOV,'isocut_threshold',1.0);
label_UX_C_ = transpose(isosplit5(transpose(UX_C_sub_),opts_isosplit5));
subplot(1,1,1); scatter(UX_C_sub_(:,1),UX_C_sub_(:,2),15,label_UX_C_); colormap(colormap_beach());
disp(sprintf(' %% writing %s.jpg',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
print('-depsc',sprintf('%s.eps',fname_fig));
close(gcf);
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%;
