  %%%%%%%%;
  % check snr definition. ;
  %%%%%%%%;
  %M = 178; N = 2e3; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 32; flag_rerun = 0;
  M = 1781; N = 2e4; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 32; flag_rerun = 0;
  n_step = 21;
  X_ = linspace(0.50,0.65,n_step); mu_ = linspace(0.0,1.0,n_step);
  snr_ = zeros(n_step,1);
  svs_ = zeros(M,n_step);
  for nstep=1:n_step;
  X = X_(nstep); mu = mu_(nstep);
  MX = ceil(M^X); NX = ceil(N^X); 
  snr_(nstep) = sqrt(MX*NX)*mu/sqrt(N);
  A_n_ = randn(M,N); B_n_ = randn(MX,NX)+mu*ones(MX,1)*(2*(rand(1,NX)>0.5) - 1);  A_n_(1:MX,1:NX) = B_n_;
  svs_(:,nstep) = eigs(A_n_*transpose(A_n_)/N,M);
  end;%for nstep=1:n_step;
  %%%%%%%%;
  % check marchenko-pastur ;
  %%%%%%%%;
  M = 1781; 
  N = 2*M;
  lambda = M/N;
  lambda_p = (1 + sqrt(lambda))^2;
  lambda_n = (1 - sqrt(lambda))^2;
  mp = @(x) (1/(2*pi)) * sqrt((lambda_p - x).*(x - lambda_n))./(lambda*x) ;
  n_x = 1024;
  x_ = linspace(lambda_n,lambda_p,n_x);
  mp_ = mp(x_);
  A_n_ = randn(M,N)/sqrt(N); 
  svs_ = eigs(A_n_*transpose(A_n_),M);
  n_h = 32;
  hx_ = linspace(min(x_),max(x_),n_h);
  h_ = hist(svs_,hx_); h_ = h_/sum(h_)/mean(diff(hx_));
  clf;
  hold on;
  plot(x_,mp_,'r-');
  bar(hx_,h_,'k');
  hold off;
