%%%%%%%%;
% How does perforation affect the spectrum of a random matrix? ;
%%%%%%%%;
n_r = 128*4; n_c = n_r+1; n_k = min(n_r,n_c);
A_ = randn(n_r,n_c);
p_ = randperm(numel(A_));
n_m = 21;
m_ = linspace(0,1,n_m); f_ = 1-m_;
s_ = zeros(n_k,n_m);
for nm=1:n_m;
m = m_(nm);
ij_missed_ = p_(1:floor(numel(A_)*m));
B_ = A_; B_(ij_missed_) = 0;
s_(:,nm) = svd(B_);
end;%for nm=1:n_m;

figure(1);
c_ = colormap(colormap_beach()); n_c = size(c_,1);
subplot(1,2,1);
hold on; for nm=1:n_m; nc=max(1,min(n_c,floor(n_c*nm/n_m))); plot(1:n_k,s_(:,nm),'Color',c_(nc,:)); end; hold off;
xlabel('rank'); ylabel('s'); title('rand: spectrum');
subplot(1,2,2);
hold on; for nm=1:n_m; nc=max(1,min(n_c,floor(n_c*nm/n_m))); plot(1:n_k,s_(:,nm)/sqrt(f_(nm)),'Color',c_(nc,:)); end; hold off;
colormap(colormap_beach());
xlabel('rank'); ylabel('s'); title('rand: rescaled');

%%%%%%%%;
% a tapered spectrum? ;
%%%%%%%%;

n_r = 128*4; n_c = n_r+1; n_k = min(n_r,n_c); s_ = transpose(exp(-linspace(0,1,n_k)/0.125));
A_ = randn(n_r,n_c);
[tmp_U_,tmp_S_,tmp_V_] = svds(A_,n_k); tmp_S_ = diag(diag(tmp_S_).*s_);
A_ = tmp_U_*tmp_S_*transpose(tmp_V_);
p_ = randperm(numel(A_));
n_m = 21;
m_ = linspace(0,1,n_m); f_ = 1-m_;
s_ = zeros(n_k,n_m);
for nm=1:n_m;
m = m_(nm);
ij_missed_ = p_(1:floor(numel(A_)*m));
B_ = A_; B_(ij_missed_) = 0;
s_(:,nm) = svd(B_);
end;%for nm=1:n_m;

figure(2);
c_ = colormap(colormap_beach()); n_c = size(c_,1);
subplot(1,2,1);
hold on; for nm=1:n_m; nc=max(1,min(n_c,floor(n_c*nm/n_m))); plot(1:n_k,s_(:,nm),'Color',c_(nc,:)); end; hold off;
xlabel('rank'); ylabel('s'); title('taper: spectrum');
subplot(1,2,2);
hold on; for nm=1:n_m; nc=max(1,min(n_c,floor(n_c*nm/n_m))); plot(1:n_k,s_(:,nm)/sqrt(f_(nm)),'Color',c_(nc,:)); end; hold off;
colormap(colormap_beach());
xlabel('rank'); ylabel('s'); title('taper: rescaled');

%%%%%%%%;
% a bulbous spectrum? ;
%%%%%%%%;

n_r = 128*4; n_c = n_r+1; n_k = min(n_r,n_c);
A_ = randn(n_r,n_c);
[tmp_U_,tmp_S_,tmp_V_] = svds(A_,n_k); tmp_S_ = eye(n_k);
A_ = tmp_U_*tmp_S_*transpose(tmp_V_);
p_ = randperm(numel(A_));
n_m = 21;
m_ = linspace(0,1,n_m); f_ = 1-m_;
s_ = zeros(n_k,n_m);
for nm=1:n_m;
m = m_(nm);
ij_missed_ = p_(1:floor(numel(A_)*m));
B_ = A_; B_(ij_missed_) = 0;
s_(:,nm) = svd(B_);
end;%for nm=1:n_m;

figure(3);
c_ = colormap(colormap_beach()); n_c = size(c_,1);
subplot(1,2,1);
hold on; for nm=1:n_m; nc=max(1,min(n_c,floor(n_c*nm/n_m))); plot(1:n_k,s_(:,nm),'Color',c_(nc,:)); end; hold off;
xlabel('rank'); ylabel('s'); title('bulge: spectrum');
subplot(1,2,2);
hold on; for nm=1:n_m; nc=max(1,min(n_c,floor(n_c*nm/n_m))); plot(1:n_k,s_(:,nm)/sqrt(f_(nm)),'Color',c_(nc,:)); end; hold off;
colormap(colormap_beach());
xlabel('rank'); ylabel('s'); title('bulge: rescaled');
