verbose=0;
n_method = 15;
flag_found_from_nu_srt_uum___ = zeros(n_u_celltype,n_u_celltype,n_method);
lpv_quad_from_nu_srt_uum___ = zeros(n_u_celltype,n_u_celltype,n_method);
n_cluster_found_from_nu_srt_uum___ = zeros(n_u_celltype,n_u_celltype,n_method);
for nl0=0:18; for nl1=nl0+1:18;
nu_celltype_0 = index_sort_u_celltype_(1+nl0); %<-- most populous. ;
if (verbose); disp(sprintf(' %% nu_celltype_0 %d %s',nu_celltype_0,u_celltype_{1+nu_celltype_0})); end;
nu_celltype_1 = index_sort_u_celltype_(1+nl1); %<-- most populous. ;
if (verbose); disp(sprintf(' %% nu_celltype_1 %d %s',nu_celltype_1,u_celltype_{1+nu_celltype_1})); end;
index_nall_from_nu_0_ = index_nall_from_nu__{1+nu_celltype_0};
index_nall_from_nu_1_ = index_nall_from_nu__{1+nu_celltype_1};
str_vs = sprintf('%s_vs_%s',u_celltype_{1+nu_celltype_0},u_celltype_{1+nu_celltype_1}); str_vs(strfind(str_vs,' '))='_';
n_celltype_0 = n_u_celltype_(1+nu_celltype_0);
n_celltype_1 = n_u_celltype_(1+nu_celltype_1);
index_sub_nu_from_nall_ = [ zeros(n_celltype_0,1) ; ones(n_celltype_1,1) ];
dir_mat_sub = sprintf('%s/dir_mat_%s',dir_data,str_vs);
%%%%%%%%;
snr_est = snr_est_from_nu_ori__(1+nu_celltype_0,1+nu_celltype_1);
if (verbose); disp(sprintf(' %% nu_celltype (%d,%d): %s: estimated snr: %0.4f',nu_celltype_0,nu_celltype_1,str_vs,snr_est)); end;
%%%%%%%%;
[ ...
 flag_found_ ...
,lpv_quad_ ...
,n_cluster_found_ ...
,label_B__ ...
,prefix_method_ ...
,legend_method_ ...
,nrank_method_ ...
,symbol_method_ ...
] = ...
test_dexcluster_driver_collect_5( ...
 str_code ...
,index_sub_nu_from_nall_ ...
,dir_mat_sub ...
,rank_estimate_A_clr ...
);
flag_found_from_nu_srt_uum___(1+nl0,1+nl1,1:numel(flag_found_)) = flag_found_;
lpv_quad_from_nu_srt_uum___(1+nl0,1+nl1,1:numel(lpv_quad_)) = lpv_quad_;
n_cluster_found_from_nu_srt_uum___(1+nl0,1+nl1,1:numel(n_cluster_found_)) = n_cluster_found_;
%%%%%%%%;
end;end;%for nl0=0:18; for nl1=nl0+1:18;
