function test_dexcluster_multi_4_collect(M,N,snr_,n_cluster,n_rank,n_iteration);

if (nargin<1);
for nl=0:3;
na=0;    
if (nl==na); M =  178; N =  2e3; n_cluster = 1; n_rank =  2; n_iteration = 8; n_shuffle = 256; end; na=na+1;
if (nl==na); M =  178; N =  2e3; n_cluster = 3; n_rank =  4; n_iteration = 8; n_shuffle = 256; end; na=na+1;
if (nl==na); M =  563; N = 6325; n_cluster = 1; n_rank =  3; n_iteration = 4; n_shuffle =  64; end; na=na+1;
if (nl==na); M =  563; N = 6325; n_cluster = 6; n_rank =  9; n_iteration = 4; n_shuffle =  64; end; na=na+1;
if (nl==na); M = 1781; N =  2e4; n_cluster = 1; n_rank =  4; n_iteration = 4; n_shuffle =  64; end; na=na+1;
if (nl==na); M = 1781; N =  2e4; n_cluster = 8; n_rank = 12; n_iteration = 4; n_shuffle =  64; end; na=na+1;
flag_rerun = 0;
n_step = 21;
snr_ = linspace(0.5,1.0,n_step);
test_dexcluster_multi_4_collect(M,N,snr_,n_cluster,n_rank,n_iteration);
end;%for nl=0:3;
disp('returning'); return;
end;%if (nargin<1);

platform = 'access1';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
dir_trunk = sprintf('/%s/rangan/dir_bcc/dir_jamison',string_root);
dir_base = sprintf('%s/dir_dexcluster_multi_4',dir_trunk);

n_step = numel(snr_);

prefix_method_ = { ...
 'tsne00_isosplit5' ...
,'tsne50_isosplit5' ...
,'umap00_default' ...
,'umap00_isosplit5' ...
,'umap00_hdbscan' ...
,'louvain00_default' ...
,'dexcluster_nonbinary_trace_ZRimax' ...
,'dexnbtZRgumb' ...
,'hnbtZRgumb' ...
,'spectral_isosplit5' ...
,'tsne00pr_isosplit5' ...
,'tsne50pr_isosplit5' ...
,'umap00pr_default' ...
,'umap00pr_isosplit5' ...
,'umap00pr_hdbscan' ...
,'louvain00pr_default' ...
,'dexcluster_nonbinary_rdrop_trace_ZRimax' ...
,'dexnbrtZRgumb' ...
,'hnbrtZRgumb' ...
};
n_method = numel(prefix_method_);
index_method_proj_off_ = [0,1,2,3,4,5,6,7,8];
index_method_proj_0on_ = [9,10,11,12,13,14,15,16,17,18];
%%%%%%%%;
legend_method_ = { ...
 'tsne00_isosplit5' ...
,'tsne50_isosplit5' ...
,'umap00_default' ...
,'umap00_isosplit5' ...
,'umap00_hdbscan' ...
,'louvain00_default' ...
,'loop00_default' ...
,'loop00_conserv' ...
,'loop00_c' ...
,'spectral_isosplit5' ...
,'tsne00pr_isosplit5' ...
,'tsne50pr_isosplit5' ...
,'umap00pr_default' ...
,'umap00pr_isosplit5' ...
,'umap00pr_hdbscan' ...
,'louvain00pr_default' ...
,'loop00pr_default' ...
,'loop00pr_conserv' ...
,'loop00pr_c' ...
};
for nl=0:numel(legend_method_)-1; legend_method_{1+nl}(strfind(legend_method_{1+nl},'_')) = ' '; end;
nrank_method_ = { ...
 [] ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
,n_rank ...
};
symbol_method_ = { ...
 'co-' ...
,'bo-' ...
,'kx-' ...
,'ko-' ...
,'k^-' ...
,'rs-' ...
,'ms-' ...
,'mo-' ...
,'mh-' ...
,'go-' ...
,'co-' ...
,'bo-' ...
,'kx-' ...
,'ko-' ...
,'k^-' ...
,'rs-' ...
,'ms-' ...
,'mo-' ...
,'mh-' ...
};

verbose=2;
n_cluster_found___ = zeros(n_step,n_method,n_iteration);
lpv_quad___ = zeros(n_step,n_method,n_iteration);
lP0_form___ = zeros(n_step,n_method,n_iteration);
lpv_prox___ = zeros(n_step,n_method,n_iteration);
flag_found___ = zeros(n_step,n_method,n_iteration);
for nstep=0:n_step-1;
snr = snr_(1+nstep);
for niteration=0:n_iteration-1;
str_xfix = test_dexcluster_multi_xfix_4('base',M,N,snr,n_cluster,n_rank,1+niteration);
fname_base = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(fname_base,'file'));
if (verbose>0); disp(sprintf(' %% %s not found, skipping',fname_base)); end;
end;%if (~exist(fname_base,'file'));
if ( exist(fname_base,'file'));
if (verbose>0); disp(sprintf(' %% %s found',fname_base)); end;
load(fname_base,'label_A_');
for nmethod=0:n_method-1;
prefix_method = prefix_method_{1+nmethod};
nrank_method = nrank_method_{1+nmethod};
str_xfix = test_dexcluster_multi_xfix_4(prefix_method,M,N,snr,n_cluster,nrank_method,1+niteration);
fname_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(fname_mat,'file'));
if (verbose>1); disp(sprintf(' %% %s not found, skipping',fname_mat)); end;
end;%if (~exist(fname_mat,'file'));
if ( exist(fname_mat,'file'));
if (verbose>1); disp(sprintf(' %% %s found',fname_mat)); end;
load(fname_mat,'label_B__','lpv_','lP0_');
n_cluster_found___(1+nstep,1+nmethod,1+niteration) = numel(unique(label_B__{1}));
lpv_quad = label_to_label_enrichment_quad_4(label_A_,label_B__{1});
lpv_quad___(1+nstep,1+nmethod,1+niteration) = lpv_quad;
lP0_form___(1+nstep,1+nmethod,1+niteration) = lP0_;
lpv_prox___(1+nstep,1+nmethod,1+niteration) = lpv_;
flag_found___(1+nstep,1+nmethod,1+niteration) = 1;
end;%if ( exist(fname_mat,'file'));
end;%for nmethod=0:n_method-1;
end;%if ( exist(fname_base,'file'));
end;%for niteration=0:n_iteration-1;
end;%for nstep=0:n_step-1;
tmp_index_ = efind(~isfinite(lpv_quad___)); lpv_quad___(1+tmp_index_)=0;
tmp_index_ = efind(~isfinite(lpv_prox___)); lpv_prox___(1+tmp_index_)=0;
tmp_index_ = efind(~isfinite(lP0_form___)); lP0_form___(1+tmp_index_)=0;
n_cluster_found__ = sum(n_cluster_found___,3)./max(1,sum(flag_found___,3));
lpv_quad__ = sum(lpv_quad___,3)./max(1,sum(flag_found___,3));
lpv_prox__ = sum(lpv_prox___,3)./max(1,sum(flag_found___,3));
lP0_form__ = sum(lP0_form___,3)./max(1,sum(flag_found___,3));

markersize_use = 15;
figure(1);clf;
ylim_ = [-1e-3,max(-lpv_quad__,[],'all')+2];
nlim_ = [-1e-3,max(n_cluster_found__,[],'all')+1];
xlim_ = [min(snr_),max(snr_)];
%%%%%%%%;
subplot(2,2,1);
hold on;
for nmethod=index_method_proj_off_
plot(snr_,-lpv_quad__(:,1+nmethod),symbol_method_{1+nmethod},'LineWidth',2,'MarkerSize',markersize_use);
end;%for nmethod=index_method_proj_off_
hold off;
ylim(ylim_); xlim(xlim_); grid on;
xlabel('snr'); ylabel('-log(pvalue)'); title(sprintf('M%d N%d n%d r%d',M,N,n_cluster,n_rank),'Interpreter','none');
legend(legend_method_{1+index_method_proj_off_},'Location','NorthWest');
title('no projection');
%%%%%%%%;
subplot(2,2,3);
hold on;
for nmethod=index_method_proj_off_
plot(snr_,n_cluster_found__(:,1+nmethod),symbol_method_{1+nmethod},'LineWidth',2,'MarkerSize',markersize_use);
end;%for nmethod=index_method_proj_off_
hold off;
ylim(nlim_); xlim(xlim_); grid on;
xlabel('snr'); ylabel('number of output clusters'); title(sprintf('M%d N%d n%d r%d',M,N,n_cluster,n_rank),'Interpreter','none');
legend(legend_method_{1+index_method_proj_off_},'Location','NorthWest');
title('no projection');
%%%%%%%%;
subplot(2,2,2);
hold on;
for nmethod=index_method_proj_0on_
plot(snr_,-lpv_quad__(:,1+nmethod),symbol_method_{1+nmethod},'LineWidth',2,'MarkerSize',markersize_use);
end;%for nmethod=index_method_proj_0on_
hold off;
ylim(ylim_); xlim(xlim_); grid on;
xlabel('snr'); ylabel('-log(pvalue)'); title(sprintf('M%d N%d n%d r%d',M,N,n_cluster,n_rank),'Interpreter','none');
legend(legend_method_{1+index_method_proj_0on_},'Location','NorthWest');
title('preliminary projection');
%%%%%%%%;
subplot(2,2,4);
hold on;
for nmethod=index_method_proj_0on_
plot(snr_,n_cluster_found__(:,1+nmethod),symbol_method_{1+nmethod},'LineWidth',2,'MarkerSize',markersize_use);
end;%for nmethod=index_method_proj_0on_
hold off;
ylim(nlim_); xlim(xlim_); grid on;
xlabel('snr'); ylabel('number of output clusters'); title(sprintf('M%d N%d n%d r%d',M,N,n_cluster,n_rank),'Interpreter','none');
legend(legend_method_{1+index_method_proj_0on_},'Location','NorthWest');
title('preliminary projection');
%%%%%%%%;
figbig;
sgtitle(sprintf('M%d N%d n%d r%d',M,N,n_cluster,n_rank));
dir_jpg = sprintf('%s/dir_jpg',dir_base); if (~exist(dir_jpg,'dir')); mkdir(dir_jpg); end;
str_fig = sprintf('%s/dir_jpg/test_dexcluster_multi_4_collect_M%d_N%d_n%d_r%d',dir_base,M,N,n_cluster,n_rank);
disp(sprintf(' %% writing %s',str_fig));
print('-djpeg',sprintf('%s.jpg',str_fig));
print('-depsc',sprintf('%s.eps',str_fig));
close(gcf);
