function test_dexcluster_multi_2(M,N,snr,n_cluster,gamma,n_rank,n_iteration,n_shuffle,flag_rerun);
% tries to find up to 8 clusters. ;
% see test_dexcluster_multi_2_collect.m ;
%{

  M = 178; N = 2e3; n_cluster = 1; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 256; flag_rerun = 0;
  %M = 1781; N = 2e4; n_cluster = 1; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 64; flag_rerun = 0;
  %M = 1781; N = 2e4; n_cluster = 8; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 64; flag_rerun = 0;
  n_step = 21;
  snr_ = linspace(0.5,1.5,n_step);
  for nstep=1:n_step;
  snr = snr_(nstep);
  test_dexcluster_multi_2(M,N,snr,n_cluster,gamma,n_rank,n_iteration,n_shuffle,flag_rerun);
  end;%for nstep=1:n_step;

  %}

platform = 'OptiPlex';
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
dir_trunk = sprintf('/%s/rangan/dir_bcc/dir_jamison',string_root);
dir_base = sprintf('%s/dir_dexcluster_multi_2',dir_trunk);

n_vrank = 2;
if (~exist(dir_base,'dir')); disp(sprintf(' %% mkdir %s',dir_base)); mkdir(dir_base); end;
%%%%%%%%;
for niteration=1:n_iteration;
disp(sprintf(' %% niteration %d/%d',niteration,n_iteration));
%%%%%%%%;
rng(niteration);
[A_n_,label_A_,n_label_A_,pf_,pi_,snr_] = random_matrix_planted_cluster_0(M,N,snr,n_cluster);
str_xfix = test_dexcluster_multi_xfix_2('base',M,N,snr,n_cluster,gamma,niteration);
str_base = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_base,'file')); 
disp(sprintf(' %% %s not found, creating',str_base)); 
save(str_base,'M','N','snr','label_A_','n_label_A_','pf_','pi_','n_cluster');
end;%if (~exist(str_base,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% spectral --> isosplit5. ;
str_xfix = test_dexcluster_multi_xfix_2('spectral_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_spectral_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_spectral_isosplit5_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_spectral_isosplit5_mat,'file') & ~exist(str_spectral_isosplit5_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_spectral_isosplit5_mat)); 
save(str_spectral_isosplit5_tmp,'str_spectral_isosplit5_mat');
try;
%%%%%%%%;
[tmp_U_,tmp_S_,tmp_V_] = svds(A_n_,n_rank);
[~,tmp_U_ij_] = sort(abs(tmp_U_(:,1)),'descend'); [~,tmp_V_ij_] = sort(abs(tmp_V_(:,1)),'descend');
lpv_ = zeros(n_rank,1); lP0_ = zeros(n_rank,1); fla_ = zeros(n_rank,1); label_B__ = cell(n_rank,1);
for nrank=1:n_rank;
A_n_sub_ = tmp_U_(:,1:nrank);
opts_isosplit5 = struct('K_init',200,'isocut_threshold',1.0);
label_B__{nrank} = transpose(isosplit5(transpose(A_n_sub_),opts_isosplit5));
[lpv_(nrank),lP0_(nrank),fla_(nrank)] = label_to_label_enrichment_2(label_A_,label_B__{nrank});
end;%for nrank=1:n_rank;
%%%%%%%%;
save(str_spectral_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_spectral_isosplit5_mat)); end;%try;
delete(str_spectral_isosplit5_tmp);
end;%if (~exist(str_spectral_isosplit5,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% spectral --> kmeansK. ;
str_xfix = test_dexcluster_multi_xfix_2('spectral_kmeansK',M,N,snr,n_cluster,gamma,niteration);
str_spectral_kmeansK_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_spectral_kmeansK_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_spectral_kmeansK_mat,'file') & ~exist(str_spectral_kmeansK_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_spectral_kmeansK_mat)); 
save(str_spectral_kmeansK_tmp,'str_spectral_kmeansK_mat');
try;
%%%%%%%%;
[tmp_U_,tmp_S_,tmp_V_] = svds(A_n_,n_rank);
[~,tmp_U_ij_] = sort(abs(tmp_U_(:,1)),'descend'); [~,tmp_V_ij_] = sort(abs(tmp_V_(:,1)),'descend');
lpv_ = zeros(n_rank,1); lP0_ = zeros(n_rank,1); fla_ = zeros(n_rank,1); label_B__ = cell(n_rank,1);
for nrank=1:n_rank;
A_n_sub_ = tmp_U_(:,1:nrank);
label_B__{nrank} = kmeans(A_n_sub_,1+n_cluster);
[lpv_(nrank),lP0_(nrank),fla_(nrank)] = label_to_label_enrichment_2(label_A_,label_B__{nrank});
end;%for nrank=1:n_rank;
%%%%%%%%;
save(str_spectral_kmeansK_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_spectral_kmeansK_mat)); end;%try;
delete(str_spectral_kmeansK_tmp);
end;%if (~exist(str_spectral_kmeansK,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% spectral --> kmeansJ. ;
str_xfix = test_dexcluster_multi_xfix_2('spectral_kmeansJ',M,N,snr,n_cluster,gamma,niteration);
str_spectral_kmeansJ_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_spectral_kmeansJ_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_spectral_kmeansJ_mat,'file') & ~exist(str_spectral_kmeansJ_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_spectral_kmeansJ_mat)); 
save(str_spectral_kmeansJ_tmp,'str_spectral_kmeansJ_mat');
try;
%%%%%%%%;
[tmp_U_,tmp_S_,tmp_V_] = svds(A_n_,n_rank);
[~,tmp_U_ij_] = sort(abs(tmp_U_(:,1)),'descend'); [~,tmp_V_ij_] = sort(abs(tmp_V_(:,1)),'descend');
lpv_ = zeros(n_rank*n_cluster,1); lP0_ = zeros(n_rank*n_cluster,1); fla_ = zeros(n_rank*n_cluster,1); label_B__ = cell(n_rank*n_cluster,1);
ntab=0;
for nrank=1:n_rank;
A_n_sub_ = tmp_U_(:,1:nrank);
for ncluster=1:n_cluster;
ntab = ntab + 1;
label_B__{ntab} = kmeans(A_n_sub_,1+ncluster);
[lpv_(ntab),lP0_(ntab),fla_(ntab)] = label_to_label_enrichment_2(label_A_,label_B__{ntab});
end;%for ncluster=1:n_cluster;
end;%for nrank=1:n_rank;
%%%%%%%%;
save(str_spectral_kmeansJ_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_spectral_kmeansJ_mat)); end;%try;
delete(str_spectral_kmeansJ_tmp);
end;%if (~exist(str_spectral_kmeansJ,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% tsne00 --> isosplit5 ;
str_xfix = test_dexcluster_multi_xfix_2('tsne00_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_tsne00_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_tsne00_isosplit5_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_tsne00_isosplit5_mat,'file') & ~exist(str_tsne00_isosplit5_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_tsne00_isosplit5_mat)); 
save(str_tsne00_isosplit5_tmp,'str_tsne00_isosplit5_mat');
try;
%%%%%%%%;
lpv_ = zeros(n_vrank,1); lP0_ = zeros(n_vrank,1); fla_ = zeros(n_vrank,1); label_B__ = cell(n_vrank,1);
for nrank=1:n_vrank;
A_n_sub_ = fast_tsne_dr_0(A_n_,struct('rand_seed',1,'no_dims',nrank,'theta',0));
opts_isosplit5 = struct('K_init',200,'isocut_threshold',1.0);
label_B__{nrank} = transpose(isosplit5(transpose(A_n_sub_),opts_isosplit5));
[lpv_(nrank),lP0_(nrank),fla_(nrank)] = label_to_label_enrichment_2(label_A_,label_B__{nrank});
end;%for nrank=1:n_vrank;
%%%%%%%%;
save(str_tsne00_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_tsne00_isosplit5_mat)); end;%try;
delete(str_tsne00_isosplit5_tmp);
end;%if (~exist(str_tsne00_isosplit5,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% tsne00 --> kmeansK ;
str_xfix = test_dexcluster_multi_xfix_2('tsne00_kmeansK',M,N,snr,n_cluster,gamma,niteration);
str_tsne00_kmeansK_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_tsne00_kmeansK_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_tsne00_kmeansK_mat,'file') & ~exist(str_tsne00_kmeansK_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_tsne00_kmeansK_mat)); 
save(str_tsne00_kmeansK_tmp,'str_tsne00_kmeansK_mat');
try;
%%%%%%%%;
lpv_ = zeros(n_vrank,1); lP0_ = zeros(n_vrank,1); fla_ = zeros(n_vrank,1); 
label_B__ = cell(n_vrank,1);
for nrank=1:n_vrank;
A_n_sub_ = fast_tsne_dr_0(A_n_,struct('rand_seed',1,'no_dims',nrank,'theta',0));
label_B__{nrank} = kmeans(A_n_sub_,1+n_cluster);
[lpv_(nrank),lP0_(nrank),fla_(nrank)] = label_to_label_enrichment_2(label_A_,label_B__{nrank});
end;%for nrank=1:n_vrank;
%%%%%%%%;
save(str_tsne00_kmeansK_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_tsne00_kmeansK_mat)); end;%try;
delete(str_tsne00_kmeansK_tmp);
end;%if (~exist(str_tsne00_kmeansK,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% tsne00 --> kmeansJ ;
str_xfix = test_dexcluster_multi_xfix_2('tsne00_kmeansJ',M,N,snr,n_cluster,gamma,niteration);
str_tsne00_kmeansJ_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_tsne00_kmeansJ_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_tsne00_kmeansJ_mat,'file') & ~exist(str_tsne00_kmeansJ_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_tsne00_kmeansJ_mat)); 
save(str_tsne00_kmeansJ_tmp,'str_tsne00_kmeansJ_mat');
try;
%%%%%%%%;
lpv_ = zeros(n_vrank*n_cluster,1); lP0_ = zeros(n_vrank*n_cluster,1); fla_ = zeros(n_vrank*n_cluster,1); 
label_B__ = cell(n_vrank*n_cluster,1);
ntab=0;
for nrank=1:n_vrank;
A_n_sub_ = fast_tsne_dr_0(A_n_,struct('rand_seed',1,'no_dims',nrank,'theta',0));
for ncluster=1:n_cluster;
ntab = ntab + 1;
label_B__{ntab} = kmeans(A_n_sub_,1+ncluster);
[lpv_(ntab),lP0_(ntab),fla_(ntab)] = label_to_label_enrichment_2(label_A_,label_B__{ntab});
end;%for ncluster=1:n_cluster;
end;%for nrank=1:n_vrank;
%%%%%%%%;
save(str_tsne00_kmeansJ_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_tsne00_kmeansJ_mat)); end;%try;
delete(str_tsne00_kmeansJ_tmp);
end;%if (~exist(str_tsne00_kmeansJ,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% tsne50 --> isosplit5 ;
str_xfix = test_dexcluster_multi_xfix_2('tsne50_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_tsne50_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_tsne50_isosplit5_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_tsne50_isosplit5_mat,'file') & ~exist(str_tsne50_isosplit5_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_tsne50_isosplit5_mat)); 
save(str_tsne50_isosplit5_tmp,'str_tsne50_isosplit5_mat');
try;
%%%%%%%%;
lpv_ = zeros(n_vrank,1); lP0_ = zeros(n_vrank,1); fla_ = zeros(n_vrank,1); 
label_B__ = cell(n_vrank,1);
for nrank=1:n_vrank;
A_n_sub_ = fast_tsne_dr_0(A_n_,struct('rand_seed',1,'no_dims',nrank,'theta',0.5));
opts_isosplit5 = struct('K_init',200,'isocut_threshold',1.0);
label_B__{nrank} = transpose(isosplit5(transpose(A_n_sub_),opts_isosplit5));
[lpv_(nrank),lP0_(nrank),fla_(nrank)] = label_to_label_enrichment_2(label_A_,label_B__{nrank});
end;%for nrank=1:n_vrank;
%%%%%%%%;
save(str_tsne50_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_tsne50_isosplit5_mat)); end;%try;
delete(str_tsne50_isosplit5_tmp);
end;%if (~exist(str_tsne50_isosplit5,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% tsne50 --> kmeansK ;
str_xfix = test_dexcluster_multi_xfix_2('tsne50_kmeansK',M,N,snr,n_cluster,gamma,niteration);
str_tsne50_kmeansK_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_tsne50_kmeansK_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_tsne50_kmeansK_mat,'file') & ~exist(str_tsne50_kmeansK_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_tsne50_kmeansK_mat)); 
save(str_tsne50_kmeansK_tmp,'str_tsne50_kmeansK_mat');
try;
%%%%%%%%;
lpv_ = zeros(n_vrank,1); lP0_ = zeros(n_vrank,1); fla_ = zeros(n_vrank,1); 
label_B__ = cell(n_vrank,1);
for nrank=1:n_vrank;
A_n_sub_ = fast_tsne_dr_0(A_n_,struct('rand_seed',1,'no_dims',nrank,'theta',0.5));
label_B__{nrank} = kmeans(A_n_sub_,n_cluster);
[lpv_(nrank),lP0_(nrank),fla_(nrank)] = label_to_label_enrichment_2(label_A_,label_B__{nrank});
end;%for nrank=1:n_vrank;
%%%%%%%%;
save(str_tsne50_kmeansK_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_tsne50_kmeansK_mat)); end;%try;
delete(str_tsne50_kmeansK_tmp);
end;%if (~exist(str_tsne50_kmeansK,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% tsne50 --> kmeansJ ;
str_xfix = test_dexcluster_multi_xfix_2('tsne50_kmeansJ',M,N,snr,n_cluster,gamma,niteration);
str_tsne50_kmeansJ_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_tsne50_kmeansJ_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_tsne50_kmeansJ_mat,'file') & ~exist(str_tsne50_kmeansJ_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_tsne50_kmeansJ_mat)); 
save(str_tsne50_kmeansJ_tmp,'str_tsne50_kmeansJ_mat');
try;
%%%%%%%%;
lpv_ = zeros(n_vrank*n_cluster,1); lP0_ = zeros(n_vrank*n_cluster,1); fla_ = zeros(n_vrank*n_cluster,1); 
label_B__ = cell(n_vrank*n_cluster,1);
ntab = 0;
for nrank=1:n_vrank;
A_n_sub_ = fast_tsne_dr_0(A_n_,struct('rand_seed',1,'no_dims',nrank,'theta',0.5));
for ncluster=1:n_cluster;
ntab = ntab + 1;
label_B__{ntab} = kmeans(A_n_sub_,1+ncluster);
[lpv_(ntab),lP0_(ntab),fla_(ntab)] = label_to_label_enrichment_2(label_A_,label_B__{ntab});
end;%for ncluster=1:n_cluster;
end;%for nrank=1:n_vrank;
%%%%%%%%;
save(str_tsne50_kmeansJ_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_tsne50_kmeansJ_mat)); end;%try;
delete(str_tsne50_kmeansJ_tmp);
end;%if (~exist(str_tsne50_kmeansJ,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% umap00 --> default ;
str_xfix = test_dexcluster_multi_xfix_2('umap00_default',M,N,snr,n_cluster,gamma,niteration);
str_umap00_default_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_umap00_default_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_umap00_default_mat,'file') & ~exist(str_umap00_default_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_umap00_default_mat)); 
save(str_umap00_default_tmp,'str_umap00_default_mat');
try;
%%%%%%%%;
lpv_ = zeros(1,1); lP0_ = zeros(1,1); fla_ = zeros(1,1); label_B__ = cell(1,1);
[A_n_sub_, ~, label_B__{1}]=run_umap(A_n_,'verbose','none');
[lpv_(1),lP0_(1),fla_(1)] = label_to_label_enrichment_2(label_A_,label_B__{1});
%%%%%%%%;
save(str_umap00_default_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_umap00_default_mat)); end;%try;
delete(str_umap00_default_tmp);
end;%if (~exist(str_umap00_default,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% umap00 --> isosplit5 ;
str_xfix = test_dexcluster_multi_xfix_2('umap00_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_umap00_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_umap00_isosplit5_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_umap00_isosplit5_mat,'file') & ~exist(str_umap00_isosplit5_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_umap00_isosplit5_mat)); 
save(str_umap00_isosplit5_tmp,'str_umap00_isosplit5_mat');
try;
%%%%%%%%;
lpv_ = zeros(1,1); lP0_ = zeros(1,1); fla_ = zeros(1,1); label_B__ = cell(1,1);
[A_n_sub_, ~, ~]=run_umap(A_n_,'verbose','none');
opts_isosplit5 = struct('K_init',200,'isocut_threshold',1.0);
label_B__{1} = transpose(isosplit5(transpose(A_n_sub_),opts_isosplit5));
[lpv_(1),lP0_(1),fla_(1)] = label_to_label_enrichment_2(label_A_,label_B__{1});
%%%%%%%%;
save(str_umap00_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_umap00_isosplit5_mat)); end;%try;
delete(str_umap00_isosplit5_tmp);
end;%if (~exist(str_umap00_isosplit5,'file'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% umap00 --> hdbscan ;
str_xfix = test_dexcluster_multi_xfix_2('umap00_hdbscan',M,N,snr,n_cluster,gamma,niteration);
str_umap00_hdbscan_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_umap00_hdbscan_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_umap00_hdbscan_mat,'file') & ~exist(str_umap00_hdbscan_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_umap00_hdbscan_mat)); 
save(str_umap00_hdbscan_tmp,'str_umap00_hdbscan_mat');
try;
%%%%%%%%;
lpv_ = zeros(1,1); lP0_ = zeros(1,1); fla_ = zeros(1,1); label_B__ = cell(1,1);
[A_n_sub_, ~, ~]=run_umap(A_n_,'verbose','none');
hdbscan_ = HDBSCAN(A_n_sub_); 
hdbscan_.minpts = 10; hdbscan_.fit_model(); hdbscan_.get_best_clusters(); hdbscan_.get_membership();
label_B__{1} = hdbscan_.labels;
[lpv_(1),lP0_(1),fla_(1)] = label_to_label_enrichment_2(label_A_,label_B__{1});
%%%%%%%%;
save(str_umap00_hdbscan_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
catch; disp(sprintf(' %% WARNING: error generating %s',str_umap00_hdbscan_mat)); end;%try;
delete(str_umap00_hdbscan_tmp);
end;%if (~exist(str_umap00_hdbscan,'file'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% dexcluster --> ZRmax ;
str_xfix = test_dexcluster_multi_xfix_2('dexcluster_nonbinary_trace_ZRmax',M,N,snr,n_cluster,gamma,niteration);
str_dexcluster_nonbinary_trace_ZRmax_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_dexcluster_nonbinary_trace_ZRmax_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_dexcluster_nonbinary_trace_ZRmax_mat,'file') & ~exist(str_dexcluster_nonbinary_trace_ZRmax_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_dexcluster_nonbinary_trace_ZRmax_mat)); 
save(str_dexcluster_nonbinary_trace_ZRmax_tmp,'str_dexcluster_nonbinary_trace_ZRmax_mat');
try;
%%%%%%%%;
prefix_base = sprintf('tmp_%s',str_xfix); 
dir_out = []; E_array_base_ = A_n_; E_array_r_ij_ = []; E_array_c_ij_ = []; p_set = [];
test_loader_dexcluster_nonbinary_trace_ZRmax_recursive_0(dir_out,prefix_base,E_array_base_,E_array_r_ij_,E_array_c_ij_,gamma,n_shuffle,p_set);
ZRmax_label_ = test_loader_dexcluster_nonbinary_trace_ZRmax_recursive_0(dir_out,prefix_base,E_array_base_,E_array_r_ij_,E_array_c_ij_,gamma,n_shuffle,p_set);
lpv_ = zeros(2,1); lP0_ = zeros(2,1); fla_ = zeros(2,1); label_B__ = cell(2,1);
label_B__{1} = label_str_to_enum_0(ZRmax_label_); 
label_B__{2} = label_rearrange_0(label_B__{1},E_array_base_);
[lpv_(1),lP0_(1),fla_(1)] = label_to_label_enrichment_2(label_A_,label_B__{1});
[lpv_(2),lP0_(2),fla_(2)] = label_to_label_enrichment_2(label_A_,label_B__{2});
%%%%%%%%;
save(str_dexcluster_nonbinary_trace_ZRmax_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
try; rmdir(sprintf(prefix_base),'s'); catch; disp(sprintf(' %% could not remove %s',sprintf(prefix_base))); end;%try;
catch; disp(sprintf(' %% WARNING: error generating %s',str_dexcluster_nonbinary_trace_ZRmax_mat)); end;%try;
delete(str_dexcluster_nonbinary_trace_ZRmax_tmp);
end;%if (~exist(str_dexcluster_nonbinary_trace_ZRmax,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% dexcluster --> ZRimax ;
str_xfix = test_dexcluster_multi_xfix_2('dexcluster_nonbinary_trace_ZRimax',M,N,snr,n_cluster,gamma,niteration);
str_dexcluster_nonbinary_trace_ZRimax_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_dexcluster_nonbinary_trace_ZRimax_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_dexcluster_nonbinary_trace_ZRimax_mat,'file') & ~exist(str_dexcluster_nonbinary_trace_ZRimax_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_dexcluster_nonbinary_trace_ZRimax_mat)); 
save(str_dexcluster_nonbinary_trace_ZRimax_tmp,'str_dexcluster_nonbinary_trace_ZRimax_mat');
%try;
%%%%%%%%;
prefix_base = sprintf('tmp_%s',str_xfix); 
dir_out = []; E_array_base_ = A_n_; E_array_r_ij_ = []; E_array_c_ij_ = []; p_set = []; n_member_lob = 2;
test_loader_dexcluster_nonbinary_trace_ZRimax_recursive_2(dir_base,dir_out,prefix_base,E_array_base_,E_array_r_ij_,E_array_c_ij_,gamma,n_shuffle,p_set,n_member_lob);
ZRimax_label_ = test_loader_dexcluster_nonbinary_trace_ZRimax_recursive_3(dir_base,dir_out,prefix_base,E_array_base_,E_array_r_ij_,E_array_c_ij_,gamma,n_shuffle,p_set,n_member_lob);
lpv_ = zeros(2,1); lP0_ = zeros(2,1); fla_ = zeros(2,1); label_B__ = cell(2,1);
label_B__{1} = label_str_to_enum_0(ZRimax_label_); 
label_B__{2} = label_rearrange_0(label_B__{1},E_array_base_);
[lpv_(1),lP0_(1),fla_(1)] = label_to_label_enrichment_2(label_A_,label_B__{1});
[lpv_(2),lP0_(2),fla_(2)] = label_to_label_enrichment_2(label_A_,label_B__{2});
%%%%%%%%;
save(str_dexcluster_nonbinary_trace_ZRimax_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
try; rmdir(sprintf('%s/dir_%s',dir_base,prefix_base),'s'); catch; disp(sprintf(' %% could not remove %s',sprintf('%s/dir_%s',dir_base,prefix_base))); end;%try;
%catch; disp(sprintf(' %% WARNING: error generating %s',str_dexcluster_nonbinary_trace_ZRimax_mat)); end;%try;
delete(str_dexcluster_nonbinary_trace_ZRimax_tmp);
end;%if (~exist(str_dexcluster_nonbinary_trace_ZRimax,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% lakcluster --> ZRimax ;
str_xfix = test_dexcluster_multi_xfix_2('lakcluster_nonbinary_trace_ZRimax',M,N,snr,n_cluster,gamma,niteration);
str_lakcluster_nonbinary_trace_ZRimax_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
str_lakcluster_nonbinary_trace_ZRimax_tmp = sprintf('%s/%s.tmp',dir_base,str_xfix);
if (~exist(str_lakcluster_nonbinary_trace_ZRimax_mat,'file') & ~exist(str_lakcluster_nonbinary_trace_ZRimax_tmp,'file')); 
disp(sprintf(' %% %s not found, creating',str_lakcluster_nonbinary_trace_ZRimax_mat)); 
save(str_lakcluster_nonbinary_trace_ZRimax_tmp,'str_lakcluster_nonbinary_trace_ZRimax_mat');
try;
%%%%%%%%;
prefix_base = sprintf('tmp_%s',str_xfix); 
dir_out = []; E_array_base_ = A_n_; E_array_r_ij_ = []; E_array_c_ij_ = []; p_set = []; n_member_lob = 2;
test_loader_lakcluster_nonbinary_trace_ZRimax_recursive_2(dir_base,dir_out,prefix_base,E_array_base_,E_array_r_ij_,E_array_c_ij_,gamma,n_shuffle,p_set,n_member_lob);
ZRimax_label_ = test_loader_lakcluster_nonbinary_trace_ZRimax_recursive_3(dir_base,dir_out,prefix_base,E_array_base_,E_array_r_ij_,E_array_c_ij_,gamma,n_shuffle,p_set,n_member_lob);
lpv_ = zeros(2,1); lP0_ = zeros(2,1); fla_ = zeros(2,1); label_B__ = cell(2,1);
label_B__{1} = label_str_to_enum_0(ZRimax_label_); 
label_B__{2} = label_rearrange_0(label_B__{1},E_array_base_);
[lpv_(1),lP0_(1),fla_(1)] = label_to_label_enrichment_2(label_A_,label_B__{1});
[lpv_(2),lP0_(2),fla_(2)] = label_to_label_enrichment_2(label_A_,label_B__{2});
%%%%%%%%;
save(str_lakcluster_nonbinary_trace_ZRimax_mat,'lpv_','lP0_','fla_','label_B__');
clear A_n_sub_ lpv_ lP0_ fla_ label_B__ ;
try; rmdir(sprintf('%s/dir_%s',dir_base,prefix_base),'s'); catch; disp(sprintf(' %% could not remove %s',sprintf('%s/dir_%s',dir_base,prefix_base))); end;%try;
catch; disp(sprintf(' %% WARNING: error generating %s',str_lakcluster_nonbinary_trace_ZRimax_mat)); end;%try;
delete(str_lakcluster_nonbinary_trace_ZRimax_tmp);
end;%if (~exist(str_lakcluster_nonbinary_trace_ZRimax,'file')); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%for niteration=1:n_iteration;

