function test_loader_plot_C_absZ__0(AB_,C_VariableName_LC_,dir_trunk,infix);

n_CCOV = AB_.n_CCOV;
n_CLabel = AB_.n_CLabel;
n_s = (n_CLabel-1)*n_CLabel/2;

[tmp_U_,tmp_S_,tmp_V_] = svds(AB_.AB_C_absZ_,1); [~,tmp_C_absZ_U_ij_] = sort(tmp_U_,'descend'); [~,tmp_C_absZ_V_ij_] = sort(tmp_V_,'descend');
[tmp_U_,tmp_S_,tmp_V_] = svds(AB_.AB_K_absZ_,1); [~,tmp_K_absZ_U_ij_] = sort(tmp_U_,'descend'); [~,tmp_K_absZ_V_ij_] = sort(tmp_V_,'descend');
%%%%%%%%;
figure(1);clf;
colormap(colormap_beach());
imagesc(AB_.AB_C_absZ_(tmp_C_absZ_U_ij_,tmp_C_absZ_V_ij_),[0,+15]); colorbar();
xlim([1,n_CCOV]); ylim([1,n_s]);
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_C_absZ_V_ij_),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'YTick',[],'YTickLabel',[]);
xlim([1,n_CCOV]); ylabel('CLabel pairs (rearranged)'); title('Covariates arranged by relevance across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_C_absZ',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%%%%%%%%;
figure(1);clf;
colormap(colormap_beach());
imagesc(AB_.AB_K_absZ_(tmp_K_absZ_U_ij_,tmp_K_absZ_V_ij_),[0,+15]); colorbar();
xlim([1,n_CCOV]); ylim([1,n_s]);
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_K_absZ_V_ij_),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'YTick',[],'YTickLabel',[]);
xlim([1,n_CCOV]); ylabel('CLabel pairs (rearranged)'); title('Covariates arranged by relative relevance across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_K_absZ',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%end;%if flag_Z;
%end;%if flag_disp;


[tmp_U_,tmp_S_,tmp_V_] = svds(AB_.AB_C_rawZ_,1); [~,tmp_C_rawZ_U_ij_] = sort(tmp_U_,'descend'); [~,tmp_C_rawZ_V_ij_] = sort(tmp_V_,'descend');
[tmp_U_,tmp_S_,tmp_V_] = svds(AB_.AB_K_rawZ_,1); [~,tmp_K_rawZ_U_ij_] = sort(tmp_U_,'descend'); [~,tmp_K_rawZ_V_ij_] = sort(tmp_V_,'descend');
%%%%%%%%;
figure(1);clf;
colormap(colormap_beach());
imagesc(AB_.AB_C_rawZ_(tmp_C_rawZ_U_ij_,tmp_C_rawZ_V_ij_),[0,+15]); colorbar();
xlim([1,n_CCOV]); ylim([1,n_s]);
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_C_rawZ_V_ij_),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'YTick',[],'YTickLabel',[]);
xlim([1,n_CCOV]); ylabel('CLabel pairs (rearranged)'); title('Covariates arranged by relevance across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_C_rawZ',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%%%%%%%%;
figure(1);clf;
colormap(colormap_beach());
imagesc(AB_.AB_K_rawZ_(tmp_K_rawZ_U_ij_,tmp_K_rawZ_V_ij_),[0,+15]); colorbar();
xlim([1,n_CCOV]); ylim([1,n_s]);
set(gca,'XTick',1:n_CCOV,'XTickLabel',C_VariableName_LC_(tmp_K_rawZ_V_ij_),'TickLabelInterpreter','none'); xtickangle(90);
set(gca,'YTick',[],'YTickLabel',[]);
xlim([1,n_CCOV]); ylabel('CLabel pairs (rearranged)'); title('Covariates arranged by relative relevance across all label-pairs');
set(gca,'FontSize',7); %set(gca,'FontName','Courier');
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('%s/dir_jpg/AB_%s_.AB_K_rawZ',dir_trunk,infix);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
%end;%if flag_Z;
%end;%if flag_disp;

