

%%%%%%%%;
M = 178; N = 2e3; n_cluster = 1; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 256; flag_rerun = 0;
%M = 1781; N = 2e4; n_cluster = 8; gamma = 0.01; n_rank = 6; n_iteration = 8; n_shuffle = 64; flag_rerun = 0;
dir_trunk = sprintf('/home/rangan/dir_bcc/dir_jamison');
dir_base = sprintf('%s/dir_dexcluster_multi_2',dir_trunk);
n_step = 21;
snr_ = linspace(0.5,1.5,n_step);
%%%%%%%%;

%%%%%%%%;
n_xrank = 2;
lpv_lakcluster_nonbinary_trace_ZRmax_ = zeros(n_xrank,n_step,1); lpv_lakcluster_nonbinary_trace_ZRmax__ = zeros(n_xrank,n_step,n_iteration);
lP0_lakcluster_nonbinary_trace_ZRmax_ = zeros(n_xrank,n_step,1); lP0_lakcluster_nonbinary_trace_ZRmax__ = zeros(n_xrank,n_step,n_iteration);
fla_lakcluster_nonbinary_trace_ZRmax_ = zeros(n_xrank,n_step,1); fla_lakcluster_nonbinary_trace_ZRmax__ = zeros(n_xrank,n_step,n_iteration);
%label_B_lakcluster_nonbinary_trace_ZRmax__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('lakcluster_nonbinary_trace_ZRimax',M,N,snr,n_cluster,gamma,niteration);
str_lakcluster_nonbinary_trace_ZRmax_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_lakcluster_nonbinary_trace_ZRmax_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_lakcluster_nonbinary_trace_ZRmax_mat)); end;
if ( exist(str_lakcluster_nonbinary_trace_ZRmax_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_lakcluster_nonbinary_trace_ZRmax_mat));
n_found = n_found+1;
tmp_ = load(str_lakcluster_nonbinary_trace_ZRmax_mat,'lpv_','lP0_','fla_','label_B__');
lpv_lakcluster_nonbinary_trace_ZRmax__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_lakcluster_nonbinary_trace_ZRmax__(:,nstep,n_found) = tmp_.lP0_(:);
fla_lakcluster_nonbinary_trace_ZRmax__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_lakcluster_nonbinary_trace_ZRmax__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_lakcluster_nonbinary_trace_ZRmax_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_lakcluster_nonbinary_trace_ZRmax_(:,nstep) = mean(lpv_lakcluster_nonbinary_trace_ZRmax__(:,nstep,1:n_found),3);
lP0_lakcluster_nonbinary_trace_ZRmax_(:,nstep) = mean(lP0_lakcluster_nonbinary_trace_ZRmax__(:,nstep,1:n_found),3);
fla_lakcluster_nonbinary_trace_ZRmax_(:,nstep) = mean(fla_lakcluster_nonbinary_trace_ZRmax__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 2;
lpv_dexcluster_nonbinary_trace_ZRmax_ = zeros(n_xrank,n_step,1); lpv_dexcluster_nonbinary_trace_ZRmax__ = zeros(n_xrank,n_step,n_iteration);
lP0_dexcluster_nonbinary_trace_ZRmax_ = zeros(n_xrank,n_step,1); lP0_dexcluster_nonbinary_trace_ZRmax__ = zeros(n_xrank,n_step,n_iteration);
fla_dexcluster_nonbinary_trace_ZRmax_ = zeros(n_xrank,n_step,1); fla_dexcluster_nonbinary_trace_ZRmax__ = zeros(n_xrank,n_step,n_iteration);
%label_B_dexcluster_nonbinary_trace_ZRmax__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('dexcluster_nonbinary_trace_ZRimax',M,N,snr,n_cluster,gamma,niteration);
str_dexcluster_nonbinary_trace_ZRmax_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_dexcluster_nonbinary_trace_ZRmax_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_dexcluster_nonbinary_trace_ZRmax_mat)); end;
if ( exist(str_dexcluster_nonbinary_trace_ZRmax_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_dexcluster_nonbinary_trace_ZRmax_mat));
n_found = n_found+1;
tmp_ = load(str_dexcluster_nonbinary_trace_ZRmax_mat,'lpv_','lP0_','fla_','label_B__');
lpv_dexcluster_nonbinary_trace_ZRmax__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_dexcluster_nonbinary_trace_ZRmax__(:,nstep,n_found) = tmp_.lP0_(:);
fla_dexcluster_nonbinary_trace_ZRmax__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_dexcluster_nonbinary_trace_ZRmax__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_dexcluster_nonbinary_trace_ZRmax_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_dexcluster_nonbinary_trace_ZRmax_(:,nstep) = mean(lpv_dexcluster_nonbinary_trace_ZRmax__(:,nstep,1:n_found),3);
lP0_dexcluster_nonbinary_trace_ZRmax_(:,nstep) = mean(lP0_dexcluster_nonbinary_trace_ZRmax__(:,nstep,1:n_found),3);
fla_dexcluster_nonbinary_trace_ZRmax_(:,nstep) = mean(fla_dexcluster_nonbinary_trace_ZRmax__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = n_rank;
lpv_spectral_kmeansK_ = zeros(n_xrank,n_step,1); lpv_spectral_kmeansK__ = zeros(n_xrank,n_step,n_iteration);
lP0_spectral_kmeansK_ = zeros(n_xrank,n_step,1); lP0_spectral_kmeansK__ = zeros(n_xrank,n_step,n_iteration);
fla_spectral_kmeansK_ = zeros(n_xrank,n_step,1); fla_spectral_kmeansK__ = zeros(n_xrank,n_step,n_iteration);
%label_B_spectral_kmeansK__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('spectral_kmeansK',M,N,snr,n_cluster,gamma,niteration);
str_spectral_kmeansK_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_spectral_kmeansK_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_spectral_kmeansK_mat)); end;
if ( exist(str_spectral_kmeansK_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_spectral_kmeansK_mat));
n_found = n_found+1;
tmp_ = load(str_spectral_kmeansK_mat,'lpv_','lP0_','fla_','label_B__');
lpv_spectral_kmeansK__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_spectral_kmeansK__(:,nstep,n_found) = tmp_.lP0_(:);
fla_spectral_kmeansK__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_spectral_kmeansK__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_spectral_kmeansK_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_spectral_kmeansK_(:,nstep) = mean(lpv_spectral_kmeansK__(:,nstep,1:n_found),3);
lP0_spectral_kmeansK_(:,nstep) = mean(lP0_spectral_kmeansK__(:,nstep,1:n_found),3);
fla_spectral_kmeansK_(:,nstep) = mean(fla_spectral_kmeansK__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = n_rank;
lpv_spectral_isosplit5_ = zeros(n_xrank,n_step,1); lpv_spectral_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
lP0_spectral_isosplit5_ = zeros(n_xrank,n_step,1); lP0_spectral_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
fla_spectral_isosplit5_ = zeros(n_xrank,n_step,1); fla_spectral_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
%label_B_spectral_isosplit5__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('spectral_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_spectral_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_spectral_isosplit5_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_spectral_isosplit5_mat)); end;
if ( exist(str_spectral_isosplit5_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_spectral_isosplit5_mat));
n_found = n_found+1;
tmp_ = load(str_spectral_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
lpv_spectral_isosplit5__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_spectral_isosplit5__(:,nstep,n_found) = tmp_.lP0_(:);
fla_spectral_isosplit5__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_spectral_isosplit5__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_spectral_isosplit5_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_spectral_isosplit5_(:,nstep) = mean(lpv_spectral_isosplit5__(:,nstep,1:n_found),3);
lP0_spectral_isosplit5_(:,nstep) = mean(lP0_spectral_isosplit5__(:,nstep,1:n_found),3);
fla_spectral_isosplit5_(:,nstep) = mean(fla_spectral_isosplit5__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 2;
lpv_tsne00_isosplit5_ = zeros(n_xrank,n_step,1); lpv_tsne00_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
lP0_tsne00_isosplit5_ = zeros(n_xrank,n_step,1); lP0_tsne00_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
fla_tsne00_isosplit5_ = zeros(n_xrank,n_step,1); fla_tsne00_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
%label_B_tsne00_isosplit5__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('tsne00_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_tsne00_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_tsne00_isosplit5_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_tsne00_isosplit5_mat)); end;
if ( exist(str_tsne00_isosplit5_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_tsne00_isosplit5_mat));
n_found = n_found+1;
tmp_ = load(str_tsne00_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
lpv_tsne00_isosplit5__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_tsne00_isosplit5__(:,nstep,n_found) = tmp_.lP0_(:);
fla_tsne00_isosplit5__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_tsne00_isosplit5__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_tsne00_isosplit5_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_tsne00_isosplit5_(:,nstep) = mean(lpv_tsne00_isosplit5__(:,nstep,1:n_found),3);
lP0_tsne00_isosplit5_(:,nstep) = mean(lP0_tsne00_isosplit5__(:,nstep,1:n_found),3);
fla_tsne00_isosplit5_(:,nstep) = mean(fla_tsne00_isosplit5__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 2;
lpv_tsne50_isosplit5_ = zeros(n_xrank,n_step,1); lpv_tsne50_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
lP0_tsne50_isosplit5_ = zeros(n_xrank,n_step,1); lP0_tsne50_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
fla_tsne50_isosplit5_ = zeros(n_xrank,n_step,1); fla_tsne50_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
%label_B_tsne50_isosplit5__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('tsne50_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_tsne50_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_tsne50_isosplit5_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_tsne50_isosplit5_mat)); end;
if ( exist(str_tsne50_isosplit5_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_tsne50_isosplit5_mat));
n_found = n_found+1;
tmp_ = load(str_tsne50_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
lpv_tsne50_isosplit5__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_tsne50_isosplit5__(:,nstep,n_found) = tmp_.lP0_(:);
fla_tsne50_isosplit5__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_tsne50_isosplit5__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_tsne50_isosplit5_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_tsne50_isosplit5_(:,nstep) = mean(lpv_tsne50_isosplit5__(:,nstep,1:n_found),3);
lP0_tsne50_isosplit5_(:,nstep) = mean(lP0_tsne50_isosplit5__(:,nstep,1:n_found),3);
fla_tsne50_isosplit5_(:,nstep) = mean(fla_tsne50_isosplit5__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 1;
lpv_umap00_default_ = zeros(n_xrank,n_step,1); lpv_umap00_default__ = zeros(n_xrank,n_step,n_iteration);
lP0_umap00_default_ = zeros(n_xrank,n_step,1); lP0_umap00_default__ = zeros(n_xrank,n_step,n_iteration);
fla_umap00_default_ = zeros(n_xrank,n_step,1); fla_umap00_default__ = zeros(n_xrank,n_step,n_iteration);
%label_B_umap00_default__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('umap00_default',M,N,snr,n_cluster,gamma,niteration);
str_umap00_default_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_umap00_default_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_umap00_default_mat)); end;
if ( exist(str_umap00_default_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_umap00_default_mat));
n_found = n_found+1;
tmp_ = load(str_umap00_default_mat,'lpv_','lP0_','fla_','label_B__');
lpv_umap00_default__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_umap00_default__(:,nstep,n_found) = tmp_.lP0_(:);
fla_umap00_default__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_umap00_default__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_umap00_default_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_umap00_default_(:,nstep) = mean(lpv_umap00_default__(:,nstep,1:n_found),3);
lP0_umap00_default_(:,nstep) = mean(lP0_umap00_default__(:,nstep,1:n_found),3);
fla_umap00_default_(:,nstep) = mean(fla_umap00_default__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 1;
lpv_umap00_isosplit5_ = zeros(n_xrank,n_step,1); lpv_umap00_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
lP0_umap00_isosplit5_ = zeros(n_xrank,n_step,1); lP0_umap00_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
fla_umap00_isosplit5_ = zeros(n_xrank,n_step,1); fla_umap00_isosplit5__ = zeros(n_xrank,n_step,n_iteration);
%label_B_umap00_isosplit5__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('umap00_isosplit5',M,N,snr,n_cluster,gamma,niteration);
str_umap00_isosplit5_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_umap00_isosplit5_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_umap00_isosplit5_mat)); end;
if ( exist(str_umap00_isosplit5_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_umap00_isosplit5_mat));
n_found = n_found+1;
tmp_ = load(str_umap00_isosplit5_mat,'lpv_','lP0_','fla_','label_B__');
lpv_umap00_isosplit5__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_umap00_isosplit5__(:,nstep,n_found) = tmp_.lP0_(:);
fla_umap00_isosplit5__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_umap00_isosplit5__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_umap00_isosplit5_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_umap00_isosplit5_(:,nstep) = mean(lpv_umap00_isosplit5__(:,nstep,1:n_found),3);
lP0_umap00_isosplit5_(:,nstep) = mean(lP0_umap00_isosplit5__(:,nstep,1:n_found),3);
fla_umap00_isosplit5_(:,nstep) = mean(fla_umap00_isosplit5__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 1;
lpv_umap00_hdbscan_ = zeros(n_xrank,n_step,1); lpv_umap00_hdbscan__ = zeros(n_xrank,n_step,n_iteration);
lP0_umap00_hdbscan_ = zeros(n_xrank,n_step,1); lP0_umap00_hdbscan__ = zeros(n_xrank,n_step,n_iteration);
fla_umap00_hdbscan_ = zeros(n_xrank,n_step,1); fla_umap00_hdbscan__ = zeros(n_xrank,n_step,n_iteration);
%label_B_umap00_hdbscan__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('umap00_hdbscan',M,N,snr,n_cluster,gamma,niteration);
str_umap00_hdbscan_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_umap00_hdbscan_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_umap00_hdbscan_mat)); end;
if ( exist(str_umap00_hdbscan_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_umap00_hdbscan_mat));
n_found = n_found+1;
tmp_ = load(str_umap00_hdbscan_mat,'lpv_','lP0_','fla_','label_B__');
lpv_umap00_hdbscan__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_umap00_hdbscan__(:,nstep,n_found) = tmp_.lP0_(:);
fla_umap00_hdbscan__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_umap00_hdbscan__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_umap00_hdbscan_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_umap00_hdbscan_(:,nstep) = mean(lpv_umap00_hdbscan__(:,nstep,1:n_found),3);
lP0_umap00_hdbscan_(:,nstep) = mean(lP0_umap00_hdbscan__(:,nstep,1:n_found),3);
fla_umap00_hdbscan_(:,nstep) = mean(fla_umap00_hdbscan__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 1;
lpv_louvain00_ = zeros(n_xrank,n_step,1); lpv_louvain00__ = zeros(n_xrank,n_step,n_iteration);
lP0_louvain00_ = zeros(n_xrank,n_step,1); lP0_louvain00__ = zeros(n_xrank,n_step,n_iteration);
fla_louvain00_ = zeros(n_xrank,n_step,1); fla_louvain00__ = zeros(n_xrank,n_step,n_iteration);
%label_B_louvain00__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('louvain00',M,N,snr,n_cluster,gamma,niteration);
str_louvain00_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_louvain00_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_louvain00_mat)); end;
if ( exist(str_louvain00_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_louvain00_mat));
n_found = n_found+1;
tmp_ = load(str_louvain00_mat,'lpv_','lP0_','fla_','label_B__');
lpv_louvain00__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_louvain00__(:,nstep,n_found) = tmp_.lP0_(:);
fla_louvain00__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_louvain00__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_louvain00_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_louvain00_(:,nstep) = mean(lpv_louvain00__(:,nstep,1:n_found),3);
lP0_louvain00_(:,nstep) = mean(lP0_louvain00__(:,nstep,1:n_found),3);
fla_louvain00_(:,nstep) = mean(fla_louvain00__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;
n_xrank = 1;
lpv_louvainpr_ = zeros(n_xrank,n_step,1); lpv_louvainpr__ = zeros(n_xrank,n_step,n_iteration);
lP0_louvainpr_ = zeros(n_xrank,n_step,1); lP0_louvainpr__ = zeros(n_xrank,n_step,n_iteration);
fla_louvainpr_ = zeros(n_xrank,n_step,1); fla_louvainpr__ = zeros(n_xrank,n_step,n_iteration);
%label_B_louvainpr__ = zeros(M,n_xrank,n_step,n_iteration);
for nstep=1:n_step;
snr = snr_(nstep);
n_found = 0;
for niteration = 1:n_iteration;
str_xfix = test_dexcluster_multi_xfix_2('louvainpr',M,N,snr,n_cluster,gamma,niteration);
str_louvainpr_mat = sprintf('%s/%s.mat',dir_base,str_xfix);
if (~exist(str_louvainpr_mat,'file')) disp(sprintf(' %% WARNING: %s not found.',str_louvainpr_mat)); end;
if ( exist(str_louvainpr_mat,'file'));
disp(sprintf(' %% found %s, loading...',str_louvainpr_mat));
n_found = n_found+1;
tmp_ = load(str_louvainpr_mat,'lpv_','lP0_','fla_','label_B__');
lpv_louvainpr__(:,nstep,n_found) = tmp_.lpv_(:);
lP0_louvainpr__(:,nstep,n_found) = tmp_.lP0_(:);
fla_louvainpr__(:,nstep,n_found) = tmp_.fla_(:);
%for nxrank=1:n_xrank; label_B_louvainpr__(:,nxrank,nstep,n_found) = tmp_.label_B__{nxrank}; end;
end; %if ( exist(str_louvainpr_mat,'file'));
end;%for niteration = 1:n_iteration;
if n_found>0;
lpv_louvainpr_(:,nstep) = mean(lpv_louvainpr__(:,nstep,1:n_found),3);
lP0_louvainpr_(:,nstep) = mean(lP0_louvainpr__(:,nstep,1:n_found),3);
fla_louvainpr_(:,nstep) = mean(fla_louvainpr__(:,nstep,1:n_found),3);
end;%if n_found>0;
end;%for nstep=1:n_step;
%%%%%%%%;

%lpv_dexcluster_nonbinary_trace_ZRmax_(1,end) = lpv_dexcluster_nonbinary_trace_ZRmax_(1,end-1);
%legend_str_ = {'loop','pca1->kmeansK','pca6->kmeansK','pca6->isosplit5','tsne00->isosplit5','tsne50->isosplit5','umap00->default','umap00->isosplit5','umap00->hdbscan'};
Msize = 15;
figure(1);clf;
%%%%%%%%;
subplot(1,2,1);
legend_str_ = {'1loop','hloop','pca1->isosplit5','pca2->isosplit5','pca3->isosplit5','pca4->isosplit5','pca5->isosplit5','pca6->isosplit5','louvain00','louvainpr'};
hold on;
plot(snr_,-lpv_lakcluster_nonbinary_trace_ZRmax_(1,:),'mh-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_dexcluster_nonbinary_trace_ZRmax_(1,:),'ms-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_kmeansK_(1,:),'gs-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_kmeansK_(6,:),'gh-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_spectral_isosplit5_(1,:),'go-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_spectral_isosplit5_(2,:),'gx-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_spectral_isosplit5_(3,:),'g^-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_spectral_isosplit5_(4,:),'gs-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_spectral_isosplit5_(5,:),'gp-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_spectral_isosplit5_(6,:),'gh-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_louvain00_(1,:),'ro-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_louvainpr_(1,:),'rx-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_tsne00_isosplit5_(1,:),'co-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_tsne50_isosplit5_(1,:),'bo-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_umap00_default_,'kx-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_umap00_isosplit5_,'ko-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_umap00_hdbscan_,'k^-','LineWidth',2,'MarkerSize',Msize);
hold off;
xlabel('snr'); ylabel('-log(pvalue)'); title(sprintf('M%d N%d n%d',M,N,n_cluster),'Interpreter','none');
legend(legend_str_,'Location','NorthWest');
%%%%%%%%;
subplot(1,2,2);
legend_str_ = {'1loop','hloop','tsne00->isosplit5','tsne50->isosplit5','umap00->default','umap00->isosplit5','umap00->hdbscan'};
hold on;
plot(snr_,-lpv_lakcluster_nonbinary_trace_ZRmax_(1,:),'mh-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_dexcluster_nonbinary_trace_ZRmax_(1,:),'ms-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_kmeansK_(1,:),'gs-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_kmeansK_(6,:),'gh-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_isosplit5_(1,:),'go-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_isosplit5_(2,:),'gx-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_isosplit5_(3,:),'g^-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_isosplit5_(4,:),'gs-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_isosplit5_(5,:),'gp-','LineWidth',2,'MarkerSize',Msize);
%plot(snr_,-lpv_spectral_isosplit5_(6,:),'gh-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_tsne00_isosplit5_(1,:),'co-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_tsne50_isosplit5_(1,:),'bo-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_umap00_default_,'kx-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_umap00_isosplit5_,'ko-','LineWidth',2,'MarkerSize',Msize);
plot(snr_,-lpv_umap00_hdbscan_,'k^-','LineWidth',2,'MarkerSize',Msize);
hold off;
xlabel('snr'); ylabel('-log(pvalue)'); title(sprintf('M%d N%d n%d',M,N,n_cluster),'Interpreter','none');
legend(legend_str_,'Location','NorthWest');
%%%%%%%%;
figbig;
str_fig = sprintf('%s/dir_jpg/test_dexcluster_multi_2b_collect_M%d_N%d_n%d',dir_base,M,N,n_cluster);
disp(sprintf(' %% writing %s',str_fig));
print('-djpeg',sprintf('%s.jpg',str_fig));
print('-depsc',sprintf('%s.eps',str_fig));
