% Test cluster-supervised pca. ;
% Clusters are each distinct gaussians with different means and (slightly) different standard-deviations. ;
% We also modulate the ratio 'alpha' used to define Alpha_. ;
% For each alpha we calculate lp_iso ;

clear; setup; rng(1);
%%%%%%%%;
M = 1024; N = 2e3;
n_cluster = 8; gamma_cluster = 2;
mu = 0.5; %<-- signal. ;
sg_ = 0.5 + rand(n_cluster,1); %<-- clusters have randomized standard-deviations. ;
mu = 0.0; sg_ = ones(n_cluster,1); %<-- no signal. ;
%%%%%%%%;
[tmp_VORI_,~] = qr(randn(N,n_cluster),0);
w_ = linspace(0,1,M+1); w_ = w_(1:end-1);
Sample_Label_ = floor(n_cluster* w_.^gamma_cluster ); %<-- gamma_cluster sets the inequality in cluster size. ;
u_Sample_Label_ = unique(Sample_Label_); n_Sample_Label = length(u_Sample_Label_);
n_Sample_Label_ = zeros(n_Sample_Label,1);
Sample_Label_ij_ = cell(n_Sample_Label);
for nSample_Label=1:n_Sample_Label;
Sample_Label_ij_{nSample_Label} = find(Sample_Label_==u_Sample_Label_(nSample_Label));
n_Sample_Label_(nSample_Label) = length(Sample_Label_ij_{nSample_Label});
end;%for nSample_Label=1:n_Sample_Label;
D_ = zeros(M,N);
for ncluster=1:n_cluster;
D_(Sample_Label_ij_{ncluster},:) = randn(n_Sample_Label_(ncluster),N)*sg_(ncluster) + mu*ones(n_Sample_Label_(ncluster),1)*transpose(tmp_VORI_(:,ncluster));
end;%for ncluster=1:n_cluster;
tmp_UORI_ = D_*tmp_VORI_;
%%%%%%%%;

%%%%%%%%;
kld__ = kld_iso__1(D_,Sample_Label_); kld_50_ = median(kld__,1);
n_alpha = 15;
alpha_ = linspace(1,n_alpha,n_alpha);
n_rank_ = zeros(n_alpha,1);
kld___ = zeros(n_cluster*(n_cluster-1),N,n_alpha);
for nalpha = 1:n_alpha;
alpha = alpha_(nalpha);
disp(sprintf(' %% nalpha %d/%d alpha %0.6f',nalpha,n_alpha,alpha));
%%%%%%%%;
Alpha_ = zeros(M,M);
for ncluster1=1:n_cluster; for ncluster2=1:n_cluster;
tmp = (1/alpha - (ncluster1==ncluster2)) / (n_Sample_Label_(ncluster1) * n_Sample_Label_(ncluster2)) ;
Alpha_(Sample_Label_ij_{ncluster1},Sample_Label_ij_{ncluster2}) = tmp;
end;end;%for ncluster1=1:n_cluster; for ncluster2=1:n_cluster;
A2_ = Alpha_ - diag(sum(Alpha_,2)); E_A2_ = eig(A2_);
n_rank_A2 = length(find(abs(E_A2_/E_A2_(1))>1e-6));
disp(sprintf(' %% E_A2_ [%+0.6f,%+0.6f]; pos %d neg %d rank %d',min(E_A2_),max(E_A2_),length(find(E_A2_>0)),length(find(E_A2_<0)),n_rank_A2));
A2fun = @(x,str) transpose(D_)*(A2_*(D_*x));
n_rank = min(M,n_rank_A2); n_rank_(nalpha) = n_rank;
[tmp_VAD_,tmp_SAD2_] = eigs(A2fun,N,n_rank,'largestabs','IsFunctionSymmetric',1,'Display',0);
tmp_SAD2_ = diag(tmp_SAD2_);
tmp_SAD_ = sqrt(abs(tmp_SAD2_)); %<-- pretend we took eigenvalues of positive definite matrix [transpose(D_)*A2_*D_*transpose(D_)*A2_*D_]. ;
tmp_DVS_ = D_*tmp_VAD_(:,1:n_rank)*diag(1./tmp_SAD_(1:n_rank));
%%%%%%%%;
kld___(:,1:n_rank,nalpha) = kld_iso__1(tmp_DVS_,Sample_Label_);
%%%%%%%%;
flag_plot=1;
if flag_plot;
figure(1);subplot(3,5,nalpha)
scatter(tmp_DVS_(:,1),tmp_DVS_(:,2),15,Sample_Label_,'filled'); colormap(colormap_beach());
axisnotick;
title(sprintf('alpha %0.2f -kld50 %+0.2f',alpha,-median(kld___(:,2,nalpha))));
figbig;drawnow();
end;%if flag_plot;
%%%%%%%%;
end;%for nalpha = 1:n_alpha;
n_rank = max(n_rank_);
kld_50__ = squeeze(median(kld___(:,1:n_rank,:),1));
%%%%%%%%;

%%%%%%%%;
plot_flag=1;
if plot_flag;
figure(2);
c_ = colormap_beach(); n_c = size(c_,1);
hold on;
plot(log2(1:n_rank),-kld_50_(1:n_rank)./[1:n_rank],'k.-');
for nalpha=1:n_alpha;
nc = max(1,min(n_c,floor(n_c*nalpha/n_alpha)));
plot(log2(1:n_rank),-kld_50__(1:n_rank,nalpha)./transpose([1:n_rank]),'o-','Color',c_(nc,:));
end;%for nalpha=1:n_alpha;
xlabel('log2(rank)'); ylabel('kld/dim');
legend(num2str(transpose([0,alpha_])),'Location','NorthEast');
title('kld/dim versus rank');
figbig;
end;%if plot_flag;
%%%%%%%%;




