%function test_loader_cluster_collect_12b();
% collect results from test_loader_cluster_wrap_driver_2.m ;

setup;
%%%%%%%%;
dir_trunk = '/data/rangan/dir_bcc/dir_jamison';
str_C_tsv_ = sprintf('%s/dir_mat/C_rank_.tsv',dir_trunk);
C_rank_ = textread(str_C_tsv_); C_rank_ = C_rank_(:,1:end-1);
str_C_nsv_ = sprintf('%s/dir_mat/C_VariableName_.nsv',dir_trunk);
fp = fopen(str_C_nsv_,'r'); C_VariableName_ = textscan(fp,'%s\n'); fclose(fp); C_VariableName_ = C_VariableName_{1};
fp_label_A_ = fopen(sprintf('%s/dir_mat/str_CLabel_sub_.nsv',dir_trunk),'r');
str_label_A_ = textscan(fp_label_A_,'%s'); fclose(fp_label_A_);
n_u = numel(str_label_A_{1});
prefix_normalization = 'li16bf';
str_E_tsv_ = sprintf('%s/dir_mat/E_%s_.tsv',dir_trunk,prefix_normalization);
fp = fopen(str_E_tsv_,'r'); tmp_ = fgetl(fp); fclose(fp);
n_E_GENE = numel(str2num(tmp_)); clear tmp_;
str_I_tsv_ = sprintf('%s/dir_mat/I_%s_.tsv',dir_trunk,prefix_normalization);
fp = fopen(str_I_tsv_,'r'); tmp_ = fgetl(fp); fclose(fp);
n_I_GENE = numel(str2num(tmp_)); clear tmp_;
label_A_ = label_str_to_enum_0(str_label_A_{1});
%%%%%%%%;

%%%%%%%%;
u_label_A_ = unique(str_label_A_{1});
n_label_A = length(u_label_A_);
label_A_each__ = zeros(n_u,n_label_A);
for nlabel_A=1:n_label_A;
label_A_each__(:,nlabel_A) = zeros(n_u,1);
tmp_ij_ = find(strcmp(str_label_A_{1},u_label_A_{nlabel_A}));
label_A_each__(tmp_ij_,nlabel_A) = 1;
end;%for nlabel_A=1:n_label_A;
%%%%%%%%;

str_X_ = {'E','I','EI'}; n_X = numel(str_X_);
%str_Z_ = {'lakcluster_nonbinary_trace_ZRimax_g010_p050_nml3','dexcluster_nonbinary_trace_ZRimax_g010_p050_nml3','spectral_isosplit5','tsne50_isosplit5','tsne00_isosplit5','umap00_isosplit5','umap00_hdbscan'}; n_Z = numel(str_Z_);
%n_Z_index_ = [2,2,6,2,2,1,1]; assert(length(n_Z_index_)>=n_Z); n_Z_index_max = max(n_Z_index_);
str_Z_ = {'dexcluster_nonbinary_trace_ZRimax_g010_p050_nml3','spectral_isosplit5','tsne50_isosplit5','tsne00_isosplit5','umap00_isosplit5','umap00_hdbscan'}; n_Z = numel(str_Z_);
n_Z_index_ = [2,6,2,2,1,1]; assert(length(n_Z_index_)>=n_Z); n_Z_index_max = max(n_Z_index_);
%str_Y_ = {'li16bf','li16bf_c127_r12','li16bf_cRRR_r12','li16bf_c012_r12','li16bf_cUE1_r1','li16bf_cUE2_r5','li16bf_cUE3_r8','li16bf_cUE4_r1','li16bf_cUE5_r1','li16bf_cUE6_r8'}; n_Y = numel(str_Y_);
str_Y_ = {'li16bf','li16bf_c127_r12'}; n_Y = numel(str_Y_);
nlpv_XYZ_ = -ones(1+n_label_A,n_X,n_Y,n_Z,n_Z_index_max);
n_cluster_XYZ_ = -ones(n_X,n_Y,n_Z,n_Z_index_max);
flag_rerun_each = 0;
for nX=1:n_X;
str_X = str_X_{nX};
disp(sprintf(' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% '));
disp(sprintf(' %% %s: ',str_X));
disp(sprintf(' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% '));
%%%%%%%%;
for nZ=1:n_Z;
str_Z = str_Z_{nZ};
n_Z_index = n_Z_index_(nZ);
%%%%%%%%;
for nY=1:n_Y;
str_Y = str_Y_{nY};
%%%%%%%%;
str_mat = sprintf('/data/rangan/dir_bcc/dir_jamison/dir_loader_cluster/dir_%s_%s_cluster/%s.mat',str_X,str_Y,str_Z);
if ( exist(str_mat,'file'));
disp(sprintf(' %% %s found, not creating',str_mat));
tmp_mat_ = load(str_mat);
for nZ_index=1:n_Z_index;
tmp_n_cluster = length(unique(tmp_mat_.label_B__{nZ_index}));
tmp_lpv = tmp_mat_.lpv_(nZ_index);
disp(sprintf(' %% %s %s %s: index %d: num clusters %d; p_value exp(%0.6f)',str_X,str_Y,str_Z,nZ_index,tmp_n_cluster,tmp_lpv));
nlpv_XYZ_(1,nX,nY,nZ,nZ_index) = -tmp_lpv;
n_cluster_XYZ_(nX,nY,nZ,nZ_index) = tmp_n_cluster;
end;%for nZ_index=1:n_Z_index;
%%%%%%%%;
str_each_pre = sprintf('/data/rangan/dir_bcc/dir_jamison/dir_loader_cluster/dir_%s_%s_cluster/%s_each',str_X,str_Y,str_Z);
str_each_mat = sprintf('%s.mat',str_each_pre);
str_each_tmp = sprintf('%s.tmp',str_each_pre);
lpv_each_ = ones(n_label_A,n_Z_index);
lp0_each_ = ones(n_label_A,n_Z_index);
if (~flag_rerun_each &&  ( exist(str_each_mat,'file') |  exist(str_each_tmp,'file'))); 
%disp(sprintf(' %% %s found, not creating',str_each_mat)); 
if ( exist(str_each_mat,'file'));
tmp_each_mat_ = load(str_each_mat); 
lpv_each_ = tmp_each_mat_.lpv_each_;
lp0_each_ = tmp_each_mat_.lp0_each_;
flag_method_each_ = tmp_each_mat_.flag_method_each_;
end;%if ( exist(str_each_mat,'file'));
 else;% if not found. ;
%disp(sprintf(' %% %s not found, creating',str_each_mat)); 
save(str_each_tmp,'str_each_mat');
lpv_each_ = zeros(n_label_A,n_Z_index);
lp0_each_ = zeros(n_label_A,n_Z_index);
flag_method_each_ = zeros(n_label_A,n_Z_index);
for nZ_index=1:n_Z_index;
for nlabel_A=1:n_label_A;
disp(sprintf(' %% %s %s %s: each for nZ_index %d nlabel_A %d (str %s)',str_X,str_Y,str_Z,nZ_index,nlabel_A,u_label_A_{nlabel_A}));
[lpv_each_(nlabel_A,nZ_index),lP0_each_(nlabel_A,nZ_index),flag_method_each_(nlabel_A,nZ_index)] = label_to_label_enrichment_2(label_A_each__(:,nlabel_A),tmp_mat_.label_B__{nZ_index});
disp(sprintf(' %% lpv exp(%0.6f) lp0 exp(%0.6f) flag_method %d',lpv_each_(nlabel_A,nZ_index),lP0_each_(nlabel_A,nZ_index),flag_method_each_(nlabel_A,nZ_index)));
end;%for nlabel_A=1:n_label_A;
end;%for nZ_index=1:n_Z_index;
save(str_each_mat,'lpv_each_','lp0_each_','flag_method_each_');
delete(str_each_tmp);
end;%if (~exist(str_each_mat,'file')); 
for nZ_index=1:n_Z_index;
tmp_n_cluster = length(unique(tmp_mat_.label_B__{nZ_index}));
tmp_lpv = tmp_mat_.lpv_(nZ_index);
disp(sprintf(' %% %s %s %s: index %d: num clusters %d; p_value exp(%0.6f)',str_X,str_Y,str_Z,nZ_index,tmp_n_cluster,tmp_lpv));
tmp_str1_ = ''; tmp_str2_ = '';
for nlabel_A=1:n_label_A;
tmp_str1_ = sprintf('%s %.3d',tmp_str1_,nlabel_A);
tmp_str2_ = sprintf('%s %.3d',tmp_str2_,round(-lpv_each_(nlabel_A,nZ_index)));
nlpv_XYZ_(1+nlabel_A,nX,nY,nZ,nZ_index) = -lpv_each_(nlabel_A,nZ_index);
end;%for nlabel_A=1:n_label_A;
disp(sprintf(' %% %s',tmp_str1_));
disp(sprintf(' %% %s',tmp_str2_));
end;%for nZ_index=1:n_Z_index;
end;%if ( exist(str_mat,'file'));
if (~exist(str_mat,'file'));
disp(sprintf(' %% %s not found, skipping',str_mat));
end;%if (~exist(str_mat,'file'));
%%%%%%%%;
end;%for nY=1:n_Y;
%%%%%%%%;
end;%for nZ=1:n_Z;
%%%%%%%%;
end;%for nX=1:n_X;

%%%%%%%%;
% Now create PYZ figure;
%%%%%%%%;
str_ticklabel_ = cell(1+n_label_A,1);
str_ticklabel_{1} = 'all';
for nlabel_A=1:n_label_A;
str_ticklabel_{1+nlabel_A} = sprintf('%d: ''%s''',nlabel_A,u_label_A_{nlabel_A});
end;%for nlabel_A=1:n_label_A;
str_ticklabel_AIBS_ = zeros(1+n_label_A,1);
str_ticklabel_AIBS_(1) = 0;
for nlabel_A=1:n_label_A;
if  strcmp(u_label_A_{nlabel_A},'NA'); 
str_ticklabel_AIBS_(1+nlabel_A) = -1; 
end;%if  strcmp(u_label_A_{nlabel_A},'NA'); 
if ~strcmp(u_label_A_{nlabel_A},'NA'); 
str_ticklabel_AIBS_(1+nlabel_A) = str2num(u_label_A_{nlabel_A}); 
end;%if ~strcmp(u_label_A_{nlabel_A},'NA'); 
end;%for nlabel_A=1:n_label_A;
[~,AIBS_ij_] = sort(str_ticklabel_AIBS_);
pre_Y_ = {'000','127','RRR','012','UE1','UE2','UE3','UE4','UE5','UE6'};
pre_Z_ = {'Loop  ','PCA    ','TSNE50 ','TSNE00 ','UmapIso ','UmapHDB '};
n_Z_index_sum = sum(n_Z_index_);
n_a = n_Z_index_sum*n_Y + 2*(n_Z-1);
T_ = -ones(n_a,1+n_label_A,n_X);
str_YZ_ = cell(n_a,1);
na=0;
for nZ=1:n_Z;
n_Z_index = n_Z_index_(nZ);
for nZ_index=1:n_Z_index;
for nY=1:n_Y;
if (n_Z_index==1); 
str_YZ_{1+na} = sprintf('%s %s',pre_Z_{nZ},pre_Y_{nY});
end;%if (n_Z_index==1); 
if (n_Z_index>1); 
str_YZ_{1+na} = sprintf('%s%d %s',pre_Z_{nZ},nZ_index,pre_Y_{nY});
end;%if (n_Z_index>1); 
for nX=1:n_X;
T_(1+na,1,nX) = nlpv_XYZ_(1,nX,nY,nZ,nZ_index);
for nlabel_A=1:n_label_A;
T_(1+na,1+nlabel_A,nX) = nlpv_XYZ_(1+nlabel_A,nX,nY,nZ,nZ_index);
end;%for nlabel_A=1:n_label_A;
end;%for nX=1:n_X;
na = na+1;
end;%for nY=1:n_Y;
end;%for nZ_index=1:n_Z_index;
if (nZ<n_Z); str_YZ_{1+na} = sprintf(' '); na = na+1; str_YZ_{1+na} = sprintf(' '); na = na+1; end;
end;%for nZ=1:n_Z;
%%%%%%%%;
nlp_threshold_ = [3,9,27,81];
Tt_ = T_; for nl=1:numel(Tt_);Tt_(nl) = sum(nlp_threshold_<T_(nl)); end;
%%%%%%%%;
for nX=1:n_X;
n_plot = 64;
str_X = str_X_{nX};
figure(nX); clf;
subplot(1,n_plot,1:n_plot-3);
%c_ = colormap_beach(); 
c_ = 1-colormap('hot');
n_c = size(c_,1); c_(1,:) = [1,1,1]; 
colormap(c_);
clim_ = [0,numel(nlp_threshold_)];
tmp_Tt_ = transpose(squeeze(Tt_(:,AIBS_ij_(2:end),nX)));
tmp_nc_ = max(2,min(n_c,1+floor(n_c*(tmp_Tt_ -  - min(clim_))/diff(clim_))));
tmp_nc_(find(tmp_Tt_<0))=1;
imagesc(tmp_nc_,[1,n_c]); 
set(gca,'XTick',1:n_a,'XTickLabel',str_YZ_); xtickangle(90);
set(gca,'YTick',1:1+n_label_A-1,'YTickLabel',str_ticklabel_AIBS_(AIBS_ij_(2:end)));
set(gca,'TickLength',[0,0]);
set(gca,'FontName','Courier');
%cbh = colorbar;
%set(cbh,'YTick',2:n_c,'YTickLabel',round(linspace(min(clim_),max(clim_),n_c-1)));
%set(cbh,'TickLength',[0]);
title(sprintf('%s',str_X_{nX}));
subplot(1,n_plot,n_plot);
imagesc(transpose(5:-1:1),[1,5]);
set(gca,'YTick',1:5,'YTickLabel',[81;27;9;3;0]);
ylabel('-log(p-value)');
figbig;
fname = sprintf('/data/rangan/dir_bcc/dir_jamison/dir_jpg/test_loader_cluster_collect_12b_%s_PYZ',str_X);
disp(sprintf(' %% writing %s',fname));
print('-djpeg',sprintf('%s.jpg',fname));
print('-depsc',sprintf('%s.eps',fname));
end;%for nX=1:n_X;

%%%%%%%%;
% Now create PZY figure;
%%%%%%%%;
str_ticklabel_ = cell(1+n_label_A,1);
str_ticklabel_{1} = 'all';
for nlabel_A=1:n_label_A;
str_ticklabel_{1+nlabel_A} = sprintf('%d: ''%s''',nlabel_A,u_label_A_{nlabel_A});
end;%for nlabel_A=1:n_label_A;
str_ticklabel_AIBS_ = zeros(1+n_label_A,1);
str_ticklabel_AIBS_(1) = 0;
for nlabel_A=1:n_label_A;
if  strcmp(u_label_A_{nlabel_A},'NA'); 
str_ticklabel_AIBS_(1+nlabel_A) = -1; 
end;%if  strcmp(u_label_A_{nlabel_A},'NA'); 
if ~strcmp(u_label_A_{nlabel_A},'NA'); 
str_ticklabel_AIBS_(1+nlabel_A) = str2num(u_label_A_{nlabel_A}); 
end;%if ~strcmp(u_label_A_{nlabel_A},'NA'); 
end;%for nlabel_A=1:n_label_A;
[~,AIBS_ij_] = sort(str_ticklabel_AIBS_);
pre_Y_ = {'000','127','RRR','012','UE1','UE2','UE3','UE4','UE5','UE6'};
pre_Z_ = {'Loop  ','PCA    ','TSNE50 ','TSNE00 ','UmapIso ','UmapHDB '};
n_Z_index_sum = sum(n_Z_index_);
n_a = n_Y*n_Z_index_sum + 2*(n_Y-1);
T_ = -ones(n_a,1+n_label_A,n_X);
str_ZY_ = cell(n_a,1);
na=0;
for nY=1:n_Y;
for nZ=1:n_Z;
n_Z_index = n_Z_index_(nZ);
for nZ_index=1:n_Z_index;
if (n_Z_index==1); 
str_ZY_{1+na} = sprintf('%s %s',pre_Z_{nZ},pre_Y_{nY});
end;%if (n_Z_index==1); 
if (n_Z_index>1); 
str_ZY_{1+na} = sprintf('%s%d %s',pre_Z_{nZ},nZ_index,pre_Y_{nY});
end;%if (n_Z_index>1); 
for nX=1:n_X;
T_(1+na,1,nX) = nlpv_XYZ_(1,nX,nY,nZ,nZ_index);
for nlabel_A=1:n_label_A;
T_(1+na,1+nlabel_A,nX) = nlpv_XYZ_(1+nlabel_A,nX,nY,nZ,nZ_index);
end;%for nlabel_A=1:n_label_A;
end;%for nX=1:n_X;
na = na+1;
end;%for nZ_index=1:n_Z_index;
end;%for nZ=1:n_Z;
str_ZY_{1+na} = sprintf(' '); na = na+1; str_ZY_{1+na} = sprintf(' '); na = na+1;
end;%for nY=1:n_Y;
%%%%%%%%;
nlp_threshold_ = [3,9,27,81];
Tt_ = T_; for nl=1:numel(Tt_);Tt_(nl) = sum(nlp_threshold_<T_(nl)); end;
%%%%%%%%;
for nX=1:n_X;
n_plot = 64;
str_X = str_X_{nX};
figure(nX); clf;
subplot(1,n_plot,1:n_plot-3);
%c_ = colormap_beach(); 
c_ = 1-colormap('hot');
n_c = size(c_,1); c_(1,:) = [1,1,1]; 
colormap(c_);
clim_ = [0,numel(nlp_threshold_)];
tmp_Tt_ = transpose(squeeze(Tt_(:,AIBS_ij_(2:end),nX)));
tmp_nc_ = max(2,min(n_c,1+floor(n_c*(tmp_Tt_ -  - min(clim_))/diff(clim_))));
tmp_nc_(find(tmp_Tt_<0))=1;
imagesc(tmp_nc_,[1,n_c]); 
set(gca,'XTick',1:n_a,'XTickLabel',str_ZY_); xtickangle(90);
set(gca,'YTick',1:1+n_label_A-1,'YTickLabel',str_ticklabel_AIBS_(AIBS_ij_(2:end)));
set(gca,'TickLength',[0,0]);
set(gca,'FontName','Courier');
%cbh = colorbar;
%set(cbh,'YTick',2:n_c,'YTickLabel',round(linspace(min(clim_),max(clim_),n_c-1)));
%set(cbh,'TickLength',[0]);
title(sprintf('%s',str_X_{nX}));
subplot(1,n_plot,n_plot);
imagesc(transpose(5:-1:1),[1,5]);
set(gca,'YTick',1:5,'YTickLabel',[81;27;9;3;0]);
ylabel('-log(p-value)');
figbig;
fname = sprintf('/data/rangan/dir_bcc/dir_jamison/dir_jpg/test_loader_cluster_collect_12b_%s_PZY',str_X);
disp(sprintf(' %% writing %s',fname));
print('-djpeg',sprintf('%s.jpg',fname));
print('-depsc',sprintf('%s.eps',fname));
end;%for nX=1:n_X;

% display table: ;
%{

  str_mat = '/data/rangan/dir_bcc/dir_jamison/dir_loader_cluster/dir_E_li16bf_cluster/dexcluster_nonbinary_trace_ZRimax_g010_p050_nml3.mat';
  tmp_mat_ = load(str_mat);
  [lP_0,cap_,cup_] = label_to_label_enrichment_lP0(label_A_,tmp_mat_.label_B__{2});
  [n_row,n_col] = size(cap_);
  rownames_ = cell(n_row,1); for nrow=1:n_row; rownames_{nrow} = sprintf('#%.2d:(%.3d)',nrow,sum(cap_(nrow,:))); end;%for nrow=1:n_row;
  colnames_ = cell(n_col,1); for ncol=1:n_col; colnames_{ncol} = sprintf('#%.2d:(%.3d)',ncol,sum(cap_(:,ncol))); end;%for ncol=1:n_col;
  T_ = array2table(cap_,'VariableNames',colnames_,'RowNames',rownames_);
  writetable(T_,'/data/rangan/dir_bcc/dir_jamison/dir_jpg/dexcluster_nonbinary_trace_ZRimax_g010_p050_nml3.xlsx','Sheet',1);
  %}
