%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% Fit linear model to rank data ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%;
% Here we try and estimate the genes E_ or I_ using the covariates C_. ;
% For now we use all of C_ to estimate E_ and I_. ;
% Eventually, we might want to use only the C_ which are not associated with quality. ;
%%%%%%%%;
n_rank = 3+3;
%%%%%%%%;
% Can we estimate the link E_rank_ = C_rank_ * zeta_rank_E_  using a low-rank zeta_rank_E_ ?
%%%%%%%%;
if flag_E;
zeta_rank_E_un_ = zeros(1+n_CCOV,n_rank);
zeta_rank_E_vn_ = zeros(n_E_GENE,n_rank);
tmp_Bn_ = pinv([ones(n_u,1) , C_rank_]);
tmp_Yn_ = E_rank_;
for nrank=1:n_rank;
[tmp_un_,tmp_vn_] = rrr_0([ones(n_u,1) , C_rank_],tmp_Yn_,tmp_Bn_);
zeta_rank_E_un_(:,nrank) = tmp_un_;
zeta_rank_E_vn_(:,nrank) = tmp_vn_;
tmp_Yn_ = tmp_Yn_ - (ones(n_u,1)*zeta_rank_E_un_(1,nrank) + C_rank_*zeta_rank_E_un_(2:end,nrank))*transpose(zeta_rank_E_vn_(:,nrank));
clear tmp_un_ tmp_vn_;
end;%for nrank=1:n_rank;
clear tmp_Yn_ tmp_Bn_;
end;%if flag_E;
%%%%%%%%
% Can we estimate the link I_rank_ = C_rank_ * zeta_rank_I_ using a low-rank zeta_rank_I_ ?
%%%%%%%%
if flag_I;
zeta_rank_I_un_ = zeros(1+n_CCOV,n_rank);
zeta_rank_I_vn_ = zeros(n_I_GENE,n_rank);
tmp_Bn_ = pinv([ones(n_u,1) , C_rank_]);
tmp_Yn_ = I_rank_;
for nrank=1:n_rank;
[tmp_un_,tmp_vn_] = rrr_0([ones(n_u,1) , C_rank_],tmp_Yn_,tmp_Bn_);
zeta_rank_I_un_(:,nrank) = tmp_un_;
zeta_rank_I_vn_(:,nrank) = tmp_vn_;
tmp_Yn_ = tmp_Yn_ - (ones(n_u,1)*zeta_rank_I_un_(1,nrank) + C_rank_*zeta_rank_I_un_(2:end,nrank))*transpose(zeta_rank_I_vn_(:,nrank));
clear tmp_un_ tmp_vn_;
end;%for nrank=1:n_rank;
clear tmp_Yn_ tmp_Bn_;
end;%if flag_I;
%%%%%%%%;
% Appears to be rank 3 or so ;
%%%%%%%%;
flag_disp=1;
if flag_disp;
if flag_E;
subplot(2,2,1);
bar(1:n_rank,sqrt(sum((ones(n_u,1)*zeta_rank_E_un_(1,:) + C_rank_*zeta_rank_E_un_(2:end,:)).^2,1)),'r');
xlabel('pc #'); ylabel('l2-norm');
title('numerical rank of zeta_rank_E_','Interpreter','none');
subplot(2,2,3);
bar(1:n_rank,log10(sqrt(sum((ones(n_u,1)*zeta_rank_E_un_(1,:) + C_rank_*zeta_rank_E_un_(2:end,:)).^2,1))),'r');
xlabel('pc #'); ylabel('log10(l2-norm)');
title('numerical rank of zeta_rank_E_','Interpreter','none');
end;%if flag_E;
if flag_I;
subplot(2,2,2);
bar(1:n_rank,sqrt(sum((ones(n_u,1)*zeta_rank_I_un_(1,:) + C_rank_*zeta_rank_I_un_(2:end,:)).^2,1)),'b');
xlabel('pc #'); ylabel('l2-norm');
title('numerical rank of zeta_rank_I_','Interpreter','none');
subplot(2,2,4);
bar(1:n_rank,log10(sqrt(sum((ones(n_u,1)*zeta_rank_I_un_(1,:) + C_rank_*zeta_rank_I_un_(2:end,:)).^2,1))),'b');
xlabel('pc #'); ylabel('log10(l2-norm)');
title('numerical rank of zeta_rank_I_','Interpreter','none');
end;%if flag_I;
set(gcf,'Position',1+[0,0,512*2,512]);
fname_base = sprintf('%s/dir_jpg/zeta_rank_X_sub_',dir_trunk);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
end;%if flag_disp;
%%%%%%%%;
n_zeta_rank_E = 3;
n_zeta_rank_I = 3;

flag_disp=1;
if flag_disp;
clf;
if flag_E;
subplot(1,2,1); tmp_ = (ones(n_u,1)*zeta_rank_E_un_(1,:) + C_rank_*zeta_rank_E_un_(2:end,:))*transpose(zeta_rank_E_vn_); hist(tmp_(:),32);
tmp_n = length(find(tmp_<1 | tmp_>n_E_GENE));
disp(sprintf(' %% zeta_rank_E_: %d/%d = %0.2f out of bounds',tmp_n,numel(tmp_),tmp_n/numel(tmp_)))
end;%if flag_E;
if flag_I;
subplot(1,2,2); tmp_ = (ones(n_u,1)*zeta_rank_I_un_(1,:) + C_rank_*zeta_rank_I_un_(2:end,:))*transpose(zeta_rank_I_vn_); hist(tmp_(:),32);
tmp_n = length(find(tmp_<1 | tmp_>n_I_GENE));
disp(sprintf(' %% zeta_rank_I_: %d/%d = %0.2f out of bounds',tmp_n,numel(tmp_),tmp_n/numel(tmp_)))
end;%if flag_I;
clear tmp_ tmp_n;
end;%if flag_disp;
%%%%%%%%;
% only 0.00 out of bounds. ;
%%%%%%%%;

flag_plot=1;
if flag_plot;
colormap(colormap_beach());
tmp_lim_ = mean(E_rank_(:)) + std(E_rank_(:))*1.5*[-1,+1];
subplot(2,2,1); imagesc( E_rank_ , tmp_lim_); title('E_rank_','Interpreter','none');
subplot(2,2,2); imagesc( ( ones(n_u,1)*zeta_rank_E_un_(1,:) + C_rank_*zeta_rank_E_un_(2:end,:) ) * transpose(zeta_rank_E_vn_(:,:)) , tmp_lim_); title('C_rank_*zeta_E_','Interpreter','none');
subplot(2,2,3); imagesc( I_rank_ , tmp_lim_); title('I_rank_','Interpreter','none');
subplot(2,2,4); imagesc( ( ones(n_u,1)*zeta_rank_I_un_(1,:) + C_rank_*zeta_rank_I_un_(2:end,:) ) * transpose(zeta_rank_I_vn_(:,:)) , tmp_lim_); title('C_rank_*zeta_I_','Interpreter','none');
figbig;
fname_base = sprintf('%s/dir_jpg/X_vs_C_zeta_rank_sub_',dir_trunk);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
end;%if flag_plot;

%%%%%%%%;
% Here we try and estimate the covariates C_ using the genes E_ or I_. ;
% For now we estimate all of C_. ;
% Eventually, we might want to only estimate the C_ which are not associated with a quality. ;
%%%%%%%%;
n_rank = 6+3;
%%%%%%%%;
% Can we estimate the link E_rank_ * beta_rank_E_ = C_rank_ using a low-rank beta_rank_E_ ?
%%%%%%%%;
if flag_E;
beta_rank_E_un_ = zeros(1+n_E_GENE,n_rank);
beta_rank_E_vn_ = zeros(n_CCOV,n_rank);
tmp_Bn_ = pinv([ones(n_u,1) , E_rank_]);
tmp_Yn_ = C_rank_;
for nrank=1:n_rank;
[tmp_un_,tmp_vn_] = rrr_0([ones(n_u,1) , E_rank_],tmp_Yn_,tmp_Bn_);
beta_rank_E_un_(:,nrank) = tmp_un_;
beta_rank_E_vn_(:,nrank) = tmp_vn_;
tmp_Yn_ = tmp_Yn_ - (ones(n_u,1)*beta_rank_E_un_(1,nrank) + E_rank_*beta_rank_E_un_(2:end,nrank))*transpose(beta_rank_E_vn_(:,nrank));
clear tmp_un_ tmp_vn_;
end;%for nrank=1:n_rank;
clear tmp_Yn_ tmp_Bn_;
end;%if flag_E;
%%%%%%%%
% Can we estimate the link I_rank_ * beta_rank_I_ = C_rank_ using a low-rank beta_rank_I_ ?
%%%%%%%%
if flag_I;
beta_rank_I_un_ = zeros(1+n_I_GENE,n_rank);
beta_rank_I_vn_ = zeros(n_CCOV,n_rank);
tmp_Bn_ = pinv([ones(n_u,1) , I_rank_]);
tmp_Yn_ = C_rank_;
for nrank=1:n_rank;
[tmp_un_,tmp_vn_] = rrr_0([ones(n_u,1) , I_rank_],tmp_Yn_,tmp_Bn_);
beta_rank_I_un_(:,nrank) = tmp_un_;
beta_rank_I_vn_(:,nrank) = tmp_vn_;
tmp_Yn_ = tmp_Yn_ - (ones(n_u,1)*beta_rank_I_un_(1,nrank) + I_rank_*beta_rank_I_un_(2:end,nrank))*transpose(beta_rank_I_vn_(:,nrank));
clear tmp_un_ tmp_vn_;
end;%for nrank=1:n_rank;
clear tmp_Yn_ tmp_Bn_;
end;%if flag_I;
%%%%%%%%;
% Appears to be rank 6 or so ;
%%%%%%%%;
flag_disp=1;
if flag_disp;
if flag_E;
subplot(2,2,1);
bar(1:n_rank,sqrt(sum((ones(n_u,1)*beta_rank_E_un_(1,:) + E_rank_*beta_rank_E_un_(2:end,:)).^2,1)),'r');
xlabel('pc #'); ylabel('l2-norm');
title('numerical rank of beta_rank_E_','Interpreter','none');
subplot(2,2,3);
bar(1:n_rank,log10(sqrt(sum((ones(n_u,1)*beta_rank_E_un_(1,:) + E_rank_*beta_rank_E_un_(2:end,:)).^2,1))),'r');
xlabel('pc #'); ylabel('log10(l2-norm)');
title('numerical rank of beta_rank_E_','Interpreter','none');
end;%if flag_E;
if flag_I;
subplot(2,2,2);
bar(1:n_rank,sqrt(sum((ones(n_u,1)*beta_rank_I_un_(1,:) + I_rank_*beta_rank_I_un_(2:end,:)).^2,1)),'b');
xlabel('pc #'); ylabel('l2-norm');
title('numerical rank of beta_rank_I_','Interpreter','none');
subplot(2,2,4);
bar(1:n_rank,log10(sqrt(sum((ones(n_u,1)*beta_rank_I_un_(1,:) + I_rank_*beta_rank_I_un_(2:end,:)).^2,1))),'b');
xlabel('pc #'); ylabel('log10(l2-norm)');
title('numerical rank of beta_rank_I_','Interpreter','none');
end;%if flag_I;
set(gcf,'Position',1+[0,0,512*2,512]);
fname_base = sprintf('%s/dir_jpg/beta_rank_X_sub_',dir_trunk);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
end;%if flag_disp;
%%%%%%%%;
n_beta_rank_E = 6;
n_beta_rank_I = 6;

flag_disp=0;
if flag_disp;
clf;
subplot(2,2,1); imagesc(C_rank_); title('Cn');
subplot(2,2,2); imagesc((ones(n_u,1)*beta_rank_I_un_(1,:) + I_rank_*beta_rank_I_un_(2:end,:))*transpose(beta_rank_I_vn_)); title('In*beta_rankn');
subplot(2,2,3); imagesc(transpose(I_rank_)*C_rank_); title('It*Cn');
subplot(2,2,4); imagesc(transpose(I_rank_)*((ones(n_u,1)*beta_rank_I_un_(1,:) + I_rank_*beta_rank_I_un_(2:end,:))*transpose(beta_rank_I_vn_))); title('It*In*beta_rankn');
end;%if flag_disp;
%%%%%%%%;
% is a logistic model necessary, or does linear model fit well? 
%%%%%%%%;
flag_disp=1;
if flag_disp;
clf;
if flag_E;
subplot(1,2,1); tmp_ = (ones(n_u,1)*beta_rank_E_un_(1,:) + E_rank_*beta_rank_E_un_(2:end,:))*transpose(beta_rank_E_vn_); hist(tmp_(:),32);
tmp_n = length(find(tmp_(:)<1 | tmp_(:)>n_u));
disp(sprintf(' %% beta_rank_E_: %d/%d = %0.2f out of bounds',tmp_n,length(tmp_(:)),tmp_n/length(tmp_(:))))
end;%if flag_E;
if flag_I;
subplot(1,2,2); tmp_ = (ones(n_u,1)*beta_rank_I_un_(1,:) + I_rank_*beta_rank_I_un_(2:end,:))*transpose(beta_rank_I_vn_); hist(tmp_(:),32);
tmp_n = length(find(tmp_(:)<1 | tmp_(:)>n_u));
disp(sprintf(' %% beta_rank_I_: %d/%d = %0.2f out of bounds',tmp_n,length(tmp_(:)),tmp_n/length(tmp_(:))))
end;%if flag_I;
clear tmp_ tmp_n;
end;%if flag_disp;
%%%%%%%%;
% only 0.03 out of bounds. ;
%%%%%%%%;

flag_plot=1;
if flag_plot;
colormap(colormap_beach());
subplot(1,3,1); imagesc(C_rank_,[1,n_u]); title('C_rank_','Interpreter','none');
subplot(1,3,2); imagesc( ( ones(n_u,1)*beta_rank_E_un_(1,:) + E_rank_*beta_rank_E_un_(2:end,:) ) * transpose(beta_rank_E_vn_(:,:)) , [1,n_u]); title('E_rank_*beta_','Interpreter','none');
subplot(1,3,3); imagesc( ( ones(n_u,1)*beta_rank_I_un_(1,:) + I_rank_*beta_rank_I_un_(2:end,:) ) * transpose(beta_rank_I_vn_(:,:)) , [1,n_u]); title('I_rank_*beta_','Interpreter','none');
figbig;
fname_base = sprintf('%s/dir_jpg/C_vs_X_beta_rank_sub_',dir_trunk);
disp(sprintf(' %% writing %s.jpg',fname_base));
print('-djpeg',sprintf('%s.jpg',fname_base));
print('-depsc',sprintf('%s.eps',fname_base));
end;%if flag_plot;
