% test out a simple message-passing algorithm. ;
clear;
rng(1);
M = 2048; N = M+1; snr = 0.6; n_cluster = 1;
[A_n_,label_A_,n_label_A_,pf_,pi_,snr_,MX_,NX_,mu_] = random_matrix_planted_cluster_0(M,N,snr,n_cluster);
D_n_base_ = A_n_(pi_{1},pi_{2});
D_t_base_ = transpose(D_n_base_);
D_n_ = D_n_base_;
D_t_ = D_t_base_;
n_iteration = 16;
for niteration=1:n_iteration;
%%%%%%%%;
DnDt_ = D_n_*transpose(D_n_); for m=1:M; DnDt_(m,m)=0; end; DnDt_ = DnDt_/std(DnDt_(:));
BnBt_X_ = zeros(M,M); BnBt_X_(1:MX_,1:MX_) = 1;
BnBt_ij_ = find(BnBt_X_(:)); n_BnBt = numel(BnBt_ij_);
DnDt_ij_ = setdiff(1:M*M,BnBt_ij_); n_DnDt = numel(DnDt_ij_);
DtDn_ = D_t_*transpose(D_t_); for n=1:N; DtDn_(n,n)=0; end; DtDn_ = DtDn_/std(DtDn_(:));
BtBn_X_ = zeros(N,N); BtBn_X_(1:NX_,1:NX_) = 1;
BtBn_ij_ = find(BtBn_X_(:)); n_BtBn = numel(BtBn_ij_);
DtDn_ij_ = setdiff(1:N*N,BtBn_ij_); n_DtDn = numel(DtDn_ij_);
sg_DnDt_ = std(DnDt_(:)); ylim_DnDt_ = 0.0 + 7.5*sg_DnDt_*[-1,+1];
sg_DtDn_ = std(DtDn_(:)); ylim_DtDn_ = 0.0 + 7.5*sg_DtDn_*[-1,+1];
%%%%%%%%;
flag_plot=0;
if flag_plot;
subplot(2,2,1); plot(1:n_BnBt,DnDt_(BnBt_ij_),'r.'); ylim(ylim_DnDt_);
subplot(2,2,2); plot(n_BnBt + (1:n_DnDt),DnDt_(DnDt_ij_),'b.'); ylim(ylim_DnDt_);
subplot(2,2,3); plot(1:n_BtBn,DtDn_(BtBn_ij_),'r.'); ylim(ylim_DtDn_);
subplot(2,2,4); plot(n_BtBn + (1:n_DtDn),DtDn_(DtDn_ij_),'b.'); ylim(ylim_DtDn_);
figbig;
end;%if flag_plot;
%%%%%%%%;
flag_plot=1;
if flag_plot;
n_h = 32; 
h_b_DnDt_ = linspace(ylim_DnDt_(1),ylim_DnDt_(2),n_h);
h_BnBt_ = hist(DnDt_(BnBt_ij_),h_b_DnDt_); h_DnDt_ = hist(DnDt_(DnDt_ij_),h_b_DnDt_);
h_b_DtDn_ = linspace(ylim_DtDn_(1),ylim_DtDn_(2),n_h);
h_BtBn_ = hist(DtDn_(BtBn_ij_),h_b_DtDn_); h_DtDn_ = hist(DtDn_(DtDn_ij_),h_b_DtDn_);
subplot(2,1,1); cla; hold on; 
stairs(h_b_DnDt_,h_DnDt_/sum(h_DnDt_),'b-');
stairs(h_b_DnDt_,h_BnBt_/sum(h_BnBt_),'r-');
subplot(2,1,2); cla; hold on; 
stairs(h_b_DtDn_,h_DtDn_/sum(h_DtDn_),'b-');
stairs(h_b_DtDn_,h_BtBn_/sum(h_BtBn_),'r-');
figbig;
drawnow;pause();
end;%if flag_plot;
%%%%%%%%;
D_n_ = exp(DnDt_); D_n_ = D_n_-mean(D_n_(:));
D_t_ = DtDn_.^3; D_t_ = D_t_-mean(D_t_(:));
%%%%%%%%;
end;%for niteration=1:n_iteration;

