function test_loader_helper_tsv_0(AB_,dir_trunk,str_prefix);

%%%%%%%%;
%fname_mat = sprintf('%s/dir_mat/dir_AB/AB_%s_.mat',dir_trunk,str_prefix);
%save(fname_mat,'AB_');
%%%%%%%%;
AB__AB_C_absZ_avg_ = AB_.AB_C_absZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_C_absZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_C_absZ_avg_','-ascii','-tabs');
AB__AB_Z_absZ_avg_ = AB_.AB_Z_absZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_Z_absZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_Z_absZ_avg_','-ascii','-tabs');
AB__AB_H_absZ_avg_ = AB_.AB_H_absZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_H_absZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_H_absZ_avg_','-ascii','-tabs');
AB__AB_K_absZ_avg_ = AB_.AB_K_absZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_K_absZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_K_absZ_avg_','-ascii','-tabs');
%%%%%%%%;
AB__AB_C_rawZ_avg_ = AB_.AB_C_rawZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_C_rawZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_C_rawZ_avg_','-ascii','-tabs');
AB__AB_Z_rawZ_avg_ = AB_.AB_Z_rawZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_Z_rawZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_Z_rawZ_avg_','-ascii','-tabs');
AB__AB_H_rawZ_avg_ = AB_.AB_H_rawZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_H_rawZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_H_rawZ_avg_','-ascii','-tabs');
AB__AB_K_rawZ_avg_ = AB_.AB_K_rawZ_avg__;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_K_rawZ_avg_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_K_rawZ_avg_','-ascii','-tabs');
%%%%%%%%;
AB__AB_C_absZ_ = AB_.AB_C_absZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_C_absZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_C_absZ_','-ascii','-tabs');
AB__AB_K_absZ_ = AB_.AB_K_absZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_K_absZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_K_absZ_','-ascii','-tabs');
AB__AB_Z_absZ_ = AB_.AB_Z_absZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_Z_absZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_Z_absZ_','-ascii','-tabs');
AB__AB_H_absZ_ = AB_.AB_H_absZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_H_absZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_H_absZ_','-ascii','-tabs');
%%%%%%%%;
AB__AB_C_rawZ_ = AB_.AB_C_rawZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_C_rawZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_C_rawZ_','-ascii','-tabs');
AB__AB_K_rawZ_ = AB_.AB_K_rawZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_K_rawZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_K_rawZ_','-ascii','-tabs');
AB__AB_Z_rawZ_ = AB_.AB_Z_rawZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_Z_rawZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_Z_rawZ_','-ascii','-tabs');
AB__AB_H_rawZ_ = AB_.AB_H_rawZ_;
fname_tsv = sprintf('%s/dir_mat/dir_AB/AB_%s_H_rawZ_.tsv',dir_trunk,str_prefix);
save(fname_tsv,'AB__AB_H_rawZ_','-ascii','-tabs');

