% Test cluster-supervised pca. ;
% Clusters are slices of a gaussian (i.e., very close to one another). ;
setup;
M = 1024; N = 2*M;
D_ = randn(M,N);
v1_ = randn(N,1); v1_ = v1_/fnorm(v1_);
v2_ = randn(N,1); v2_ = v2_ - v1_*dot(v2_,v1_); v2_ = v2_/fnorm(v2_);
v3_ = randn(N,1); v3_ = v3_ - v1_*dot(v3_,v1_); v3_ = v3_ - v2_*dot(v3_,v2_); v3_ = v3_/fnorm(v3_);
u1_ = D_*v1_; u2_ = D_*v2_; u3_ = D_*v3_; w_ = atan2(u2_,u1_);
Sample_Label_ = floor(5* ((w_+pi)/(2*pi)).^1 );
u_Sample_Label_ = unique(Sample_Label_); n_Sample_Label = length(u_Sample_Label_);
n_Sample_Label_ = zeros(n_Sample_Label,1);
for nSample_Label=1:n_Sample_Label;
n_Sample_Label_(nSample_Label) = length(find(Sample_Label_==u_Sample_Label_(nSample_Label)));
end;%for nSample_Label=1:n_Sample_Label;
[tmp_U_,tmp_S_,tmp_V_] = svds(D_,3);
Delta_ = zeros(M,M);
Alpha_ = zeros(M,M);
for nm1=1:M; for nm2=1:M;
Delta_(nm1,nm2) = (Sample_Label_(nm1)==Sample_Label_(nm2));
end;end;%for nm1=1:M; for nm2=1:M;
%Alpha_ = 1-1*Delta_;
for nm1=1:M; for nm2=1:M;
tmp_m1 = find(u_Sample_Label_==Sample_Label_(nm1)); assert(length(tmp_m1)==1);
tmp_m2 = find(u_Sample_Label_==Sample_Label_(nm2)); assert(length(tmp_m2)==1);
Alpha_(nm1,nm2) = (1-2*(Sample_Label_(nm1)==Sample_Label_(nm2))) / (n_Sample_Label_(tmp_m1)*n_Sample_Label_(tmp_m2)) ;
end;end;%for nm1=1:M; for nm2=1:M;
A2_ = Alpha_ - diag(sum(Alpha_,2));
A1_ = real(sqrtm(-A2_));
[tmp_UAD_,tmp_SAD_,tmp_VAD_] = svds(A1_*D_,M);
%%%%%%%%;
e_n_ = ones(M,1); e_t_ = ones(1,M);
S1_ori = e_t_*transpose(Alpha_)*(D_*v1_).^2 + e_t_*(Alpha_)*(D_*v1_).^2 - 2*(transpose(v1_)*transpose(D_)*Alpha_*D_*v1_);
S2_ori = e_t_*transpose(Alpha_)*(D_*v2_).^2 + e_t_*(Alpha_)*(D_*v2_).^2 - 2*(transpose(v2_)*transpose(D_)*Alpha_*D_*v2_);
disp(sprintf(' %% S_ori: [%0.6f , %0.6f]',S1_ori,S2_ori));
S1_SVD = e_t_*transpose(Alpha_)*(D_*tmp_V_(:,1)).^2 + e_t_*(Alpha_)*(D_*tmp_V_(:,1)).^2 - 2*(transpose(tmp_V_(:,1))*transpose(D_)*Alpha_*D_*tmp_V_(:,1));
S2_SVD = e_t_*transpose(Alpha_)*(D_*tmp_V_(:,2)).^2 + e_t_*(Alpha_)*(D_*tmp_V_(:,2)).^2 - 2*(transpose(tmp_V_(:,2))*transpose(D_)*Alpha_*D_*tmp_V_(:,2));
disp(sprintf(' %% S_SVD: [%0.6f , %0.6f]',S1_SVD,S2_SVD));
S1_UAD = e_t_*transpose(Alpha_)*(D_*tmp_VAD_(:,1)).^2 + e_t_*(Alpha_)*(D_*tmp_VAD_(:,1)).^2 - 2*(transpose(tmp_VAD_(:,1))*transpose(D_)*Alpha_*D_*tmp_VAD_(:,1));
S2_UAD = e_t_*transpose(Alpha_)*(D_*tmp_VAD_(:,2)).^2 + e_t_*(Alpha_)*(D_*tmp_VAD_(:,2)).^2 - 2*(transpose(tmp_VAD_(:,2))*transpose(D_)*Alpha_*D_*tmp_VAD_(:,2));
disp(sprintf(' %% S_UAD: [%0.6f , %0.6f]',S1_UAD,S2_UAD));
%%%%%%%%;
subplot(2,2,1)
scatter3(u1_,u2_,u3_,15,Sample_Label_,'filled'); colormap(colormap_beach()); axis vis3d;
axisnotick;
title(sprintf('ori S[%0.6f %0.6f]',S1_ori,S2_ori));
subplot(2,2,2);
scatter3(tmp_U_(:,1),tmp_U_(:,2),tmp_U_(:,3),15,Sample_Label_,'filled'); colormap(colormap_beach()); axis vis3d;
axisnotick;
title(sprintf('SVD S[%0.6f %0.6f]',S1_SVD,S2_SVD));
subplot(2,2,3);
scatter3(tmp_UAD_(:,1),tmp_UAD_(:,2),tmp_UAD_(:,3),15,Sample_Label_,'filled'); colormap(colormap_beach()); axis vis3d;
title(sprintf('UAD S[%0.6f %0.6f]',S1_UAD,S2_UAD));
axisnotick;
subplot(2,2,4);
[~,tmp_ij_] = sort(Sample_Label_);
imagesc(Alpha_(tmp_ij_,tmp_ij_)); axisnotick;
title('Alpha');
figbig;
