function [AB_] = test_loader_helper_sub_0(AB_,C_Label_);

%%%%%%%%;
% Now run through the cluster pairs, ;
% recording the labels for each pair. ;
%%%%%%%%
n_CLabel = AB_.n_CLabel;
u_CLabel_ = unique(C_Label_); assert(n_CLabel==length(u_CLabel_));
n_s = n_CLabel*n_CLabel;
AB_.CLabel_pair_ = cell(n_s,1);
ns=0;
for nA=1:n_CLabel;
for nB=1:n_CLabel;
AB_.CLabel_pair_{1+ns} = sprintf('%s,%s',u_CLabel_{nA},u_CLabel_{nB});
ns = ns+1;
end;%for nB=1:n_CLabel;
end;%for nA=1:n_CLabel;

%%%%%%%%;
% Now run through the cluster pairs, ;
% recording the absolute-value of the z-score for each covariate. ;
%%%%%%%%
n_CCOV = AB_.n_CCOV;
n_CLabel = AB_.n_CLabel;
n_s = n_CLabel*n_CLabel;
%flag_disp=1;
%if flag_disp;
%if flag_Z;
AB_.AB_C_absZ_ = zeros(n_s,n_CCOV);
AB_.AB_K_absZ_ = zeros(n_s,n_CCOV);
AB_.AB_C_rawZ_ = zeros(n_s,n_CCOV);
AB_.AB_K_rawZ_ = zeros(n_s,n_CCOV);
ns=0;
for nA=1:n_CLabel;
for nB=1:n_CLabel;
%%%%%%%%;
tmp_ij1_ = squeeze(AB_.AB_C_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze( abs(AB_.AB_C_sort_list_ori__(nA,nB,:) - AB_.AB_C_sort_list_avg__(nA,nB,:))./AB_.AB_C_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_C_absZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
tmp_ij1_ = squeeze(AB_.AB_K_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze( abs(AB_.AB_K_sort_list_ori__(nA,nB,:) - AB_.AB_K_sort_list_avg__(nA,nB,:))./AB_.AB_K_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_K_absZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
%%%%%%%%;
tmp_ij1_ = squeeze(AB_.AB_C_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze(    (AB_.AB_C_sort_list_ori__(nA,nB,:) - AB_.AB_C_sort_list_avg__(nA,nB,:))./AB_.AB_C_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_C_rawZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
tmp_ij1_ = squeeze(AB_.AB_K_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze(    (AB_.AB_K_sort_list_ori__(nA,nB,:) - AB_.AB_K_sort_list_avg__(nA,nB,:))./AB_.AB_K_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_K_rawZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
%%%%%%%%;
ns = ns+1;
end;%for nB=1:n_CLabel;
end;%for nA=1:n_CLabel;

%%%%%%%%;
% Now run through the cluster pairs, ;
% recording the absolute-value of the z-score for each gene. ;
%%%%%%%%
n_Z_GENE = AB_.n_Z_GENE;
n_CLabel = AB_.n_CLabel;
n_s = n_CLabel*n_CLabel;
%flag_disp=1;
%if flag_disp;
%if flag_Z;
AB_.AB_Z_absZ_ = zeros(n_s,n_Z_GENE);
AB_.AB_H_absZ_ = zeros(n_s,n_Z_GENE);
AB_.AB_Z_rawZ_ = zeros(n_s,n_Z_GENE);
AB_.AB_H_rawZ_ = zeros(n_s,n_Z_GENE);
ns=0;
for nA=1:n_CLabel;
for nB=1:n_CLabel;
%%%%%%%%;
tmp_ij1_ = squeeze(AB_.AB_Z_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze( abs(AB_.AB_Z_sort_list_ori__(nA,nB,:) - AB_.AB_Z_sort_list_avg__(nA,nB,:))./AB_.AB_Z_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_Z_absZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
tmp_ij1_ = squeeze(AB_.AB_H_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze( abs(AB_.AB_H_sort_list_ori__(nA,nB,:) - AB_.AB_H_sort_list_avg__(nA,nB,:))./AB_.AB_H_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_H_absZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
%%%%%%%%;
tmp_ij1_ = squeeze(AB_.AB_Z_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze(    (AB_.AB_Z_sort_list_ori__(nA,nB,:) - AB_.AB_Z_sort_list_avg__(nA,nB,:))./AB_.AB_Z_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_Z_rawZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
tmp_ij1_ = squeeze(AB_.AB_H_sort_list_ij__(nA,nB,:)); 
tmp_z_ = squeeze(    (AB_.AB_H_sort_list_ori__(nA,nB,:) - AB_.AB_H_sort_list_avg__(nA,nB,:))./AB_.AB_H_sort_list_std__(nA,nB,:) / sqrt(2) ); 
tmp_ij2_ = find(isfinite(tmp_z_));
AB_.AB_H_rawZ_(1+ns,tmp_ij1_(tmp_ij2_)) = tmp_z_(tmp_ij2_);
%%%%%%%%;
ns = ns+1;
end;%for nB=1:n_CLabel;
end;%for nA=1:n_CLabel;
