% Test cluster-supervised pca. ;
% Clusters are each distinct gaussians with different means and (slightly) different standard-deviations. ;
% We also modulate the ratio 'alpha' used to define Alpha_. ;

clear; setup; rng(1);
%%%%%%%%;
M = 1024; N = 2e3;
n_cluster = 5; gamma_cluster = 2;
mu = 0.5; %<-- signal. ;
%sg_ = ones(n_cluster,1);
sg_ = 0.5 + rand(n_cluster,1); %<-- clusters have randomized standard-deviations. ;
%%%%%%%%;
[tmp_VORI_,~] = qr(randn(N,n_cluster),0);
w_ = linspace(0,1,M+1); w_ = w_(1:end-1);
Sample_Label_ = floor(n_cluster* w_.^gamma_cluster ); %<-- gamma_cluster sets the inequality in cluster size. ;
u_Sample_Label_ = unique(Sample_Label_); n_Sample_Label = length(u_Sample_Label_);
n_Sample_Label_ = zeros(n_Sample_Label,1);
Sample_Label_ij_ = cell(n_Sample_Label);
for nSample_Label=1:n_Sample_Label;
Sample_Label_ij_{nSample_Label} = find(Sample_Label_==u_Sample_Label_(nSample_Label));
n_Sample_Label_(nSample_Label) = length(Sample_Label_ij_{nSample_Label});
end;%for nSample_Label=1:n_Sample_Label;
D_ = zeros(M,N);
for ncluster=1:n_cluster;
D_(Sample_Label_ij_{ncluster},:) = randn(n_Sample_Label_(ncluster),N)*sg_(ncluster) + mu*ones(n_Sample_Label_(ncluster),1)*transpose(tmp_VORI_(:,ncluster));
end;%for ncluster=1:n_cluster;
tmp_UORI_ = D_*tmp_VORI_;
%%%%%%%%;

n_alpha = 15;
alpha_ = linspace(1,n_alpha,n_alpha);
for nalpha = 1:n_alpha;
alpha = alpha_(nalpha);
disp(sprintf(' %% nalpha %d/%d alpha %0.6f',nalpha,n_alpha,alpha));
%%%%%%%%;
Alpha_ = zeros(M,M);
for ncluster1=1:n_cluster; for ncluster2=1:n_cluster;
tmp = (1/alpha - (ncluster1==ncluster2)) / (n_Sample_Label_(ncluster1) * n_Sample_Label_(ncluster2)) ;
Alpha_(Sample_Label_ij_{ncluster1},Sample_Label_ij_{ncluster2}) = tmp;
end;end;%for ncluster1=1:n_cluster; for ncluster2=1:n_cluster;
A2_ = Alpha_ - diag(sum(Alpha_,2)); E_A2_ = eig(A2_);
n_rank_A2 = length(find(abs(E_A2_/E_A2_(1))>1e-6));
disp(sprintf(' %% E_A2_ [%+0.6f,%+0.6f]; pos %d neg %d rank %d',min(E_A2_),max(E_A2_),length(find(E_A2_>0)),length(find(E_A2_<0)),n_rank_A2));
A2fun = @(x,str) transpose(D_)*(A2_*(D_*x));
n_rank = min(M,n_rank_A2);
[tmp_VAD_,tmp_SAD2_] = eigs(A2fun,N,n_rank,'largestabs','IsFunctionSymmetric',1,'Display',0);
tmp_SAD2_ = diag(tmp_SAD2_);
tmp_SAD_ = sqrt(abs(tmp_SAD2_)); %<-- pretend we took eigenvalues of positive definite matrix [transpose(D_)*A2_*D_*transpose(D_)*A2_*D_]. ;
tmp_DVS_ = D_*tmp_VAD_(:,1:n_rank)*diag(1./tmp_SAD_(1:n_rank));
%%%%%%%%;
e_n_ = ones(M,1); e_t_ = ones(1,M);
S1_ORI = e_t_*transpose(Alpha_)*(D_*tmp_VORI_(:,1)).^2 + e_t_*(Alpha_)*(D_*tmp_VORI_(:,1)).^2 - 2*(transpose(tmp_VORI_(:,1))*transpose(D_)*Alpha_*D_*tmp_VORI_(:,1));
S2_ORI = e_t_*transpose(Alpha_)*(D_*tmp_VORI_(:,2)).^2 + e_t_*(Alpha_)*(D_*tmp_VORI_(:,2)).^2 - 2*(transpose(tmp_VORI_(:,2))*transpose(D_)*Alpha_*D_*tmp_VORI_(:,2));
%disp(sprintf(' %% S_ORI: [%0.6f , %0.6f]',S1_ORI,S2_ORI));
S1_UAD = e_t_*transpose(Alpha_)*(D_*tmp_VAD_(:,1)).^2 + e_t_*(Alpha_)*(D_*tmp_VAD_(:,1)).^2 - 2*(transpose(tmp_VAD_(:,1))*transpose(D_)*Alpha_*D_*tmp_VAD_(:,1));
S2_UAD = e_t_*transpose(Alpha_)*(D_*tmp_VAD_(:,2)).^2 + e_t_*(Alpha_)*(D_*tmp_VAD_(:,2)).^2 - 2*(transpose(tmp_VAD_(:,2))*transpose(D_)*Alpha_*D_*tmp_VAD_(:,2));
%disp(sprintf(' %% S_UAD: [%0.6f , %0.6f]',S1_UAD,S2_UAD));
%%%%%%%%;
flag_plot=1;
if flag_plot;
subplot(3,5,nalpha)
scatter(tmp_DVS_(:,1),tmp_DVS_(:,2),15,Sample_Label_,'filled'); colormap(colormap_beach());
axisnotick;
title(sprintf('alpha %0.2f',alpha));
drawnow();
end;%if flag_plot;
%%%%%%%%;
end;%for nalpha = 1:n_alpha;
figbig;

flag_plot=0;
if flag_plot;
subplot(2,2,1)
%scatter3(tmp_UORI_(:,1),tmp_UORI_(:,2),tmp_UORI_(:,3),15,Sample_Label_,'filled'); colormap(colormap_beach()); axis vis3d;
scatter(tmp_UORI_(:,1),tmp_UORI_(:,2),15,Sample_Label_,'filled'); colormap(colormap_beach());
axisnotick;
title(sprintf('ori S[%0.6f %0.6f]',S1_ORI,S2_ORI));
subplot(2,2,2);
%scatter3(tmp_UAD_(:,1),tmp_UAD_(:,2),tmp_UAD_(:,3),15,Sample_Label_,'filled'); colormap(colormap_beach()); axis vis3d;
scatter(tmp_UAD_(:,1),tmp_UAD_(:,2),15,Sample_Label_,'filled'); colormap(colormap_beach());;
axisnotick;
title(sprintf('UAD S[%0.6f %0.6f]',S1_UAD,S2_UAD));
subplot(2,2,3);
%scatter3(tmp_DVS_(:,1),tmp_DVS_(:,2),tmp_DVS_(:,3),15,Sample_Label_,'filled'); colormap(colormap_beach()); axis vis3d;
scatter(tmp_DVS_(:,1),tmp_DVS_(:,2),15,Sample_Label_,'filled'); colormap(colormap_beach());
axisnotick;
title(sprintf('DVS'));
subplot(2,2,4);
[~,tmp_ij_] = sort(Sample_Label_);
imagesc(Alpha_(tmp_ij_,tmp_ij_)); axisnotick;
title('Alpha');
title(sprintf('Alpha'));
figbig;
end;%if flag_plot;


