function [kta_opt_] = tw_chiani_fit(A_);
% fits gamma distribution to the data in A_. ;
verbose=1;
kta_wis_ = [ 46.44604884387787 ; 0.18605402228279347 ; 9.848007781128567 ]; %<-- k, theta, alpha for wishart matrices with beta==1. ;
A_ = A_(:);
n_u = numel(A_);
tw_nll = @(kta_) sum(tw_chiani_nll(A_,kta_(1+0),kta_(1+1),kta_(1+2)));
kta_opt_ = fminsearch(tw_nll,kta_wis_,optimset('MaxIter',1e4,'MaxFunEvals',1e4));
if (verbose);
figure(1);clf;
n_h = 32;
h_x_lim_ = mean(A_) + std(A_,1)*3.5*[-1,+1];
h_x_ = linspace(min(h_x_lim_),max(h_x_lim_),n_h);
h_A_ = hist(A_,h_x_);
h_A_ = h_A_/sum(h_A_)/mean(diff(h_x_));
x_ = linspace(min(h_x_lim_),max(h_x_lim_),1024);
rho_ = tw_chiani_pdf(x_,1,kta_opt_);
hold on;
stairs(h_x_,h_A_,'k-','LineWidth',2);
plot(x_,rho_,'r-','LineWidth',2);
hold off;
xlabel('x');
ylabel('dist');
title('tw_chiani_fit','Interpreter','none');
end;%if (verbose);
