% scp -p rangan@access1.cims.nyu.edu:/data/rangan/dir_bcc/dir_PGC_20180304/dir_m/xxxcluster_PGC_uADZSZDA_ver12_dr.m /scratch/avr209/dir_PGC_20180304/dir_m/ ;

%{
%%%%%%%%%%%%%%%%;
% Single run. ;
%%%%%%%%%%%%%%%%;

  clear;clc;flag_platform = 2; 
  if flag_platform==1; string_platform = '/home/arangan'; end; 
  if flag_platform==2; string_platform = '/data/rangan/dir_bcc'; end; 
  if flag_platform==3; string_platform = '/scratch/avr209'; end; 
  dir_trunk = sprintf('%s/dir_PGC_20180304',string_platform); 
  dir_code = sprintf('%s/dir_lakcluster_c_dev',string_platform);
  flag_rerun = 0; 
  B_MLT=34;
  n_mds=20; 
  pbs_walltime = 2.50*strcmp(string_platform,'/home/arangan'); 
  slurm_walltime = 2.50*strcmp(string_platform,'/scratch/avr209'); 
  slurm_nnodes = 1; slurm_tpn = 15; slurm_memdecl = 64 ; % Note, if 64+GB requested we should run on snappy. ;
  row_factor=1.0;col_factor=1.0; 
  flag_verbose=0;
  flag_dex_vs_lak = {'lak'}; 
  if (strcmp(flag_dex_vs_lak{1},'dex')); gamma=0.004; end;
  if (strcmp(flag_dex_vs_lak{1},'lak')); gamma=0.001; end;
  for flag_reverse=0;%flag_reverse=[0,1]; 
  for cl_num=4;%for cl_num=1:4; 
  [study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num); Icat_full = n_study; Ireq_half = floor(Icat_full/2); 
  string_prefix = sprintf('PGC_cl%d_maf01',cl_num); 
  for n_maf = 4;%for n_maf = [5,4]; 
  if n_maf==1; maf_lo_threshold = 0.01; maf_hi_threshold = 0.50; end; % all (since we thresholded maf at 0.01 to start with) ;
  if n_maf==2; maf_lo_threshold = 0.01; maf_hi_threshold = 0.05; end; % extreme snps (differential expression only, no loop-counting later on) ;
  if n_maf==3; maf_lo_threshold = 0.01; maf_hi_threshold = 0.10; end; % extreme snps (differential expression only, no loop-counting later on) ;
  if n_maf==4; maf_lo_threshold = 0.10; maf_hi_threshold = 0.50; end; % more balanced snps (differential expression to start, as well as loop-counting later on) ;
  if n_maf==5; maf_lo_threshold = 0.25; maf_hi_threshold = 0.50; end; % more balanced snps (differential expression to start, as well as loop-counting later on) ;
  for n_cov=[2];%for n_cov=[0,1,2]; 
  if n_cov==0; Ireq=0; Icat=1; mds_used_=[]; mds_repl=0; end; % no mds-components. ;
  if n_cov==1; Ireq=0; Icat=1; mds_used_=[1:2]; mds_repl=1; end; % only correct for mds-components [1:2], but replicated only once, so that each 'sector' is 90 degrees ;
  if n_cov==2; Ireq=0; Icat=1; mds_used_=[1:2]; mds_repl=2; end; % only correct for mds-components [1:2], but replicated twice, so that each 'sector' is 45 degrees ;
  if n_cov==3; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[]; mds_repl=0; end; % correct for study, requiring at least Ireq_half, but not for mds-components. ;
  if n_cov==4; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[1:2]; mds_repl=1; end; % correct for study, requiring at least Ireq_half, as well as correct for mds-components [1:2], but replicated only once, so that each 'sector' is 90 degrees ;
  if n_cov==5; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[1:2]; mds_repl=2; end; % correct for study, requiring at least Ireq_half, as well as correct for mds-components [1:2], replicated twice, so that each 'sector' is 45 degrees ;
  nshuffle=0; n_scramble=0;
  %xxxcluster_PGC_uADZSZDA_ver12(dir_code,dir_trunk,string_prefix,maf_lo_threshold,maf_hi_threshold,flag_dex_vs_lak{1},flag_reverse,Icat,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,{},[],nshuffle,flag_rerun,pbs_walltime,slurm_walltime,slurm_nnodes,slurm_tpn,slurm_memdecl,row_factor,col_factor,flag_verbose);
  if (cl_num==4 && flag_reverse==0);
  nshuffle=0; n_scramble=1;
  scramble_out_xdrop_ = {'/data/rangan/dir_bcc/dir_PGC_20180304/dir_PGC_cl4_maf01_analyze/dir_PGC_cl4_maf01_dex_p25_D_m2r2_g004/PGC_cl4_maf01_dex_p25_D_m2r2_g004_out_xdrop_ni275.txt'};
  scramble_rseed_ = [1];
  xxxcluster_PGC_uADZSZDA_ver12(dir_code,dir_trunk,string_prefix,maf_lo_threshold,maf_hi_threshold,flag_dex_vs_lak{1},flag_reverse,Icat,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,scramble_out_xdrop_,scramble_rseed_,nshuffle,flag_rerun,pbs_walltime,slurm_walltime,slurm_nnodes,slurm_tpn,slurm_memdecl,row_factor,col_factor,flag_verbose);
  end;%if (cl_num==4 && flag_reverse==0);
  end;%for n_cov=[0,1,2]; 
  end;%for n_maf = [5,4];
  end;%for cl_num = [1:4]; 
  end;%for flag_reverse=[0,1]; 

  %}


%%%%%%%%%%%%%%%%;
% Multiple runs. ;
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% declare trunk ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
flag_platform = 2;
if flag_platform==1; string_platform = '/home/arangan'; end;
if flag_platform==2; string_platform = '/data/rangan/dir_bcc'; end;
if flag_platform==3; string_platform = '/scratch/avr209'; end;
dir_trunk = sprintf('%s/dir_PGC_20180304',string_platform);
dir_code = sprintf('%s/dir_lakcluster_c_dev',string_platform);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% run ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
flag_rerun = 0;
B_MLT=34;n_mds=20;
pbs_walltime = 13.50*strcmp(string_platform,'/home/arangan');
slurm_walltime = 13.50*strcmp(string_platform,'/scratch/avr209');
slurm_nnodes = 1; slurm_tpn = 15; slurm_memdecl = 64; % Note, if 64+GB requested we should run on snappy. ;
row_factor=1.0;col_factor=1.0; 
flag_verbose=0;
for flag_dex_vs_lak = {'lak'}; %for flag_dex_vs_lak = {'dex','lak'};
if (strcmp(flag_dex_vs_lak{1},'dex')); gamma=0.004; end;
if (strcmp(flag_dex_vs_lak{1},'lak')); gamma=0.001; end;
for flag_reverse = 0;%for flag_reverse=[0,1]; 
for cl_num = 4; %for cl_num=1:4;
[study_trunk_,study_name_,n_study] = lisa_define_study_ver0(cl_num); Icat_full = n_study; Ireq_half = floor(Icat_full/2);
string_prefix = sprintf('PGC_cl%d_maf01',cl_num);
for n_maf = 1;%for n_maf=[1:5]; 
if n_maf==1; maf_lo_threshold = 0.01; maf_hi_threshold = 0.50; end; % all (since we thresholded maf at 0.01 to start with) ;
if n_maf==2; maf_lo_threshold = 0.01; maf_hi_threshold = 0.05; end; % extreme snps (differential expression only, no loop-counting later on) ;
if n_maf==3; maf_lo_threshold = 0.01; maf_hi_threshold = 0.10; end; % extreme snps (differential expression only, no loop-counting later on) ;
if n_maf==4; maf_lo_threshold = 0.10; maf_hi_threshold = 0.50; end; % more balanced snps (differential expression to start, as well as loop-counting later on) ;
if n_maf==5; maf_lo_threshold = 0.25; maf_hi_threshold = 0.50; end; % more balanced snps (differential expression to start, as well as loop-counting later on) ;
for n_cov=2;%for n_cov=[0,1,2];
if n_cov==0; Ireq=0; Icat=1; mds_used_=[]; mds_repl=0; end; % do not correct for mds-components. ;
if n_cov==1; Ireq=0; Icat=1; mds_used_=[1:2]; mds_repl=1; end; % only correct for mds-components [1:2], but replicated only once, so that each 'sector' is 90 degrees ;
if n_cov==2; Ireq=0; Icat=1; mds_used_=[1:2]; mds_repl=2; end; % only correct for mds-components [1:2], but replicated twice, so that each 'sector' is 45 degrees ;
if n_cov==3; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[]; mds_repl=0; end; % correct for study, requiring at least Ireq_half, but not for mds-components. ;
if n_cov==4; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[1:2]; mds_repl=1; end; % correct for study, requiring at least Ireq_half, as well as correct for mds-components [1:2], but replicated only once, so that each 'sector' is 90 degrees ;
if n_cov==5; Ireq=Ireq_half; Icat=Icat_full; mds_used_=[1:2]; mds_repl=2; end; % correct for study, requiring at least Ireq_half, as well as correct for mds-components [1:2], replicated twice, so that each 'sector' is 45 degrees ;
if (flag_platform==1 | flag_platform==2 | flag_platform==3);
nshuffle=0; n_scramble=0;
xxxcluster_PGC_uADZSZDA_ver12(dir_code,dir_trunk,string_prefix,maf_lo_threshold,maf_hi_threshold,flag_dex_vs_lak{1},flag_reverse,Icat,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,{},[],nshuffle,flag_rerun,pbs_walltime,slurm_walltime,slurm_nnodes,slurm_tpn,slurm_memdecl,row_factor,col_factor,flag_verbose);
if (cl_num==4 && flag_reverse==0);
nshuffle=0; n_scramble=1;
scramble_out_xdrop_ = {'/data/rangan/dir_bcc/dir_PGC_20180304/dir_PGC_cl4_maf01_analyze/dir_PGC_cl4_maf01_dex_p25_D_m2r2_g004/PGC_cl4_maf01_dex_p25_D_m2r2_g004_out_xdrop_ni275.txt'};
scramble_rseed_ = [1];
xxxcluster_PGC_uADZSZDA_ver12(dir_code,dir_trunk,string_prefix,maf_lo_threshold,maf_hi_threshold,flag_dex_vs_lak{1},flag_reverse,Icat,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,scramble_out_xdrop_,scramble_rseed_,nshuffle,flag_rerun,pbs_walltime,slurm_walltime,slurm_nnodes,slurm_tpn,slurm_memdecl,row_factor,col_factor,flag_verbose);
end;%if (cl_num==4 && flag_reverse==0);
end;%if (flag_platform==1);
if (flag_platform==3);
for nshuffle=1:64; 
n_scramble=0;
xxxcluster_PGC_uADZSZDA_ver12(dir_code,dir_trunk,string_prefix,maf_lo_threshold,maf_hi_threshold,flag_dex_vs_lak{1},flag_reverse,Icat,n_mds,mds_used_,mds_repl,gamma,B_MLT,Ireq,n_scramble,{},[],nshuffle,flag_rerun,pbs_walltime,slurm_walltime,slurm_nnodes,slurm_tpn,slurm_memdecl,row_factor,col_factor,flag_verbose); 
end;%for nshuffle=1:64; 
end;%if (flag_platform==3);
end;%for n_cov=[1];
end;%for n_maf=[1:5];
end;%for cl_num=1:4;
end;%for flag_reverse=[0,1]; 
end;%for flag_dex_vs_lak = {'dex','lak'};
