function ...
[ ...
 rindex_ ...
,cindex_ ...
,out_xdrop_ ...
] = ...
load_out_xdrop_ver0( ...
fname ...
);

if (~exist(fname,'file')); disp(sprintf(' %% Warning, %s not found in load_out_xdrop_ver0',fname)); end;

out_xdrop_ = textread(fname);
rindex_ = out_xdrop_(find(out_xdrop_(:,1)>=0),1);
cindex_ = out_xdrop_(find(out_xdrop_(:,2)>=0),2);





 
