function ...
[ ...
 A_p_c_ ...
,A_p_ ...
,AZ_rsum_ ...
] = ...
load_A_p_c_from_dir_0( ...
 dir_out_s0000 ...
,poplength ...
);

na=0;
if (nargin<1+na); dir_out_s0000=pwd; end; na=na+1;
if (nargin<1+na); poplength=1920; end; na=na+1;

fname_A_p = sprintf('%s/A_p.mda',dir_out_s0000);
fcheck(fname_A_p);
A_p_ = mda_read_r8(fname_A_p);
fname_AZ_rsum = sprintf('%s/AZ_rsum.mda',dir_out_s0000);
fcheck(fname_AZ_rsum);
AZ_rsum_ = mda_read_r8(fname_AZ_rsum);
A_p_c_ = reshape(transpose(repmat(A_p_(:),[1,poplength])),[numel(A_p_)*poplength,1]);
A_p_c_ = A_p_c_(1:numel(AZ_rsum_));



