function ...
[ ...
 niter_ ...
,r_rem_ ...
,c_rem_ ...
,QR_ ...
,QC_ ...
,I_rem_ ...
,trace_ ...
] = ...
load_trace_ver0( ...
fname ...
);

if (~exist(fname,'file')); disp(sprintf(' %% Warning, %s not found in load_trace_ver0',fname)); end;

trace_ = textread(fname);
[n_iteration,trace_ncols] = size(trace_);
if (n_iteration==1 | trace_ncols~=6); disp(sprintf(' %% Warning, n_iteration %d trace_ncols %d in trace',n_iteration,trace_ncols)); end;
niter_ = (trace_(:,1));
r_rem_ = (trace_(:,2));
c_rem_ = (trace_(:,3));
QR_ = (trace_(:,4));
QC_ = (trace_(:,5));
I_rem_ = (trace_(:,6));





 
