function ...
[ ...
 flag_error ...
] = ....
xxxcluster_fromdisk_uADZSZDA_check_2( ...
 shuffle_num ...
,M_n_rows_ ...
,M_n_cols ...
,A_n_rij_ ...
,A_n_cij ...
,Z_n_rij_ ...
,T_n_cols ...
,T_n_ ...
,T_n_cij ...
);

flag_error = 0;

nbins = numel(M_n_rows_);
if (numel(intersect(A_n_cij,1:M_n_cols))<numel(A_n_cij));
disp(sprintf(' %% Warning, A_n_cij indices out of bounds in xxxcluster_fromdisk_uADZSZDA_check_2.m'));
flag_error = flag_error + 1;
end;%if (numel(intersect(A_n_cij,1:M_n_cols))<numel(A_n_cij));
if (numel(intersect(T_n_cij,1:T_n_cols))<numel(T_n_cij));
disp(sprintf(' %% Warning, T_n_cij indices out of bounds in xxxcluster_fromdisk_uADZSZDA_check_2.m'));
flag_error = flag_error + 1;
end;%if (numel(intersect(T_n_cij,1:T_n_cols))<numel(T_n_cij));

for nb1=0:nbins-1;
if (numel(intersect(A_n_rij_{1+nb1},Z_n_rij_{1+nb1}))>0); 
disp(sprintf(' %% Warning, nonzero intersection(A_n_rij_,Z_n_rij_) for 1+nb1=%d in xxxcluster_fromdisk_uADZSZDA_check_2.m',1+nb1));
flag_error = flag_error + 1;
end; %if (numel(intersect(A_n_rij_{1+nb1},Z_n_rij_{1+nb1}))>0); 
if (numel(intersect(A_n_rij_{1+nb1},1:M_n_rows_(1+nb1)))<numel(A_n_rij_{1+nb1}));
disp(sprintf(' %% Warning, A_n_rij_ indices out of bounds for for 1+nb1=%d in xxxcluster_fromdisk_uADZSZDA_check_2.m',1+nb1));
flag_error = flag_error + 1;
end;%if (numel(intersect(A_n_rij_{1+nb1},1:M_n_rows_(1+nb1)))<numel(A_n_rij_{1+nb1}));
if (numel(intersect(Z_n_rij_{1+nb1},1:M_n_rows_(1+nb1)))<numel(Z_n_rij_{1+nb1}));
disp(sprintf(' %% Warning, Z_n_rij_ indices out of bounds for for 1+nb1=%d in xxxcluster_fromdisk_uADZSZDA_check_2.m',1+nb1));
flag_error = flag_error + 1;
end;%if (numel(intersect(Z_n_rij_{1+nb1},1:M_n_rows_(1+nb1)))<numel(Z_n_rij_{1+nb1}));
end;%for nb1=0:nbins-1;
