function str_out = xxxcluster_fromdisk_uADZSZDA_excerpt_0(fp,str_0,n_bin,d_1,str_1,str_2);
str_out = '';
if (fp>0); fprintf(fp,str_0); end;
str_out = sprintf('%s%s',str_out,str_0);
for nb=0:n_bin-1; 
if (n_bin==1);
if (fp>0); fprintf(fp,'%s%sfull%s',d_1,str_1,str_2); end;
str_out = sprintf('%s%s%sfull%s',str_out,d_1,str_1,str_2);
end; %if (n_bin==1); 
if (n_bin>1); 
if (fp>0); fprintf(fp,'%s%s%0.2d%s',d_1,str_1,1+nb,str_2); end;
str_out = sprintf('%s%s%s%0.2d%s',str_out,d_1,str_1,1+nb,str_2);
end; %if (n_bin>1); 
if (fp>0); if nb<n_bin-1; fprintf(fp,','); else fprintf(fp,';'); end; end;
if nb<n_bin-1; str_out = sprintf('%s,',str_out); else str_out = sprintf('%s;',str_out); end;
end; %for nb=0:n_bin-1; 
if (fp>0); fprintf(fp,'\n'); end;
str_out = sprintf('%s\n',str_out);
